
###
GET https://50zbb0xdqkgx.c01-15.plentymarkets.com/rest/availabilities
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzViZGIwZjk2MjY3NTBmNTAzZWZkN2NiZDIwMjczZWQ3OTcxNzJhOGQyMzZkOTU3N2VmZjMzNTY3MjEzNjVlMWZjNzlmYWE1MjU5NDc1Y2QiLCJpYXQiOjE2MDI2NTg3MDEsIm5iZiI6MTYwMjY1ODcwMSwiZXhwIjoxNjAyNzQ1MTAxLCJzdWIiOiI1Iiwic2NvcGVzIjpbIioiXX0.ArpafwJAYUrWvGsjNKKIUSxUjTKf37UAWGT8g0Qli1YquA1tiGjiBWKmU9a9-56DEw_9WZ7DHINCvEeI0SwTkLY-D6E24cjpc7qLUs56ILFfgZ4sJ8wsDKekaFFIETL3z2pJ3SYdDbVaNLQJc-sk5xIgYYI14-PYevRXVCdJZX9R6mf5GpyO-dC64JisfodSHmDxMUUsiak6KgfTjL1Ebo2QEO6h6hkmdWDehvVQSqnoQ0ZIDiIRdVJsLVnDpsw9u4TxAUd7YCsM9CRBf2vyRrmfocJRben_Ssd2bUxwilR7YAliNo502KQLpUTEhRyhg1Hp-y33rMxq_errOsPQ24wH6aSUHX_D9o_2EmK1foI05FV-2KhBYliEaXhP4BcnpapQVIYBeJs1jDqDh0H04pG1heq5fxt3sPn3iHz_qGMdhepb03gVf2TE2dOze1TX-leZ_4rj1yxXi3OAM0z0pWWhcni1PLvEDybtcQQJpiwkGfJXa76Wq4MXGzOl0uZEa5woXLereNVf7NxiOASjh5kAWbRdGLrlEPy1UEfCLfIICfwNoqnag5S66jesaUL5UQzwdZVXCy5gbabSo_pfeTPxinEfBSflESEm36qIRxS0CT8yd97tsOUTW4o2rSDkMZOlpvtxPVDIxDt-oNOckh2Z1Vri1aTMnWvWvnl_PTk

###
GET https://50zbb0xdqkgx.c01-15.plentymarkets.com/rest/item_sets
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzViZGIwZjk2MjY3NTBmNTAzZWZkN2NiZDIwMjczZWQ3OTcxNzJhOGQyMzZkOTU3N2VmZjMzNTY3MjEzNjVlMWZjNzlmYWE1MjU5NDc1Y2QiLCJpYXQiOjE2MDI2NTg3MDEsIm5iZiI6MTYwMjY1ODcwMSwiZXhwIjoxNjAyNzQ1MTAxLCJzdWIiOiI1Iiwic2NvcGVzIjpbIioiXX0.ArpafwJAYUrWvGsjNKKIUSxUjTKf37UAWGT8g0Qli1YquA1tiGjiBWKmU9a9-56DEw_9WZ7DHINCvEeI0SwTkLY-D6E24cjpc7qLUs56ILFfgZ4sJ8wsDKekaFFIETL3z2pJ3SYdDbVaNLQJc-sk5xIgYYI14-PYevRXVCdJZX9R6mf5GpyO-dC64JisfodSHmDxMUUsiak6KgfTjL1Ebo2QEO6h6hkmdWDehvVQSqnoQ0ZIDiIRdVJsLVnDpsw9u4TxAUd7YCsM9CRBf2vyRrmfocJRben_Ssd2bUxwilR7YAliNo502KQLpUTEhRyhg1Hp-y33rMxq_errOsPQ24wH6aSUHX_D9o_2EmK1foI05FV-2KhBYliEaXhP4BcnpapQVIYBeJs1jDqDh0H04pG1heq5fxt3sPn3iHz_qGMdhepb03gVf2TE2dOze1TX-leZ_4rj1yxXi3OAM0z0pWWhcni1PLvEDybtcQQJpiwkGfJXa76Wq4MXGzOl0uZEa5woXLereNVf7NxiOASjh5kAWbRdGLrlEPy1UEfCLfIICfwNoqnag5S66jesaUL5UQzwdZVXCy5gbabSo_pfeTPxinEfBSflESEm36qIRxS0CT8yd97tsOUTW4o2rSDkMZOlpvtxPVDIxDt-oNOckh2Z1Vri1aTMnWvWvnl_PTk

###
GET https://50zbb0xdqkgx.c01-15.plentymarkets.com/rest/items
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzViZGIwZjk2MjY3NTBmNTAzZWZkN2NiZDIwMjczZWQ3OTcxNzJhOGQyMzZkOTU3N2VmZjMzNTY3MjEzNjVlMWZjNzlmYWE1MjU5NDc1Y2QiLCJpYXQiOjE2MDI2NTg3MDEsIm5iZiI6MTYwMjY1ODcwMSwiZXhwIjoxNjAyNzQ1MTAxLCJzdWIiOiI1Iiwic2NvcGVzIjpbIioiXX0.ArpafwJAYUrWvGsjNKKIUSxUjTKf37UAWGT8g0Qli1YquA1tiGjiBWKmU9a9-56DEw_9WZ7DHINCvEeI0SwTkLY-D6E24cjpc7qLUs56ILFfgZ4sJ8wsDKekaFFIETL3z2pJ3SYdDbVaNLQJc-sk5xIgYYI14-PYevRXVCdJZX9R6mf5GpyO-dC64JisfodSHmDxMUUsiak6KgfTjL1Ebo2QEO6h6hkmdWDehvVQSqnoQ0ZIDiIRdVJsLVnDpsw9u4TxAUd7YCsM9CRBf2vyRrmfocJRben_Ssd2bUxwilR7YAliNo502KQLpUTEhRyhg1Hp-y33rMxq_errOsPQ24wH6aSUHX_D9o_2EmK1foI05FV-2KhBYliEaXhP4BcnpapQVIYBeJs1jDqDh0H04pG1heq5fxt3sPn3iHz_qGMdhepb03gVf2TE2dOze1TX-leZ_4rj1yxXi3OAM0z0pWWhcni1PLvEDybtcQQJpiwkGfJXa76Wq4MXGzOl0uZEa5woXLereNVf7NxiOASjh5kAWbRdGLrlEPy1UEfCLfIICfwNoqnag5S66jesaUL5UQzwdZVXCy5gbabSo_pfeTPxinEfBSflESEm36qIRxS0CT8yd97tsOUTW4o2rSDkMZOlpvtxPVDIxDt-oNOckh2Z1Vri1aTMnWvWvnl_PTk

###
GET https://50zbb0xdqkgx.c01-15.plentymarkets.com/rest/items/7769
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzViZGIwZjk2MjY3NTBmNTAzZWZkN2NiZDIwMjczZWQ3OTcxNzJhOGQyMzZkOTU3N2VmZjMzNTY3MjEzNjVlMWZjNzlmYWE1MjU5NDc1Y2QiLCJpYXQiOjE2MDI2NTg3MDEsIm5iZiI6MTYwMjY1ODcwMSwiZXhwIjoxNjAyNzQ1MTAxLCJzdWIiOiI1Iiwic2NvcGVzIjpbIioiXX0.ArpafwJAYUrWvGsjNKKIUSxUjTKf37UAWGT8g0Qli1YquA1tiGjiBWKmU9a9-56DEw_9WZ7DHINCvEeI0SwTkLY-D6E24cjpc7qLUs56ILFfgZ4sJ8wsDKekaFFIETL3z2pJ3SYdDbVaNLQJc-sk5xIgYYI14-PYevRXVCdJZX9R6mf5GpyO-dC64JisfodSHmDxMUUsiak6KgfTjL1Ebo2QEO6h6hkmdWDehvVQSqnoQ0ZIDiIRdVJsLVnDpsw9u4TxAUd7YCsM9CRBf2vyRrmfocJRben_Ssd2bUxwilR7YAliNo502KQLpUTEhRyhg1Hp-y33rMxq_errOsPQ24wH6aSUHX_D9o_2EmK1foI05FV-2KhBYliEaXhP4BcnpapQVIYBeJs1jDqDh0H04pG1heq5fxt3sPn3iHz_qGMdhepb03gVf2TE2dOze1TX-leZ_4rj1yxXi3OAM0z0pWWhcni1PLvEDybtcQQJpiwkGfJXa76Wq4MXGzOl0uZEa5woXLereNVf7NxiOASjh5kAWbRdGLrlEPy1UEfCLfIICfwNoqnag5S66jesaUL5UQzwdZVXCy5gbabSo_pfeTPxinEfBSflESEm36qIRxS0CT8yd97tsOUTW4o2rSDkMZOlpvtxPVDIxDt-oNOckh2Z1Vri1aTMnWvWvnl_PTk


###
GET https://50zbb0xdqkgx.c01-15.plentymarkets.com/rest/items/variations
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzViZGIwZjk2MjY3NTBmNTAzZWZkN2NiZDIwMjczZWQ3OTcxNzJhOGQyMzZkOTU3N2VmZjMzNTY3MjEzNjVlMWZjNzlmYWE1MjU5NDc1Y2QiLCJpYXQiOjE2MDI2NTg3MDEsIm5iZiI6MTYwMjY1ODcwMSwiZXhwIjoxNjAyNzQ1MTAxLCJzdWIiOiI1Iiwic2NvcGVzIjpbIioiXX0.ArpafwJAYUrWvGsjNKKIUSxUjTKf37UAWGT8g0Qli1YquA1tiGjiBWKmU9a9-56DEw_9WZ7DHINCvEeI0SwTkLY-D6E24cjpc7qLUs56ILFfgZ4sJ8wsDKekaFFIETL3z2pJ3SYdDbVaNLQJc-sk5xIgYYI14-PYevRXVCdJZX9R6mf5GpyO-dC64JisfodSHmDxMUUsiak6KgfTjL1Ebo2QEO6h6hkmdWDehvVQSqnoQ0ZIDiIRdVJsLVnDpsw9u4TxAUd7YCsM9CRBf2vyRrmfocJRben_Ssd2bUxwilR7YAliNo502KQLpUTEhRyhg1Hp-y33rMxq_errOsPQ24wH6aSUHX_D9o_2EmK1foI05FV-2KhBYliEaXhP4BcnpapQVIYBeJs1jDqDh0H04pG1heq5fxt3sPn3iHz_qGMdhepb03gVf2TE2dOze1TX-leZ_4rj1yxXi3OAM0z0pWWhcni1PLvEDybtcQQJpiwkGfJXa76Wq4MXGzOl0uZEa5woXLereNVf7NxiOASjh5kAWbRdGLrlEPy1UEfCLfIICfwNoqnag5S66jesaUL5UQzwdZVXCy5gbabSo_pfeTPxinEfBSflESEm36qIRxS0CT8yd97tsOUTW4o2rSDkMZOlpvtxPVDIxDt-oNOckh2Z1Vri1aTMnWvWvnl_PTk

###
GET https://50zbb0xdqkgx.c01-15.plentymarkets.com/rest/items/attributes
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzViZGIwZjk2MjY3NTBmNTAzZWZkN2NiZDIwMjczZWQ3OTcxNzJhOGQyMzZkOTU3N2VmZjMzNTY3MjEzNjVlMWZjNzlmYWE1MjU5NDc1Y2QiLCJpYXQiOjE2MDI2NTg3MDEsIm5iZiI6MTYwMjY1ODcwMSwiZXhwIjoxNjAyNzQ1MTAxLCJzdWIiOiI1Iiwic2NvcGVzIjpbIioiXX0.ArpafwJAYUrWvGsjNKKIUSxUjTKf37UAWGT8g0Qli1YquA1tiGjiBWKmU9a9-56DEw_9WZ7DHINCvEeI0SwTkLY-D6E24cjpc7qLUs56ILFfgZ4sJ8wsDKekaFFIETL3z2pJ3SYdDbVaNLQJc-sk5xIgYYI14-PYevRXVCdJZX9R6mf5GpyO-dC64JisfodSHmDxMUUsiak6KgfTjL1Ebo2QEO6h6hkmdWDehvVQSqnoQ0ZIDiIRdVJsLVnDpsw9u4TxAUd7YCsM9CRBf2vyRrmfocJRben_Ssd2bUxwilR7YAliNo502KQLpUTEhRyhg1Hp-y33rMxq_errOsPQ24wH6aSUHX_D9o_2EmK1foI05FV-2KhBYliEaXhP4BcnpapQVIYBeJs1jDqDh0H04pG1heq5fxt3sPn3iHz_qGMdhepb03gVf2TE2dOze1TX-leZ_4rj1yxXi3OAM0z0pWWhcni1PLvEDybtcQQJpiwkGfJXa76Wq4MXGzOl0uZEa5woXLereNVf7NxiOASjh5kAWbRdGLrlEPy1UEfCLfIICfwNoqnag5S66jesaUL5UQzwdZVXCy5gbabSo_pfeTPxinEfBSflESEm36qIRxS0CT8yd97tsOUTW4o2rSDkMZOlpvtxPVDIxDt-oNOckh2Z1Vri1aTMnWvWvnl_PTk

###
GET https://50zbb0xdqkgx.c01-15.plentymarkets.com/rest/items/barcodes
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzViZGIwZjk2MjY3NTBmNTAzZWZkN2NiZDIwMjczZWQ3OTcxNzJhOGQyMzZkOTU3N2VmZjMzNTY3MjEzNjVlMWZjNzlmYWE1MjU5NDc1Y2QiLCJpYXQiOjE2MDI2NTg3MDEsIm5iZiI6MTYwMjY1ODcwMSwiZXhwIjoxNjAyNzQ1MTAxLCJzdWIiOiI1Iiwic2NvcGVzIjpbIioiXX0.ArpafwJAYUrWvGsjNKKIUSxUjTKf37UAWGT8g0Qli1YquA1tiGjiBWKmU9a9-56DEw_9WZ7DHINCvEeI0SwTkLY-D6E24cjpc7qLUs56ILFfgZ4sJ8wsDKekaFFIETL3z2pJ3SYdDbVaNLQJc-sk5xIgYYI14-PYevRXVCdJZX9R6mf5GpyO-dC64JisfodSHmDxMUUsiak6KgfTjL1Ebo2QEO6h6hkmdWDehvVQSqnoQ0ZIDiIRdVJsLVnDpsw9u4TxAUd7YCsM9CRBf2vyRrmfocJRben_Ssd2bUxwilR7YAliNo502KQLpUTEhRyhg1Hp-y33rMxq_errOsPQ24wH6aSUHX_D9o_2EmK1foI05FV-2KhBYliEaXhP4BcnpapQVIYBeJs1jDqDh0H04pG1heq5fxt3sPn3iHz_qGMdhepb03gVf2TE2dOze1TX-leZ_4rj1yxXi3OAM0z0pWWhcni1PLvEDybtcQQJpiwkGfJXa76Wq4MXGzOl0uZEa5woXLereNVf7NxiOASjh5kAWbRdGLrlEPy1UEfCLfIICfwNoqnag5S66jesaUL5UQzwdZVXCy5gbabSo_pfeTPxinEfBSflESEm36qIRxS0CT8yd97tsOUTW4o2rSDkMZOlpvtxPVDIxDt-oNOckh2Z1Vri1aTMnWvWvnl_PTk

###
GET https://50zbb0xdqkgx.c01-15.plentymarkets.com/rest/items/item_shipping_profiles
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzViZGIwZjk2MjY3NTBmNTAzZWZkN2NiZDIwMjczZWQ3OTcxNzJhOGQyMzZkOTU3N2VmZjMzNTY3MjEzNjVlMWZjNzlmYWE1MjU5NDc1Y2QiLCJpYXQiOjE2MDI2NTg3MDEsIm5iZiI6MTYwMjY1ODcwMSwiZXhwIjoxNjAyNzQ1MTAxLCJzdWIiOiI1Iiwic2NvcGVzIjpbIioiXX0.ArpafwJAYUrWvGsjNKKIUSxUjTKf37UAWGT8g0Qli1YquA1tiGjiBWKmU9a9-56DEw_9WZ7DHINCvEeI0SwTkLY-D6E24cjpc7qLUs56ILFfgZ4sJ8wsDKekaFFIETL3z2pJ3SYdDbVaNLQJc-sk5xIgYYI14-PYevRXVCdJZX9R6mf5GpyO-dC64JisfodSHmDxMUUsiak6KgfTjL1Ebo2QEO6h6hkmdWDehvVQSqnoQ0ZIDiIRdVJsLVnDpsw9u4TxAUd7YCsM9CRBf2vyRrmfocJRben_Ssd2bUxwilR7YAliNo502KQLpUTEhRyhg1Hp-y33rMxq_errOsPQ24wH6aSUHX_D9o_2EmK1foI05FV-2KhBYliEaXhP4BcnpapQVIYBeJs1jDqDh0H04pG1heq5fxt3sPn3iHz_qGMdhepb03gVf2TE2dOze1TX-leZ_4rj1yxXi3OAM0z0pWWhcni1PLvEDybtcQQJpiwkGfJXa76Wq4MXGzOl0uZEa5woXLereNVf7NxiOASjh5kAWbRdGLrlEPy1UEfCLfIICfwNoqnag5S66jesaUL5UQzwdZVXCy5gbabSo_pfeTPxinEfBSflESEm36qIRxS0CT8yd97tsOUTW4o2rSDkMZOlpvtxPVDIxDt-oNOckh2Z1Vri1aTMnWvWvnl_PTk

###
POST https://50zbb0xdqkgx.c01-15.plentymarkets.com/rest/items/item_shipping_profiles
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzViZGIwZjk2MjY3NTBmNTAzZWZkN2NiZDIwMjczZWQ3OTcxNzJhOGQyMzZkOTU3N2VmZjMzNTY3MjEzNjVlMWZjNzlmYWE1MjU5NDc1Y2QiLCJpYXQiOjE2MDI2NTg3MDEsIm5iZiI6MTYwMjY1ODcwMSwiZXhwIjoxNjAyNzQ1MTAxLCJzdWIiOiI1Iiwic2NvcGVzIjpbIioiXX0.ArpafwJAYUrWvGsjNKKIUSxUjTKf37UAWGT8g0Qli1YquA1tiGjiBWKmU9a9-56DEw_9WZ7DHINCvEeI0SwTkLY-D6E24cjpc7qLUs56ILFfgZ4sJ8wsDKekaFFIETL3z2pJ3SYdDbVaNLQJc-sk5xIgYYI14-PYevRXVCdJZX9R6mf5GpyO-dC64JisfodSHmDxMUUsiak6KgfTjL1Ebo2QEO6h6hkmdWDehvVQSqnoQ0ZIDiIRdVJsLVnDpsw9u4TxAUd7YCsM9CRBf2vyRrmfocJRben_Ssd2bUxwilR7YAliNo502KQLpUTEhRyhg1Hp-y33rMxq_errOsPQ24wH6aSUHX_D9o_2EmK1foI05FV-2KhBYliEaXhP4BcnpapQVIYBeJs1jDqDh0H04pG1heq5fxt3sPn3iHz_qGMdhepb03gVf2TE2dOze1TX-leZ_4rj1yxXi3OAM0z0pWWhcni1PLvEDybtcQQJpiwkGfJXa76Wq4MXGzOl0uZEa5woXLereNVf7NxiOASjh5kAWbRdGLrlEPy1UEfCLfIICfwNoqnag5S66jesaUL5UQzwdZVXCy5gbabSo_pfeTPxinEfBSflESEm36qIRxS0CT8yd97tsOUTW4o2rSDkMZOlpvtxPVDIxDt-oNOckh2Z1Vri1aTMnWvWvnl_PTk

[
  {
    "itemId": 7786,
    "profileId": 6
  },
  {
    "itemId": 7786,
    "profileId": 7
  },
  {
    "itemId": 7786,
    "profileId": 8
  }
]

###
GET https://50zbb0xdqkgx.c01-15.plentymarkets.com/rest/items/7769/variations/29044/descriptions
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzViZGIwZjk2MjY3NTBmNTAzZWZkN2NiZDIwMjczZWQ3OTcxNzJhOGQyMzZkOTU3N2VmZjMzNTY3MjEzNjVlMWZjNzlmYWE1MjU5NDc1Y2QiLCJpYXQiOjE2MDI2NTg3MDEsIm5iZiI6MTYwMjY1ODcwMSwiZXhwIjoxNjAyNzQ1MTAxLCJzdWIiOiI1Iiwic2NvcGVzIjpbIioiXX0.ArpafwJAYUrWvGsjNKKIUSxUjTKf37UAWGT8g0Qli1YquA1tiGjiBWKmU9a9-56DEw_9WZ7DHINCvEeI0SwTkLY-D6E24cjpc7qLUs56ILFfgZ4sJ8wsDKekaFFIETL3z2pJ3SYdDbVaNLQJc-sk5xIgYYI14-PYevRXVCdJZX9R6mf5GpyO-dC64JisfodSHmDxMUUsiak6KgfTjL1Ebo2QEO6h6hkmdWDehvVQSqnoQ0ZIDiIRdVJsLVnDpsw9u4TxAUd7YCsM9CRBf2vyRrmfocJRben_Ssd2bUxwilR7YAliNo502KQLpUTEhRyhg1Hp-y33rMxq_errOsPQ24wH6aSUHX_D9o_2EmK1foI05FV-2KhBYliEaXhP4BcnpapQVIYBeJs1jDqDh0H04pG1heq5fxt3sPn3iHz_qGMdhepb03gVf2TE2dOze1TX-leZ_4rj1yxXi3OAM0z0pWWhcni1PLvEDybtcQQJpiwkGfJXa76Wq4MXGzOl0uZEa5woXLereNVf7NxiOASjh5kAWbRdGLrlEPy1UEfCLfIICfwNoqnag5S66jesaUL5UQzwdZVXCy5gbabSo_pfeTPxinEfBSflESEm36qIRxS0CT8yd97tsOUTW4o2rSDkMZOlpvtxPVDIxDt-oNOckh2Z1Vri1aTMnWvWvnl_PTk

###
GET https://50zbb0xdqkgx.c01-15.plentymarkets.com/rest/items/7769/variations/29044?with=variationTexts
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzViZGIwZjk2MjY3NTBmNTAzZWZkN2NiZDIwMjczZWQ3OTcxNzJhOGQyMzZkOTU3N2VmZjMzNTY3MjEzNjVlMWZjNzlmYWE1MjU5NDc1Y2QiLCJpYXQiOjE2MDI2NTg3MDEsIm5iZiI6MTYwMjY1ODcwMSwiZXhwIjoxNjAyNzQ1MTAxLCJzdWIiOiI1Iiwic2NvcGVzIjpbIioiXX0.ArpafwJAYUrWvGsjNKKIUSxUjTKf37UAWGT8g0Qli1YquA1tiGjiBWKmU9a9-56DEw_9WZ7DHINCvEeI0SwTkLY-D6E24cjpc7qLUs56ILFfgZ4sJ8wsDKekaFFIETL3z2pJ3SYdDbVaNLQJc-sk5xIgYYI14-PYevRXVCdJZX9R6mf5GpyO-dC64JisfodSHmDxMUUsiak6KgfTjL1Ebo2QEO6h6hkmdWDehvVQSqnoQ0ZIDiIRdVJsLVnDpsw9u4TxAUd7YCsM9CRBf2vyRrmfocJRben_Ssd2bUxwilR7YAliNo502KQLpUTEhRyhg1Hp-y33rMxq_errOsPQ24wH6aSUHX_D9o_2EmK1foI05FV-2KhBYliEaXhP4BcnpapQVIYBeJs1jDqDh0H04pG1heq5fxt3sPn3iHz_qGMdhepb03gVf2TE2dOze1TX-leZ_4rj1yxXi3OAM0z0pWWhcni1PLvEDybtcQQJpiwkGfJXa76Wq4MXGzOl0uZEa5woXLereNVf7NxiOASjh5kAWbRdGLrlEPy1UEfCLfIICfwNoqnag5S66jesaUL5UQzwdZVXCy5gbabSo_pfeTPxinEfBSflESEm36qIRxS0CT8yd97tsOUTW4o2rSDkMZOlpvtxPVDIxDt-oNOckh2Z1Vri1aTMnWvWvnl_PTk

###
GET https://50zbb0xdqkgx.c01-15.plentymarkets.com/rest/items/7769/variations/29044?with=itemCrossSelling
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzViZGIwZjk2MjY3NTBmNTAzZWZkN2NiZDIwMjczZWQ3OTcxNzJhOGQyMzZkOTU3N2VmZjMzNTY3MjEzNjVlMWZjNzlmYWE1MjU5NDc1Y2QiLCJpYXQiOjE2MDI2NTg3MDEsIm5iZiI6MTYwMjY1ODcwMSwiZXhwIjoxNjAyNzQ1MTAxLCJzdWIiOiI1Iiwic2NvcGVzIjpbIioiXX0.ArpafwJAYUrWvGsjNKKIUSxUjTKf37UAWGT8g0Qli1YquA1tiGjiBWKmU9a9-56DEw_9WZ7DHINCvEeI0SwTkLY-D6E24cjpc7qLUs56ILFfgZ4sJ8wsDKekaFFIETL3z2pJ3SYdDbVaNLQJc-sk5xIgYYI14-PYevRXVCdJZX9R6mf5GpyO-dC64JisfodSHmDxMUUsiak6KgfTjL1Ebo2QEO6h6hkmdWDehvVQSqnoQ0ZIDiIRdVJsLVnDpsw9u4TxAUd7YCsM9CRBf2vyRrmfocJRben_Ssd2bUxwilR7YAliNo502KQLpUTEhRyhg1Hp-y33rMxq_errOsPQ24wH6aSUHX_D9o_2EmK1foI05FV-2KhBYliEaXhP4BcnpapQVIYBeJs1jDqDh0H04pG1heq5fxt3sPn3iHz_qGMdhepb03gVf2TE2dOze1TX-leZ_4rj1yxXi3OAM0z0pWWhcni1PLvEDybtcQQJpiwkGfJXa76Wq4MXGzOl0uZEa5woXLereNVf7NxiOASjh5kAWbRdGLrlEPy1UEfCLfIICfwNoqnag5S66jesaUL5UQzwdZVXCy5gbabSo_pfeTPxinEfBSflESEm36qIRxS0CT8yd97tsOUTW4o2rSDkMZOlpvtxPVDIxDt-oNOckh2Z1Vri1aTMnWvWvnl_PTk

###
GET https://50zbb0xdqkgx.c01-15.plentymarkets.com/rest/items/7769/variations/29044?with=itemImages
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzViZGIwZjk2MjY3NTBmNTAzZWZkN2NiZDIwMjczZWQ3OTcxNzJhOGQyMzZkOTU3N2VmZjMzNTY3MjEzNjVlMWZjNzlmYWE1MjU5NDc1Y2QiLCJpYXQiOjE2MDI2NTg3MDEsIm5iZiI6MTYwMjY1ODcwMSwiZXhwIjoxNjAyNzQ1MTAxLCJzdWIiOiI1Iiwic2NvcGVzIjpbIioiXX0.ArpafwJAYUrWvGsjNKKIUSxUjTKf37UAWGT8g0Qli1YquA1tiGjiBWKmU9a9-56DEw_9WZ7DHINCvEeI0SwTkLY-D6E24cjpc7qLUs56ILFfgZ4sJ8wsDKekaFFIETL3z2pJ3SYdDbVaNLQJc-sk5xIgYYI14-PYevRXVCdJZX9R6mf5GpyO-dC64JisfodSHmDxMUUsiak6KgfTjL1Ebo2QEO6h6hkmdWDehvVQSqnoQ0ZIDiIRdVJsLVnDpsw9u4TxAUd7YCsM9CRBf2vyRrmfocJRben_Ssd2bUxwilR7YAliNo502KQLpUTEhRyhg1Hp-y33rMxq_errOsPQ24wH6aSUHX_D9o_2EmK1foI05FV-2KhBYliEaXhP4BcnpapQVIYBeJs1jDqDh0H04pG1heq5fxt3sPn3iHz_qGMdhepb03gVf2TE2dOze1TX-leZ_4rj1yxXi3OAM0z0pWWhcni1PLvEDybtcQQJpiwkGfJXa76Wq4MXGzOl0uZEa5woXLereNVf7NxiOASjh5kAWbRdGLrlEPy1UEfCLfIICfwNoqnag5S66jesaUL5UQzwdZVXCy5gbabSo_pfeTPxinEfBSflESEm36qIRxS0CT8yd97tsOUTW4o2rSDkMZOlpvtxPVDIxDt-oNOckh2Z1Vri1aTMnWvWvnl_PTk

###



###
POST https://50zbb0xdqkgx.c01-15.plentymarkets.com/rest/items
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzViZGIwZjk2MjY3NTBmNTAzZWZkN2NiZDIwMjczZWQ3OTcxNzJhOGQyMzZkOTU3N2VmZjMzNTY3MjEzNjVlMWZjNzlmYWE1MjU5NDc1Y2QiLCJpYXQiOjE2MDI2NTg3MDEsIm5iZiI6MTYwMjY1ODcwMSwiZXhwIjoxNjAyNzQ1MTAxLCJzdWIiOiI1Iiwic2NvcGVzIjpbIioiXX0.ArpafwJAYUrWvGsjNKKIUSxUjTKf37UAWGT8g0Qli1YquA1tiGjiBWKmU9a9-56DEw_9WZ7DHINCvEeI0SwTkLY-D6E24cjpc7qLUs56ILFfgZ4sJ8wsDKekaFFIETL3z2pJ3SYdDbVaNLQJc-sk5xIgYYI14-PYevRXVCdJZX9R6mf5GpyO-dC64JisfodSHmDxMUUsiak6KgfTjL1Ebo2QEO6h6hkmdWDehvVQSqnoQ0ZIDiIRdVJsLVnDpsw9u4TxAUd7YCsM9CRBf2vyRrmfocJRben_Ssd2bUxwilR7YAliNo502KQLpUTEhRyhg1Hp-y33rMxq_errOsPQ24wH6aSUHX_D9o_2EmK1foI05FV-2KhBYliEaXhP4BcnpapQVIYBeJs1jDqDh0H04pG1heq5fxt3sPn3iHz_qGMdhepb03gVf2TE2dOze1TX-leZ_4rj1yxXi3OAM0z0pWWhcni1PLvEDybtcQQJpiwkGfJXa76Wq4MXGzOl0uZEa5woXLereNVf7NxiOASjh5kAWbRdGLrlEPy1UEfCLfIICfwNoqnag5S66jesaUL5UQzwdZVXCy5gbabSo_pfeTPxinEfBSflESEm36qIRxS0CT8yd97tsOUTW4o2rSDkMZOlpvtxPVDIxDt-oNOckh2Z1Vri1aTMnWvWvnl_PTk

{
    "position":1,
    "stockType":0,
    "storeSpecial":2,
    "condition":0,
    "feedback":0,
    "isSubscribable":false,
    "isShippingPackage":false,
    "itemType":"default",
    "variations":[{
        "variationCategories": [{
            "categoryId":46
        }],
        "unit":{
            "unitId":1,
            "content":1
        }
    }]
}


