### DEV -------------------

https://5lb6aot5e3yq.c01-17.plentymarkets.com/rest/orders/201?with[]=documents

###
GET https://5lb6aot5e3yq.c01-17.plentymarkets.com/rest/orders/201?with[]=documents
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiM2ZkNjAzNDQ0NDhjYzBhZjE4Mzk4NzMyOGQ4NWJjMzM3NWI2ZjM0MzVkYWYyOWQwY2UzMzk1OTc4OTc0YTdmZTEwZDdkOGEzNzg0YzNiMjMiLCJpYXQiOjE2MTQzMzc5OTgsIm5iZiI6MTYxNDMzNzk5OCwiZXhwIjoxNjE0NDI0Mzk4LCJzdWIiOiIyNCIsInNjb3BlcyI6WyIqIl19.BHUdddBmeR2r0Rel5ZonzjhMk8XWzBiZ97_B3pYou-uaRo7grjQcICiDHP2oSkp1BGUiabE4B__N5gBPR7FzZUaTG63JlsLGmUdRy_06BoPNOZZIDri2Rh1MzespX5UzcDBVQPvX-_n3v3YqUNJabtEvMik3CDsTrJfozbyttUG3v2-3uifM3cnjPESTbHRJ5mLPV6ljPuZV5R1LWvrQYhgThlEGTY64o-hIMBMZBii0tlsKJQ9Flw3COls93st0vji_CCFg5wo25uQuGI2s2MHvD40zdOlG1WIm2qP2Um3SVZwooHo_Q8I86H2GaUxitiXO41GuHrSjN2orON-F6SHrmyOjyyAlq-fhHMRMW1JKPSKTpdOFJxL1s-m7QIF9mga4xwYylsMaTE0nFI0D8I7V74uYK6FWCUHsmoggwIaBsyLurYDSAxOaz1VGb9iFjZfQRViONtYJ7W2GzvzIgA_9-RGyN2qoSrewGfnxdJOvQSa9u7kjd9lGGtwl4aIXh13TaFXvBVF9x33j44dY8154vRvrmpKyOU_nG-tp4yzPBfNjm-OP3aqvhmbgTjKcyGSxz_lmeS7Ks6l9kz-6WrsR5jgx72J-ohGdcK2MfWw87P-Zkx2nq5Yx-5i87KnBBWbXIbOrqhD2FOX8iuz26QGSgs5isy7TzSCW78gE5hg

###
GET https://5lb6aot5e3yq.c01-17.plentymarkets.com/rest/orders/40994?with[]=documents&with[]=payments
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiM2ZkNjAzNDQ0NDhjYzBhZjE4Mzk4NzMyOGQ4NWJjMzM3NWI2ZjM0MzVkYWYyOWQwY2UzMzk1OTc4OTc0YTdmZTEwZDdkOGEzNzg0YzNiMjMiLCJpYXQiOjE2MTQzMzc5OTgsIm5iZiI6MTYxNDMzNzk5OCwiZXhwIjoxNjE0NDI0Mzk4LCJzdWIiOiIyNCIsInNjb3BlcyI6WyIqIl19.BHUdddBmeR2r0Rel5ZonzjhMk8XWzBiZ97_B3pYou-uaRo7grjQcICiDHP2oSkp1BGUiabE4B__N5gBPR7FzZUaTG63JlsLGmUdRy_06BoPNOZZIDri2Rh1MzespX5UzcDBVQPvX-_n3v3YqUNJabtEvMik3CDsTrJfozbyttUG3v2-3uifM3cnjPESTbHRJ5mLPV6ljPuZV5R1LWvrQYhgThlEGTY64o-hIMBMZBii0tlsKJQ9Flw3COls93st0vji_CCFg5wo25uQuGI2s2MHvD40zdOlG1WIm2qP2Um3SVZwooHo_Q8I86H2GaUxitiXO41GuHrSjN2orON-F6SHrmyOjyyAlq-fhHMRMW1JKPSKTpdOFJxL1s-m7QIF9mga4xwYylsMaTE0nFI0D8I7V74uYK6FWCUHsmoggwIaBsyLurYDSAxOaz1VGb9iFjZfQRViONtYJ7W2GzvzIgA_9-RGyN2qoSrewGfnxdJOvQSa9u7kjd9lGGtwl4aIXh13TaFXvBVF9x33j44dY8154vRvrmpKyOU_nG-tp4yzPBfNjm-OP3aqvhmbgTjKcyGSxz_lmeS7Ks6l9kz-6WrsR5jgx72J-ohGdcK2MfWw87P-Zkx2nq5Yx-5i87KnBBWbXIbOrqhD2FOX8iuz26QGSgs5isy7TzSCW78gE5hg

###
GET https://5lb6aot5e3yq.c01-17.plentymarkets.com/rest/documents/10
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiM2ZkNjAzNDQ0NDhjYzBhZjE4Mzk4NzMyOGQ4NWJjMzM3NWI2ZjM0MzVkYWYyOWQwY2UzMzk1OTc4OTc0YTdmZTEwZDdkOGEzNzg0YzNiMjMiLCJpYXQiOjE2MTQzMzc5OTgsIm5iZiI6MTYxNDMzNzk5OCwiZXhwIjoxNjE0NDI0Mzk4LCJzdWIiOiIyNCIsInNjb3BlcyI6WyIqIl19.BHUdddBmeR2r0Rel5ZonzjhMk8XWzBiZ97_B3pYou-uaRo7grjQcICiDHP2oSkp1BGUiabE4B__N5gBPR7FzZUaTG63JlsLGmUdRy_06BoPNOZZIDri2Rh1MzespX5UzcDBVQPvX-_n3v3YqUNJabtEvMik3CDsTrJfozbyttUG3v2-3uifM3cnjPESTbHRJ5mLPV6ljPuZV5R1LWvrQYhgThlEGTY64o-hIMBMZBii0tlsKJQ9Flw3COls93st0vji_CCFg5wo25uQuGI2s2MHvD40zdOlG1WIm2qP2Um3SVZwooHo_Q8I86H2GaUxitiXO41GuHrSjN2orON-F6SHrmyOjyyAlq-fhHMRMW1JKPSKTpdOFJxL1s-m7QIF9mga4xwYylsMaTE0nFI0D8I7V74uYK6FWCUHsmoggwIaBsyLurYDSAxOaz1VGb9iFjZfQRViONtYJ7W2GzvzIgA_9-RGyN2qoSrewGfnxdJOvQSa9u7kjd9lGGtwl4aIXh13TaFXvBVF9x33j44dY8154vRvrmpKyOU_nG-tp4yzPBfNjm-OP3aqvhmbgTjKcyGSxz_lmeS7Ks6l9kz-6WrsR5jgx72J-ohGdcK2MfWw87P-Zkx2nq5Yx-5i87KnBBWbXIbOrqhD2FOX8iuz26QGSgs5isy7TzSCW78gE5hg



###
GET https://5lb6aot5e3yq.c01-17.plentymarkets.com/rest/payments/25024
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiM2ZkNjAzNDQ0NDhjYzBhZjE4Mzk4NzMyOGQ4NWJjMzM3NWI2ZjM0MzVkYWYyOWQwY2UzMzk1OTc4OTc0YTdmZTEwZDdkOGEzNzg0YzNiMjMiLCJpYXQiOjE2MTQzMzc5OTgsIm5iZiI6MTYxNDMzNzk5OCwiZXhwIjoxNjE0NDI0Mzk4LCJzdWIiOiIyNCIsInNjb3BlcyI6WyIqIl19.BHUdddBmeR2r0Rel5ZonzjhMk8XWzBiZ97_B3pYou-uaRo7grjQcICiDHP2oSkp1BGUiabE4B__N5gBPR7FzZUaTG63JlsLGmUdRy_06BoPNOZZIDri2Rh1MzespX5UzcDBVQPvX-_n3v3YqUNJabtEvMik3CDsTrJfozbyttUG3v2-3uifM3cnjPESTbHRJ5mLPV6ljPuZV5R1LWvrQYhgThlEGTY64o-hIMBMZBii0tlsKJQ9Flw3COls93st0vji_CCFg5wo25uQuGI2s2MHvD40zdOlG1WIm2qP2Um3SVZwooHo_Q8I86H2GaUxitiXO41GuHrSjN2orON-F6SHrmyOjyyAlq-fhHMRMW1JKPSKTpdOFJxL1s-m7QIF9mga4xwYylsMaTE0nFI0D8I7V74uYK6FWCUHsmoggwIaBsyLurYDSAxOaz1VGb9iFjZfQRViONtYJ7W2GzvzIgA_9-RGyN2qoSrewGfnxdJOvQSa9u7kjd9lGGtwl4aIXh13TaFXvBVF9x33j44dY8154vRvrmpKyOU_nG-tp4yzPBfNjm-OP3aqvhmbgTjKcyGSxz_lmeS7Ks6l9kz-6WrsR5jgx72J-ohGdcK2MfWw87P-Zkx2nq5Yx-5i87KnBBWbXIbOrqhD2FOX8iuz26QGSgs5isy7TzSCW78gE5hg



