GET https://qqx6xqycwfc0.c01-15.plentymarkets.com/rest/orders/40994
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNTJjODdmNGEyZGE2YjAzNmZiOTU1NmM1MTYzNGZmYTQ3NDM5ODA0NGY3NTk1YWM0YmE0ZTIxNmJiNDIxM2NmMDM5YWQwNDc4Y2MyNmQzNmYiLCJpYXQiOjE2MTIxOTgzMDUsIm5iZiI6MTYxMjE5ODMwNSwiZXhwIjoxNjEyMjg0NzA1LCJzdWIiOiIxMSIsInNjb3BlcyI6WyIqIl19.nhhJ4aO-Or3kNnfaQuory5YTI2BARc2j4WVQzC3rk2IYAvHsE_Px8rr7JENM8mwvzakro2YQ6b1tSY_xUYzI7mRlfznokZgUIzhmG5li2gYz4qDnjDkIZbGXtZPravnFCHSw0rSfjZzUSfR-F2giCrD50lENgzkrSBTsDyeMuHFLJtTemsQy7k1ToRuAwRkYXR2kEc6wwVYEikr4MKwEeQbjbFa4daLOBbnR1mVFUiemGZf0AdBp0wpYAHLIgIjhrkzrHsABZ1PHXubbY7SBXdLGkM8l5hJPWpARebmTnPfP61tEh9SdUPSC8cC8Z5e469dDQ6T9WZcFfDHcVeVsmWWtUXf31vu5X_IiMEEbnwqFopdoy9L5EfEOpdGW0wPe9uHL8MD9iSlpUj4x2O__4q3G00e4jcumJG22kgMHUGzrZjP6E_wJ-TwlfxSSU_qGp7dHWMIA0wXX5PCqhoZ9mh_atFRmZaNjq6Nj5ONNPq4JP-NjNDQAGCjfT7YpPtwxbbefYHcS8XaluacLXua5A4ex6Bqk5zA_Uav5ZK0SIJkLlK4xR4slbNmtJxBLnVuhcNj4pX_fT54EhIZqJeSNTlYqm8tjh25Eo50DnkMjZ-Gk9zkJVp_GuypRtbDY6fmJg5OzShQe4dWwgYUItILyFf-DabFA0Tw7caiD30DLWDk

###
GET https://qqx6xqycwfc0.c01-15.plentymarkets.com/rest/orders/40994?with[]=documents&with[]=payments
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNTJjODdmNGEyZGE2YjAzNmZiOTU1NmM1MTYzNGZmYTQ3NDM5ODA0NGY3NTk1YWM0YmE0ZTIxNmJiNDIxM2NmMDM5YWQwNDc4Y2MyNmQzNmYiLCJpYXQiOjE2MTIxOTgzMDUsIm5iZiI6MTYxMjE5ODMwNSwiZXhwIjoxNjEyMjg0NzA1LCJzdWIiOiIxMSIsInNjb3BlcyI6WyIqIl19.nhhJ4aO-Or3kNnfaQuory5YTI2BARc2j4WVQzC3rk2IYAvHsE_Px8rr7JENM8mwvzakro2YQ6b1tSY_xUYzI7mRlfznokZgUIzhmG5li2gYz4qDnjDkIZbGXtZPravnFCHSw0rSfjZzUSfR-F2giCrD50lENgzkrSBTsDyeMuHFLJtTemsQy7k1ToRuAwRkYXR2kEc6wwVYEikr4MKwEeQbjbFa4daLOBbnR1mVFUiemGZf0AdBp0wpYAHLIgIjhrkzrHsABZ1PHXubbY7SBXdLGkM8l5hJPWpARebmTnPfP61tEh9SdUPSC8cC8Z5e469dDQ6T9WZcFfDHcVeVsmWWtUXf31vu5X_IiMEEbnwqFopdoy9L5EfEOpdGW0wPe9uHL8MD9iSlpUj4x2O__4q3G00e4jcumJG22kgMHUGzrZjP6E_wJ-TwlfxSSU_qGp7dHWMIA0wXX5PCqhoZ9mh_atFRmZaNjq6Nj5ONNPq4JP-NjNDQAGCjfT7YpPtwxbbefYHcS8XaluacLXua5A4ex6Bqk5zA_Uav5ZK0SIJkLlK4xR4slbNmtJxBLnVuhcNj4pX_fT54EhIZqJeSNTlYqm8tjh25Eo50DnkMjZ-Gk9zkJVp_GuypRtbDY6fmJg5OzShQe4dWwgYUItILyFf-DabFA0Tw7caiD30DLWDk

###
GET https://qqx6xqycwfc0.c01-15.plentymarkets.com/rest/documents/10
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNTJjODdmNGEyZGE2YjAzNmZiOTU1NmM1MTYzNGZmYTQ3NDM5ODA0NGY3NTk1YWM0YmE0ZTIxNmJiNDIxM2NmMDM5YWQwNDc4Y2MyNmQzNmYiLCJpYXQiOjE2MTIxOTgzMDUsIm5iZiI6MTYxMjE5ODMwNSwiZXhwIjoxNjEyMjg0NzA1LCJzdWIiOiIxMSIsInNjb3BlcyI6WyIqIl19.nhhJ4aO-Or3kNnfaQuory5YTI2BARc2j4WVQzC3rk2IYAvHsE_Px8rr7JENM8mwvzakro2YQ6b1tSY_xUYzI7mRlfznokZgUIzhmG5li2gYz4qDnjDkIZbGXtZPravnFCHSw0rSfjZzUSfR-F2giCrD50lENgzkrSBTsDyeMuHFLJtTemsQy7k1ToRuAwRkYXR2kEc6wwVYEikr4MKwEeQbjbFa4daLOBbnR1mVFUiemGZf0AdBp0wpYAHLIgIjhrkzrHsABZ1PHXubbY7SBXdLGkM8l5hJPWpARebmTnPfP61tEh9SdUPSC8cC8Z5e469dDQ6T9WZcFfDHcVeVsmWWtUXf31vu5X_IiMEEbnwqFopdoy9L5EfEOpdGW0wPe9uHL8MD9iSlpUj4x2O__4q3G00e4jcumJG22kgMHUGzrZjP6E_wJ-TwlfxSSU_qGp7dHWMIA0wXX5PCqhoZ9mh_atFRmZaNjq6Nj5ONNPq4JP-NjNDQAGCjfT7YpPtwxbbefYHcS8XaluacLXua5A4ex6Bqk5zA_Uav5ZK0SIJkLlK4xR4slbNmtJxBLnVuhcNj4pX_fT54EhIZqJeSNTlYqm8tjh25Eo50DnkMjZ-Gk9zkJVp_GuypRtbDY6fmJg5OzShQe4dWwgYUItILyFf-DabFA0Tw7caiD30DLWDk



###
GET https://qqx6xqycwfc0.c01-15.plentymarkets.com/rest/payments/25024
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNTJjODdmNGEyZGE2YjAzNmZiOTU1NmM1MTYzNGZmYTQ3NDM5ODA0NGY3NTk1YWM0YmE0ZTIxNmJiNDIxM2NmMDM5YWQwNDc4Y2MyNmQzNmYiLCJpYXQiOjE2MTIxOTgzMDUsIm5iZiI6MTYxMjE5ODMwNSwiZXhwIjoxNjEyMjg0NzA1LCJzdWIiOiIxMSIsInNjb3BlcyI6WyIqIl19.nhhJ4aO-Or3kNnfaQuory5YTI2BARc2j4WVQzC3rk2IYAvHsE_Px8rr7JENM8mwvzakro2YQ6b1tSY_xUYzI7mRlfznokZgUIzhmG5li2gYz4qDnjDkIZbGXtZPravnFCHSw0rSfjZzUSfR-F2giCrD50lENgzkrSBTsDyeMuHFLJtTemsQy7k1ToRuAwRkYXR2kEc6wwVYEikr4MKwEeQbjbFa4daLOBbnR1mVFUiemGZf0AdBp0wpYAHLIgIjhrkzrHsABZ1PHXubbY7SBXdLGkM8l5hJPWpARebmTnPfP61tEh9SdUPSC8cC8Z5e469dDQ6T9WZcFfDHcVeVsmWWtUXf31vu5X_IiMEEbnwqFopdoy9L5EfEOpdGW0wPe9uHL8MD9iSlpUj4x2O__4q3G00e4jcumJG22kgMHUGzrZjP6E_wJ-TwlfxSSU_qGp7dHWMIA0wXX5PCqhoZ9mh_atFRmZaNjq6Nj5ONNPq4JP-NjNDQAGCjfT7YpPtwxbbefYHcS8XaluacLXua5A4ex6Bqk5zA_Uav5ZK0SIJkLlK4xR4slbNmtJxBLnVuhcNj4pX_fT54EhIZqJeSNTlYqm8tjh25Eo50DnkMjZ-Gk9zkJVp_GuypRtbDY6fmJg5OzShQe4dWwgYUItILyFf-DabFA0Tw7caiD30DLWDk



