###
GET https://5lb6aot5e3yq.c01-17.plentymarkets.com/rest/webstores
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiODIwY2UzMGFlYzBiNDVjYTUwNWM2MTYwMDhkYmVmOTQ0MDg1MTQyYTc2ZjU4ZDUwMjkxOTc2NGZkN2IxNjBmMTc0NDcyOWViN2M0ZjY1NDgiLCJpYXQiOjE2MDQyMzE4NDksIm5iZiI6MTYwNDIzMTg0OSwiZXhwIjoxNjA0MzE4MjQ5LCJzdWIiOiIyNCIsInNjb3BlcyI6WyIqIl19.VjZIWwE_iGuLyqAt57qrf8YInXSfVkiFzvycOJoq0uVMFdBZ-OlNE6HOcjHkVqYz0zqF6WjnZQL8TmnXoVSpY1xlRsOoyj7bXWDt8FdKxYlS6gP8936N-dZ6KwpAKslA4T3_xBGg0UT2O2uvO633wjptTnAbKKG8r6nPOfz-7YU62xST6iVBYllPeQAXg3Vrdo3_ixHVJH-AgrBvd5i8xev81V6P_5Xy8EwNEZc15KMeVrhfxVvzV_CN8hHa2_n--zbqRBwhpvGDidU_u36QlFIQhlZz3pjd1QbrB5Oox8N6ur7PGTvqAkagG6ZGkL0eLJeYWZ1Vbf_5_nJ8pF8ZwDQH60fG9RVT5iwnuvsbnaLG7lbBLzBxJvZYQOSwZRLDWdslWmVy0fQ3Dwmd0x6DeCyrP3BxsJ05tJWG7hMgd6UXSl0yx5G9qzjgpwB7va-a9YaXgsO7qMUqZbkIAhJSPbBajVJ_-88tI8GVr_yWF2sBDJ2EKrZVacu2E85aQTQmaVR1ohEk7serls3rWHwI_ZLU0qO9kMMGSqaxIt1cHLeZqHrjP0cfZPeixGQOfUSJZ8bvzMYv05eJBmXcIkJqJ34BB8esdP5qr0sNscR1G4Q_MiEwgBRxkkIaoWkBt58S76M2sLT4CuF1jPfIv2iH6BKMKk1iIvhQ1gvaR2ENMYA

