###
GET https://0ln54b0xbwq1.c01-16.plentymarkets.com/rest/pim/variations?with=additionalSkus%2CattributeValues%2Cbarcodes%2Ccategories%2Ccategories.categoryBranch%2Cbase%2Cbase.item%2Cbase.itemSerialNumber%2Cbase.feedback%2Cbase.crossSelling%2Cbase.texts%2Cbase.availability%2Cbase.images%2Cbase.shippingProfiles%2Cbase.stock%2Cbase.stockStorageLocations%2CbundleComponents%2Cclients%2CdefaultCategories%2Cimages%2Cmarkets%2CmarketIdentNumbers%2CsalesPrices%2Cskus%2Csupplier%2Csupplier.supplier%2Cwarehouses%2Cunit%2Ctags%2Cproperties%2Ccomments&itemsPerPage=50
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTc3ZGMzODljNzEzMjkyNmFlOTczNjU4NmU5MzUyOWMzODgyMDgzZjhhNTMwNzcwZDQ4NzljNWUxNDVlZmFmNThmZWQyZTE4Nzk4NmQzZTUiLCJpYXQiOjE2OTM0ODk5ODEuODA5NywibmJmIjoxNjkzNDg5OTgxLjgwOTcsImV4cCI6MTY5MzU3NjM4MS44MDc0LCJzdWIiOiI3Iiwic2NvcGVzIjpbIioiXX0.gKbvKmWaMJiDKUNMX9ukkeYiZru3nkH1LQ7oLtbu05AiP9XLfcCRxvdsBf9Q67iJXye9EyDCT5-MTscM2Sx_zac3tDVKFYilWAmcOMhowMto4DWNc4DA74Emm-gPc8i7zEWbbjGqTtFaucFg8Fi_608UPsp_XRwJFE37g_4nRMzzDfcFpdcKlA95I_TmlKzE44rNiMbJ5JI5fxTLdqkQUm8TI6mSaVA878h97qX1yTPD3fX4fMjkE-JeM256lvw--59vp1aK3jrwCEJYnnM76zO1-E5ZUmm8lGIiVibhg9CmI1pbC9C3kWoKuk-hh8XUhuUXWS3k4FMPNh6PyfOgyrdWz0h5047UYq2O4aVBmwZ2kZUCVrM2PsnsnC5vg_lILHeruYTMkgAK46sS2yVCO4NoaTC3ZpjhswaMRWsDDE5LIcpL8y3wBbYQXSp-rLMlwLxKhedCl567D98ffZ98g8BFb6ZRsK39SFJzgBbChALpWeCRpKd7UiGxW9vcF5lfmHTiX9ujO_Hs9D2PLNDTPVK-gg8SEG-U36P5OnrKvZ-Pu6clbpD2qHF5Ej7EVsA3XqV8DMy22cMxeZwZOS7OVpZqjdVNfuLxF92w2o_7vhHAc_n6lgbaEeTTpPYOGgL91gyazoBrEPNiUiR9rSPY61UDalWsQBFSUBuIHxEtRG4

###
GET https://0ln54b0xbwq1.c01-16.plentymarkets.com/rest/pim/variations?ids=8182&with=properties,properties.property
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTc3ZGMzODljNzEzMjkyNmFlOTczNjU4NmU5MzUyOWMzODgyMDgzZjhhNTMwNzcwZDQ4NzljNWUxNDVlZmFmNThmZWQyZTE4Nzk4NmQzZTUiLCJpYXQiOjE2OTM0ODk5ODEuODA5NywibmJmIjoxNjkzNDg5OTgxLjgwOTcsImV4cCI6MTY5MzU3NjM4MS44MDc0LCJzdWIiOiI3Iiwic2NvcGVzIjpbIioiXX0.gKbvKmWaMJiDKUNMX9ukkeYiZru3nkH1LQ7oLtbu05AiP9XLfcCRxvdsBf9Q67iJXye9EyDCT5-MTscM2Sx_zac3tDVKFYilWAmcOMhowMto4DWNc4DA74Emm-gPc8i7zEWbbjGqTtFaucFg8Fi_608UPsp_XRwJFE37g_4nRMzzDfcFpdcKlA95I_TmlKzE44rNiMbJ5JI5fxTLdqkQUm8TI6mSaVA878h97qX1yTPD3fX4fMjkE-JeM256lvw--59vp1aK3jrwCEJYnnM76zO1-E5ZUmm8lGIiVibhg9CmI1pbC9C3kWoKuk-hh8XUhuUXWS3k4FMPNh6PyfOgyrdWz0h5047UYq2O4aVBmwZ2kZUCVrM2PsnsnC5vg_lILHeruYTMkgAK46sS2yVCO4NoaTC3ZpjhswaMRWsDDE5LIcpL8y3wBbYQXSp-rLMlwLxKhedCl567D98ffZ98g8BFb6ZRsK39SFJzgBbChALpWeCRpKd7UiGxW9vcF5lfmHTiX9ujO_Hs9D2PLNDTPVK-gg8SEG-U36P5OnrKvZ-Pu6clbpD2qHF5Ej7EVsA3XqV8DMy22cMxeZwZOS7OVpZqjdVNfuLxF92w2o_7vhHAc_n6lgbaEeTTpPYOGgL91gyazoBrEPNiUiR9rSPY61UDalWsQBFSUBuIHxEtRG4
