###
GET https://0ln54b0xbwq1.c01-16.plentymarkets.com/rest/orders/30459
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzU0ZmNhY2RkMDc1NDY4ZDg5Mjc4YzcyNGRlODI1MDIyOGQ2NDA2NDhiODJhNWUzOGVlMzYxMzA4ZDk5MzBlNzQwOTRiYjM4NWY2YWNhNzMiLCJpYXQiOjE2ODc5NTMxNjIuODc0NywibmJmIjoxNjg3OTUzMTYyLjg3NDcsImV4cCI6MTY4ODAzOTU2Mi44NzMxLCJzdWIiOiI3Iiwic2NvcGVzIjpbIioiXX0.rzyayBxjrIClWvhdwjBb6CldBZmI1PcuQi6BWI9ZpDKd5KxmbUIMWfvfYA_3o0DRt3ENssbGxEmCipGyxq6FIk8SARhZF5nLKroke_hzy52fYsPeo5grScwT4RSUvqrJNmsgbN-l2djq8x6DKLpAi1U6How2C2XHjR6oHxmfEpoIxjpnmAPiybzK3Pr-Gr021pW3vDEsX2TXUaVlIF5tX6dz-i0FRd9zqn864CXGkepxt8mIrf0idZDgiDMY8BMNF83AutGU9uvls98L7rvAaXkqD4l_9GL8qnJsIn2pKjIYB65KYkU1A9N20MPY8pRUjG_ZTWtrEdJEPAcTnbhEjGbe51k6WztCvj5sc0vx-M4X6PodmC-soCvnI6Dzsj73ZtjGxEXhMQDgBthzyQWiFLYVuHly_fDfAtcj3q3oj6fCNjipc1YrgpfeWBYE7uNTpF0F1DB5hLLnk5aH-TxaMCsogePgJmdYZMJYWkU2pEd-Gv_Jk1c6XSKYnsArcfvX7yKe11Hf2Kf6a042HUQ8eOG4fLox4OfHLh0xy9VIxzlmsNdwJxc80UfKgOnPb8Nx4Y24NwK0a4tjRPTkdBfNpOZoDXesmadMCSls10K2nP3o4b5Gj8Fb7wzRG2ihB-d-OxcNrIMszc81yk9qlrlGGB16-47u543ZcOijgAwLVuU

