###
GET https://omjfa5ubmq1v.c01-16.plentymarkets.com/rest/payments/methods
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYWM0NTU4M2JhNGNjMDhjZWM4YjdjNjE3Mjc5MmZiYzI5MGRlZWRlYWVhY2UwYjFiZjc1NmQ2ZTg3MDI5NmNhMDBjNmI4N2FkMDg5NjdlN2UiLCJpYXQiOjE2MTQ2MTM5ODEsIm5iZiI6MTYxNDYxMzk4MSwiZXhwIjoxNjE0NzAwMzgxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.kTaWQ0BLVcp5PVhq12roEgGkTOJQNInx6MIH-y2QfFMwqaWgPD3nE-x0fuLPm2LsxIVUgeXuSRoxuNSMo1xosqyiUHUp1HDKPPDMPrFPHloaOfIKObL2RwjT8PDvsD6qO316iTBdpGwclWisfUeHCwoc8lS_BD6eLKNJHbzhq-jK7EquW-xjiV4teS86m49AeZTpIOa1fAR1s2a8mWqrk6iXJ1_Zz4uUYLBo9nquypfXHUk6cplZqCu4frH-O5CF5Nen6-nEYXFrrlb00tOa5yd1E4Qx0Yw_xi_cDqNoPuI8sUi-I-l_fa0bmLOVu7s75XzpBcKA3bD_iGe90HAyTzFjW_rxobp0ohLWfIBdydGzEAKcSO9QcdjbzvisLvf-0jzAtXkCvSKzaE3UF6aUcrOwdQd3Ebrobw7r_k0FTadP8TnCIa2OrX1cG1zBQZB6N9AAogmFSUhHVkqnskp5m4FyzbFa2VwDRZThAOanIdQzQ7dYKxmOyXl4Fg6a_0FYmVZE1YUY61wHdhzg3vSqTg-cP8iH9800vgamQeZ59ypBUgpNM2zyP8OZvaqFqi0ERrgRTxIXJl6IQgi7eieB8a2kSb7YZp1mxYdZmG4CY6p3R6mRFKxq2Boa5t3PxvuoFiXIKr7DvmuV5SPJHhSG5Ol0pFymSdB-03DOYPRK6f4

###
GET https://omjfa5ubmq1v.c01-16.plentymarkets.com/rest/payments/methods/6000
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYWM0NTU4M2JhNGNjMDhjZWM4YjdjNjE3Mjc5MmZiYzI5MGRlZWRlYWVhY2UwYjFiZjc1NmQ2ZTg3MDI5NmNhMDBjNmI4N2FkMDg5NjdlN2UiLCJpYXQiOjE2MTQ2MTM5ODEsIm5iZiI6MTYxNDYxMzk4MSwiZXhwIjoxNjE0NzAwMzgxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.kTaWQ0BLVcp5PVhq12roEgGkTOJQNInx6MIH-y2QfFMwqaWgPD3nE-x0fuLPm2LsxIVUgeXuSRoxuNSMo1xosqyiUHUp1HDKPPDMPrFPHloaOfIKObL2RwjT8PDvsD6qO316iTBdpGwclWisfUeHCwoc8lS_BD6eLKNJHbzhq-jK7EquW-xjiV4teS86m49AeZTpIOa1fAR1s2a8mWqrk6iXJ1_Zz4uUYLBo9nquypfXHUk6cplZqCu4frH-O5CF5Nen6-nEYXFrrlb00tOa5yd1E4Qx0Yw_xi_cDqNoPuI8sUi-I-l_fa0bmLOVu7s75XzpBcKA3bD_iGe90HAyTzFjW_rxobp0ohLWfIBdydGzEAKcSO9QcdjbzvisLvf-0jzAtXkCvSKzaE3UF6aUcrOwdQd3Ebrobw7r_k0FTadP8TnCIa2OrX1cG1zBQZB6N9AAogmFSUhHVkqnskp5m4FyzbFa2VwDRZThAOanIdQzQ7dYKxmOyXl4Fg6a_0FYmVZE1YUY61wHdhzg3vSqTg-cP8iH9800vgamQeZ59ypBUgpNM2zyP8OZvaqFqi0ERrgRTxIXJl6IQgi7eieB8a2kSb7YZp1mxYdZmG4CY6p3R6mRFKxq2Boa5t3PxvuoFiXIKr7DvmuV5SPJHhSG5Ol0pFymSdB-03DOYPRK6f4

###
GET https://omjfa5ubmq1v.c01-16.plentymarkets.com/rest/payments/methods/ebics
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYWM0NTU4M2JhNGNjMDhjZWM4YjdjNjE3Mjc5MmZiYzI5MGRlZWRlYWVhY2UwYjFiZjc1NmQ2ZTg3MDI5NmNhMDBjNmI4N2FkMDg5NjdlN2UiLCJpYXQiOjE2MTQ2MTM5ODEsIm5iZiI6MTYxNDYxMzk4MSwiZXhwIjoxNjE0NzAwMzgxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.kTaWQ0BLVcp5PVhq12roEgGkTOJQNInx6MIH-y2QfFMwqaWgPD3nE-x0fuLPm2LsxIVUgeXuSRoxuNSMo1xosqyiUHUp1HDKPPDMPrFPHloaOfIKObL2RwjT8PDvsD6qO316iTBdpGwclWisfUeHCwoc8lS_BD6eLKNJHbzhq-jK7EquW-xjiV4teS86m49AeZTpIOa1fAR1s2a8mWqrk6iXJ1_Zz4uUYLBo9nquypfXHUk6cplZqCu4frH-O5CF5Nen6-nEYXFrrlb00tOa5yd1E4Qx0Yw_xi_cDqNoPuI8sUi-I-l_fa0bmLOVu7s75XzpBcKA3bD_iGe90HAyTzFjW_rxobp0ohLWfIBdydGzEAKcSO9QcdjbzvisLvf-0jzAtXkCvSKzaE3UF6aUcrOwdQd3Ebrobw7r_k0FTadP8TnCIa2OrX1cG1zBQZB6N9AAogmFSUhHVkqnskp5m4FyzbFa2VwDRZThAOanIdQzQ7dYKxmOyXl4Fg6a_0FYmVZE1YUY61wHdhzg3vSqTg-cP8iH9800vgamQeZ59ypBUgpNM2zyP8OZvaqFqi0ERrgRTxIXJl6IQgi7eieB8a2kSb7YZp1mxYdZmG4CY6p3R6mRFKxq2Boa5t3PxvuoFiXIKr7DvmuV5SPJHhSG5Ol0pFymSdB-03DOYPRK6f4

###
GET https://omjfa5ubmq1v.c01-16.plentymarkets.com/rest/payments/methods/list
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYWM0NTU4M2JhNGNjMDhjZWM4YjdjNjE3Mjc5MmZiYzI5MGRlZWRlYWVhY2UwYjFiZjc1NmQ2ZTg3MDI5NmNhMDBjNmI4N2FkMDg5NjdlN2UiLCJpYXQiOjE2MTQ2MTM5ODEsIm5iZiI6MTYxNDYxMzk4MSwiZXhwIjoxNjE0NzAwMzgxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.kTaWQ0BLVcp5PVhq12roEgGkTOJQNInx6MIH-y2QfFMwqaWgPD3nE-x0fuLPm2LsxIVUgeXuSRoxuNSMo1xosqyiUHUp1HDKPPDMPrFPHloaOfIKObL2RwjT8PDvsD6qO316iTBdpGwclWisfUeHCwoc8lS_BD6eLKNJHbzhq-jK7EquW-xjiV4teS86m49AeZTpIOa1fAR1s2a8mWqrk6iXJ1_Zz4uUYLBo9nquypfXHUk6cplZqCu4frH-O5CF5Nen6-nEYXFrrlb00tOa5yd1E4Qx0Yw_xi_cDqNoPuI8sUi-I-l_fa0bmLOVu7s75XzpBcKA3bD_iGe90HAyTzFjW_rxobp0ohLWfIBdydGzEAKcSO9QcdjbzvisLvf-0jzAtXkCvSKzaE3UF6aUcrOwdQd3Ebrobw7r_k0FTadP8TnCIa2OrX1cG1zBQZB6N9AAogmFSUhHVkqnskp5m4FyzbFa2VwDRZThAOanIdQzQ7dYKxmOyXl4Fg6a_0FYmVZE1YUY61wHdhzg3vSqTg-cP8iH9800vgamQeZ59ypBUgpNM2zyP8OZvaqFqi0ERrgRTxIXJl6IQgi7eieB8a2kSb7YZp1mxYdZmG4CY6p3R6mRFKxq2Boa5t3PxvuoFiXIKr7DvmuV5SPJHhSG5Ol0pFymSdB-03DOYPRK6f4

###
GET https://omjfa5ubmq1v.c01-16.plentymarkets.com/rest/payments/methods/list/backend_active
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYWM0NTU4M2JhNGNjMDhjZWM4YjdjNjE3Mjc5MmZiYzI5MGRlZWRlYWVhY2UwYjFiZjc1NmQ2ZTg3MDI5NmNhMDBjNmI4N2FkMDg5NjdlN2UiLCJpYXQiOjE2MTQ2MTM5ODEsIm5iZiI6MTYxNDYxMzk4MSwiZXhwIjoxNjE0NzAwMzgxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.kTaWQ0BLVcp5PVhq12roEgGkTOJQNInx6MIH-y2QfFMwqaWgPD3nE-x0fuLPm2LsxIVUgeXuSRoxuNSMo1xosqyiUHUp1HDKPPDMPrFPHloaOfIKObL2RwjT8PDvsD6qO316iTBdpGwclWisfUeHCwoc8lS_BD6eLKNJHbzhq-jK7EquW-xjiV4teS86m49AeZTpIOa1fAR1s2a8mWqrk6iXJ1_Zz4uUYLBo9nquypfXHUk6cplZqCu4frH-O5CF5Nen6-nEYXFrrlb00tOa5yd1E4Qx0Yw_xi_cDqNoPuI8sUi-I-l_fa0bmLOVu7s75XzpBcKA3bD_iGe90HAyTzFjW_rxobp0ohLWfIBdydGzEAKcSO9QcdjbzvisLvf-0jzAtXkCvSKzaE3UF6aUcrOwdQd3Ebrobw7r_k0FTadP8TnCIa2OrX1cG1zBQZB6N9AAogmFSUhHVkqnskp5m4FyzbFa2VwDRZThAOanIdQzQ7dYKxmOyXl4Fg6a_0FYmVZE1YUY61wHdhzg3vSqTg-cP8iH9800vgamQeZ59ypBUgpNM2zyP8OZvaqFqi0ERrgRTxIXJl6IQgi7eieB8a2kSb7YZp1mxYdZmG4CY6p3R6mRFKxq2Boa5t3PxvuoFiXIKr7DvmuV5SPJHhSG5Ol0pFymSdB-03DOYPRK6f4

###
GET https://omjfa5ubmq1v.c01-16.plentymarkets.com/rest/payments/methodNames/6000
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYWM0NTU4M2JhNGNjMDhjZWM4YjdjNjE3Mjc5MmZiYzI5MGRlZWRlYWVhY2UwYjFiZjc1NmQ2ZTg3MDI5NmNhMDBjNmI4N2FkMDg5NjdlN2UiLCJpYXQiOjE2MTQ2MTM5ODEsIm5iZiI6MTYxNDYxMzk4MSwiZXhwIjoxNjE0NzAwMzgxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.kTaWQ0BLVcp5PVhq12roEgGkTOJQNInx6MIH-y2QfFMwqaWgPD3nE-x0fuLPm2LsxIVUgeXuSRoxuNSMo1xosqyiUHUp1HDKPPDMPrFPHloaOfIKObL2RwjT8PDvsD6qO316iTBdpGwclWisfUeHCwoc8lS_BD6eLKNJHbzhq-jK7EquW-xjiV4teS86m49AeZTpIOa1fAR1s2a8mWqrk6iXJ1_Zz4uUYLBo9nquypfXHUk6cplZqCu4frH-O5CF5Nen6-nEYXFrrlb00tOa5yd1E4Qx0Yw_xi_cDqNoPuI8sUi-I-l_fa0bmLOVu7s75XzpBcKA3bD_iGe90HAyTzFjW_rxobp0ohLWfIBdydGzEAKcSO9QcdjbzvisLvf-0jzAtXkCvSKzaE3UF6aUcrOwdQd3Ebrobw7r_k0FTadP8TnCIa2OrX1cG1zBQZB6N9AAogmFSUhHVkqnskp5m4FyzbFa2VwDRZThAOanIdQzQ7dYKxmOyXl4Fg6a_0FYmVZE1YUY61wHdhzg3vSqTg-cP8iH9800vgamQeZ59ypBUgpNM2zyP8OZvaqFqi0ERrgRTxIXJl6IQgi7eieB8a2kSb7YZp1mxYdZmG4CY6p3R6mRFKxq2Boa5t3PxvuoFiXIKr7DvmuV5SPJHhSG5Ol0pFymSdB-03DOYPRK6f4

###
GET https://omjfa5ubmq1v.c01-16.plentymarkets.com/rest/payments/methods/ebics
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYWM0NTU4M2JhNGNjMDhjZWM4YjdjNjE3Mjc5MmZiYzI5MGRlZWRlYWVhY2UwYjFiZjc1NmQ2ZTg3MDI5NmNhMDBjNmI4N2FkMDg5NjdlN2UiLCJpYXQiOjE2MTQ2MTM5ODEsIm5iZiI6MTYxNDYxMzk4MSwiZXhwIjoxNjE0NzAwMzgxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.kTaWQ0BLVcp5PVhq12roEgGkTOJQNInx6MIH-y2QfFMwqaWgPD3nE-x0fuLPm2LsxIVUgeXuSRoxuNSMo1xosqyiUHUp1HDKPPDMPrFPHloaOfIKObL2RwjT8PDvsD6qO316iTBdpGwclWisfUeHCwoc8lS_BD6eLKNJHbzhq-jK7EquW-xjiV4teS86m49AeZTpIOa1fAR1s2a8mWqrk6iXJ1_Zz4uUYLBo9nquypfXHUk6cplZqCu4frH-O5CF5Nen6-nEYXFrrlb00tOa5yd1E4Qx0Yw_xi_cDqNoPuI8sUi-I-l_fa0bmLOVu7s75XzpBcKA3bD_iGe90HAyTzFjW_rxobp0ohLWfIBdydGzEAKcSO9QcdjbzvisLvf-0jzAtXkCvSKzaE3UF6aUcrOwdQd3Ebrobw7r_k0FTadP8TnCIa2OrX1cG1zBQZB6N9AAogmFSUhHVkqnskp5m4FyzbFa2VwDRZThAOanIdQzQ7dYKxmOyXl4Fg6a_0FYmVZE1YUY61wHdhzg3vSqTg-cP8iH9800vgamQeZ59ypBUgpNM2zyP8OZvaqFqi0ERrgRTxIXJl6IQgi7eieB8a2kSb7YZp1mxYdZmG4CY6p3R6mRFKxq2Boa5t3PxvuoFiXIKr7DvmuV5SPJHhSG5Ol0pFymSdB-03DOYPRK6f4

###
GET https://omjfa5ubmq1v.c01-16.plentymarkets.com/rest/payments/methods/ebics
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYWM0NTU4M2JhNGNjMDhjZWM4YjdjNjE3Mjc5MmZiYzI5MGRlZWRlYWVhY2UwYjFiZjc1NmQ2ZTg3MDI5NmNhMDBjNmI4N2FkMDg5NjdlN2UiLCJpYXQiOjE2MTQ2MTM5ODEsIm5iZiI6MTYxNDYxMzk4MSwiZXhwIjoxNjE0NzAwMzgxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.kTaWQ0BLVcp5PVhq12roEgGkTOJQNInx6MIH-y2QfFMwqaWgPD3nE-x0fuLPm2LsxIVUgeXuSRoxuNSMo1xosqyiUHUp1HDKPPDMPrFPHloaOfIKObL2RwjT8PDvsD6qO316iTBdpGwclWisfUeHCwoc8lS_BD6eLKNJHbzhq-jK7EquW-xjiV4teS86m49AeZTpIOa1fAR1s2a8mWqrk6iXJ1_Zz4uUYLBo9nquypfXHUk6cplZqCu4frH-O5CF5Nen6-nEYXFrrlb00tOa5yd1E4Qx0Yw_xi_cDqNoPuI8sUi-I-l_fa0bmLOVu7s75XzpBcKA3bD_iGe90HAyTzFjW_rxobp0ohLWfIBdydGzEAKcSO9QcdjbzvisLvf-0jzAtXkCvSKzaE3UF6aUcrOwdQd3Ebrobw7r_k0FTadP8TnCIa2OrX1cG1zBQZB6N9AAogmFSUhHVkqnskp5m4FyzbFa2VwDRZThAOanIdQzQ7dYKxmOyXl4Fg6a_0FYmVZE1YUY61wHdhzg3vSqTg-cP8iH9800vgamQeZ59ypBUgpNM2zyP8OZvaqFqi0ERrgRTxIXJl6IQgi7eieB8a2kSb7YZp1mxYdZmG4CY6p3R6mRFKxq2Boa5t3PxvuoFiXIKr7DvmuV5SPJHhSG5Ol0pFymSdB-03DOYPRK6f4
