
###
GET https://43krt0tbdqmu.c01-14.plentymarkets.com/rest/items/sales_prices
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYjQ2OGU0ODg2OTQ3OWJiMzczYTE5ZTcyMjNiZTY2MDNiMTU4MjU2YTY0ZjM3NzkwZGRiNDJiZWQwMGQ0ZTk1NWRkZmJlMGIxYTdkMTkxOGYiLCJpYXQiOjE1OTY5MTM2NzQsIm5iZiI6MTU5NjkxMzY3NCwiZXhwIjoxNTk3MDAwMDc0LCJzdWIiOiIzMSIsInNjb3BlcyI6WyIqIl19.Thsoi4JRt-MRE3Xag5DOBADe6Sf_kPd80zJFe1Ms0aZ-ycaB5mIiVud_Wxp4t6xUXJ43cXwWws-YxHOLiXmYJG_Ju52j3QTTwZFcNugyIyfRuT4CS_habd1BvJCpRl2WxZJ-9_eOIcj7tkjB9FJdFLwFDPvbQqPRKim9BRQmz8ax0hQfxMCcp6nSdC5yTGVlOUPA1ZdYHcHH3bb1-NNqxdP6-1HLxNYWwcIk-DM3r-f87M6fohFqoga4GKPj3wB7-9Uulc5U2v8F6w8s6RfDLLAjpnE7AT6aVYrdCQ9CpWInbxy2aq1EypLMBT0h5SRCOT9Ptmz7UYjCQE-fc72p40rLQ643Jj7TApk5EkUqiIxGAEzlFFBRVJq9ZAT6SJYjEiW2Z6LrYFsy7nIX7rK2WyrGhe_l_ixSguv9e4C3HJrXXySdYqA48b26iBV3_Zs7NQ8ne7BEiRzKV82tlNKuL9Etp4F21Njg5gMoIix6Owdlog07jLxqjCJXrMUtnNWqD90c_lkqAjasX4s6nhcMDjlIvh54MgaidYjaJWuYXyba2ylGQNoeKPGF-Cem4vV8Hrq76mNGbMUrtF-xjKnDlNScnHGIBOf2Bknr36QqVRG7c8INJ9TUPDM9v9XE5GPekv9C9cag5TkGsuDFR-J2qajBxHSmSIvcOUKbqj_DdEU

###
GET https://43krt0tbdqmu.c01-14.plentymarkets.com/rest/item_sets
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYjQ2OGU0ODg2OTQ3OWJiMzczYTE5ZTcyMjNiZTY2MDNiMTU4MjU2YTY0ZjM3NzkwZGRiNDJiZWQwMGQ0ZTk1NWRkZmJlMGIxYTdkMTkxOGYiLCJpYXQiOjE1OTY5MTM2NzQsIm5iZiI6MTU5NjkxMzY3NCwiZXhwIjoxNTk3MDAwMDc0LCJzdWIiOiIzMSIsInNjb3BlcyI6WyIqIl19.Thsoi4JRt-MRE3Xag5DOBADe6Sf_kPd80zJFe1Ms0aZ-ycaB5mIiVud_Wxp4t6xUXJ43cXwWws-YxHOLiXmYJG_Ju52j3QTTwZFcNugyIyfRuT4CS_habd1BvJCpRl2WxZJ-9_eOIcj7tkjB9FJdFLwFDPvbQqPRKim9BRQmz8ax0hQfxMCcp6nSdC5yTGVlOUPA1ZdYHcHH3bb1-NNqxdP6-1HLxNYWwcIk-DM3r-f87M6fohFqoga4GKPj3wB7-9Uulc5U2v8F6w8s6RfDLLAjpnE7AT6aVYrdCQ9CpWInbxy2aq1EypLMBT0h5SRCOT9Ptmz7UYjCQE-fc72p40rLQ643Jj7TApk5EkUqiIxGAEzlFFBRVJq9ZAT6SJYjEiW2Z6LrYFsy7nIX7rK2WyrGhe_l_ixSguv9e4C3HJrXXySdYqA48b26iBV3_Zs7NQ8ne7BEiRzKV82tlNKuL9Etp4F21Njg5gMoIix6Owdlog07jLxqjCJXrMUtnNWqD90c_lkqAjasX4s6nhcMDjlIvh54MgaidYjaJWuYXyba2ylGQNoeKPGF-Cem4vV8Hrq76mNGbMUrtF-xjKnDlNScnHGIBOf2Bknr36QqVRG7c8INJ9TUPDM9v9XE5GPekv9C9cag5TkGsuDFR-J2qajBxHSmSIvcOUKbqj_DdEU

###
GET https://43krt0tbdqmu.c01-14.plentymarkets.com/rest/item_sets
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYjQ2OGU0ODg2OTQ3OWJiMzczYTE5ZTcyMjNiZTY2MDNiMTU4MjU2YTY0ZjM3NzkwZGRiNDJiZWQwMGQ0ZTk1NWRkZmJlMGIxYTdkMTkxOGYiLCJpYXQiOjE1OTY5MTM2NzQsIm5iZiI6MTU5NjkxMzY3NCwiZXhwIjoxNTk3MDAwMDc0LCJzdWIiOiIzMSIsInNjb3BlcyI6WyIqIl19.Thsoi4JRt-MRE3Xag5DOBADe6Sf_kPd80zJFe1Ms0aZ-ycaB5mIiVud_Wxp4t6xUXJ43cXwWws-YxHOLiXmYJG_Ju52j3QTTwZFcNugyIyfRuT4CS_habd1BvJCpRl2WxZJ-9_eOIcj7tkjB9FJdFLwFDPvbQqPRKim9BRQmz8ax0hQfxMCcp6nSdC5yTGVlOUPA1ZdYHcHH3bb1-NNqxdP6-1HLxNYWwcIk-DM3r-f87M6fohFqoga4GKPj3wB7-9Uulc5U2v8F6w8s6RfDLLAjpnE7AT6aVYrdCQ9CpWInbxy2aq1EypLMBT0h5SRCOT9Ptmz7UYjCQE-fc72p40rLQ643Jj7TApk5EkUqiIxGAEzlFFBRVJq9ZAT6SJYjEiW2Z6LrYFsy7nIX7rK2WyrGhe_l_ixSguv9e4C3HJrXXySdYqA48b26iBV3_Zs7NQ8ne7BEiRzKV82tlNKuL9Etp4F21Njg5gMoIix6Owdlog07jLxqjCJXrMUtnNWqD90c_lkqAjasX4s6nhcMDjlIvh54MgaidYjaJWuYXyba2ylGQNoeKPGF-Cem4vV8Hrq76mNGbMUrtF-xjKnDlNScnHGIBOf2Bknr36QqVRG7c8INJ9TUPDM9v9XE5GPekv9C9cag5TkGsuDFR-J2qajBxHSmSIvcOUKbqj_DdEU

