
###
GET https://7hkykyo11q5u.c01-17.plentymarkets.com/rest/availabilities
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDZkMjM3M2ZiOWUxYjI3NTNmMTQ5MGRjZTI0MTZmMGE1MjZhNjQzZjQ5MmFiNDk2MTViMTliZjAzZTE3ZGVlZGY1ZGIyMmE2ZWYzN2FlNjEiLCJpYXQiOjE2MDM5OTI2MDcsIm5iZiI6MTYwMzk5MjYwNywiZXhwIjoxNjA0MDc5MDA3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.ecFm6IB4H5hRe6umyah2UeRKGom5vttwADMiT-QP3npuimaUvS2Wor8lgS-6eD9IsMKr2_3FDJAuB9_xYiGetUc4KxQUFOxuZIqbQWol0pLvGZyjXL140TQPMqvcXtRTSguV5ix4VLACUMf5ZQ4fMqKa9c63N-LtWAs2y0ujheQK3sjXEAxyDrOzD9hCfZlPOGZnA8egVC1quBOedvToZBOWMXt7L9KyKhEsy6xIkTAbfyvilgD4ZhVMR17cSHzPQLonufzsic4h-FWEG5f51y7n3gx3fwAVDcnis_fcCTDO77ks0uYaHcWuEcT8r8sa1T67_RvlSh2X33gpsYFbY0XUrmb91J1up6aoh2iBINeptnudM2iWrLOhH7z-oQvlTYum93VB9sBZp1NvPoDEhbKAxJnP6kVyUJeY2yGX_VebnAYoPJkz6Vr3Y2szR0ZQHAzWMXrSmjqLQ_e02s9LiYNx_il1yZTKgcd8CrqfcvhfU6dYr-ZtF2KE73TZeTAWuGLAr4YN3azGiNVkBQEPanumzIyBh24sOz1wr-UBHOMD9O-Sow0KAdscRxItEIu1B13pi8LZQhd4B8mM8ARd0MbFrnyfMlx1O7QO-UdBsE2uaClGxPKJqEXMgh4xL3wparTBNdVwenT7jT6e8tzT-PcUKG1jeSm0PGYDjtbsQ_4

###
GET https://7hkykyo11q5u.c01-17.plentymarkets.com/rest/item_sets
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDZkMjM3M2ZiOWUxYjI3NTNmMTQ5MGRjZTI0MTZmMGE1MjZhNjQzZjQ5MmFiNDk2MTViMTliZjAzZTE3ZGVlZGY1ZGIyMmE2ZWYzN2FlNjEiLCJpYXQiOjE2MDM5OTI2MDcsIm5iZiI6MTYwMzk5MjYwNywiZXhwIjoxNjA0MDc5MDA3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.ecFm6IB4H5hRe6umyah2UeRKGom5vttwADMiT-QP3npuimaUvS2Wor8lgS-6eD9IsMKr2_3FDJAuB9_xYiGetUc4KxQUFOxuZIqbQWol0pLvGZyjXL140TQPMqvcXtRTSguV5ix4VLACUMf5ZQ4fMqKa9c63N-LtWAs2y0ujheQK3sjXEAxyDrOzD9hCfZlPOGZnA8egVC1quBOedvToZBOWMXt7L9KyKhEsy6xIkTAbfyvilgD4ZhVMR17cSHzPQLonufzsic4h-FWEG5f51y7n3gx3fwAVDcnis_fcCTDO77ks0uYaHcWuEcT8r8sa1T67_RvlSh2X33gpsYFbY0XUrmb91J1up6aoh2iBINeptnudM2iWrLOhH7z-oQvlTYum93VB9sBZp1NvPoDEhbKAxJnP6kVyUJeY2yGX_VebnAYoPJkz6Vr3Y2szR0ZQHAzWMXrSmjqLQ_e02s9LiYNx_il1yZTKgcd8CrqfcvhfU6dYr-ZtF2KE73TZeTAWuGLAr4YN3azGiNVkBQEPanumzIyBh24sOz1wr-UBHOMD9O-Sow0KAdscRxItEIu1B13pi8LZQhd4B8mM8ARd0MbFrnyfMlx1O7QO-UdBsE2uaClGxPKJqEXMgh4xL3wparTBNdVwenT7jT6e8tzT-PcUKG1jeSm0PGYDjtbsQ_4

###
GET https://7hkykyo11q5u.c01-17.plentymarkets.com/rest/items
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDZkMjM3M2ZiOWUxYjI3NTNmMTQ5MGRjZTI0MTZmMGE1MjZhNjQzZjQ5MmFiNDk2MTViMTliZjAzZTE3ZGVlZGY1ZGIyMmE2ZWYzN2FlNjEiLCJpYXQiOjE2MDM5OTI2MDcsIm5iZiI6MTYwMzk5MjYwNywiZXhwIjoxNjA0MDc5MDA3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.ecFm6IB4H5hRe6umyah2UeRKGom5vttwADMiT-QP3npuimaUvS2Wor8lgS-6eD9IsMKr2_3FDJAuB9_xYiGetUc4KxQUFOxuZIqbQWol0pLvGZyjXL140TQPMqvcXtRTSguV5ix4VLACUMf5ZQ4fMqKa9c63N-LtWAs2y0ujheQK3sjXEAxyDrOzD9hCfZlPOGZnA8egVC1quBOedvToZBOWMXt7L9KyKhEsy6xIkTAbfyvilgD4ZhVMR17cSHzPQLonufzsic4h-FWEG5f51y7n3gx3fwAVDcnis_fcCTDO77ks0uYaHcWuEcT8r8sa1T67_RvlSh2X33gpsYFbY0XUrmb91J1up6aoh2iBINeptnudM2iWrLOhH7z-oQvlTYum93VB9sBZp1NvPoDEhbKAxJnP6kVyUJeY2yGX_VebnAYoPJkz6Vr3Y2szR0ZQHAzWMXrSmjqLQ_e02s9LiYNx_il1yZTKgcd8CrqfcvhfU6dYr-ZtF2KE73TZeTAWuGLAr4YN3azGiNVkBQEPanumzIyBh24sOz1wr-UBHOMD9O-Sow0KAdscRxItEIu1B13pi8LZQhd4B8mM8ARd0MbFrnyfMlx1O7QO-UdBsE2uaClGxPKJqEXMgh4xL3wparTBNdVwenT7jT6e8tzT-PcUKG1jeSm0PGYDjtbsQ_4

###
GET https://7hkykyo11q5u.c01-17.plentymarkets.com/rest/items/7769
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDZkMjM3M2ZiOWUxYjI3NTNmMTQ5MGRjZTI0MTZmMGE1MjZhNjQzZjQ5MmFiNDk2MTViMTliZjAzZTE3ZGVlZGY1ZGIyMmE2ZWYzN2FlNjEiLCJpYXQiOjE2MDM5OTI2MDcsIm5iZiI6MTYwMzk5MjYwNywiZXhwIjoxNjA0MDc5MDA3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.ecFm6IB4H5hRe6umyah2UeRKGom5vttwADMiT-QP3npuimaUvS2Wor8lgS-6eD9IsMKr2_3FDJAuB9_xYiGetUc4KxQUFOxuZIqbQWol0pLvGZyjXL140TQPMqvcXtRTSguV5ix4VLACUMf5ZQ4fMqKa9c63N-LtWAs2y0ujheQK3sjXEAxyDrOzD9hCfZlPOGZnA8egVC1quBOedvToZBOWMXt7L9KyKhEsy6xIkTAbfyvilgD4ZhVMR17cSHzPQLonufzsic4h-FWEG5f51y7n3gx3fwAVDcnis_fcCTDO77ks0uYaHcWuEcT8r8sa1T67_RvlSh2X33gpsYFbY0XUrmb91J1up6aoh2iBINeptnudM2iWrLOhH7z-oQvlTYum93VB9sBZp1NvPoDEhbKAxJnP6kVyUJeY2yGX_VebnAYoPJkz6Vr3Y2szR0ZQHAzWMXrSmjqLQ_e02s9LiYNx_il1yZTKgcd8CrqfcvhfU6dYr-ZtF2KE73TZeTAWuGLAr4YN3azGiNVkBQEPanumzIyBh24sOz1wr-UBHOMD9O-Sow0KAdscRxItEIu1B13pi8LZQhd4B8mM8ARd0MbFrnyfMlx1O7QO-UdBsE2uaClGxPKJqEXMgh4xL3wparTBNdVwenT7jT6e8tzT-PcUKG1jeSm0PGYDjtbsQ_4


###
GET https://7hkykyo11q5u.c01-17.plentymarkets.com/rest/items/variations
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDZkMjM3M2ZiOWUxYjI3NTNmMTQ5MGRjZTI0MTZmMGE1MjZhNjQzZjQ5MmFiNDk2MTViMTliZjAzZTE3ZGVlZGY1ZGIyMmE2ZWYzN2FlNjEiLCJpYXQiOjE2MDM5OTI2MDcsIm5iZiI6MTYwMzk5MjYwNywiZXhwIjoxNjA0MDc5MDA3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.ecFm6IB4H5hRe6umyah2UeRKGom5vttwADMiT-QP3npuimaUvS2Wor8lgS-6eD9IsMKr2_3FDJAuB9_xYiGetUc4KxQUFOxuZIqbQWol0pLvGZyjXL140TQPMqvcXtRTSguV5ix4VLACUMf5ZQ4fMqKa9c63N-LtWAs2y0ujheQK3sjXEAxyDrOzD9hCfZlPOGZnA8egVC1quBOedvToZBOWMXt7L9KyKhEsy6xIkTAbfyvilgD4ZhVMR17cSHzPQLonufzsic4h-FWEG5f51y7n3gx3fwAVDcnis_fcCTDO77ks0uYaHcWuEcT8r8sa1T67_RvlSh2X33gpsYFbY0XUrmb91J1up6aoh2iBINeptnudM2iWrLOhH7z-oQvlTYum93VB9sBZp1NvPoDEhbKAxJnP6kVyUJeY2yGX_VebnAYoPJkz6Vr3Y2szR0ZQHAzWMXrSmjqLQ_e02s9LiYNx_il1yZTKgcd8CrqfcvhfU6dYr-ZtF2KE73TZeTAWuGLAr4YN3azGiNVkBQEPanumzIyBh24sOz1wr-UBHOMD9O-Sow0KAdscRxItEIu1B13pi8LZQhd4B8mM8ARd0MbFrnyfMlx1O7QO-UdBsE2uaClGxPKJqEXMgh4xL3wparTBNdVwenT7jT6e8tzT-PcUKG1jeSm0PGYDjtbsQ_4

###
GET https://7hkykyo11q5u.c01-17.plentymarkets.com/rest/items/attributes
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDZkMjM3M2ZiOWUxYjI3NTNmMTQ5MGRjZTI0MTZmMGE1MjZhNjQzZjQ5MmFiNDk2MTViMTliZjAzZTE3ZGVlZGY1ZGIyMmE2ZWYzN2FlNjEiLCJpYXQiOjE2MDM5OTI2MDcsIm5iZiI6MTYwMzk5MjYwNywiZXhwIjoxNjA0MDc5MDA3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.ecFm6IB4H5hRe6umyah2UeRKGom5vttwADMiT-QP3npuimaUvS2Wor8lgS-6eD9IsMKr2_3FDJAuB9_xYiGetUc4KxQUFOxuZIqbQWol0pLvGZyjXL140TQPMqvcXtRTSguV5ix4VLACUMf5ZQ4fMqKa9c63N-LtWAs2y0ujheQK3sjXEAxyDrOzD9hCfZlPOGZnA8egVC1quBOedvToZBOWMXt7L9KyKhEsy6xIkTAbfyvilgD4ZhVMR17cSHzPQLonufzsic4h-FWEG5f51y7n3gx3fwAVDcnis_fcCTDO77ks0uYaHcWuEcT8r8sa1T67_RvlSh2X33gpsYFbY0XUrmb91J1up6aoh2iBINeptnudM2iWrLOhH7z-oQvlTYum93VB9sBZp1NvPoDEhbKAxJnP6kVyUJeY2yGX_VebnAYoPJkz6Vr3Y2szR0ZQHAzWMXrSmjqLQ_e02s9LiYNx_il1yZTKgcd8CrqfcvhfU6dYr-ZtF2KE73TZeTAWuGLAr4YN3azGiNVkBQEPanumzIyBh24sOz1wr-UBHOMD9O-Sow0KAdscRxItEIu1B13pi8LZQhd4B8mM8ARd0MbFrnyfMlx1O7QO-UdBsE2uaClGxPKJqEXMgh4xL3wparTBNdVwenT7jT6e8tzT-PcUKG1jeSm0PGYDjtbsQ_4

###
GET https://7hkykyo11q5u.c01-17.plentymarkets.com/rest/items/barcodes
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDZkMjM3M2ZiOWUxYjI3NTNmMTQ5MGRjZTI0MTZmMGE1MjZhNjQzZjQ5MmFiNDk2MTViMTliZjAzZTE3ZGVlZGY1ZGIyMmE2ZWYzN2FlNjEiLCJpYXQiOjE2MDM5OTI2MDcsIm5iZiI6MTYwMzk5MjYwNywiZXhwIjoxNjA0MDc5MDA3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.ecFm6IB4H5hRe6umyah2UeRKGom5vttwADMiT-QP3npuimaUvS2Wor8lgS-6eD9IsMKr2_3FDJAuB9_xYiGetUc4KxQUFOxuZIqbQWol0pLvGZyjXL140TQPMqvcXtRTSguV5ix4VLACUMf5ZQ4fMqKa9c63N-LtWAs2y0ujheQK3sjXEAxyDrOzD9hCfZlPOGZnA8egVC1quBOedvToZBOWMXt7L9KyKhEsy6xIkTAbfyvilgD4ZhVMR17cSHzPQLonufzsic4h-FWEG5f51y7n3gx3fwAVDcnis_fcCTDO77ks0uYaHcWuEcT8r8sa1T67_RvlSh2X33gpsYFbY0XUrmb91J1up6aoh2iBINeptnudM2iWrLOhH7z-oQvlTYum93VB9sBZp1NvPoDEhbKAxJnP6kVyUJeY2yGX_VebnAYoPJkz6Vr3Y2szR0ZQHAzWMXrSmjqLQ_e02s9LiYNx_il1yZTKgcd8CrqfcvhfU6dYr-ZtF2KE73TZeTAWuGLAr4YN3azGiNVkBQEPanumzIyBh24sOz1wr-UBHOMD9O-Sow0KAdscRxItEIu1B13pi8LZQhd4B8mM8ARd0MbFrnyfMlx1O7QO-UdBsE2uaClGxPKJqEXMgh4xL3wparTBNdVwenT7jT6e8tzT-PcUKG1jeSm0PGYDjtbsQ_4

###
GET https://7hkykyo11q5u.c01-17.plentymarkets.com/rest/items/item_shipping_profiles
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDZkMjM3M2ZiOWUxYjI3NTNmMTQ5MGRjZTI0MTZmMGE1MjZhNjQzZjQ5MmFiNDk2MTViMTliZjAzZTE3ZGVlZGY1ZGIyMmE2ZWYzN2FlNjEiLCJpYXQiOjE2MDM5OTI2MDcsIm5iZiI6MTYwMzk5MjYwNywiZXhwIjoxNjA0MDc5MDA3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.ecFm6IB4H5hRe6umyah2UeRKGom5vttwADMiT-QP3npuimaUvS2Wor8lgS-6eD9IsMKr2_3FDJAuB9_xYiGetUc4KxQUFOxuZIqbQWol0pLvGZyjXL140TQPMqvcXtRTSguV5ix4VLACUMf5ZQ4fMqKa9c63N-LtWAs2y0ujheQK3sjXEAxyDrOzD9hCfZlPOGZnA8egVC1quBOedvToZBOWMXt7L9KyKhEsy6xIkTAbfyvilgD4ZhVMR17cSHzPQLonufzsic4h-FWEG5f51y7n3gx3fwAVDcnis_fcCTDO77ks0uYaHcWuEcT8r8sa1T67_RvlSh2X33gpsYFbY0XUrmb91J1up6aoh2iBINeptnudM2iWrLOhH7z-oQvlTYum93VB9sBZp1NvPoDEhbKAxJnP6kVyUJeY2yGX_VebnAYoPJkz6Vr3Y2szR0ZQHAzWMXrSmjqLQ_e02s9LiYNx_il1yZTKgcd8CrqfcvhfU6dYr-ZtF2KE73TZeTAWuGLAr4YN3azGiNVkBQEPanumzIyBh24sOz1wr-UBHOMD9O-Sow0KAdscRxItEIu1B13pi8LZQhd4B8mM8ARd0MbFrnyfMlx1O7QO-UdBsE2uaClGxPKJqEXMgh4xL3wparTBNdVwenT7jT6e8tzT-PcUKG1jeSm0PGYDjtbsQ_4

###
POST https://7hkykyo11q5u.c01-17.plentymarkets.com/rest/items/item_shipping_profiles
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDZkMjM3M2ZiOWUxYjI3NTNmMTQ5MGRjZTI0MTZmMGE1MjZhNjQzZjQ5MmFiNDk2MTViMTliZjAzZTE3ZGVlZGY1ZGIyMmE2ZWYzN2FlNjEiLCJpYXQiOjE2MDM5OTI2MDcsIm5iZiI6MTYwMzk5MjYwNywiZXhwIjoxNjA0MDc5MDA3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.ecFm6IB4H5hRe6umyah2UeRKGom5vttwADMiT-QP3npuimaUvS2Wor8lgS-6eD9IsMKr2_3FDJAuB9_xYiGetUc4KxQUFOxuZIqbQWol0pLvGZyjXL140TQPMqvcXtRTSguV5ix4VLACUMf5ZQ4fMqKa9c63N-LtWAs2y0ujheQK3sjXEAxyDrOzD9hCfZlPOGZnA8egVC1quBOedvToZBOWMXt7L9KyKhEsy6xIkTAbfyvilgD4ZhVMR17cSHzPQLonufzsic4h-FWEG5f51y7n3gx3fwAVDcnis_fcCTDO77ks0uYaHcWuEcT8r8sa1T67_RvlSh2X33gpsYFbY0XUrmb91J1up6aoh2iBINeptnudM2iWrLOhH7z-oQvlTYum93VB9sBZp1NvPoDEhbKAxJnP6kVyUJeY2yGX_VebnAYoPJkz6Vr3Y2szR0ZQHAzWMXrSmjqLQ_e02s9LiYNx_il1yZTKgcd8CrqfcvhfU6dYr-ZtF2KE73TZeTAWuGLAr4YN3azGiNVkBQEPanumzIyBh24sOz1wr-UBHOMD9O-Sow0KAdscRxItEIu1B13pi8LZQhd4B8mM8ARd0MbFrnyfMlx1O7QO-UdBsE2uaClGxPKJqEXMgh4xL3wparTBNdVwenT7jT6e8tzT-PcUKG1jeSm0PGYDjtbsQ_4

[
  {
    "itemId": 7786,
    "profileId": 6
  },
  {
    "itemId": 7786,
    "profileId": 7
  },
  {
    "itemId": 7786,
    "profileId": 8
  }
]

###
GET https://7hkykyo11q5u.c01-17.plentymarkets.com/rest/items/7769/variations/29044/descriptions
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDZkMjM3M2ZiOWUxYjI3NTNmMTQ5MGRjZTI0MTZmMGE1MjZhNjQzZjQ5MmFiNDk2MTViMTliZjAzZTE3ZGVlZGY1ZGIyMmE2ZWYzN2FlNjEiLCJpYXQiOjE2MDM5OTI2MDcsIm5iZiI6MTYwMzk5MjYwNywiZXhwIjoxNjA0MDc5MDA3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.ecFm6IB4H5hRe6umyah2UeRKGom5vttwADMiT-QP3npuimaUvS2Wor8lgS-6eD9IsMKr2_3FDJAuB9_xYiGetUc4KxQUFOxuZIqbQWol0pLvGZyjXL140TQPMqvcXtRTSguV5ix4VLACUMf5ZQ4fMqKa9c63N-LtWAs2y0ujheQK3sjXEAxyDrOzD9hCfZlPOGZnA8egVC1quBOedvToZBOWMXt7L9KyKhEsy6xIkTAbfyvilgD4ZhVMR17cSHzPQLonufzsic4h-FWEG5f51y7n3gx3fwAVDcnis_fcCTDO77ks0uYaHcWuEcT8r8sa1T67_RvlSh2X33gpsYFbY0XUrmb91J1up6aoh2iBINeptnudM2iWrLOhH7z-oQvlTYum93VB9sBZp1NvPoDEhbKAxJnP6kVyUJeY2yGX_VebnAYoPJkz6Vr3Y2szR0ZQHAzWMXrSmjqLQ_e02s9LiYNx_il1yZTKgcd8CrqfcvhfU6dYr-ZtF2KE73TZeTAWuGLAr4YN3azGiNVkBQEPanumzIyBh24sOz1wr-UBHOMD9O-Sow0KAdscRxItEIu1B13pi8LZQhd4B8mM8ARd0MbFrnyfMlx1O7QO-UdBsE2uaClGxPKJqEXMgh4xL3wparTBNdVwenT7jT6e8tzT-PcUKG1jeSm0PGYDjtbsQ_4

###
GET https://7hkykyo11q5u.c01-17.plentymarkets.com/rest/items/7769/variations/29044?with=variationTexts
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDZkMjM3M2ZiOWUxYjI3NTNmMTQ5MGRjZTI0MTZmMGE1MjZhNjQzZjQ5MmFiNDk2MTViMTliZjAzZTE3ZGVlZGY1ZGIyMmE2ZWYzN2FlNjEiLCJpYXQiOjE2MDM5OTI2MDcsIm5iZiI6MTYwMzk5MjYwNywiZXhwIjoxNjA0MDc5MDA3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.ecFm6IB4H5hRe6umyah2UeRKGom5vttwADMiT-QP3npuimaUvS2Wor8lgS-6eD9IsMKr2_3FDJAuB9_xYiGetUc4KxQUFOxuZIqbQWol0pLvGZyjXL140TQPMqvcXtRTSguV5ix4VLACUMf5ZQ4fMqKa9c63N-LtWAs2y0ujheQK3sjXEAxyDrOzD9hCfZlPOGZnA8egVC1quBOedvToZBOWMXt7L9KyKhEsy6xIkTAbfyvilgD4ZhVMR17cSHzPQLonufzsic4h-FWEG5f51y7n3gx3fwAVDcnis_fcCTDO77ks0uYaHcWuEcT8r8sa1T67_RvlSh2X33gpsYFbY0XUrmb91J1up6aoh2iBINeptnudM2iWrLOhH7z-oQvlTYum93VB9sBZp1NvPoDEhbKAxJnP6kVyUJeY2yGX_VebnAYoPJkz6Vr3Y2szR0ZQHAzWMXrSmjqLQ_e02s9LiYNx_il1yZTKgcd8CrqfcvhfU6dYr-ZtF2KE73TZeTAWuGLAr4YN3azGiNVkBQEPanumzIyBh24sOz1wr-UBHOMD9O-Sow0KAdscRxItEIu1B13pi8LZQhd4B8mM8ARd0MbFrnyfMlx1O7QO-UdBsE2uaClGxPKJqEXMgh4xL3wparTBNdVwenT7jT6e8tzT-PcUKG1jeSm0PGYDjtbsQ_4

###
GET https://7hkykyo11q5u.c01-17.plentymarkets.com/rest/items/7769/variations/29044?with=itemCrossSelling
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDZkMjM3M2ZiOWUxYjI3NTNmMTQ5MGRjZTI0MTZmMGE1MjZhNjQzZjQ5MmFiNDk2MTViMTliZjAzZTE3ZGVlZGY1ZGIyMmE2ZWYzN2FlNjEiLCJpYXQiOjE2MDM5OTI2MDcsIm5iZiI6MTYwMzk5MjYwNywiZXhwIjoxNjA0MDc5MDA3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.ecFm6IB4H5hRe6umyah2UeRKGom5vttwADMiT-QP3npuimaUvS2Wor8lgS-6eD9IsMKr2_3FDJAuB9_xYiGetUc4KxQUFOxuZIqbQWol0pLvGZyjXL140TQPMqvcXtRTSguV5ix4VLACUMf5ZQ4fMqKa9c63N-LtWAs2y0ujheQK3sjXEAxyDrOzD9hCfZlPOGZnA8egVC1quBOedvToZBOWMXt7L9KyKhEsy6xIkTAbfyvilgD4ZhVMR17cSHzPQLonufzsic4h-FWEG5f51y7n3gx3fwAVDcnis_fcCTDO77ks0uYaHcWuEcT8r8sa1T67_RvlSh2X33gpsYFbY0XUrmb91J1up6aoh2iBINeptnudM2iWrLOhH7z-oQvlTYum93VB9sBZp1NvPoDEhbKAxJnP6kVyUJeY2yGX_VebnAYoPJkz6Vr3Y2szR0ZQHAzWMXrSmjqLQ_e02s9LiYNx_il1yZTKgcd8CrqfcvhfU6dYr-ZtF2KE73TZeTAWuGLAr4YN3azGiNVkBQEPanumzIyBh24sOz1wr-UBHOMD9O-Sow0KAdscRxItEIu1B13pi8LZQhd4B8mM8ARd0MbFrnyfMlx1O7QO-UdBsE2uaClGxPKJqEXMgh4xL3wparTBNdVwenT7jT6e8tzT-PcUKG1jeSm0PGYDjtbsQ_4

###
GET https://7hkykyo11q5u.c01-17.plentymarkets.com/rest/items/7769/variations/29044?with=itemImages
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDZkMjM3M2ZiOWUxYjI3NTNmMTQ5MGRjZTI0MTZmMGE1MjZhNjQzZjQ5MmFiNDk2MTViMTliZjAzZTE3ZGVlZGY1ZGIyMmE2ZWYzN2FlNjEiLCJpYXQiOjE2MDM5OTI2MDcsIm5iZiI6MTYwMzk5MjYwNywiZXhwIjoxNjA0MDc5MDA3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.ecFm6IB4H5hRe6umyah2UeRKGom5vttwADMiT-QP3npuimaUvS2Wor8lgS-6eD9IsMKr2_3FDJAuB9_xYiGetUc4KxQUFOxuZIqbQWol0pLvGZyjXL140TQPMqvcXtRTSguV5ix4VLACUMf5ZQ4fMqKa9c63N-LtWAs2y0ujheQK3sjXEAxyDrOzD9hCfZlPOGZnA8egVC1quBOedvToZBOWMXt7L9KyKhEsy6xIkTAbfyvilgD4ZhVMR17cSHzPQLonufzsic4h-FWEG5f51y7n3gx3fwAVDcnis_fcCTDO77ks0uYaHcWuEcT8r8sa1T67_RvlSh2X33gpsYFbY0XUrmb91J1up6aoh2iBINeptnudM2iWrLOhH7z-oQvlTYum93VB9sBZp1NvPoDEhbKAxJnP6kVyUJeY2yGX_VebnAYoPJkz6Vr3Y2szR0ZQHAzWMXrSmjqLQ_e02s9LiYNx_il1yZTKgcd8CrqfcvhfU6dYr-ZtF2KE73TZeTAWuGLAr4YN3azGiNVkBQEPanumzIyBh24sOz1wr-UBHOMD9O-Sow0KAdscRxItEIu1B13pi8LZQhd4B8mM8ARd0MbFrnyfMlx1O7QO-UdBsE2uaClGxPKJqEXMgh4xL3wparTBNdVwenT7jT6e8tzT-PcUKG1jeSm0PGYDjtbsQ_4

###
GET https://7hkykyo11q5u.c01-17.plentymarkets.com/rest/items?page=1&with=variations,itemImages,itemShippingProfiles
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDZkMjM3M2ZiOWUxYjI3NTNmMTQ5MGRjZTI0MTZmMGE1MjZhNjQzZjQ5MmFiNDk2MTViMTliZjAzZTE3ZGVlZGY1ZGIyMmE2ZWYzN2FlNjEiLCJpYXQiOjE2MDM5OTI2MDcsIm5iZiI6MTYwMzk5MjYwNywiZXhwIjoxNjA0MDc5MDA3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.ecFm6IB4H5hRe6umyah2UeRKGom5vttwADMiT-QP3npuimaUvS2Wor8lgS-6eD9IsMKr2_3FDJAuB9_xYiGetUc4KxQUFOxuZIqbQWol0pLvGZyjXL140TQPMqvcXtRTSguV5ix4VLACUMf5ZQ4fMqKa9c63N-LtWAs2y0ujheQK3sjXEAxyDrOzD9hCfZlPOGZnA8egVC1quBOedvToZBOWMXt7L9KyKhEsy6xIkTAbfyvilgD4ZhVMR17cSHzPQLonufzsic4h-FWEG5f51y7n3gx3fwAVDcnis_fcCTDO77ks0uYaHcWuEcT8r8sa1T67_RvlSh2X33gpsYFbY0XUrmb91J1up6aoh2iBINeptnudM2iWrLOhH7z-oQvlTYum93VB9sBZp1NvPoDEhbKAxJnP6kVyUJeY2yGX_VebnAYoPJkz6Vr3Y2szR0ZQHAzWMXrSmjqLQ_e02s9LiYNx_il1yZTKgcd8CrqfcvhfU6dYr-ZtF2KE73TZeTAWuGLAr4YN3azGiNVkBQEPanumzIyBh24sOz1wr-UBHOMD9O-Sow0KAdscRxItEIu1B13pi8LZQhd4B8mM8ARd0MbFrnyfMlx1O7QO-UdBsE2uaClGxPKJqEXMgh4xL3wparTBNdVwenT7jT6e8tzT-PcUKG1jeSm0PGYDjtbsQ_4

###
## additionalSkus,attributeValues,attributeValues.attribute,attributeValues.attributeValue,barcodes,barcodes.barcode,base,base.item,base.itemSerialNumber,base.feedback,base.characteristics,base.crossSelling,base.texts,base.availability',base.images,base.shippingProfiles,base.stock,base.stockStorageLocations,bundleComponents,categories,categories.category,categories.categoryBranch,clients,defaultCategories,defaultCategories.category,images,images.image,markets,marketIdentNumbers,salesPrices,salesPrices.salesPrice,skus,supplier,supplier.supplier,timestamps,warehouses,warehouses.warehouse,unit,unit.unit,tags,tags.tag,properties,properties.property
GET https://7hkykyo11q5u.c01-17.plentymarkets.com/rest/pim/variations?with=base.texts
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDZkMjM3M2ZiOWUxYjI3NTNmMTQ5MGRjZTI0MTZmMGE1MjZhNjQzZjQ5MmFiNDk2MTViMTliZjAzZTE3ZGVlZGY1ZGIyMmE2ZWYzN2FlNjEiLCJpYXQiOjE2MDM5OTI2MDcsIm5iZiI6MTYwMzk5MjYwNywiZXhwIjoxNjA0MDc5MDA3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.ecFm6IB4H5hRe6umyah2UeRKGom5vttwADMiT-QP3npuimaUvS2Wor8lgS-6eD9IsMKr2_3FDJAuB9_xYiGetUc4KxQUFOxuZIqbQWol0pLvGZyjXL140TQPMqvcXtRTSguV5ix4VLACUMf5ZQ4fMqKa9c63N-LtWAs2y0ujheQK3sjXEAxyDrOzD9hCfZlPOGZnA8egVC1quBOedvToZBOWMXt7L9KyKhEsy6xIkTAbfyvilgD4ZhVMR17cSHzPQLonufzsic4h-FWEG5f51y7n3gx3fwAVDcnis_fcCTDO77ks0uYaHcWuEcT8r8sa1T67_RvlSh2X33gpsYFbY0XUrmb91J1up6aoh2iBINeptnudM2iWrLOhH7z-oQvlTYum93VB9sBZp1NvPoDEhbKAxJnP6kVyUJeY2yGX_VebnAYoPJkz6Vr3Y2szR0ZQHAzWMXrSmjqLQ_e02s9LiYNx_il1yZTKgcd8CrqfcvhfU6dYr-ZtF2KE73TZeTAWuGLAr4YN3azGiNVkBQEPanumzIyBh24sOz1wr-UBHOMD9O-Sow0KAdscRxItEIu1B13pi8LZQhd4B8mM8ARd0MbFrnyfMlx1O7QO-UdBsE2uaClGxPKJqEXMgh4xL3wparTBNdVwenT7jT6e8tzT-PcUKG1jeSm0PGYDjtbsQ_4


###
POST https://7hkykyo11q5u.c01-17.plentymarkets.com/rest/items
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDZkMjM3M2ZiOWUxYjI3NTNmMTQ5MGRjZTI0MTZmMGE1MjZhNjQzZjQ5MmFiNDk2MTViMTliZjAzZTE3ZGVlZGY1ZGIyMmE2ZWYzN2FlNjEiLCJpYXQiOjE2MDM5OTI2MDcsIm5iZiI6MTYwMzk5MjYwNywiZXhwIjoxNjA0MDc5MDA3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.ecFm6IB4H5hRe6umyah2UeRKGom5vttwADMiT-QP3npuimaUvS2Wor8lgS-6eD9IsMKr2_3FDJAuB9_xYiGetUc4KxQUFOxuZIqbQWol0pLvGZyjXL140TQPMqvcXtRTSguV5ix4VLACUMf5ZQ4fMqKa9c63N-LtWAs2y0ujheQK3sjXEAxyDrOzD9hCfZlPOGZnA8egVC1quBOedvToZBOWMXt7L9KyKhEsy6xIkTAbfyvilgD4ZhVMR17cSHzPQLonufzsic4h-FWEG5f51y7n3gx3fwAVDcnis_fcCTDO77ks0uYaHcWuEcT8r8sa1T67_RvlSh2X33gpsYFbY0XUrmb91J1up6aoh2iBINeptnudM2iWrLOhH7z-oQvlTYum93VB9sBZp1NvPoDEhbKAxJnP6kVyUJeY2yGX_VebnAYoPJkz6Vr3Y2szR0ZQHAzWMXrSmjqLQ_e02s9LiYNx_il1yZTKgcd8CrqfcvhfU6dYr-ZtF2KE73TZeTAWuGLAr4YN3azGiNVkBQEPanumzIyBh24sOz1wr-UBHOMD9O-Sow0KAdscRxItEIu1B13pi8LZQhd4B8mM8ARd0MbFrnyfMlx1O7QO-UdBsE2uaClGxPKJqEXMgh4xL3wparTBNdVwenT7jT6e8tzT-PcUKG1jeSm0PGYDjtbsQ_4

[
    {
        "position":1,
        "stockType":0,
        "storeSpecial":2,
        "condition":0,
        "feedback":0,
        "isSubscribable":false,
        "isShippingPackage":false,
        "itemType":"default",
        "variations": [
            {
                "variationCategories": [
                    {
                        "categoryId": 46
                    }
                ],
                "unit": {
                    "unitId": 1,
                    "content": 1
                }
            }
        ]
    }
]

