###
GET ivnijlp9xjod.c01-15.plentymarkets.com/rest/pim/variations?with=additionalSkus%2CattributeValues%2Cbarcodes%2Ccategories%2Ccategories.categoryBranch%2Cbase%2Cbase.item%2Cbase.itemSerialNumber%2Cbase.feedback%2Cbase.crossSelling%2Cbase.texts%2Cbase.availability%2Cbase.images%2Cbase.shippingProfiles%2Cbase.stock%2Cbase.stockStorageLocations%2CbundleComponents%2Cclients%2CdefaultCategories%2Cimages%2Cmarkets%2CmarketIdentNumbers%2CsalesPrices%2Cskus%2Csupplier%2Csupplier.supplier%2Cwarehouses%2Cunit%2Ctags%2Cproperties%2Ccomments&itemsPerPage=50&page=71
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTdkNWNjNTAxOTRlYjA4ZmEwYTU3NmE1NTY4ZWU1Y2QyODMxNzM4YjQ5YWYzZDlmMjYzYzRmNjIyMWZiYjk4Yjg1OTEyMWNkMjNhZWFiMjQiLCJpYXQiOjE2NTc1MjEwMDguNzM4MSwibmJmIjoxNjU3NTIxMDA4LjczODEsImV4cCI6MTY1NzYwNzQwOC43MzU2LCJzdWIiOiI4Iiwic2NvcGVzIjpbIioiXX0.X412gyNL4iN0-I2XNRrGbbQV-zruRXq3-SrMxYVbelwqRtMnTdpRDrwZ90qCo_lZKoH2olDB2lvRAZzXVlxPXSOXMHw96yvfzN7w1yEryJgk3Jxzyj_SSc47w5abqFAzGDTstswX9ix7TNLuAp_UTEppgomH6NHHBeExIxE50Le4TrzR5vAdzhbt-6Ol54000RdliAwVt2dZ9OGWfqtaVxojH5W66G4LLmtcDKXlTgxRY0bNgYILkKV7zIJFmhavQRwMt_UYA9BaKkrdAiwGa9OL2qrX9G0udUGET7yX-xfm7bgxOLxpnWIrB0x2fAxnrftbZfCqjtXVwHUhCdTUWfXQ10jn8BWev0qsJ1c0Cml1PGI6CnSoLUHAuAUWbMmNIc2zwiERAEToWotCGuk9S0iLsk-GOtFQWEnlaKaNprZV73LhdQVtNB0sdgDm9hgXEbbJOs9yzihE3lGpT9x-H6xss6Vh8D78jS9PXTvs2HfJml0PkwkLdjOcLgYEdxaAkPL7UWK-m-Go7CEuJ41JGzEEHOZSwrtYJcTUy4T7txCNUl0xMK8WJfZy67yfoMvOYAoItGX5QPR0wtvq83zk9vKfg_L4kPjAcI3YrL-WoSYJyhzqas9hNCYDfHYY-JAWeQH-LxSaNTvkLrVQSGAh3jjgG_GAbUI1h80_h9GLxuw

###
GET https://ivnijlp9xjod.c01-15.plentymarkets.com/rest/stockmanagement/warehouses
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTdkNWNjNTAxOTRlYjA4ZmEwYTU3NmE1NTY4ZWU1Y2QyODMxNzM4YjQ5YWYzZDlmMjYzYzRmNjIyMWZiYjk4Yjg1OTEyMWNkMjNhZWFiMjQiLCJpYXQiOjE2NTc1MjEwMDguNzM4MSwibmJmIjoxNjU3NTIxMDA4LjczODEsImV4cCI6MTY1NzYwNzQwOC43MzU2LCJzdWIiOiI4Iiwic2NvcGVzIjpbIioiXX0.X412gyNL4iN0-I2XNRrGbbQV-zruRXq3-SrMxYVbelwqRtMnTdpRDrwZ90qCo_lZKoH2olDB2lvRAZzXVlxPXSOXMHw96yvfzN7w1yEryJgk3Jxzyj_SSc47w5abqFAzGDTstswX9ix7TNLuAp_UTEppgomH6NHHBeExIxE50Le4TrzR5vAdzhbt-6Ol54000RdliAwVt2dZ9OGWfqtaVxojH5W66G4LLmtcDKXlTgxRY0bNgYILkKV7zIJFmhavQRwMt_UYA9BaKkrdAiwGa9OL2qrX9G0udUGET7yX-xfm7bgxOLxpnWIrB0x2fAxnrftbZfCqjtXVwHUhCdTUWfXQ10jn8BWev0qsJ1c0Cml1PGI6CnSoLUHAuAUWbMmNIc2zwiERAEToWotCGuk9S0iLsk-GOtFQWEnlaKaNprZV73LhdQVtNB0sdgDm9hgXEbbJOs9yzihE3lGpT9x-H6xss6Vh8D78jS9PXTvs2HfJml0PkwkLdjOcLgYEdxaAkPL7UWK-m-Go7CEuJ41JGzEEHOZSwrtYJcTUy4T7txCNUl0xMK8WJfZy67yfoMvOYAoItGX5QPR0wtvq83zk9vKfg_L4kPjAcI3YrL-WoSYJyhzqas9hNCYDfHYY-JAWeQH-LxSaNTvkLrVQSGAh3jjgG_GAbUI1h80_h9GLxuw

###
GET https://ivnijlp9xjod.c01-15.plentymarkets.com/rest/properties/groups
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTdkNWNjNTAxOTRlYjA4ZmEwYTU3NmE1NTY4ZWU1Y2QyODMxNzM4YjQ5YWYzZDlmMjYzYzRmNjIyMWZiYjk4Yjg1OTEyMWNkMjNhZWFiMjQiLCJpYXQiOjE2NTc1MjEwMDguNzM4MSwibmJmIjoxNjU3NTIxMDA4LjczODEsImV4cCI6MTY1NzYwNzQwOC43MzU2LCJzdWIiOiI4Iiwic2NvcGVzIjpbIioiXX0.X412gyNL4iN0-I2XNRrGbbQV-zruRXq3-SrMxYVbelwqRtMnTdpRDrwZ90qCo_lZKoH2olDB2lvRAZzXVlxPXSOXMHw96yvfzN7w1yEryJgk3Jxzyj_SSc47w5abqFAzGDTstswX9ix7TNLuAp_UTEppgomH6NHHBeExIxE50Le4TrzR5vAdzhbt-6Ol54000RdliAwVt2dZ9OGWfqtaVxojH5W66G4LLmtcDKXlTgxRY0bNgYILkKV7zIJFmhavQRwMt_UYA9BaKkrdAiwGa9OL2qrX9G0udUGET7yX-xfm7bgxOLxpnWIrB0x2fAxnrftbZfCqjtXVwHUhCdTUWfXQ10jn8BWev0qsJ1c0Cml1PGI6CnSoLUHAuAUWbMmNIc2zwiERAEToWotCGuk9S0iLsk-GOtFQWEnlaKaNprZV73LhdQVtNB0sdgDm9hgXEbbJOs9yzihE3lGpT9x-H6xss6Vh8D78jS9PXTvs2HfJml0PkwkLdjOcLgYEdxaAkPL7UWK-m-Go7CEuJ41JGzEEHOZSwrtYJcTUy4T7txCNUl0xMK8WJfZy67yfoMvOYAoItGX5QPR0wtvq83zk9vKfg_L4kPjAcI3YrL-WoSYJyhzqas9hNCYDfHYY-JAWeQH-LxSaNTvkLrVQSGAh3jjgG_GAbUI1h80_h9GLxuw

###
POST https://ivnijlp9xjod.c01-15.plentymarkets.com/rest/properties/groups
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTdkNWNjNTAxOTRlYjA4ZmEwYTU3NmE1NTY4ZWU1Y2QyODMxNzM4YjQ5YWYzZDlmMjYzYzRmNjIyMWZiYjk4Yjg1OTEyMWNkMjNhZWFiMjQiLCJpYXQiOjE2NTc1MjEwMDguNzM4MSwibmJmIjoxNjU3NTIxMDA4LjczODEsImV4cCI6MTY1NzYwNzQwOC43MzU2LCJzdWIiOiI4Iiwic2NvcGVzIjpbIioiXX0.X412gyNL4iN0-I2XNRrGbbQV-zruRXq3-SrMxYVbelwqRtMnTdpRDrwZ90qCo_lZKoH2olDB2lvRAZzXVlxPXSOXMHw96yvfzN7w1yEryJgk3Jxzyj_SSc47w5abqFAzGDTstswX9ix7TNLuAp_UTEppgomH6NHHBeExIxE50Le4TrzR5vAdzhbt-6Ol54000RdliAwVt2dZ9OGWfqtaVxojH5W66G4LLmtcDKXlTgxRY0bNgYILkKV7zIJFmhavQRwMt_UYA9BaKkrdAiwGa9OL2qrX9G0udUGET7yX-xfm7bgxOLxpnWIrB0x2fAxnrftbZfCqjtXVwHUhCdTUWfXQ10jn8BWev0qsJ1c0Cml1PGI6CnSoLUHAuAUWbMmNIc2zwiERAEToWotCGuk9S0iLsk-GOtFQWEnlaKaNprZV73LhdQVtNB0sdgDm9hgXEbbJOs9yzihE3lGpT9x-H6xss6Vh8D78jS9PXTvs2HfJml0PkwkLdjOcLgYEdxaAkPL7UWK-m-Go7CEuJ41JGzEEHOZSwrtYJcTUy4T7txCNUl0xMK8WJfZy67yfoMvOYAoItGX5QPR0wtvq83zk9vKfg_L4kPjAcI3YrL-WoSYJyhzqas9hNCYDfHYY-JAWeQH-LxSaNTvkLrVQSGAh3jjgG_GAbUI1h80_h9GLxuw

{
    "position": 2,
    "names": [
        {
            "lang": "en",
            "name": "Default"
        }
    ]
}

###
GET https://ivnijlp9xjod.c01-15.plentymarkets.com/rest/v2/properties
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTdkNWNjNTAxOTRlYjA4ZmEwYTU3NmE1NTY4ZWU1Y2QyODMxNzM4YjQ5YWYzZDlmMjYzYzRmNjIyMWZiYjk4Yjg1OTEyMWNkMjNhZWFiMjQiLCJpYXQiOjE2NTc1MjEwMDguNzM4MSwibmJmIjoxNjU3NTIxMDA4LjczODEsImV4cCI6MTY1NzYwNzQwOC43MzU2LCJzdWIiOiI4Iiwic2NvcGVzIjpbIioiXX0.X412gyNL4iN0-I2XNRrGbbQV-zruRXq3-SrMxYVbelwqRtMnTdpRDrwZ90qCo_lZKoH2olDB2lvRAZzXVlxPXSOXMHw96yvfzN7w1yEryJgk3Jxzyj_SSc47w5abqFAzGDTstswX9ix7TNLuAp_UTEppgomH6NHHBeExIxE50Le4TrzR5vAdzhbt-6Ol54000RdliAwVt2dZ9OGWfqtaVxojH5W66G4LLmtcDKXlTgxRY0bNgYILkKV7zIJFmhavQRwMt_UYA9BaKkrdAiwGa9OL2qrX9G0udUGET7yX-xfm7bgxOLxpnWIrB0x2fAxnrftbZfCqjtXVwHUhCdTUWfXQ10jn8BWev0qsJ1c0Cml1PGI6CnSoLUHAuAUWbMmNIc2zwiERAEToWotCGuk9S0iLsk-GOtFQWEnlaKaNprZV73LhdQVtNB0sdgDm9hgXEbbJOs9yzihE3lGpT9x-H6xss6Vh8D78jS9PXTvs2HfJml0PkwkLdjOcLgYEdxaAkPL7UWK-m-Go7CEuJ41JGzEEHOZSwrtYJcTUy4T7txCNUl0xMK8WJfZy67yfoMvOYAoItGX5QPR0wtvq83zk9vKfg_L4kPjAcI3YrL-WoSYJyhzqas9hNCYDfHYY-JAWeQH-LxSaNTvkLrVQSGAh3jjgG_GAbUI1h80_h9GLxuw


###
GET https://ivnijlp9xjod.c01-15.plentymarkets.com/rest/items
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTdkNWNjNTAxOTRlYjA4ZmEwYTU3NmE1NTY4ZWU1Y2QyODMxNzM4YjQ5YWYzZDlmMjYzYzRmNjIyMWZiYjk4Yjg1OTEyMWNkMjNhZWFiMjQiLCJpYXQiOjE2NTc1MjEwMDguNzM4MSwibmJmIjoxNjU3NTIxMDA4LjczODEsImV4cCI6MTY1NzYwNzQwOC43MzU2LCJzdWIiOiI4Iiwic2NvcGVzIjpbIioiXX0.X412gyNL4iN0-I2XNRrGbbQV-zruRXq3-SrMxYVbelwqRtMnTdpRDrwZ90qCo_lZKoH2olDB2lvRAZzXVlxPXSOXMHw96yvfzN7w1yEryJgk3Jxzyj_SSc47w5abqFAzGDTstswX9ix7TNLuAp_UTEppgomH6NHHBeExIxE50Le4TrzR5vAdzhbt-6Ol54000RdliAwVt2dZ9OGWfqtaVxojH5W66G4LLmtcDKXlTgxRY0bNgYILkKV7zIJFmhavQRwMt_UYA9BaKkrdAiwGa9OL2qrX9G0udUGET7yX-xfm7bgxOLxpnWIrB0x2fAxnrftbZfCqjtXVwHUhCdTUWfXQ10jn8BWev0qsJ1c0Cml1PGI6CnSoLUHAuAUWbMmNIc2zwiERAEToWotCGuk9S0iLsk-GOtFQWEnlaKaNprZV73LhdQVtNB0sdgDm9hgXEbbJOs9yzihE3lGpT9x-H6xss6Vh8D78jS9PXTvs2HfJml0PkwkLdjOcLgYEdxaAkPL7UWK-m-Go7CEuJ41JGzEEHOZSwrtYJcTUy4T7txCNUl0xMK8WJfZy67yfoMvOYAoItGX5QPR0wtvq83zk9vKfg_L4kPjAcI3YrL-WoSYJyhzqas9hNCYDfHYY-JAWeQH-LxSaNTvkLrVQSGAh3jjgG_GAbUI1h80_h9GLxuw

###
GET https://ivnijlp9xjod.c01-15.plentymarkets.com/rest/items/7769
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTdkNWNjNTAxOTRlYjA4ZmEwYTU3NmE1NTY4ZWU1Y2QyODMxNzM4YjQ5YWYzZDlmMjYzYzRmNjIyMWZiYjk4Yjg1OTEyMWNkMjNhZWFiMjQiLCJpYXQiOjE2NTc1MjEwMDguNzM4MSwibmJmIjoxNjU3NTIxMDA4LjczODEsImV4cCI6MTY1NzYwNzQwOC43MzU2LCJzdWIiOiI4Iiwic2NvcGVzIjpbIioiXX0.X412gyNL4iN0-I2XNRrGbbQV-zruRXq3-SrMxYVbelwqRtMnTdpRDrwZ90qCo_lZKoH2olDB2lvRAZzXVlxPXSOXMHw96yvfzN7w1yEryJgk3Jxzyj_SSc47w5abqFAzGDTstswX9ix7TNLuAp_UTEppgomH6NHHBeExIxE50Le4TrzR5vAdzhbt-6Ol54000RdliAwVt2dZ9OGWfqtaVxojH5W66G4LLmtcDKXlTgxRY0bNgYILkKV7zIJFmhavQRwMt_UYA9BaKkrdAiwGa9OL2qrX9G0udUGET7yX-xfm7bgxOLxpnWIrB0x2fAxnrftbZfCqjtXVwHUhCdTUWfXQ10jn8BWev0qsJ1c0Cml1PGI6CnSoLUHAuAUWbMmNIc2zwiERAEToWotCGuk9S0iLsk-GOtFQWEnlaKaNprZV73LhdQVtNB0sdgDm9hgXEbbJOs9yzihE3lGpT9x-H6xss6Vh8D78jS9PXTvs2HfJml0PkwkLdjOcLgYEdxaAkPL7UWK-m-Go7CEuJ41JGzEEHOZSwrtYJcTUy4T7txCNUl0xMK8WJfZy67yfoMvOYAoItGX5QPR0wtvq83zk9vKfg_L4kPjAcI3YrL-WoSYJyhzqas9hNCYDfHYY-JAWeQH-LxSaNTvkLrVQSGAh3jjgG_GAbUI1h80_h9GLxuw


###
GET https://ivnijlp9xjod.c01-15.plentymarkets.com/rest/items/variations
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTdkNWNjNTAxOTRlYjA4ZmEwYTU3NmE1NTY4ZWU1Y2QyODMxNzM4YjQ5YWYzZDlmMjYzYzRmNjIyMWZiYjk4Yjg1OTEyMWNkMjNhZWFiMjQiLCJpYXQiOjE2NTc1MjEwMDguNzM4MSwibmJmIjoxNjU3NTIxMDA4LjczODEsImV4cCI6MTY1NzYwNzQwOC43MzU2LCJzdWIiOiI4Iiwic2NvcGVzIjpbIioiXX0.X412gyNL4iN0-I2XNRrGbbQV-zruRXq3-SrMxYVbelwqRtMnTdpRDrwZ90qCo_lZKoH2olDB2lvRAZzXVlxPXSOXMHw96yvfzN7w1yEryJgk3Jxzyj_SSc47w5abqFAzGDTstswX9ix7TNLuAp_UTEppgomH6NHHBeExIxE50Le4TrzR5vAdzhbt-6Ol54000RdliAwVt2dZ9OGWfqtaVxojH5W66G4LLmtcDKXlTgxRY0bNgYILkKV7zIJFmhavQRwMt_UYA9BaKkrdAiwGa9OL2qrX9G0udUGET7yX-xfm7bgxOLxpnWIrB0x2fAxnrftbZfCqjtXVwHUhCdTUWfXQ10jn8BWev0qsJ1c0Cml1PGI6CnSoLUHAuAUWbMmNIc2zwiERAEToWotCGuk9S0iLsk-GOtFQWEnlaKaNprZV73LhdQVtNB0sdgDm9hgXEbbJOs9yzihE3lGpT9x-H6xss6Vh8D78jS9PXTvs2HfJml0PkwkLdjOcLgYEdxaAkPL7UWK-m-Go7CEuJ41JGzEEHOZSwrtYJcTUy4T7txCNUl0xMK8WJfZy67yfoMvOYAoItGX5QPR0wtvq83zk9vKfg_L4kPjAcI3YrL-WoSYJyhzqas9hNCYDfHYY-JAWeQH-LxSaNTvkLrVQSGAh3jjgG_GAbUI1h80_h9GLxuw

###
GET https://ivnijlp9xjod.c01-15.plentymarkets.com/rest/items/attributes
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTdkNWNjNTAxOTRlYjA4ZmEwYTU3NmE1NTY4ZWU1Y2QyODMxNzM4YjQ5YWYzZDlmMjYzYzRmNjIyMWZiYjk4Yjg1OTEyMWNkMjNhZWFiMjQiLCJpYXQiOjE2NTc1MjEwMDguNzM4MSwibmJmIjoxNjU3NTIxMDA4LjczODEsImV4cCI6MTY1NzYwNzQwOC43MzU2LCJzdWIiOiI4Iiwic2NvcGVzIjpbIioiXX0.X412gyNL4iN0-I2XNRrGbbQV-zruRXq3-SrMxYVbelwqRtMnTdpRDrwZ90qCo_lZKoH2olDB2lvRAZzXVlxPXSOXMHw96yvfzN7w1yEryJgk3Jxzyj_SSc47w5abqFAzGDTstswX9ix7TNLuAp_UTEppgomH6NHHBeExIxE50Le4TrzR5vAdzhbt-6Ol54000RdliAwVt2dZ9OGWfqtaVxojH5W66G4LLmtcDKXlTgxRY0bNgYILkKV7zIJFmhavQRwMt_UYA9BaKkrdAiwGa9OL2qrX9G0udUGET7yX-xfm7bgxOLxpnWIrB0x2fAxnrftbZfCqjtXVwHUhCdTUWfXQ10jn8BWev0qsJ1c0Cml1PGI6CnSoLUHAuAUWbMmNIc2zwiERAEToWotCGuk9S0iLsk-GOtFQWEnlaKaNprZV73LhdQVtNB0sdgDm9hgXEbbJOs9yzihE3lGpT9x-H6xss6Vh8D78jS9PXTvs2HfJml0PkwkLdjOcLgYEdxaAkPL7UWK-m-Go7CEuJ41JGzEEHOZSwrtYJcTUy4T7txCNUl0xMK8WJfZy67yfoMvOYAoItGX5QPR0wtvq83zk9vKfg_L4kPjAcI3YrL-WoSYJyhzqas9hNCYDfHYY-JAWeQH-LxSaNTvkLrVQSGAh3jjgG_GAbUI1h80_h9GLxuw

###
GET https://ivnijlp9xjod.c01-15.plentymarkets.com/rest/items/barcodes
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTdkNWNjNTAxOTRlYjA4ZmEwYTU3NmE1NTY4ZWU1Y2QyODMxNzM4YjQ5YWYzZDlmMjYzYzRmNjIyMWZiYjk4Yjg1OTEyMWNkMjNhZWFiMjQiLCJpYXQiOjE2NTc1MjEwMDguNzM4MSwibmJmIjoxNjU3NTIxMDA4LjczODEsImV4cCI6MTY1NzYwNzQwOC43MzU2LCJzdWIiOiI4Iiwic2NvcGVzIjpbIioiXX0.X412gyNL4iN0-I2XNRrGbbQV-zruRXq3-SrMxYVbelwqRtMnTdpRDrwZ90qCo_lZKoH2olDB2lvRAZzXVlxPXSOXMHw96yvfzN7w1yEryJgk3Jxzyj_SSc47w5abqFAzGDTstswX9ix7TNLuAp_UTEppgomH6NHHBeExIxE50Le4TrzR5vAdzhbt-6Ol54000RdliAwVt2dZ9OGWfqtaVxojH5W66G4LLmtcDKXlTgxRY0bNgYILkKV7zIJFmhavQRwMt_UYA9BaKkrdAiwGa9OL2qrX9G0udUGET7yX-xfm7bgxOLxpnWIrB0x2fAxnrftbZfCqjtXVwHUhCdTUWfXQ10jn8BWev0qsJ1c0Cml1PGI6CnSoLUHAuAUWbMmNIc2zwiERAEToWotCGuk9S0iLsk-GOtFQWEnlaKaNprZV73LhdQVtNB0sdgDm9hgXEbbJOs9yzihE3lGpT9x-H6xss6Vh8D78jS9PXTvs2HfJml0PkwkLdjOcLgYEdxaAkPL7UWK-m-Go7CEuJ41JGzEEHOZSwrtYJcTUy4T7txCNUl0xMK8WJfZy67yfoMvOYAoItGX5QPR0wtvq83zk9vKfg_L4kPjAcI3YrL-WoSYJyhzqas9hNCYDfHYY-JAWeQH-LxSaNTvkLrVQSGAh3jjgG_GAbUI1h80_h9GLxuw

###
GET https://ivnijlp9xjod.c01-15.plentymarkets.com/rest/items/item_shipping_profiles
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTdkNWNjNTAxOTRlYjA4ZmEwYTU3NmE1NTY4ZWU1Y2QyODMxNzM4YjQ5YWYzZDlmMjYzYzRmNjIyMWZiYjk4Yjg1OTEyMWNkMjNhZWFiMjQiLCJpYXQiOjE2NTc1MjEwMDguNzM4MSwibmJmIjoxNjU3NTIxMDA4LjczODEsImV4cCI6MTY1NzYwNzQwOC43MzU2LCJzdWIiOiI4Iiwic2NvcGVzIjpbIioiXX0.X412gyNL4iN0-I2XNRrGbbQV-zruRXq3-SrMxYVbelwqRtMnTdpRDrwZ90qCo_lZKoH2olDB2lvRAZzXVlxPXSOXMHw96yvfzN7w1yEryJgk3Jxzyj_SSc47w5abqFAzGDTstswX9ix7TNLuAp_UTEppgomH6NHHBeExIxE50Le4TrzR5vAdzhbt-6Ol54000RdliAwVt2dZ9OGWfqtaVxojH5W66G4LLmtcDKXlTgxRY0bNgYILkKV7zIJFmhavQRwMt_UYA9BaKkrdAiwGa9OL2qrX9G0udUGET7yX-xfm7bgxOLxpnWIrB0x2fAxnrftbZfCqjtXVwHUhCdTUWfXQ10jn8BWev0qsJ1c0Cml1PGI6CnSoLUHAuAUWbMmNIc2zwiERAEToWotCGuk9S0iLsk-GOtFQWEnlaKaNprZV73LhdQVtNB0sdgDm9hgXEbbJOs9yzihE3lGpT9x-H6xss6Vh8D78jS9PXTvs2HfJml0PkwkLdjOcLgYEdxaAkPL7UWK-m-Go7CEuJ41JGzEEHOZSwrtYJcTUy4T7txCNUl0xMK8WJfZy67yfoMvOYAoItGX5QPR0wtvq83zk9vKfg_L4kPjAcI3YrL-WoSYJyhzqas9hNCYDfHYY-JAWeQH-LxSaNTvkLrVQSGAh3jjgG_GAbUI1h80_h9GLxuw

###
POST https://ivnijlp9xjod.c01-15.plentymarkets.com/rest/items/item_shipping_profiles
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTdkNWNjNTAxOTRlYjA4ZmEwYTU3NmE1NTY4ZWU1Y2QyODMxNzM4YjQ5YWYzZDlmMjYzYzRmNjIyMWZiYjk4Yjg1OTEyMWNkMjNhZWFiMjQiLCJpYXQiOjE2NTc1MjEwMDguNzM4MSwibmJmIjoxNjU3NTIxMDA4LjczODEsImV4cCI6MTY1NzYwNzQwOC43MzU2LCJzdWIiOiI4Iiwic2NvcGVzIjpbIioiXX0.X412gyNL4iN0-I2XNRrGbbQV-zruRXq3-SrMxYVbelwqRtMnTdpRDrwZ90qCo_lZKoH2olDB2lvRAZzXVlxPXSOXMHw96yvfzN7w1yEryJgk3Jxzyj_SSc47w5abqFAzGDTstswX9ix7TNLuAp_UTEppgomH6NHHBeExIxE50Le4TrzR5vAdzhbt-6Ol54000RdliAwVt2dZ9OGWfqtaVxojH5W66G4LLmtcDKXlTgxRY0bNgYILkKV7zIJFmhavQRwMt_UYA9BaKkrdAiwGa9OL2qrX9G0udUGET7yX-xfm7bgxOLxpnWIrB0x2fAxnrftbZfCqjtXVwHUhCdTUWfXQ10jn8BWev0qsJ1c0Cml1PGI6CnSoLUHAuAUWbMmNIc2zwiERAEToWotCGuk9S0iLsk-GOtFQWEnlaKaNprZV73LhdQVtNB0sdgDm9hgXEbbJOs9yzihE3lGpT9x-H6xss6Vh8D78jS9PXTvs2HfJml0PkwkLdjOcLgYEdxaAkPL7UWK-m-Go7CEuJ41JGzEEHOZSwrtYJcTUy4T7txCNUl0xMK8WJfZy67yfoMvOYAoItGX5QPR0wtvq83zk9vKfg_L4kPjAcI3YrL-WoSYJyhzqas9hNCYDfHYY-JAWeQH-LxSaNTvkLrVQSGAh3jjgG_GAbUI1h80_h9GLxuw

[
  {
    "itemId": 7786,
    "profileId": 6
  },
  {
    "itemId": 7786,
    "profileId": 7
  },
  {
    "itemId": 7786,
    "profileId": 8
  }
]

###
GET https://ivnijlp9xjod.c01-15.plentymarkets.com/rest/items/7769/variations/29044/descriptions
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTdkNWNjNTAxOTRlYjA4ZmEwYTU3NmE1NTY4ZWU1Y2QyODMxNzM4YjQ5YWYzZDlmMjYzYzRmNjIyMWZiYjk4Yjg1OTEyMWNkMjNhZWFiMjQiLCJpYXQiOjE2NTc1MjEwMDguNzM4MSwibmJmIjoxNjU3NTIxMDA4LjczODEsImV4cCI6MTY1NzYwNzQwOC43MzU2LCJzdWIiOiI4Iiwic2NvcGVzIjpbIioiXX0.X412gyNL4iN0-I2XNRrGbbQV-zruRXq3-SrMxYVbelwqRtMnTdpRDrwZ90qCo_lZKoH2olDB2lvRAZzXVlxPXSOXMHw96yvfzN7w1yEryJgk3Jxzyj_SSc47w5abqFAzGDTstswX9ix7TNLuAp_UTEppgomH6NHHBeExIxE50Le4TrzR5vAdzhbt-6Ol54000RdliAwVt2dZ9OGWfqtaVxojH5W66G4LLmtcDKXlTgxRY0bNgYILkKV7zIJFmhavQRwMt_UYA9BaKkrdAiwGa9OL2qrX9G0udUGET7yX-xfm7bgxOLxpnWIrB0x2fAxnrftbZfCqjtXVwHUhCdTUWfXQ10jn8BWev0qsJ1c0Cml1PGI6CnSoLUHAuAUWbMmNIc2zwiERAEToWotCGuk9S0iLsk-GOtFQWEnlaKaNprZV73LhdQVtNB0sdgDm9hgXEbbJOs9yzihE3lGpT9x-H6xss6Vh8D78jS9PXTvs2HfJml0PkwkLdjOcLgYEdxaAkPL7UWK-m-Go7CEuJ41JGzEEHOZSwrtYJcTUy4T7txCNUl0xMK8WJfZy67yfoMvOYAoItGX5QPR0wtvq83zk9vKfg_L4kPjAcI3YrL-WoSYJyhzqas9hNCYDfHYY-JAWeQH-LxSaNTvkLrVQSGAh3jjgG_GAbUI1h80_h9GLxuw

###
GET https://ivnijlp9xjod.c01-15.plentymarkets.com/rest/items/7769/variations/29044?with=variationTexts
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTdkNWNjNTAxOTRlYjA4ZmEwYTU3NmE1NTY4ZWU1Y2QyODMxNzM4YjQ5YWYzZDlmMjYzYzRmNjIyMWZiYjk4Yjg1OTEyMWNkMjNhZWFiMjQiLCJpYXQiOjE2NTc1MjEwMDguNzM4MSwibmJmIjoxNjU3NTIxMDA4LjczODEsImV4cCI6MTY1NzYwNzQwOC43MzU2LCJzdWIiOiI4Iiwic2NvcGVzIjpbIioiXX0.X412gyNL4iN0-I2XNRrGbbQV-zruRXq3-SrMxYVbelwqRtMnTdpRDrwZ90qCo_lZKoH2olDB2lvRAZzXVlxPXSOXMHw96yvfzN7w1yEryJgk3Jxzyj_SSc47w5abqFAzGDTstswX9ix7TNLuAp_UTEppgomH6NHHBeExIxE50Le4TrzR5vAdzhbt-6Ol54000RdliAwVt2dZ9OGWfqtaVxojH5W66G4LLmtcDKXlTgxRY0bNgYILkKV7zIJFmhavQRwMt_UYA9BaKkrdAiwGa9OL2qrX9G0udUGET7yX-xfm7bgxOLxpnWIrB0x2fAxnrftbZfCqjtXVwHUhCdTUWfXQ10jn8BWev0qsJ1c0Cml1PGI6CnSoLUHAuAUWbMmNIc2zwiERAEToWotCGuk9S0iLsk-GOtFQWEnlaKaNprZV73LhdQVtNB0sdgDm9hgXEbbJOs9yzihE3lGpT9x-H6xss6Vh8D78jS9PXTvs2HfJml0PkwkLdjOcLgYEdxaAkPL7UWK-m-Go7CEuJ41JGzEEHOZSwrtYJcTUy4T7txCNUl0xMK8WJfZy67yfoMvOYAoItGX5QPR0wtvq83zk9vKfg_L4kPjAcI3YrL-WoSYJyhzqas9hNCYDfHYY-JAWeQH-LxSaNTvkLrVQSGAh3jjgG_GAbUI1h80_h9GLxuw

###
GET https://ivnijlp9xjod.c01-15.plentymarkets.com/rest/items/7769/variations/29044?with=itemCrossSelling
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTdkNWNjNTAxOTRlYjA4ZmEwYTU3NmE1NTY4ZWU1Y2QyODMxNzM4YjQ5YWYzZDlmMjYzYzRmNjIyMWZiYjk4Yjg1OTEyMWNkMjNhZWFiMjQiLCJpYXQiOjE2NTc1MjEwMDguNzM4MSwibmJmIjoxNjU3NTIxMDA4LjczODEsImV4cCI6MTY1NzYwNzQwOC43MzU2LCJzdWIiOiI4Iiwic2NvcGVzIjpbIioiXX0.X412gyNL4iN0-I2XNRrGbbQV-zruRXq3-SrMxYVbelwqRtMnTdpRDrwZ90qCo_lZKoH2olDB2lvRAZzXVlxPXSOXMHw96yvfzN7w1yEryJgk3Jxzyj_SSc47w5abqFAzGDTstswX9ix7TNLuAp_UTEppgomH6NHHBeExIxE50Le4TrzR5vAdzhbt-6Ol54000RdliAwVt2dZ9OGWfqtaVxojH5W66G4LLmtcDKXlTgxRY0bNgYILkKV7zIJFmhavQRwMt_UYA9BaKkrdAiwGa9OL2qrX9G0udUGET7yX-xfm7bgxOLxpnWIrB0x2fAxnrftbZfCqjtXVwHUhCdTUWfXQ10jn8BWev0qsJ1c0Cml1PGI6CnSoLUHAuAUWbMmNIc2zwiERAEToWotCGuk9S0iLsk-GOtFQWEnlaKaNprZV73LhdQVtNB0sdgDm9hgXEbbJOs9yzihE3lGpT9x-H6xss6Vh8D78jS9PXTvs2HfJml0PkwkLdjOcLgYEdxaAkPL7UWK-m-Go7CEuJ41JGzEEHOZSwrtYJcTUy4T7txCNUl0xMK8WJfZy67yfoMvOYAoItGX5QPR0wtvq83zk9vKfg_L4kPjAcI3YrL-WoSYJyhzqas9hNCYDfHYY-JAWeQH-LxSaNTvkLrVQSGAh3jjgG_GAbUI1h80_h9GLxuw

###
GET https://ivnijlp9xjod.c01-15.plentymarkets.com/rest/items/7769/variations/29044?with=itemImages
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTdkNWNjNTAxOTRlYjA4ZmEwYTU3NmE1NTY4ZWU1Y2QyODMxNzM4YjQ5YWYzZDlmMjYzYzRmNjIyMWZiYjk4Yjg1OTEyMWNkMjNhZWFiMjQiLCJpYXQiOjE2NTc1MjEwMDguNzM4MSwibmJmIjoxNjU3NTIxMDA4LjczODEsImV4cCI6MTY1NzYwNzQwOC43MzU2LCJzdWIiOiI4Iiwic2NvcGVzIjpbIioiXX0.X412gyNL4iN0-I2XNRrGbbQV-zruRXq3-SrMxYVbelwqRtMnTdpRDrwZ90qCo_lZKoH2olDB2lvRAZzXVlxPXSOXMHw96yvfzN7w1yEryJgk3Jxzyj_SSc47w5abqFAzGDTstswX9ix7TNLuAp_UTEppgomH6NHHBeExIxE50Le4TrzR5vAdzhbt-6Ol54000RdliAwVt2dZ9OGWfqtaVxojH5W66G4LLmtcDKXlTgxRY0bNgYILkKV7zIJFmhavQRwMt_UYA9BaKkrdAiwGa9OL2qrX9G0udUGET7yX-xfm7bgxOLxpnWIrB0x2fAxnrftbZfCqjtXVwHUhCdTUWfXQ10jn8BWev0qsJ1c0Cml1PGI6CnSoLUHAuAUWbMmNIc2zwiERAEToWotCGuk9S0iLsk-GOtFQWEnlaKaNprZV73LhdQVtNB0sdgDm9hgXEbbJOs9yzihE3lGpT9x-H6xss6Vh8D78jS9PXTvs2HfJml0PkwkLdjOcLgYEdxaAkPL7UWK-m-Go7CEuJ41JGzEEHOZSwrtYJcTUy4T7txCNUl0xMK8WJfZy67yfoMvOYAoItGX5QPR0wtvq83zk9vKfg_L4kPjAcI3YrL-WoSYJyhzqas9hNCYDfHYY-JAWeQH-LxSaNTvkLrVQSGAh3jjgG_GAbUI1h80_h9GLxuw

###
GET https://ivnijlp9xjod.c01-15.plentymarkets.com/rest/items?page=1&with=variations,itemImages,itemShippingProfiles
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTdkNWNjNTAxOTRlYjA4ZmEwYTU3NmE1NTY4ZWU1Y2QyODMxNzM4YjQ5YWYzZDlmMjYzYzRmNjIyMWZiYjk4Yjg1OTEyMWNkMjNhZWFiMjQiLCJpYXQiOjE2NTc1MjEwMDguNzM4MSwibmJmIjoxNjU3NTIxMDA4LjczODEsImV4cCI6MTY1NzYwNzQwOC43MzU2LCJzdWIiOiI4Iiwic2NvcGVzIjpbIioiXX0.X412gyNL4iN0-I2XNRrGbbQV-zruRXq3-SrMxYVbelwqRtMnTdpRDrwZ90qCo_lZKoH2olDB2lvRAZzXVlxPXSOXMHw96yvfzN7w1yEryJgk3Jxzyj_SSc47w5abqFAzGDTstswX9ix7TNLuAp_UTEppgomH6NHHBeExIxE50Le4TrzR5vAdzhbt-6Ol54000RdliAwVt2dZ9OGWfqtaVxojH5W66G4LLmtcDKXlTgxRY0bNgYILkKV7zIJFmhavQRwMt_UYA9BaKkrdAiwGa9OL2qrX9G0udUGET7yX-xfm7bgxOLxpnWIrB0x2fAxnrftbZfCqjtXVwHUhCdTUWfXQ10jn8BWev0qsJ1c0Cml1PGI6CnSoLUHAuAUWbMmNIc2zwiERAEToWotCGuk9S0iLsk-GOtFQWEnlaKaNprZV73LhdQVtNB0sdgDm9hgXEbbJOs9yzihE3lGpT9x-H6xss6Vh8D78jS9PXTvs2HfJml0PkwkLdjOcLgYEdxaAkPL7UWK-m-Go7CEuJ41JGzEEHOZSwrtYJcTUy4T7txCNUl0xMK8WJfZy67yfoMvOYAoItGX5QPR0wtvq83zk9vKfg_L4kPjAcI3YrL-WoSYJyhzqas9hNCYDfHYY-JAWeQH-LxSaNTvkLrVQSGAh3jjgG_GAbUI1h80_h9GLxuw

###
## additionalSkus,attributeValues,attributeValues.attribute,attributeValues.attributeValue,barcodes,barcodes.barcode,base,base.item,base.itemSerialNumber,base.feedback,base.characteristics,base.crossSelling,base.texts,base.availability',base.images,base.shippingProfiles,base.stock,base.stockStorageLocations,bundleComponents,categories,categories.category,categories.categoryBranch,clients,defaultCategories,defaultCategories.category,images,images.image,markets,marketIdentNumbers,salesPrices,salesPrices.salesPrice,skus,supplier,supplier.supplier,timestamps,warehouses,warehouses.warehouse,unit,unit.unit,tags,tags.tag,properties,properties.property
GET https://ivnijlp9xjod.c01-15.plentymarkets.com/rest/pim/variations?with=base.texts
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTdkNWNjNTAxOTRlYjA4ZmEwYTU3NmE1NTY4ZWU1Y2QyODMxNzM4YjQ5YWYzZDlmMjYzYzRmNjIyMWZiYjk4Yjg1OTEyMWNkMjNhZWFiMjQiLCJpYXQiOjE2NTc1MjEwMDguNzM4MSwibmJmIjoxNjU3NTIxMDA4LjczODEsImV4cCI6MTY1NzYwNzQwOC43MzU2LCJzdWIiOiI4Iiwic2NvcGVzIjpbIioiXX0.X412gyNL4iN0-I2XNRrGbbQV-zruRXq3-SrMxYVbelwqRtMnTdpRDrwZ90qCo_lZKoH2olDB2lvRAZzXVlxPXSOXMHw96yvfzN7w1yEryJgk3Jxzyj_SSc47w5abqFAzGDTstswX9ix7TNLuAp_UTEppgomH6NHHBeExIxE50Le4TrzR5vAdzhbt-6Ol54000RdliAwVt2dZ9OGWfqtaVxojH5W66G4LLmtcDKXlTgxRY0bNgYILkKV7zIJFmhavQRwMt_UYA9BaKkrdAiwGa9OL2qrX9G0udUGET7yX-xfm7bgxOLxpnWIrB0x2fAxnrftbZfCqjtXVwHUhCdTUWfXQ10jn8BWev0qsJ1c0Cml1PGI6CnSoLUHAuAUWbMmNIc2zwiERAEToWotCGuk9S0iLsk-GOtFQWEnlaKaNprZV73LhdQVtNB0sdgDm9hgXEbbJOs9yzihE3lGpT9x-H6xss6Vh8D78jS9PXTvs2HfJml0PkwkLdjOcLgYEdxaAkPL7UWK-m-Go7CEuJ41JGzEEHOZSwrtYJcTUy4T7txCNUl0xMK8WJfZy67yfoMvOYAoItGX5QPR0wtvq83zk9vKfg_L4kPjAcI3YrL-WoSYJyhzqas9hNCYDfHYY-JAWeQH-LxSaNTvkLrVQSGAh3jjgG_GAbUI1h80_h9GLxuw


###
POST https://ivnijlp9xjod.c01-15.plentymarkets.com/rest/items
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTdkNWNjNTAxOTRlYjA4ZmEwYTU3NmE1NTY4ZWU1Y2QyODMxNzM4YjQ5YWYzZDlmMjYzYzRmNjIyMWZiYjk4Yjg1OTEyMWNkMjNhZWFiMjQiLCJpYXQiOjE2NTc1MjEwMDguNzM4MSwibmJmIjoxNjU3NTIxMDA4LjczODEsImV4cCI6MTY1NzYwNzQwOC43MzU2LCJzdWIiOiI4Iiwic2NvcGVzIjpbIioiXX0.X412gyNL4iN0-I2XNRrGbbQV-zruRXq3-SrMxYVbelwqRtMnTdpRDrwZ90qCo_lZKoH2olDB2lvRAZzXVlxPXSOXMHw96yvfzN7w1yEryJgk3Jxzyj_SSc47w5abqFAzGDTstswX9ix7TNLuAp_UTEppgomH6NHHBeExIxE50Le4TrzR5vAdzhbt-6Ol54000RdliAwVt2dZ9OGWfqtaVxojH5W66G4LLmtcDKXlTgxRY0bNgYILkKV7zIJFmhavQRwMt_UYA9BaKkrdAiwGa9OL2qrX9G0udUGET7yX-xfm7bgxOLxpnWIrB0x2fAxnrftbZfCqjtXVwHUhCdTUWfXQ10jn8BWev0qsJ1c0Cml1PGI6CnSoLUHAuAUWbMmNIc2zwiERAEToWotCGuk9S0iLsk-GOtFQWEnlaKaNprZV73LhdQVtNB0sdgDm9hgXEbbJOs9yzihE3lGpT9x-H6xss6Vh8D78jS9PXTvs2HfJml0PkwkLdjOcLgYEdxaAkPL7UWK-m-Go7CEuJ41JGzEEHOZSwrtYJcTUy4T7txCNUl0xMK8WJfZy67yfoMvOYAoItGX5QPR0wtvq83zk9vKfg_L4kPjAcI3YrL-WoSYJyhzqas9hNCYDfHYY-JAWeQH-LxSaNTvkLrVQSGAh3jjgG_GAbUI1h80_h9GLxuw

[
    {
        "position":1,
        "stockType":0,
        "storeSpecial":2,
        "condition":0,
        "feedback":0,
        "isSubscribable":false,
        "isShippingPackage":false,
        "itemType":"default",
        "variations": [
            {
                "variationCategories": [
                    {
                        "categoryId": 46
                    }
                ],
                "unit": {
                    "unitId": 1,
                    "content": 1
                }
            }
        ]
    }
]

