###
GET https://qqx6xqycwfc0.c01-15.plentymarkets.com/rest/accounts/addresses
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzM0NGI4Njk4NmM2OTk2Y2MzYmQ0MmJiZDg2ZTM0NDJhYmJkYzdkOGJlOGU4MWYyODA5ZDYyNjI4YzQxZTY1ZjQ0ZDE5YzkzZjQxOTdmOTUiLCJpYXQiOjE2NzY3OTY5NjguNjQwMiwibmJmIjoxNjc2Nzk2OTY4LjY0MDIsImV4cCI6MTY3Njg4MzM2OC42MzUsInN1YiI6IjExIiwic2NvcGVzIjpbIioiXX0.HLoWA_1CUH55ut7Sz4R88JMhk6oi5VyQx4meyC0UdOs6WjiAblAYUthVYFH6zujo_bXib6Cx2nkD7PZnybbWOFayNTrGgFs02xckLFPLUn8a_8nXicj3HXRp3MUe8U0LCvjVAzrBxs08FTRawpWwcBENmaVgt_yDhRlHgO3kQvQbQu7Fuf7D5TekdldgyIFTD7ZlwP_PD5MegSTAAX2p3iWiDnHwY090YTozPhgmOxGE_gX4Q5Iw_Jvd7XRPvhJxmO5O_Y1LV25pl1WSXzigC6U7ZtbmzIzFwFMIVJihSDt_8JC17I6F6Sh1UMRBIHjLqHVSXUST_ftZTE7IHcXz_omJUlPmyfpCduO2EokwxDVXCmTjIUjibemT7xdd5n9m5ABpMjAFJ2D6IaJbBnlTN6U6FHl6zl-TWOMI8s0lLmd6yXQ9-RRNvGIL7nt8X7plQJg0rqLmdaglr-RY9bs_qj7EGZms3WLEwmCE4qh-phJ3Crnia4trrcK8dZyRQP7f8gbtNRRa41Es-ItrzHJO3kwhk_6zE9bLC9AitUMNssGv7G8iHeb74Ut7W7h8gRh3puJFulim35Ncr8sCa_wtlZjsk2Smx-AT2ICVmcnACQBRdIkfBDZflmr8j8sKBF3AH4R7I0dBXnudb-f7LRtJ-gZdPnYSZg8x-X9wpjHUHPU

###
GET https://qqx6xqycwfc0.c01-15.plentymarkets.com/rest/accounts/addresses?page=1&itemsPerPage=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzM0NGI4Njk4NmM2OTk2Y2MzYmQ0MmJiZDg2ZTM0NDJhYmJkYzdkOGJlOGU4MWYyODA5ZDYyNjI4YzQxZTY1ZjQ0ZDE5YzkzZjQxOTdmOTUiLCJpYXQiOjE2NzY3OTY5NjguNjQwMiwibmJmIjoxNjc2Nzk2OTY4LjY0MDIsImV4cCI6MTY3Njg4MzM2OC42MzUsInN1YiI6IjExIiwic2NvcGVzIjpbIioiXX0.HLoWA_1CUH55ut7Sz4R88JMhk6oi5VyQx4meyC0UdOs6WjiAblAYUthVYFH6zujo_bXib6Cx2nkD7PZnybbWOFayNTrGgFs02xckLFPLUn8a_8nXicj3HXRp3MUe8U0LCvjVAzrBxs08FTRawpWwcBENmaVgt_yDhRlHgO3kQvQbQu7Fuf7D5TekdldgyIFTD7ZlwP_PD5MegSTAAX2p3iWiDnHwY090YTozPhgmOxGE_gX4Q5Iw_Jvd7XRPvhJxmO5O_Y1LV25pl1WSXzigC6U7ZtbmzIzFwFMIVJihSDt_8JC17I6F6Sh1UMRBIHjLqHVSXUST_ftZTE7IHcXz_omJUlPmyfpCduO2EokwxDVXCmTjIUjibemT7xdd5n9m5ABpMjAFJ2D6IaJbBnlTN6U6FHl6zl-TWOMI8s0lLmd6yXQ9-RRNvGIL7nt8X7plQJg0rqLmdaglr-RY9bs_qj7EGZms3WLEwmCE4qh-phJ3Crnia4trrcK8dZyRQP7f8gbtNRRa41Es-ItrzHJO3kwhk_6zE9bLC9AitUMNssGv7G8iHeb74Ut7W7h8gRh3puJFulim35Ncr8sCa_wtlZjsk2Smx-AT2ICVmcnACQBRdIkfBDZflmr8j8sKBF3AH4R7I0dBXnudb-f7LRtJ-gZdPnYSZg8x-X9wpjHUHPU

###
GET https://qqx6xqycwfc0.c01-15.plentymarkets.com/rest/accounts/addresses?with=contactRelations,orderRelations&itemsPerPage=150&page=25
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzM0NGI4Njk4NmM2OTk2Y2MzYmQ0MmJiZDg2ZTM0NDJhYmJkYzdkOGJlOGU4MWYyODA5ZDYyNjI4YzQxZTY1ZjQ0ZDE5YzkzZjQxOTdmOTUiLCJpYXQiOjE2NzY3OTY5NjguNjQwMiwibmJmIjoxNjc2Nzk2OTY4LjY0MDIsImV4cCI6MTY3Njg4MzM2OC42MzUsInN1YiI6IjExIiwic2NvcGVzIjpbIioiXX0.HLoWA_1CUH55ut7Sz4R88JMhk6oi5VyQx4meyC0UdOs6WjiAblAYUthVYFH6zujo_bXib6Cx2nkD7PZnybbWOFayNTrGgFs02xckLFPLUn8a_8nXicj3HXRp3MUe8U0LCvjVAzrBxs08FTRawpWwcBENmaVgt_yDhRlHgO3kQvQbQu7Fuf7D5TekdldgyIFTD7ZlwP_PD5MegSTAAX2p3iWiDnHwY090YTozPhgmOxGE_gX4Q5Iw_Jvd7XRPvhJxmO5O_Y1LV25pl1WSXzigC6U7ZtbmzIzFwFMIVJihSDt_8JC17I6F6Sh1UMRBIHjLqHVSXUST_ftZTE7IHcXz_omJUlPmyfpCduO2EokwxDVXCmTjIUjibemT7xdd5n9m5ABpMjAFJ2D6IaJbBnlTN6U6FHl6zl-TWOMI8s0lLmd6yXQ9-RRNvGIL7nt8X7plQJg0rqLmdaglr-RY9bs_qj7EGZms3WLEwmCE4qh-phJ3Crnia4trrcK8dZyRQP7f8gbtNRRa41Es-ItrzHJO3kwhk_6zE9bLC9AitUMNssGv7G8iHeb74Ut7W7h8gRh3puJFulim35Ncr8sCa_wtlZjsk2Smx-AT2ICVmcnACQBRdIkfBDZflmr8j8sKBF3AH4R7I0dBXnudb-f7LRtJ-gZdPnYSZg8x-X9wpjHUHPU

###
GET https://qqx6xqycwfc0.c01-15.plentymarkets.com/rest/accounts/addresses/86223
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzM0NGI4Njk4NmM2OTk2Y2MzYmQ0MmJiZDg2ZTM0NDJhYmJkYzdkOGJlOGU4MWYyODA5ZDYyNjI4YzQxZTY1ZjQ0ZDE5YzkzZjQxOTdmOTUiLCJpYXQiOjE2NzY3OTY5NjguNjQwMiwibmJmIjoxNjc2Nzk2OTY4LjY0MDIsImV4cCI6MTY3Njg4MzM2OC42MzUsInN1YiI6IjExIiwic2NvcGVzIjpbIioiXX0.HLoWA_1CUH55ut7Sz4R88JMhk6oi5VyQx4meyC0UdOs6WjiAblAYUthVYFH6zujo_bXib6Cx2nkD7PZnybbWOFayNTrGgFs02xckLFPLUn8a_8nXicj3HXRp3MUe8U0LCvjVAzrBxs08FTRawpWwcBENmaVgt_yDhRlHgO3kQvQbQu7Fuf7D5TekdldgyIFTD7ZlwP_PD5MegSTAAX2p3iWiDnHwY090YTozPhgmOxGE_gX4Q5Iw_Jvd7XRPvhJxmO5O_Y1LV25pl1WSXzigC6U7ZtbmzIzFwFMIVJihSDt_8JC17I6F6Sh1UMRBIHjLqHVSXUST_ftZTE7IHcXz_omJUlPmyfpCduO2EokwxDVXCmTjIUjibemT7xdd5n9m5ABpMjAFJ2D6IaJbBnlTN6U6FHl6zl-TWOMI8s0lLmd6yXQ9-RRNvGIL7nt8X7plQJg0rqLmdaglr-RY9bs_qj7EGZms3WLEwmCE4qh-phJ3Crnia4trrcK8dZyRQP7f8gbtNRRa41Es-ItrzHJO3kwhk_6zE9bLC9AitUMNssGv7G8iHeb74Ut7W7h8gRh3puJFulim35Ncr8sCa_wtlZjsk2Smx-AT2ICVmcnACQBRdIkfBDZflmr8j8sKBF3AH4R7I0dBXnudb-f7LRtJ-gZdPnYSZg8x-X9wpjHUHPU

###
GET https://qqx6xqycwfc0.c01-15.plentymarkets.com/rest/accounts/addresses/contact_relations
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzM0NGI4Njk4NmM2OTk2Y2MzYmQ0MmJiZDg2ZTM0NDJhYmJkYzdkOGJlOGU4MWYyODA5ZDYyNjI4YzQxZTY1ZjQ0ZDE5YzkzZjQxOTdmOTUiLCJpYXQiOjE2NzY3OTY5NjguNjQwMiwibmJmIjoxNjc2Nzk2OTY4LjY0MDIsImV4cCI6MTY3Njg4MzM2OC42MzUsInN1YiI6IjExIiwic2NvcGVzIjpbIioiXX0.HLoWA_1CUH55ut7Sz4R88JMhk6oi5VyQx4meyC0UdOs6WjiAblAYUthVYFH6zujo_bXib6Cx2nkD7PZnybbWOFayNTrGgFs02xckLFPLUn8a_8nXicj3HXRp3MUe8U0LCvjVAzrBxs08FTRawpWwcBENmaVgt_yDhRlHgO3kQvQbQu7Fuf7D5TekdldgyIFTD7ZlwP_PD5MegSTAAX2p3iWiDnHwY090YTozPhgmOxGE_gX4Q5Iw_Jvd7XRPvhJxmO5O_Y1LV25pl1WSXzigC6U7ZtbmzIzFwFMIVJihSDt_8JC17I6F6Sh1UMRBIHjLqHVSXUST_ftZTE7IHcXz_omJUlPmyfpCduO2EokwxDVXCmTjIUjibemT7xdd5n9m5ABpMjAFJ2D6IaJbBnlTN6U6FHl6zl-TWOMI8s0lLmd6yXQ9-RRNvGIL7nt8X7plQJg0rqLmdaglr-RY9bs_qj7EGZms3WLEwmCE4qh-phJ3Crnia4trrcK8dZyRQP7f8gbtNRRa41Es-ItrzHJO3kwhk_6zE9bLC9AitUMNssGv7G8iHeb74Ut7W7h8gRh3puJFulim35Ncr8sCa_wtlZjsk2Smx-AT2ICVmcnACQBRdIkfBDZflmr8j8sKBF3AH4R7I0dBXnudb-f7LRtJ-gZdPnYSZg8x-X9wpjHUHPU

###
GET https://qqx6xqycwfc0.c01-15.plentymarkets.com/rest/accounts/addresses/contact_relations?contactId=61021
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzM0NGI4Njk4NmM2OTk2Y2MzYmQ0MmJiZDg2ZTM0NDJhYmJkYzdkOGJlOGU4MWYyODA5ZDYyNjI4YzQxZTY1ZjQ0ZDE5YzkzZjQxOTdmOTUiLCJpYXQiOjE2NzY3OTY5NjguNjQwMiwibmJmIjoxNjc2Nzk2OTY4LjY0MDIsImV4cCI6MTY3Njg4MzM2OC42MzUsInN1YiI6IjExIiwic2NvcGVzIjpbIioiXX0.HLoWA_1CUH55ut7Sz4R88JMhk6oi5VyQx4meyC0UdOs6WjiAblAYUthVYFH6zujo_bXib6Cx2nkD7PZnybbWOFayNTrGgFs02xckLFPLUn8a_8nXicj3HXRp3MUe8U0LCvjVAzrBxs08FTRawpWwcBENmaVgt_yDhRlHgO3kQvQbQu7Fuf7D5TekdldgyIFTD7ZlwP_PD5MegSTAAX2p3iWiDnHwY090YTozPhgmOxGE_gX4Q5Iw_Jvd7XRPvhJxmO5O_Y1LV25pl1WSXzigC6U7ZtbmzIzFwFMIVJihSDt_8JC17I6F6Sh1UMRBIHjLqHVSXUST_ftZTE7IHcXz_omJUlPmyfpCduO2EokwxDVXCmTjIUjibemT7xdd5n9m5ABpMjAFJ2D6IaJbBnlTN6U6FHl6zl-TWOMI8s0lLmd6yXQ9-RRNvGIL7nt8X7plQJg0rqLmdaglr-RY9bs_qj7EGZms3WLEwmCE4qh-phJ3Crnia4trrcK8dZyRQP7f8gbtNRRa41Es-ItrzHJO3kwhk_6zE9bLC9AitUMNssGv7G8iHeb74Ut7W7h8gRh3puJFulim35Ncr8sCa_wtlZjsk2Smx-AT2ICVmcnACQBRdIkfBDZflmr8j8sKBF3AH4R7I0dBXnudb-f7LRtJ-gZdPnYSZg8x-X9wpjHUHPU

###
GET https://qqx6xqycwfc0.c01-15.plentymarkets.com/rest/accounts/addresses/option_types
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzM0NGI4Njk4NmM2OTk2Y2MzYmQ0MmJiZDg2ZTM0NDJhYmJkYzdkOGJlOGU4MWYyODA5ZDYyNjI4YzQxZTY1ZjQ0ZDE5YzkzZjQxOTdmOTUiLCJpYXQiOjE2NzY3OTY5NjguNjQwMiwibmJmIjoxNjc2Nzk2OTY4LjY0MDIsImV4cCI6MTY3Njg4MzM2OC42MzUsInN1YiI6IjExIiwic2NvcGVzIjpbIioiXX0.HLoWA_1CUH55ut7Sz4R88JMhk6oi5VyQx4meyC0UdOs6WjiAblAYUthVYFH6zujo_bXib6Cx2nkD7PZnybbWOFayNTrGgFs02xckLFPLUn8a_8nXicj3HXRp3MUe8U0LCvjVAzrBxs08FTRawpWwcBENmaVgt_yDhRlHgO3kQvQbQu7Fuf7D5TekdldgyIFTD7ZlwP_PD5MegSTAAX2p3iWiDnHwY090YTozPhgmOxGE_gX4Q5Iw_Jvd7XRPvhJxmO5O_Y1LV25pl1WSXzigC6U7ZtbmzIzFwFMIVJihSDt_8JC17I6F6Sh1UMRBIHjLqHVSXUST_ftZTE7IHcXz_omJUlPmyfpCduO2EokwxDVXCmTjIUjibemT7xdd5n9m5ABpMjAFJ2D6IaJbBnlTN6U6FHl6zl-TWOMI8s0lLmd6yXQ9-RRNvGIL7nt8X7plQJg0rqLmdaglr-RY9bs_qj7EGZms3WLEwmCE4qh-phJ3Crnia4trrcK8dZyRQP7f8gbtNRRa41Es-ItrzHJO3kwhk_6zE9bLC9AitUMNssGv7G8iHeb74Ut7W7h8gRh3puJFulim35Ncr8sCa_wtlZjsk2Smx-AT2ICVmcnACQBRdIkfBDZflmr8j8sKBF3AH4R7I0dBXnudb-f7LRtJ-gZdPnYSZg8x-X9wpjHUHPU

###
GET https://qqx6xqycwfc0.c01-15.plentymarkets.com/rest/accounts/addresses/options/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzM0NGI4Njk4NmM2OTk2Y2MzYmQ0MmJiZDg2ZTM0NDJhYmJkYzdkOGJlOGU4MWYyODA5ZDYyNjI4YzQxZTY1ZjQ0ZDE5YzkzZjQxOTdmOTUiLCJpYXQiOjE2NzY3OTY5NjguNjQwMiwibmJmIjoxNjc2Nzk2OTY4LjY0MDIsImV4cCI6MTY3Njg4MzM2OC42MzUsInN1YiI6IjExIiwic2NvcGVzIjpbIioiXX0.HLoWA_1CUH55ut7Sz4R88JMhk6oi5VyQx4meyC0UdOs6WjiAblAYUthVYFH6zujo_bXib6Cx2nkD7PZnybbWOFayNTrGgFs02xckLFPLUn8a_8nXicj3HXRp3MUe8U0LCvjVAzrBxs08FTRawpWwcBENmaVgt_yDhRlHgO3kQvQbQu7Fuf7D5TekdldgyIFTD7ZlwP_PD5MegSTAAX2p3iWiDnHwY090YTozPhgmOxGE_gX4Q5Iw_Jvd7XRPvhJxmO5O_Y1LV25pl1WSXzigC6U7ZtbmzIzFwFMIVJihSDt_8JC17I6F6Sh1UMRBIHjLqHVSXUST_ftZTE7IHcXz_omJUlPmyfpCduO2EokwxDVXCmTjIUjibemT7xdd5n9m5ABpMjAFJ2D6IaJbBnlTN6U6FHl6zl-TWOMI8s0lLmd6yXQ9-RRNvGIL7nt8X7plQJg0rqLmdaglr-RY9bs_qj7EGZms3WLEwmCE4qh-phJ3Crnia4trrcK8dZyRQP7f8gbtNRRa41Es-ItrzHJO3kwhk_6zE9bLC9AitUMNssGv7G8iHeb74Ut7W7h8gRh3puJFulim35Ncr8sCa_wtlZjsk2Smx-AT2ICVmcnACQBRdIkfBDZflmr8j8sKBF3AH4R7I0dBXnudb-f7LRtJ-gZdPnYSZg8x-X9wpjHUHPU

###
GET https://qqx6xqycwfc0.c01-15.plentymarkets.com/rest/accounts/addresses/pos_relations
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzM0NGI4Njk4NmM2OTk2Y2MzYmQ0MmJiZDg2ZTM0NDJhYmJkYzdkOGJlOGU4MWYyODA5ZDYyNjI4YzQxZTY1ZjQ0ZDE5YzkzZjQxOTdmOTUiLCJpYXQiOjE2NzY3OTY5NjguNjQwMiwibmJmIjoxNjc2Nzk2OTY4LjY0MDIsImV4cCI6MTY3Njg4MzM2OC42MzUsInN1YiI6IjExIiwic2NvcGVzIjpbIioiXX0.HLoWA_1CUH55ut7Sz4R88JMhk6oi5VyQx4meyC0UdOs6WjiAblAYUthVYFH6zujo_bXib6Cx2nkD7PZnybbWOFayNTrGgFs02xckLFPLUn8a_8nXicj3HXRp3MUe8U0LCvjVAzrBxs08FTRawpWwcBENmaVgt_yDhRlHgO3kQvQbQu7Fuf7D5TekdldgyIFTD7ZlwP_PD5MegSTAAX2p3iWiDnHwY090YTozPhgmOxGE_gX4Q5Iw_Jvd7XRPvhJxmO5O_Y1LV25pl1WSXzigC6U7ZtbmzIzFwFMIVJihSDt_8JC17I6F6Sh1UMRBIHjLqHVSXUST_ftZTE7IHcXz_omJUlPmyfpCduO2EokwxDVXCmTjIUjibemT7xdd5n9m5ABpMjAFJ2D6IaJbBnlTN6U6FHl6zl-TWOMI8s0lLmd6yXQ9-RRNvGIL7nt8X7plQJg0rqLmdaglr-RY9bs_qj7EGZms3WLEwmCE4qh-phJ3Crnia4trrcK8dZyRQP7f8gbtNRRa41Es-ItrzHJO3kwhk_6zE9bLC9AitUMNssGv7G8iHeb74Ut7W7h8gRh3puJFulim35Ncr8sCa_wtlZjsk2Smx-AT2ICVmcnACQBRdIkfBDZflmr8j8sKBF3AH4R7I0dBXnudb-f7LRtJ-gZdPnYSZg8x-X9wpjHUHPU

###
GET https://qqx6xqycwfc0.c01-15.plentymarkets.com/rest/accounts/addresses/relation_types
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzM0NGI4Njk4NmM2OTk2Y2MzYmQ0MmJiZDg2ZTM0NDJhYmJkYzdkOGJlOGU4MWYyODA5ZDYyNjI4YzQxZTY1ZjQ0ZDE5YzkzZjQxOTdmOTUiLCJpYXQiOjE2NzY3OTY5NjguNjQwMiwibmJmIjoxNjc2Nzk2OTY4LjY0MDIsImV4cCI6MTY3Njg4MzM2OC42MzUsInN1YiI6IjExIiwic2NvcGVzIjpbIioiXX0.HLoWA_1CUH55ut7Sz4R88JMhk6oi5VyQx4meyC0UdOs6WjiAblAYUthVYFH6zujo_bXib6Cx2nkD7PZnybbWOFayNTrGgFs02xckLFPLUn8a_8nXicj3HXRp3MUe8U0LCvjVAzrBxs08FTRawpWwcBENmaVgt_yDhRlHgO3kQvQbQu7Fuf7D5TekdldgyIFTD7ZlwP_PD5MegSTAAX2p3iWiDnHwY090YTozPhgmOxGE_gX4Q5Iw_Jvd7XRPvhJxmO5O_Y1LV25pl1WSXzigC6U7ZtbmzIzFwFMIVJihSDt_8JC17I6F6Sh1UMRBIHjLqHVSXUST_ftZTE7IHcXz_omJUlPmyfpCduO2EokwxDVXCmTjIUjibemT7xdd5n9m5ABpMjAFJ2D6IaJbBnlTN6U6FHl6zl-TWOMI8s0lLmd6yXQ9-RRNvGIL7nt8X7plQJg0rqLmdaglr-RY9bs_qj7EGZms3WLEwmCE4qh-phJ3Crnia4trrcK8dZyRQP7f8gbtNRRa41Es-ItrzHJO3kwhk_6zE9bLC9AitUMNssGv7G8iHeb74Ut7W7h8gRh3puJFulim35Ncr8sCa_wtlZjsk2Smx-AT2ICVmcnACQBRdIkfBDZflmr8j8sKBF3AH4R7I0dBXnudb-f7LRtJ-gZdPnYSZg8x-X9wpjHUHPU

###
GET https://qqx6xqycwfc0.c01-15.plentymarkets.com/rest/accounts/addresses/102/options
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzM0NGI4Njk4NmM2OTk2Y2MzYmQ0MmJiZDg2ZTM0NDJhYmJkYzdkOGJlOGU4MWYyODA5ZDYyNjI4YzQxZTY1ZjQ0ZDE5YzkzZjQxOTdmOTUiLCJpYXQiOjE2NzY3OTY5NjguNjQwMiwibmJmIjoxNjc2Nzk2OTY4LjY0MDIsImV4cCI6MTY3Njg4MzM2OC42MzUsInN1YiI6IjExIiwic2NvcGVzIjpbIioiXX0.HLoWA_1CUH55ut7Sz4R88JMhk6oi5VyQx4meyC0UdOs6WjiAblAYUthVYFH6zujo_bXib6Cx2nkD7PZnybbWOFayNTrGgFs02xckLFPLUn8a_8nXicj3HXRp3MUe8U0LCvjVAzrBxs08FTRawpWwcBENmaVgt_yDhRlHgO3kQvQbQu7Fuf7D5TekdldgyIFTD7ZlwP_PD5MegSTAAX2p3iWiDnHwY090YTozPhgmOxGE_gX4Q5Iw_Jvd7XRPvhJxmO5O_Y1LV25pl1WSXzigC6U7ZtbmzIzFwFMIVJihSDt_8JC17I6F6Sh1UMRBIHjLqHVSXUST_ftZTE7IHcXz_omJUlPmyfpCduO2EokwxDVXCmTjIUjibemT7xdd5n9m5ABpMjAFJ2D6IaJbBnlTN6U6FHl6zl-TWOMI8s0lLmd6yXQ9-RRNvGIL7nt8X7plQJg0rqLmdaglr-RY9bs_qj7EGZms3WLEwmCE4qh-phJ3Crnia4trrcK8dZyRQP7f8gbtNRRa41Es-ItrzHJO3kwhk_6zE9bLC9AitUMNssGv7G8iHeb74Ut7W7h8gRh3puJFulim35Ncr8sCa_wtlZjsk2Smx-AT2ICVmcnACQBRdIkfBDZflmr8j8sKBF3AH4R7I0dBXnudb-f7LRtJ-gZdPnYSZg8x-X9wpjHUHPU

###
GET https://qqx6xqycwfc0.c01-15.plentymarkets.com/rest/accounts/addresses/{addressId}/related_data
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzM0NGI4Njk4NmM2OTk2Y2MzYmQ0MmJiZDg2ZTM0NDJhYmJkYzdkOGJlOGU4MWYyODA5ZDYyNjI4YzQxZTY1ZjQ0ZDE5YzkzZjQxOTdmOTUiLCJpYXQiOjE2NzY3OTY5NjguNjQwMiwibmJmIjoxNjc2Nzk2OTY4LjY0MDIsImV4cCI6MTY3Njg4MzM2OC42MzUsInN1YiI6IjExIiwic2NvcGVzIjpbIioiXX0.HLoWA_1CUH55ut7Sz4R88JMhk6oi5VyQx4meyC0UdOs6WjiAblAYUthVYFH6zujo_bXib6Cx2nkD7PZnybbWOFayNTrGgFs02xckLFPLUn8a_8nXicj3HXRp3MUe8U0LCvjVAzrBxs08FTRawpWwcBENmaVgt_yDhRlHgO3kQvQbQu7Fuf7D5TekdldgyIFTD7ZlwP_PD5MegSTAAX2p3iWiDnHwY090YTozPhgmOxGE_gX4Q5Iw_Jvd7XRPvhJxmO5O_Y1LV25pl1WSXzigC6U7ZtbmzIzFwFMIVJihSDt_8JC17I6F6Sh1UMRBIHjLqHVSXUST_ftZTE7IHcXz_omJUlPmyfpCduO2EokwxDVXCmTjIUjibemT7xdd5n9m5ABpMjAFJ2D6IaJbBnlTN6U6FHl6zl-TWOMI8s0lLmd6yXQ9-RRNvGIL7nt8X7plQJg0rqLmdaglr-RY9bs_qj7EGZms3WLEwmCE4qh-phJ3Crnia4trrcK8dZyRQP7f8gbtNRRa41Es-ItrzHJO3kwhk_6zE9bLC9AitUMNssGv7G8iHeb74Ut7W7h8gRh3puJFulim35Ncr8sCa_wtlZjsk2Smx-AT2ICVmcnACQBRdIkfBDZflmr8j8sKBF3AH4R7I0dBXnudb-f7LRtJ-gZdPnYSZg8x-X9wpjHUHPU

###
GET https://qqx6xqycwfc0.c01-15.plentymarkets.com/rest/accounts/contact_relations/{accountContactRelationId}
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzM0NGI4Njk4NmM2OTk2Y2MzYmQ0MmJiZDg2ZTM0NDJhYmJkYzdkOGJlOGU4MWYyODA5ZDYyNjI4YzQxZTY1ZjQ0ZDE5YzkzZjQxOTdmOTUiLCJpYXQiOjE2NzY3OTY5NjguNjQwMiwibmJmIjoxNjc2Nzk2OTY4LjY0MDIsImV4cCI6MTY3Njg4MzM2OC42MzUsInN1YiI6IjExIiwic2NvcGVzIjpbIioiXX0.HLoWA_1CUH55ut7Sz4R88JMhk6oi5VyQx4meyC0UdOs6WjiAblAYUthVYFH6zujo_bXib6Cx2nkD7PZnybbWOFayNTrGgFs02xckLFPLUn8a_8nXicj3HXRp3MUe8U0LCvjVAzrBxs08FTRawpWwcBENmaVgt_yDhRlHgO3kQvQbQu7Fuf7D5TekdldgyIFTD7ZlwP_PD5MegSTAAX2p3iWiDnHwY090YTozPhgmOxGE_gX4Q5Iw_Jvd7XRPvhJxmO5O_Y1LV25pl1WSXzigC6U7ZtbmzIzFwFMIVJihSDt_8JC17I6F6Sh1UMRBIHjLqHVSXUST_ftZTE7IHcXz_omJUlPmyfpCduO2EokwxDVXCmTjIUjibemT7xdd5n9m5ABpMjAFJ2D6IaJbBnlTN6U6FHl6zl-TWOMI8s0lLmd6yXQ9-RRNvGIL7nt8X7plQJg0rqLmdaglr-RY9bs_qj7EGZms3WLEwmCE4qh-phJ3Crnia4trrcK8dZyRQP7f8gbtNRRa41Es-ItrzHJO3kwhk_6zE9bLC9AitUMNssGv7G8iHeb74Ut7W7h8gRh3puJFulim35Ncr8sCa_wtlZjsk2Smx-AT2ICVmcnACQBRdIkfBDZflmr8j8sKBF3AH4R7I0dBXnudb-f7LRtJ-gZdPnYSZg8x-X9wpjHUHPU


### ORDER PROPERTY CREATE
GET https://qqx6xqycwfc0.c01-15.plentymarkets.com/rest/batch
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzM0NGI4Njk4NmM2OTk2Y2MzYmQ0MmJiZDg2ZTM0NDJhYmJkYzdkOGJlOGU4MWYyODA5ZDYyNjI4YzQxZTY1ZjQ0ZDE5YzkzZjQxOTdmOTUiLCJpYXQiOjE2NzY3OTY5NjguNjQwMiwibmJmIjoxNjc2Nzk2OTY4LjY0MDIsImV4cCI6MTY3Njg4MzM2OC42MzUsInN1YiI6IjExIiwic2NvcGVzIjpbIioiXX0.HLoWA_1CUH55ut7Sz4R88JMhk6oi5VyQx4meyC0UdOs6WjiAblAYUthVYFH6zujo_bXib6Cx2nkD7PZnybbWOFayNTrGgFs02xckLFPLUn8a_8nXicj3HXRp3MUe8U0LCvjVAzrBxs08FTRawpWwcBENmaVgt_yDhRlHgO3kQvQbQu7Fuf7D5TekdldgyIFTD7ZlwP_PD5MegSTAAX2p3iWiDnHwY090YTozPhgmOxGE_gX4Q5Iw_Jvd7XRPvhJxmO5O_Y1LV25pl1WSXzigC6U7ZtbmzIzFwFMIVJihSDt_8JC17I6F6Sh1UMRBIHjLqHVSXUST_ftZTE7IHcXz_omJUlPmyfpCduO2EokwxDVXCmTjIUjibemT7xdd5n9m5ABpMjAFJ2D6IaJbBnlTN6U6FHl6zl-TWOMI8s0lLmd6yXQ9-RRNvGIL7nt8X7plQJg0rqLmdaglr-RY9bs_qj7EGZms3WLEwmCE4qh-phJ3Crnia4trrcK8dZyRQP7f8gbtNRRa41Es-ItrzHJO3kwhk_6zE9bLC9AitUMNssGv7G8iHeb74Ut7W7h8gRh3puJFulim35Ncr8sCa_wtlZjsk2Smx-AT2ICVmcnACQBRdIkfBDZflmr8j8sKBF3AH4R7I0dBXnudb-f7LRtJ-gZdPnYSZg8x-X9wpjHUHPU

{
    "payloads": [
        {
            "resource": "/rest/accounts/addresses/1007",
            "method": "GET",
            "body": {
            }
        },
        {
            "resource": "/rest/accounts/addresses/1008",
            "method": "GET",
            "body": {
            }
        }
    ]
}
