###
GET https://www.sscsupply.at/rest/orders/77579
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGNhNmIyNjE0NGViMTVlZmM5YzRhMGYzMzQ4MDQwMGRiNTBjYTJjZmJmN2VjODU4MmI2MjcxZGI5MjI0NjgwNjlkNTU1NDI2NTk3MTA1MzkiLCJpYXQiOjE2NzkwNTc2ODMuNTI3NSwibmJmIjoxNjc5MDU3NjgzLjUyNzUsImV4cCI6MTY3OTE0NDA4My41MjU0LCJzdWIiOiI1NCIsInNjb3BlcyI6WyIqIl19.KUN7sf7Xrz6iLFbaHGhq9jWEjZa54EcxnyWCaeat6g1YzvhRR9VO7FfoUYMtelR1fL9EsbWzBaHgpmzVB-1wYXujjFn6Igsxlp1VQC1mWyUwLlaczVWgmP9HGqxl9jI-iNzgHhJ3x9FnBDT78yE1z-iFGufsQ3dVmckmHDrOF6mHJTvVOUNMpYDznRDnIJsjDdm7nAeFF7VQqA2sYUsjSRKo51jv-plBUuZUKBzM2I2F-1vL3Mmr7bhf_iCg3beeyjR9v0g-5EZyqyJ-uZ4Pm0ysbdpYcdufMIKTKf5c6ycv5yEJNfnzQwW0aZFpll5Cq79s7m4BjXQx6prcm-i2GPyv5nBLTws418p692my5fknYbSl9zWkV7_pHJu1p9DLjE_km-9cvcv3vFCXwqrn3ho80GkBAtzaTASZt_OJvdKcdQ9-StUcpnDSgYp0em86cp3H564SgMTjcymV8JJ8-1RtsnB_oPHaqsSex30CnwfaX9S7LeL-gpADrUK5SdR1uT4QuZmD5s9ls6g6sEKfHcAq2of1SAHM0XUtJ134SYKDwy6FSSULhmFnkLj2zEFsp_7JYs_M-4CU4Cc37WdJrh42MIFkTm8KbCrRQvnZvbT6KsiuuclVBK68fmtMtHRMF-s90CK2ymn24Xva-VzN5LCRmp8qBO01W9B3WAgWqRU

### referrerId=10.00
GET https://www.sscsupply.at/rest/orders?referrerId=10.00&updatedAtFrom=2021-03-08T00%3A00%3A00%2B00%3A00
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGNhNmIyNjE0NGViMTVlZmM5YzRhMGYzMzQ4MDQwMGRiNTBjYTJjZmJmN2VjODU4MmI2MjcxZGI5MjI0NjgwNjlkNTU1NDI2NTk3MTA1MzkiLCJpYXQiOjE2NzkwNTc2ODMuNTI3NSwibmJmIjoxNjc5MDU3NjgzLjUyNzUsImV4cCI6MTY3OTE0NDA4My41MjU0LCJzdWIiOiI1NCIsInNjb3BlcyI6WyIqIl19.KUN7sf7Xrz6iLFbaHGhq9jWEjZa54EcxnyWCaeat6g1YzvhRR9VO7FfoUYMtelR1fL9EsbWzBaHgpmzVB-1wYXujjFn6Igsxlp1VQC1mWyUwLlaczVWgmP9HGqxl9jI-iNzgHhJ3x9FnBDT78yE1z-iFGufsQ3dVmckmHDrOF6mHJTvVOUNMpYDznRDnIJsjDdm7nAeFF7VQqA2sYUsjSRKo51jv-plBUuZUKBzM2I2F-1vL3Mmr7bhf_iCg3beeyjR9v0g-5EZyqyJ-uZ4Pm0ysbdpYcdufMIKTKf5c6ycv5yEJNfnzQwW0aZFpll5Cq79s7m4BjXQx6prcm-i2GPyv5nBLTws418p692my5fknYbSl9zWkV7_pHJu1p9DLjE_km-9cvcv3vFCXwqrn3ho80GkBAtzaTASZt_OJvdKcdQ9-StUcpnDSgYp0em86cp3H564SgMTjcymV8JJ8-1RtsnB_oPHaqsSex30CnwfaX9S7LeL-gpADrUK5SdR1uT4QuZmD5s9ls6g6sEKfHcAq2of1SAHM0XUtJ134SYKDwy6FSSULhmFnkLj2zEFsp_7JYs_M-4CU4Cc37WdJrh42MIFkTm8KbCrRQvnZvbT6KsiuuclVBK68fmtMtHRMF-s90CK2ymn24Xva-VzN5LCRmp8qBO01W9B3WAgWqRU

### updatedAtFrom WC3 ::: 2022-08-19T13:20:36+00:00 || 2016-10-24T13:33:23+02:00
GET https://www.sscsupply.at/rest/orders?updatedAtFrom=2022-08-19T14%3A00%3A00%2B01%3A00
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGNhNmIyNjE0NGViMTVlZmM5YzRhMGYzMzQ4MDQwMGRiNTBjYTJjZmJmN2VjODU4MmI2MjcxZGI5MjI0NjgwNjlkNTU1NDI2NTk3MTA1MzkiLCJpYXQiOjE2NzkwNTc2ODMuNTI3NSwibmJmIjoxNjc5MDU3NjgzLjUyNzUsImV4cCI6MTY3OTE0NDA4My41MjU0LCJzdWIiOiI1NCIsInNjb3BlcyI6WyIqIl19.KUN7sf7Xrz6iLFbaHGhq9jWEjZa54EcxnyWCaeat6g1YzvhRR9VO7FfoUYMtelR1fL9EsbWzBaHgpmzVB-1wYXujjFn6Igsxlp1VQC1mWyUwLlaczVWgmP9HGqxl9jI-iNzgHhJ3x9FnBDT78yE1z-iFGufsQ3dVmckmHDrOF6mHJTvVOUNMpYDznRDnIJsjDdm7nAeFF7VQqA2sYUsjSRKo51jv-plBUuZUKBzM2I2F-1vL3Mmr7bhf_iCg3beeyjR9v0g-5EZyqyJ-uZ4Pm0ysbdpYcdufMIKTKf5c6ycv5yEJNfnzQwW0aZFpll5Cq79s7m4BjXQx6prcm-i2GPyv5nBLTws418p692my5fknYbSl9zWkV7_pHJu1p9DLjE_km-9cvcv3vFCXwqrn3ho80GkBAtzaTASZt_OJvdKcdQ9-StUcpnDSgYp0em86cp3H564SgMTjcymV8JJ8-1RtsnB_oPHaqsSex30CnwfaX9S7LeL-gpADrUK5SdR1uT4QuZmD5s9ls6g6sEKfHcAq2of1SAHM0XUtJ134SYKDwy6FSSULhmFnkLj2zEFsp_7JYs_M-4CU4Cc37WdJrh42MIFkTm8KbCrRQvnZvbT6KsiuuclVBK68fmtMtHRMF-s90CK2ymn24Xva-VzN5LCRmp8qBO01W9B3WAgWqRU

### with filters encoded test !!
GET https://www.sscsupply.at/rest/orders?updatedAtFrom=2022-03-27T13%3A36%3A53%2B00%3A00&itemsPerPage=150&with%5B%5D=addresses%26with%5B%5D%3Drelations%26with%5B%5D%3Dcomments%26with%5B%5D%3Dlocation%26with%5B%5D%3Dpayments%26with%5B%5D%3Ddocuments%26with%5B%5D%3DshippingPackages%26with%5B%5D%3DcontactReceiver&page=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGNhNmIyNjE0NGViMTVlZmM5YzRhMGYzMzQ4MDQwMGRiNTBjYTJjZmJmN2VjODU4MmI2MjcxZGI5MjI0NjgwNjlkNTU1NDI2NTk3MTA1MzkiLCJpYXQiOjE2NzkwNTc2ODMuNTI3NSwibmJmIjoxNjc5MDU3NjgzLjUyNzUsImV4cCI6MTY3OTE0NDA4My41MjU0LCJzdWIiOiI1NCIsInNjb3BlcyI6WyIqIl19.KUN7sf7Xrz6iLFbaHGhq9jWEjZa54EcxnyWCaeat6g1YzvhRR9VO7FfoUYMtelR1fL9EsbWzBaHgpmzVB-1wYXujjFn6Igsxlp1VQC1mWyUwLlaczVWgmP9HGqxl9jI-iNzgHhJ3x9FnBDT78yE1z-iFGufsQ3dVmckmHDrOF6mHJTvVOUNMpYDznRDnIJsjDdm7nAeFF7VQqA2sYUsjSRKo51jv-plBUuZUKBzM2I2F-1vL3Mmr7bhf_iCg3beeyjR9v0g-5EZyqyJ-uZ4Pm0ysbdpYcdufMIKTKf5c6ycv5yEJNfnzQwW0aZFpll5Cq79s7m4BjXQx6prcm-i2GPyv5nBLTws418p692my5fknYbSl9zWkV7_pHJu1p9DLjE_km-9cvcv3vFCXwqrn3ho80GkBAtzaTASZt_OJvdKcdQ9-StUcpnDSgYp0em86cp3H564SgMTjcymV8JJ8-1RtsnB_oPHaqsSex30CnwfaX9S7LeL-gpADrUK5SdR1uT4QuZmD5s9ls6g6sEKfHcAq2of1SAHM0XUtJ134SYKDwy6FSSULhmFnkLj2zEFsp_7JYs_M-4CU4Cc37WdJrh42MIFkTm8KbCrRQvnZvbT6KsiuuclVBK68fmtMtHRMF-s90CK2ymn24Xva-VzN5LCRmp8qBO01W9B3WAgWqRU

### with filters decoded test !!
GET https://www.sscsupply.at/rest/orders?updatedAtFrom=2022-03-27T13%3A36%3A53%2B00%3A00&with[]=addresses&with[]=relations&with[]=comments&with[]=location&with[]=payments&with[]=documents&with[]=shippingPackages&with[]=contactReceiver
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGNhNmIyNjE0NGViMTVlZmM5YzRhMGYzMzQ4MDQwMGRiNTBjYTJjZmJmN2VjODU4MmI2MjcxZGI5MjI0NjgwNjlkNTU1NDI2NTk3MTA1MzkiLCJpYXQiOjE2NzkwNTc2ODMuNTI3NSwibmJmIjoxNjc5MDU3NjgzLjUyNzUsImV4cCI6MTY3OTE0NDA4My41MjU0LCJzdWIiOiI1NCIsInNjb3BlcyI6WyIqIl19.KUN7sf7Xrz6iLFbaHGhq9jWEjZa54EcxnyWCaeat6g1YzvhRR9VO7FfoUYMtelR1fL9EsbWzBaHgpmzVB-1wYXujjFn6Igsxlp1VQC1mWyUwLlaczVWgmP9HGqxl9jI-iNzgHhJ3x9FnBDT78yE1z-iFGufsQ3dVmckmHDrOF6mHJTvVOUNMpYDznRDnIJsjDdm7nAeFF7VQqA2sYUsjSRKo51jv-plBUuZUKBzM2I2F-1vL3Mmr7bhf_iCg3beeyjR9v0g-5EZyqyJ-uZ4Pm0ysbdpYcdufMIKTKf5c6ycv5yEJNfnzQwW0aZFpll5Cq79s7m4BjXQx6prcm-i2GPyv5nBLTws418p692my5fknYbSl9zWkV7_pHJu1p9DLjE_km-9cvcv3vFCXwqrn3ho80GkBAtzaTASZt_OJvdKcdQ9-StUcpnDSgYp0em86cp3H564SgMTjcymV8JJ8-1RtsnB_oPHaqsSex30CnwfaX9S7LeL-gpADrUK5SdR1uT4QuZmD5s9ls6g6sEKfHcAq2of1SAHM0XUtJ134SYKDwy6FSSULhmFnkLj2zEFsp_7JYs_M-4CU4Cc37WdJrh42MIFkTm8KbCrRQvnZvbT6KsiuuclVBK68fmtMtHRMF-s90CK2ymn24Xva-VzN5LCRmp8qBO01W9B3WAgWqRU

### with filters 6966
GET https://www.sscsupply.at/rest/orders/74955?with[]=addresses&with[]=relations&with[]=comments&with[]=location&with[]=payments&with[]=documents&with[]=contactSender&with[]=contactReceiver&with[]=warehouseSender&with[]=warehouseReceiver&with[]=originOrderReferences&with[]=shippingPackages&with[]=shippingInformation&with[]=paymentTerms&with[]=properties
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGNhNmIyNjE0NGViMTVlZmM5YzRhMGYzMzQ4MDQwMGRiNTBjYTJjZmJmN2VjODU4MmI2MjcxZGI5MjI0NjgwNjlkNTU1NDI2NTk3MTA1MzkiLCJpYXQiOjE2NzkwNTc2ODMuNTI3NSwibmJmIjoxNjc5MDU3NjgzLjUyNzUsImV4cCI6MTY3OTE0NDA4My41MjU0LCJzdWIiOiI1NCIsInNjb3BlcyI6WyIqIl19.KUN7sf7Xrz6iLFbaHGhq9jWEjZa54EcxnyWCaeat6g1YzvhRR9VO7FfoUYMtelR1fL9EsbWzBaHgpmzVB-1wYXujjFn6Igsxlp1VQC1mWyUwLlaczVWgmP9HGqxl9jI-iNzgHhJ3x9FnBDT78yE1z-iFGufsQ3dVmckmHDrOF6mHJTvVOUNMpYDznRDnIJsjDdm7nAeFF7VQqA2sYUsjSRKo51jv-plBUuZUKBzM2I2F-1vL3Mmr7bhf_iCg3beeyjR9v0g-5EZyqyJ-uZ4Pm0ysbdpYcdufMIKTKf5c6ycv5yEJNfnzQwW0aZFpll5Cq79s7m4BjXQx6prcm-i2GPyv5nBLTws418p692my5fknYbSl9zWkV7_pHJu1p9DLjE_km-9cvcv3vFCXwqrn3ho80GkBAtzaTASZt_OJvdKcdQ9-StUcpnDSgYp0em86cp3H564SgMTjcymV8JJ8-1RtsnB_oPHaqsSex30CnwfaX9S7LeL-gpADrUK5SdR1uT4QuZmD5s9ls6g6sEKfHcAq2of1SAHM0XUtJ134SYKDwy6FSSULhmFnkLj2zEFsp_7JYs_M-4CU4Cc37WdJrh42MIFkTm8KbCrRQvnZvbT6KsiuuclVBK68fmtMtHRMF-s90CK2ymn24Xva-VzN5LCRmp8qBO01W9B3WAgWqRU

###
GET https://www.sscsupply.at/rest/orders?orderIds=3535,3536
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGNhNmIyNjE0NGViMTVlZmM5YzRhMGYzMzQ4MDQwMGRiNTBjYTJjZmJmN2VjODU4MmI2MjcxZGI5MjI0NjgwNjlkNTU1NDI2NTk3MTA1MzkiLCJpYXQiOjE2NzkwNTc2ODMuNTI3NSwibmJmIjoxNjc5MDU3NjgzLjUyNzUsImV4cCI6MTY3OTE0NDA4My41MjU0LCJzdWIiOiI1NCIsInNjb3BlcyI6WyIqIl19.KUN7sf7Xrz6iLFbaHGhq9jWEjZa54EcxnyWCaeat6g1YzvhRR9VO7FfoUYMtelR1fL9EsbWzBaHgpmzVB-1wYXujjFn6Igsxlp1VQC1mWyUwLlaczVWgmP9HGqxl9jI-iNzgHhJ3x9FnBDT78yE1z-iFGufsQ3dVmckmHDrOF6mHJTvVOUNMpYDznRDnIJsjDdm7nAeFF7VQqA2sYUsjSRKo51jv-plBUuZUKBzM2I2F-1vL3Mmr7bhf_iCg3beeyjR9v0g-5EZyqyJ-uZ4Pm0ysbdpYcdufMIKTKf5c6ycv5yEJNfnzQwW0aZFpll5Cq79s7m4BjXQx6prcm-i2GPyv5nBLTws418p692my5fknYbSl9zWkV7_pHJu1p9DLjE_km-9cvcv3vFCXwqrn3ho80GkBAtzaTASZt_OJvdKcdQ9-StUcpnDSgYp0em86cp3H564SgMTjcymV8JJ8-1RtsnB_oPHaqsSex30CnwfaX9S7LeL-gpADrUK5SdR1uT4QuZmD5s9ls6g6sEKfHcAq2of1SAHM0XUtJ134SYKDwy6FSSULhmFnkLj2zEFsp_7JYs_M-4CU4Cc37WdJrh42MIFkTm8KbCrRQvnZvbT6KsiuuclVBK68fmtMtHRMF-s90CK2ymn24Xva-VzN5LCRmp8qBO01W9B3WAgWqRU

### with=documents
GET https://www.sscsupply.at/rest/orders?orderIds=6815&with=documents
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGNhNmIyNjE0NGViMTVlZmM5YzRhMGYzMzQ4MDQwMGRiNTBjYTJjZmJmN2VjODU4MmI2MjcxZGI5MjI0NjgwNjlkNTU1NDI2NTk3MTA1MzkiLCJpYXQiOjE2NzkwNTc2ODMuNTI3NSwibmJmIjoxNjc5MDU3NjgzLjUyNzUsImV4cCI6MTY3OTE0NDA4My41MjU0LCJzdWIiOiI1NCIsInNjb3BlcyI6WyIqIl19.KUN7sf7Xrz6iLFbaHGhq9jWEjZa54EcxnyWCaeat6g1YzvhRR9VO7FfoUYMtelR1fL9EsbWzBaHgpmzVB-1wYXujjFn6Igsxlp1VQC1mWyUwLlaczVWgmP9HGqxl9jI-iNzgHhJ3x9FnBDT78yE1z-iFGufsQ3dVmckmHDrOF6mHJTvVOUNMpYDznRDnIJsjDdm7nAeFF7VQqA2sYUsjSRKo51jv-plBUuZUKBzM2I2F-1vL3Mmr7bhf_iCg3beeyjR9v0g-5EZyqyJ-uZ4Pm0ysbdpYcdufMIKTKf5c6ycv5yEJNfnzQwW0aZFpll5Cq79s7m4BjXQx6prcm-i2GPyv5nBLTws418p692my5fknYbSl9zWkV7_pHJu1p9DLjE_km-9cvcv3vFCXwqrn3ho80GkBAtzaTASZt_OJvdKcdQ9-StUcpnDSgYp0em86cp3H564SgMTjcymV8JJ8-1RtsnB_oPHaqsSex30CnwfaX9S7LeL-gpADrUK5SdR1uT4QuZmD5s9ls6g6sEKfHcAq2of1SAHM0XUtJ134SYKDwy6FSSULhmFnkLj2zEFsp_7JYs_M-4CU4Cc37WdJrh42MIFkTm8KbCrRQvnZvbT6KsiuuclVBK68fmtMtHRMF-s90CK2ymn24Xva-VzN5LCRmp8qBO01W9B3WAgWqRU

###
GET https://www.sscsupply.at/rest/documents/186
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGNhNmIyNjE0NGViMTVlZmM5YzRhMGYzMzQ4MDQwMGRiNTBjYTJjZmJmN2VjODU4MmI2MjcxZGI5MjI0NjgwNjlkNTU1NDI2NTk3MTA1MzkiLCJpYXQiOjE2NzkwNTc2ODMuNTI3NSwibmJmIjoxNjc5MDU3NjgzLjUyNzUsImV4cCI6MTY3OTE0NDA4My41MjU0LCJzdWIiOiI1NCIsInNjb3BlcyI6WyIqIl19.KUN7sf7Xrz6iLFbaHGhq9jWEjZa54EcxnyWCaeat6g1YzvhRR9VO7FfoUYMtelR1fL9EsbWzBaHgpmzVB-1wYXujjFn6Igsxlp1VQC1mWyUwLlaczVWgmP9HGqxl9jI-iNzgHhJ3x9FnBDT78yE1z-iFGufsQ3dVmckmHDrOF6mHJTvVOUNMpYDznRDnIJsjDdm7nAeFF7VQqA2sYUsjSRKo51jv-plBUuZUKBzM2I2F-1vL3Mmr7bhf_iCg3beeyjR9v0g-5EZyqyJ-uZ4Pm0ysbdpYcdufMIKTKf5c6ycv5yEJNfnzQwW0aZFpll5Cq79s7m4BjXQx6prcm-i2GPyv5nBLTws418p692my5fknYbSl9zWkV7_pHJu1p9DLjE_km-9cvcv3vFCXwqrn3ho80GkBAtzaTASZt_OJvdKcdQ9-StUcpnDSgYp0em86cp3H564SgMTjcymV8JJ8-1RtsnB_oPHaqsSex30CnwfaX9S7LeL-gpADrUK5SdR1uT4QuZmD5s9ls6g6sEKfHcAq2of1SAHM0XUtJ134SYKDwy6FSSULhmFnkLj2zEFsp_7JYs_M-4CU4Cc37WdJrh42MIFkTm8KbCrRQvnZvbT6KsiuuclVBK68fmtMtHRMF-s90CK2ymn24Xva-VzN5LCRmp8qBO01W9B3WAgWqRU

### ORDER REFERRES
GET https://www.sscsupply.at/rest/orders/referrers
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGNhNmIyNjE0NGViMTVlZmM5YzRhMGYzMzQ4MDQwMGRiNTBjYTJjZmJmN2VjODU4MmI2MjcxZGI5MjI0NjgwNjlkNTU1NDI2NTk3MTA1MzkiLCJpYXQiOjE2NzkwNTc2ODMuNTI3NSwibmJmIjoxNjc5MDU3NjgzLjUyNzUsImV4cCI6MTY3OTE0NDA4My41MjU0LCJzdWIiOiI1NCIsInNjb3BlcyI6WyIqIl19.KUN7sf7Xrz6iLFbaHGhq9jWEjZa54EcxnyWCaeat6g1YzvhRR9VO7FfoUYMtelR1fL9EsbWzBaHgpmzVB-1wYXujjFn6Igsxlp1VQC1mWyUwLlaczVWgmP9HGqxl9jI-iNzgHhJ3x9FnBDT78yE1z-iFGufsQ3dVmckmHDrOF6mHJTvVOUNMpYDznRDnIJsjDdm7nAeFF7VQqA2sYUsjSRKo51jv-plBUuZUKBzM2I2F-1vL3Mmr7bhf_iCg3beeyjR9v0g-5EZyqyJ-uZ4Pm0ysbdpYcdufMIKTKf5c6ycv5yEJNfnzQwW0aZFpll5Cq79s7m4BjXQx6prcm-i2GPyv5nBLTws418p692my5fknYbSl9zWkV7_pHJu1p9DLjE_km-9cvcv3vFCXwqrn3ho80GkBAtzaTASZt_OJvdKcdQ9-StUcpnDSgYp0em86cp3H564SgMTjcymV8JJ8-1RtsnB_oPHaqsSex30CnwfaX9S7LeL-gpADrUK5SdR1uT4QuZmD5s9ls6g6sEKfHcAq2of1SAHM0XUtJ134SYKDwy6FSSULhmFnkLj2zEFsp_7JYs_M-4CU4Cc37WdJrh42MIFkTm8KbCrRQvnZvbT6KsiuuclVBK68fmtMtHRMF-s90CK2ymn24Xva-VzN5LCRmp8qBO01W9B3WAgWqRU

###
GET https://www.sscsupply.at/rest/orders?parentOrderId=3797,3794
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGNhNmIyNjE0NGViMTVlZmM5YzRhMGYzMzQ4MDQwMGRiNTBjYTJjZmJmN2VjODU4MmI2MjcxZGI5MjI0NjgwNjlkNTU1NDI2NTk3MTA1MzkiLCJpYXQiOjE2NzkwNTc2ODMuNTI3NSwibmJmIjoxNjc5MDU3NjgzLjUyNzUsImV4cCI6MTY3OTE0NDA4My41MjU0LCJzdWIiOiI1NCIsInNjb3BlcyI6WyIqIl19.KUN7sf7Xrz6iLFbaHGhq9jWEjZa54EcxnyWCaeat6g1YzvhRR9VO7FfoUYMtelR1fL9EsbWzBaHgpmzVB-1wYXujjFn6Igsxlp1VQC1mWyUwLlaczVWgmP9HGqxl9jI-iNzgHhJ3x9FnBDT78yE1z-iFGufsQ3dVmckmHDrOF6mHJTvVOUNMpYDznRDnIJsjDdm7nAeFF7VQqA2sYUsjSRKo51jv-plBUuZUKBzM2I2F-1vL3Mmr7bhf_iCg3beeyjR9v0g-5EZyqyJ-uZ4Pm0ysbdpYcdufMIKTKf5c6ycv5yEJNfnzQwW0aZFpll5Cq79s7m4BjXQx6prcm-i2GPyv5nBLTws418p692my5fknYbSl9zWkV7_pHJu1p9DLjE_km-9cvcv3vFCXwqrn3ho80GkBAtzaTASZt_OJvdKcdQ9-StUcpnDSgYp0em86cp3H564SgMTjcymV8JJ8-1RtsnB_oPHaqsSex30CnwfaX9S7LeL-gpADrUK5SdR1uT4QuZmD5s9ls6g6sEKfHcAq2of1SAHM0XUtJ134SYKDwy6FSSULhmFnkLj2zEFsp_7JYs_M-4CU4Cc37WdJrh42MIFkTm8KbCrRQvnZvbT6KsiuuclVBK68fmtMtHRMF-s90CK2ymn24Xva-VzN5LCRmp8qBO01W9B3WAgWqRU

###
GET https://www.sscsupply.at/rest/orders?externalOrderId=000000057,000000056
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGNhNmIyNjE0NGViMTVlZmM5YzRhMGYzMzQ4MDQwMGRiNTBjYTJjZmJmN2VjODU4MmI2MjcxZGI5MjI0NjgwNjlkNTU1NDI2NTk3MTA1MzkiLCJpYXQiOjE2NzkwNTc2ODMuNTI3NSwibmJmIjoxNjc5MDU3NjgzLjUyNzUsImV4cCI6MTY3OTE0NDA4My41MjU0LCJzdWIiOiI1NCIsInNjb3BlcyI6WyIqIl19.KUN7sf7Xrz6iLFbaHGhq9jWEjZa54EcxnyWCaeat6g1YzvhRR9VO7FfoUYMtelR1fL9EsbWzBaHgpmzVB-1wYXujjFn6Igsxlp1VQC1mWyUwLlaczVWgmP9HGqxl9jI-iNzgHhJ3x9FnBDT78yE1z-iFGufsQ3dVmckmHDrOF6mHJTvVOUNMpYDznRDnIJsjDdm7nAeFF7VQqA2sYUsjSRKo51jv-plBUuZUKBzM2I2F-1vL3Mmr7bhf_iCg3beeyjR9v0g-5EZyqyJ-uZ4Pm0ysbdpYcdufMIKTKf5c6ycv5yEJNfnzQwW0aZFpll5Cq79s7m4BjXQx6prcm-i2GPyv5nBLTws418p692my5fknYbSl9zWkV7_pHJu1p9DLjE_km-9cvcv3vFCXwqrn3ho80GkBAtzaTASZt_OJvdKcdQ9-StUcpnDSgYp0em86cp3H564SgMTjcymV8JJ8-1RtsnB_oPHaqsSex30CnwfaX9S7LeL-gpADrUK5SdR1uT4QuZmD5s9ls6g6sEKfHcAq2of1SAHM0XUtJ134SYKDwy6FSSULhmFnkLj2zEFsp_7JYs_M-4CU4Cc37WdJrh42MIFkTm8KbCrRQvnZvbT6KsiuuclVBK68fmtMtHRMF-s90CK2ymn24Xva-VzN5LCRmp8qBO01W9B3WAgWqRU

###
GET https://www.sscsupply.at/rest/orders?clientId=51213
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGNhNmIyNjE0NGViMTVlZmM5YzRhMGYzMzQ4MDQwMGRiNTBjYTJjZmJmN2VjODU4MmI2MjcxZGI5MjI0NjgwNjlkNTU1NDI2NTk3MTA1MzkiLCJpYXQiOjE2NzkwNTc2ODMuNTI3NSwibmJmIjoxNjc5MDU3NjgzLjUyNzUsImV4cCI6MTY3OTE0NDA4My41MjU0LCJzdWIiOiI1NCIsInNjb3BlcyI6WyIqIl19.KUN7sf7Xrz6iLFbaHGhq9jWEjZa54EcxnyWCaeat6g1YzvhRR9VO7FfoUYMtelR1fL9EsbWzBaHgpmzVB-1wYXujjFn6Igsxlp1VQC1mWyUwLlaczVWgmP9HGqxl9jI-iNzgHhJ3x9FnBDT78yE1z-iFGufsQ3dVmckmHDrOF6mHJTvVOUNMpYDznRDnIJsjDdm7nAeFF7VQqA2sYUsjSRKo51jv-plBUuZUKBzM2I2F-1vL3Mmr7bhf_iCg3beeyjR9v0g-5EZyqyJ-uZ4Pm0ysbdpYcdufMIKTKf5c6ycv5yEJNfnzQwW0aZFpll5Cq79s7m4BjXQx6prcm-i2GPyv5nBLTws418p692my5fknYbSl9zWkV7_pHJu1p9DLjE_km-9cvcv3vFCXwqrn3ho80GkBAtzaTASZt_OJvdKcdQ9-StUcpnDSgYp0em86cp3H564SgMTjcymV8JJ8-1RtsnB_oPHaqsSex30CnwfaX9S7LeL-gpADrUK5SdR1uT4QuZmD5s9ls6g6sEKfHcAq2of1SAHM0XUtJ134SYKDwy6FSSULhmFnkLj2zEFsp_7JYs_M-4CU4Cc37WdJrh42MIFkTm8KbCrRQvnZvbT6KsiuuclVBK68fmtMtHRMF-s90CK2ymn24Xva-VzN5LCRmp8qBO01W9B3WAgWqRU

###
GET https://www.sscsupply.at/rest/orders?itemsPerPage=2&statusFrom=7.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGNhNmIyNjE0NGViMTVlZmM5YzRhMGYzMzQ4MDQwMGRiNTBjYTJjZmJmN2VjODU4MmI2MjcxZGI5MjI0NjgwNjlkNTU1NDI2NTk3MTA1MzkiLCJpYXQiOjE2NzkwNTc2ODMuNTI3NSwibmJmIjoxNjc5MDU3NjgzLjUyNzUsImV4cCI6MTY3OTE0NDA4My41MjU0LCJzdWIiOiI1NCIsInNjb3BlcyI6WyIqIl19.KUN7sf7Xrz6iLFbaHGhq9jWEjZa54EcxnyWCaeat6g1YzvhRR9VO7FfoUYMtelR1fL9EsbWzBaHgpmzVB-1wYXujjFn6Igsxlp1VQC1mWyUwLlaczVWgmP9HGqxl9jI-iNzgHhJ3x9FnBDT78yE1z-iFGufsQ3dVmckmHDrOF6mHJTvVOUNMpYDznRDnIJsjDdm7nAeFF7VQqA2sYUsjSRKo51jv-plBUuZUKBzM2I2F-1vL3Mmr7bhf_iCg3beeyjR9v0g-5EZyqyJ-uZ4Pm0ysbdpYcdufMIKTKf5c6ycv5yEJNfnzQwW0aZFpll5Cq79s7m4BjXQx6prcm-i2GPyv5nBLTws418p692my5fknYbSl9zWkV7_pHJu1p9DLjE_km-9cvcv3vFCXwqrn3ho80GkBAtzaTASZt_OJvdKcdQ9-StUcpnDSgYp0em86cp3H564SgMTjcymV8JJ8-1RtsnB_oPHaqsSex30CnwfaX9S7LeL-gpADrUK5SdR1uT4QuZmD5s9ls6g6sEKfHcAq2of1SAHM0XUtJ134SYKDwy6FSSULhmFnkLj2zEFsp_7JYs_M-4CU4Cc37WdJrh42MIFkTm8KbCrRQvnZvbT6KsiuuclVBK68fmtMtHRMF-s90CK2ymn24Xva-VzN5LCRmp8qBO01W9B3WAgWqRU

###
GET https://www.sscsupply.at/rest/orders/4718/items
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGNhNmIyNjE0NGViMTVlZmM5YzRhMGYzMzQ4MDQwMGRiNTBjYTJjZmJmN2VjODU4MmI2MjcxZGI5MjI0NjgwNjlkNTU1NDI2NTk3MTA1MzkiLCJpYXQiOjE2NzkwNTc2ODMuNTI3NSwibmJmIjoxNjc5MDU3NjgzLjUyNzUsImV4cCI6MTY3OTE0NDA4My41MjU0LCJzdWIiOiI1NCIsInNjb3BlcyI6WyIqIl19.KUN7sf7Xrz6iLFbaHGhq9jWEjZa54EcxnyWCaeat6g1YzvhRR9VO7FfoUYMtelR1fL9EsbWzBaHgpmzVB-1wYXujjFn6Igsxlp1VQC1mWyUwLlaczVWgmP9HGqxl9jI-iNzgHhJ3x9FnBDT78yE1z-iFGufsQ3dVmckmHDrOF6mHJTvVOUNMpYDznRDnIJsjDdm7nAeFF7VQqA2sYUsjSRKo51jv-plBUuZUKBzM2I2F-1vL3Mmr7bhf_iCg3beeyjR9v0g-5EZyqyJ-uZ4Pm0ysbdpYcdufMIKTKf5c6ycv5yEJNfnzQwW0aZFpll5Cq79s7m4BjXQx6prcm-i2GPyv5nBLTws418p692my5fknYbSl9zWkV7_pHJu1p9DLjE_km-9cvcv3vFCXwqrn3ho80GkBAtzaTASZt_OJvdKcdQ9-StUcpnDSgYp0em86cp3H564SgMTjcymV8JJ8-1RtsnB_oPHaqsSex30CnwfaX9S7LeL-gpADrUK5SdR1uT4QuZmD5s9ls6g6sEKfHcAq2of1SAHM0XUtJ134SYKDwy6FSSULhmFnkLj2zEFsp_7JYs_M-4CU4Cc37WdJrh42MIFkTm8KbCrRQvnZvbT6KsiuuclVBK68fmtMtHRMF-s90CK2ymn24Xva-VzN5LCRmp8qBO01W9B3WAgWqRU

###
GET https://www.sscsupply.at/rest/payments/69515
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGNhNmIyNjE0NGViMTVlZmM5YzRhMGYzMzQ4MDQwMGRiNTBjYTJjZmJmN2VjODU4MmI2MjcxZGI5MjI0NjgwNjlkNTU1NDI2NTk3MTA1MzkiLCJpYXQiOjE2NzkwNTc2ODMuNTI3NSwibmJmIjoxNjc5MDU3NjgzLjUyNzUsImV4cCI6MTY3OTE0NDA4My41MjU0LCJzdWIiOiI1NCIsInNjb3BlcyI6WyIqIl19.KUN7sf7Xrz6iLFbaHGhq9jWEjZa54EcxnyWCaeat6g1YzvhRR9VO7FfoUYMtelR1fL9EsbWzBaHgpmzVB-1wYXujjFn6Igsxlp1VQC1mWyUwLlaczVWgmP9HGqxl9jI-iNzgHhJ3x9FnBDT78yE1z-iFGufsQ3dVmckmHDrOF6mHJTvVOUNMpYDznRDnIJsjDdm7nAeFF7VQqA2sYUsjSRKo51jv-plBUuZUKBzM2I2F-1vL3Mmr7bhf_iCg3beeyjR9v0g-5EZyqyJ-uZ4Pm0ysbdpYcdufMIKTKf5c6ycv5yEJNfnzQwW0aZFpll5Cq79s7m4BjXQx6prcm-i2GPyv5nBLTws418p692my5fknYbSl9zWkV7_pHJu1p9DLjE_km-9cvcv3vFCXwqrn3ho80GkBAtzaTASZt_OJvdKcdQ9-StUcpnDSgYp0em86cp3H564SgMTjcymV8JJ8-1RtsnB_oPHaqsSex30CnwfaX9S7LeL-gpADrUK5SdR1uT4QuZmD5s9ls6g6sEKfHcAq2of1SAHM0XUtJ134SYKDwy6FSSULhmFnkLj2zEFsp_7JYs_M-4CU4Cc37WdJrh42MIFkTm8KbCrRQvnZvbT6KsiuuclVBK68fmtMtHRMF-s90CK2ymn24Xva-VzN5LCRmp8qBO01W9B3WAgWqRU

###
https://www.sscsupply.at/rest/orders?orderIds=77558&itemsPerPage=50&page=1&with[]=payments&with[]=payments.properties
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGNhNmIyNjE0NGViMTVlZmM5YzRhMGYzMzQ4MDQwMGRiNTBjYTJjZmJmN2VjODU4MmI2MjcxZGI5MjI0NjgwNjlkNTU1NDI2NTk3MTA1MzkiLCJpYXQiOjE2NzkwNTc2ODMuNTI3NSwibmJmIjoxNjc5MDU3NjgzLjUyNzUsImV4cCI6MTY3OTE0NDA4My41MjU0LCJzdWIiOiI1NCIsInNjb3BlcyI6WyIqIl19.KUN7sf7Xrz6iLFbaHGhq9jWEjZa54EcxnyWCaeat6g1YzvhRR9VO7FfoUYMtelR1fL9EsbWzBaHgpmzVB-1wYXujjFn6Igsxlp1VQC1mWyUwLlaczVWgmP9HGqxl9jI-iNzgHhJ3x9FnBDT78yE1z-iFGufsQ3dVmckmHDrOF6mHJTvVOUNMpYDznRDnIJsjDdm7nAeFF7VQqA2sYUsjSRKo51jv-plBUuZUKBzM2I2F-1vL3Mmr7bhf_iCg3beeyjR9v0g-5EZyqyJ-uZ4Pm0ysbdpYcdufMIKTKf5c6ycv5yEJNfnzQwW0aZFpll5Cq79s7m4BjXQx6prcm-i2GPyv5nBLTws418p692my5fknYbSl9zWkV7_pHJu1p9DLjE_km-9cvcv3vFCXwqrn3ho80GkBAtzaTASZt_OJvdKcdQ9-StUcpnDSgYp0em86cp3H564SgMTjcymV8JJ8-1RtsnB_oPHaqsSex30CnwfaX9S7LeL-gpADrUK5SdR1uT4QuZmD5s9ls6g6sEKfHcAq2of1SAHM0XUtJ134SYKDwy6FSSULhmFnkLj2zEFsp_7JYs_M-4CU4Cc37WdJrh42MIFkTm8KbCrRQvnZvbT6KsiuuclVBK68fmtMtHRMF-s90CK2ymn24Xva-VzN5LCRmp8qBO01W9B3WAgWqRU


