GET https://5lb6aot5e3yq.c01-17.plentymarkets.com/rest/orders/201?with[]=documents
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZTcyNzg3NmVlMTE0NGFhMjk2ZjczYjcwNzMwZmMyNjlkNDI0MDE2MTc5OGIzZWUyYTgzZDgxOTdlYzBkMTQ0NTljMDgzNDhlOWEzZWU5ZjIiLCJpYXQiOjE2MDQzMzkwMTUsIm5iZiI6MTYwNDMzOTAxNSwiZXhwIjoxNjA0NDI1NDE1LCJzdWIiOiIyNCIsInNjb3BlcyI6WyIqIl19.k1hnEdFQdxslf8mIOC4Wzl0d1hmrzQ_dqyE2_gXNqVCTPuQaSqYzJnk2w5B5UxsCfdEWoCTbUZWA8AmbaUZcXXusn3oXPpDMdBU_VvwSKeQXQt0bl3pVbOLUqPLIiPwlW6ZTloZXurUAr-RS1uda1fhTvZEC1RR-4jsR-q0VeQbU9iwIY6j0ymuYZDgkymfSDScZ4h4RTt7VRgaY0ZTYTcgVDS8l1t_0pYNXVGNMJ8Vs_88_ryCLIv8ScoVcEivtxQS_Bou8wUu-6HqZQHqvtWh8Z5PHN29r0vfoYtSxy6S88Wl4ZT51yIrBsOwrX5IyV5EY-Bjjd3WmxFZcjYWurP2aaQpKoQhKSG5xDKfRTerZp1i_uQ8XPxzbMY8zshibdf7MbX7gyid2l2rD68d0oXuhWP4XoKyVMHAzHbHFBcwqXYNoA4iCxW9bCvQvW-QoIWNUCuLSqlAYvUXMbagYs50SR6DC41duVcgVyE1axyFoud2TNep44vbUykFqhLxATQafBk79wYVtRaAc-4Xi19DHZOM5R_lDzAJhmqoti-YwtXBmwryTIRJJ_5wlQLA_8ny117x45MFbf0T2GhMpU4Pmyo3FFd96nVLn_KacuYLFgpDuaWHc2893HJR3GN3RChXuZ9NggCWMcVz-_xhp0tfo4Ske-mgiSvUe_ZbHQdc

###
GET https://5lb6aot5e3yq.c01-17.plentymarkets.com/rest/documents/10
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZTcyNzg3NmVlMTE0NGFhMjk2ZjczYjcwNzMwZmMyNjlkNDI0MDE2MTc5OGIzZWUyYTgzZDgxOTdlYzBkMTQ0NTljMDgzNDhlOWEzZWU5ZjIiLCJpYXQiOjE2MDQzMzkwMTUsIm5iZiI6MTYwNDMzOTAxNSwiZXhwIjoxNjA0NDI1NDE1LCJzdWIiOiIyNCIsInNjb3BlcyI6WyIqIl19.k1hnEdFQdxslf8mIOC4Wzl0d1hmrzQ_dqyE2_gXNqVCTPuQaSqYzJnk2w5B5UxsCfdEWoCTbUZWA8AmbaUZcXXusn3oXPpDMdBU_VvwSKeQXQt0bl3pVbOLUqPLIiPwlW6ZTloZXurUAr-RS1uda1fhTvZEC1RR-4jsR-q0VeQbU9iwIY6j0ymuYZDgkymfSDScZ4h4RTt7VRgaY0ZTYTcgVDS8l1t_0pYNXVGNMJ8Vs_88_ryCLIv8ScoVcEivtxQS_Bou8wUu-6HqZQHqvtWh8Z5PHN29r0vfoYtSxy6S88Wl4ZT51yIrBsOwrX5IyV5EY-Bjjd3WmxFZcjYWurP2aaQpKoQhKSG5xDKfRTerZp1i_uQ8XPxzbMY8zshibdf7MbX7gyid2l2rD68d0oXuhWP4XoKyVMHAzHbHFBcwqXYNoA4iCxW9bCvQvW-QoIWNUCuLSqlAYvUXMbagYs50SR6DC41duVcgVyE1axyFoud2TNep44vbUykFqhLxATQafBk79wYVtRaAc-4Xi19DHZOM5R_lDzAJhmqoti-YwtXBmwryTIRJJ_5wlQLA_8ny117x45MFbf0T2GhMpU4Pmyo3FFd96nVLn_KacuYLFgpDuaWHc2893HJR3GN3RChXuZ9NggCWMcVz-_xhp0tfo4Ske-mgiSvUe_ZbHQdc



