###
GET https://ec9521ta8er0.c01-16.plentymarkets.com/rest/items
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMWIxY2ZkNzc1OTkyY2I0N2U4M2JjNmQ4MDNjYmY0NjAyOTAzZmM4ZDk0OTQ3ZTVjYjgwOTMxMjU3ZDZmOGY5NGE5MmFjZThiOTFmMzZjZGIiLCJpYXQiOjE2MTk3MDM3NDQsIm5iZiI6MTYxOTcwMzc0NCwiZXhwIjoxNjE5NzkwMTQ0LCJzdWIiOiI1Iiwic2NvcGVzIjpbIioiXX0.kMtzNP8HgFaUp61qCKCQzPLAnWGJvNm_QZnWKoXkC22B5Ne3jEymyUqUoo1gJ1GnNBxCPGH43DsgFRlO4MUxoLJvTpTN7gGZPwUEaA9mGk6B0q0qF5sedDLBat_gum0buOZ6M8NDoth11cNZOvEXVPUy2ymVs1eFGJ_teN1uW6kZIbz6x6-jkSMcYUn1DQa-IZ153XlyF5nGHHhNWiD0sxKUCEoBwgCr-spYKHDbn6Ahat8RBNZP_gTV_iAC4o0783HuPL44wxMybm4M-3swTlskw5aJ7s3bKXt5k7vt9oKLLm7OC1aV7I0uzkoqZPkmrENJ7wZ97zqxIukbf08sxSyHdnmVV2RSlJJ2CFTOoSw6soaMXSIekab8uOa1zIwRadqSWS6FimprZytuQFC92dvR509yr3pM-BbkipZ5QTC0QCfSgp0Ctp4XRamh80he_KaQUYGoG4MLHnmCK4YASIg0tZkaHaOa3lH63jdICWuCi_EVr_VGq43lB8E8UATE8AggEkdZV4OAheOg4qaxpAu_ZxP2lY8z2757rXMnOyqz-bMH00OFfg8R5G8uE4DrooGKjWCEns9GPcWbAcBCnGZI01aQcqQBf2dXojK_v8zVZJpGRyoKpWxm7LYAYZf-hdg2anGhKsFNss7xosIQmxIicbkS8Y6TY0dvt96OD4o

###
GET https://ec9521ta8er0.c01-16.plentymarkets.com/rest/items/314729/images
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMWIxY2ZkNzc1OTkyY2I0N2U4M2JjNmQ4MDNjYmY0NjAyOTAzZmM4ZDk0OTQ3ZTVjYjgwOTMxMjU3ZDZmOGY5NGE5MmFjZThiOTFmMzZjZGIiLCJpYXQiOjE2MTk3MDM3NDQsIm5iZiI6MTYxOTcwMzc0NCwiZXhwIjoxNjE5NzkwMTQ0LCJzdWIiOiI1Iiwic2NvcGVzIjpbIioiXX0.kMtzNP8HgFaUp61qCKCQzPLAnWGJvNm_QZnWKoXkC22B5Ne3jEymyUqUoo1gJ1GnNBxCPGH43DsgFRlO4MUxoLJvTpTN7gGZPwUEaA9mGk6B0q0qF5sedDLBat_gum0buOZ6M8NDoth11cNZOvEXVPUy2ymVs1eFGJ_teN1uW6kZIbz6x6-jkSMcYUn1DQa-IZ153XlyF5nGHHhNWiD0sxKUCEoBwgCr-spYKHDbn6Ahat8RBNZP_gTV_iAC4o0783HuPL44wxMybm4M-3swTlskw5aJ7s3bKXt5k7vt9oKLLm7OC1aV7I0uzkoqZPkmrENJ7wZ97zqxIukbf08sxSyHdnmVV2RSlJJ2CFTOoSw6soaMXSIekab8uOa1zIwRadqSWS6FimprZytuQFC92dvR509yr3pM-BbkipZ5QTC0QCfSgp0Ctp4XRamh80he_KaQUYGoG4MLHnmCK4YASIg0tZkaHaOa3lH63jdICWuCi_EVr_VGq43lB8E8UATE8AggEkdZV4OAheOg4qaxpAu_ZxP2lY8z2757rXMnOyqz-bMH00OFfg8R5G8uE4DrooGKjWCEns9GPcWbAcBCnGZI01aQcqQBf2dXojK_v8zVZJpGRyoKpWxm7LYAYZf-hdg2anGhKsFNss7xosIQmxIicbkS8Y6TY0dvt96OD4o

###
GET https://ec9521ta8er0.c01-16.plentymarkets.com/rest/items/314729/variations/16431/variation_images
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMWIxY2ZkNzc1OTkyY2I0N2U4M2JjNmQ4MDNjYmY0NjAyOTAzZmM4ZDk0OTQ3ZTVjYjgwOTMxMjU3ZDZmOGY5NGE5MmFjZThiOTFmMzZjZGIiLCJpYXQiOjE2MTk3MDM3NDQsIm5iZiI6MTYxOTcwMzc0NCwiZXhwIjoxNjE5NzkwMTQ0LCJzdWIiOiI1Iiwic2NvcGVzIjpbIioiXX0.kMtzNP8HgFaUp61qCKCQzPLAnWGJvNm_QZnWKoXkC22B5Ne3jEymyUqUoo1gJ1GnNBxCPGH43DsgFRlO4MUxoLJvTpTN7gGZPwUEaA9mGk6B0q0qF5sedDLBat_gum0buOZ6M8NDoth11cNZOvEXVPUy2ymVs1eFGJ_teN1uW6kZIbz6x6-jkSMcYUn1DQa-IZ153XlyF5nGHHhNWiD0sxKUCEoBwgCr-spYKHDbn6Ahat8RBNZP_gTV_iAC4o0783HuPL44wxMybm4M-3swTlskw5aJ7s3bKXt5k7vt9oKLLm7OC1aV7I0uzkoqZPkmrENJ7wZ97zqxIukbf08sxSyHdnmVV2RSlJJ2CFTOoSw6soaMXSIekab8uOa1zIwRadqSWS6FimprZytuQFC92dvR509yr3pM-BbkipZ5QTC0QCfSgp0Ctp4XRamh80he_KaQUYGoG4MLHnmCK4YASIg0tZkaHaOa3lH63jdICWuCi_EVr_VGq43lB8E8UATE8AggEkdZV4OAheOg4qaxpAu_ZxP2lY8z2757rXMnOyqz-bMH00OFfg8R5G8uE4DrooGKjWCEns9GPcWbAcBCnGZI01aQcqQBf2dXojK_v8zVZJpGRyoKpWxm7LYAYZf-hdg2anGhKsFNss7xosIQmxIicbkS8Y6TY0dvt96OD4o
