###
GET https://skorohoda.plentymarkets-cloud02.com/rest/accounts/addresses
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzBhOGRlZmIxYTgwMzU4Y2ZlOGI5NzFkMjY4NTM4YmY2MzFhYzY2OThkZDYzYmY2ZmUxZDUwYTNhNzk0MzliODM0NzNkYjYwOWFlZGI0ZTIiLCJpYXQiOjE2ODAyNTE5MDYuNjUzNCwibmJmIjoxNjgwMjUxOTA2LjY1MzQsImV4cCI6MTY4MDMzODMwNi41Mzk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.Y7Sp7SgOe3pq3oGoQLw7JcYKjfIfBrAI9XLM_iVw1xMSWic3VgAkSffWr_s3Mv8oVPSTfXcuoyyHiuKTenY5yhdhRl4Zelj_v7alUBddAokXC0I1jUBxy2-UkoqGFwUXUPlgjnIEiM3QSx0DEr7T8EKVsVmfi0nvD2qFs_D5hm06f0cJGiYXVLU1c_4C4xMewMTTDExO8L4V_69SAU8MmM3ihVCU0R87DQ2q8eH6oH42F5cFw9ENh_Q5HObp5s4IeX26FrGi49QHKhYgv8Szw-z1ve-J8yyAgoaORHR-LhBJCBmnCsqt9aQmGMs1RIGmBUBX6Ci3i9iKba7VaAa5h_aksB3-q99ZcqPq4C9WzfS2-LJhaEjqd3t9GiXJw4Al6bmnOU037k_kbnkevuFPztyFoVZt1QrY-41Ll8ky2rJgef9SuzjSk4iz3SfQELYdAMtM85DhQ5Fs2DzeA61vDnOlQFSW7lAwFXPcXYqqf7s9OeFGlwrUSgIfSe_L71mfPSJa3HKz2GKoYO7rSY0esunLJD-LF4YJk4oWEBmQV1A0ewVfg1BY1aVLInU5rFR-VuEFQFkebhlFxnq5GT-jYtmNaCVAQY24atl1oDbnEwVWaR01VgzU0Et9vde2Tts7GeKgBe2bsgP7MPqHA_c2J9XrhIFE8NFTLMqxzII8RRc

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/accounts/addresses?page=1&itemsPerPage=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzBhOGRlZmIxYTgwMzU4Y2ZlOGI5NzFkMjY4NTM4YmY2MzFhYzY2OThkZDYzYmY2ZmUxZDUwYTNhNzk0MzliODM0NzNkYjYwOWFlZGI0ZTIiLCJpYXQiOjE2ODAyNTE5MDYuNjUzNCwibmJmIjoxNjgwMjUxOTA2LjY1MzQsImV4cCI6MTY4MDMzODMwNi41Mzk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.Y7Sp7SgOe3pq3oGoQLw7JcYKjfIfBrAI9XLM_iVw1xMSWic3VgAkSffWr_s3Mv8oVPSTfXcuoyyHiuKTenY5yhdhRl4Zelj_v7alUBddAokXC0I1jUBxy2-UkoqGFwUXUPlgjnIEiM3QSx0DEr7T8EKVsVmfi0nvD2qFs_D5hm06f0cJGiYXVLU1c_4C4xMewMTTDExO8L4V_69SAU8MmM3ihVCU0R87DQ2q8eH6oH42F5cFw9ENh_Q5HObp5s4IeX26FrGi49QHKhYgv8Szw-z1ve-J8yyAgoaORHR-LhBJCBmnCsqt9aQmGMs1RIGmBUBX6Ci3i9iKba7VaAa5h_aksB3-q99ZcqPq4C9WzfS2-LJhaEjqd3t9GiXJw4Al6bmnOU037k_kbnkevuFPztyFoVZt1QrY-41Ll8ky2rJgef9SuzjSk4iz3SfQELYdAMtM85DhQ5Fs2DzeA61vDnOlQFSW7lAwFXPcXYqqf7s9OeFGlwrUSgIfSe_L71mfPSJa3HKz2GKoYO7rSY0esunLJD-LF4YJk4oWEBmQV1A0ewVfg1BY1aVLInU5rFR-VuEFQFkebhlFxnq5GT-jYtmNaCVAQY24atl1oDbnEwVWaR01VgzU0Et9vde2Tts7GeKgBe2bsgP7MPqHA_c2J9XrhIFE8NFTLMqxzII8RRc

### -- With Filters: contactRelations,orderRelations
GET https://skorohoda.plentymarkets-cloud02.com/rest/accounts/addresses?with=contactRelations,orderRelations&page=1&itemsPerPage=2
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzBhOGRlZmIxYTgwMzU4Y2ZlOGI5NzFkMjY4NTM4YmY2MzFhYzY2OThkZDYzYmY2ZmUxZDUwYTNhNzk0MzliODM0NzNkYjYwOWFlZGI0ZTIiLCJpYXQiOjE2ODAyNTE5MDYuNjUzNCwibmJmIjoxNjgwMjUxOTA2LjY1MzQsImV4cCI6MTY4MDMzODMwNi41Mzk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.Y7Sp7SgOe3pq3oGoQLw7JcYKjfIfBrAI9XLM_iVw1xMSWic3VgAkSffWr_s3Mv8oVPSTfXcuoyyHiuKTenY5yhdhRl4Zelj_v7alUBddAokXC0I1jUBxy2-UkoqGFwUXUPlgjnIEiM3QSx0DEr7T8EKVsVmfi0nvD2qFs_D5hm06f0cJGiYXVLU1c_4C4xMewMTTDExO8L4V_69SAU8MmM3ihVCU0R87DQ2q8eH6oH42F5cFw9ENh_Q5HObp5s4IeX26FrGi49QHKhYgv8Szw-z1ve-J8yyAgoaORHR-LhBJCBmnCsqt9aQmGMs1RIGmBUBX6Ci3i9iKba7VaAa5h_aksB3-q99ZcqPq4C9WzfS2-LJhaEjqd3t9GiXJw4Al6bmnOU037k_kbnkevuFPztyFoVZt1QrY-41Ll8ky2rJgef9SuzjSk4iz3SfQELYdAMtM85DhQ5Fs2DzeA61vDnOlQFSW7lAwFXPcXYqqf7s9OeFGlwrUSgIfSe_L71mfPSJa3HKz2GKoYO7rSY0esunLJD-LF4YJk4oWEBmQV1A0ewVfg1BY1aVLInU5rFR-VuEFQFkebhlFxnq5GT-jYtmNaCVAQY24atl1oDbnEwVWaR01VgzU0Et9vde2Tts7GeKgBe2bsgP7MPqHA_c2J9XrhIFE8NFTLMqxzII8RRc

### -- ID: 6060 / With Filters: contactRelations,orderRelations
GET https://skorohoda.plentymarkets-cloud02.com/rest/accounts/addresses/6060?with=contactRelations,orderRelations
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzBhOGRlZmIxYTgwMzU4Y2ZlOGI5NzFkMjY4NTM4YmY2MzFhYzY2OThkZDYzYmY2ZmUxZDUwYTNhNzk0MzliODM0NzNkYjYwOWFlZGI0ZTIiLCJpYXQiOjE2ODAyNTE5MDYuNjUzNCwibmJmIjoxNjgwMjUxOTA2LjY1MzQsImV4cCI6MTY4MDMzODMwNi41Mzk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.Y7Sp7SgOe3pq3oGoQLw7JcYKjfIfBrAI9XLM_iVw1xMSWic3VgAkSffWr_s3Mv8oVPSTfXcuoyyHiuKTenY5yhdhRl4Zelj_v7alUBddAokXC0I1jUBxy2-UkoqGFwUXUPlgjnIEiM3QSx0DEr7T8EKVsVmfi0nvD2qFs_D5hm06f0cJGiYXVLU1c_4C4xMewMTTDExO8L4V_69SAU8MmM3ihVCU0R87DQ2q8eH6oH42F5cFw9ENh_Q5HObp5s4IeX26FrGi49QHKhYgv8Szw-z1ve-J8yyAgoaORHR-LhBJCBmnCsqt9aQmGMs1RIGmBUBX6Ci3i9iKba7VaAa5h_aksB3-q99ZcqPq4C9WzfS2-LJhaEjqd3t9GiXJw4Al6bmnOU037k_kbnkevuFPztyFoVZt1QrY-41Ll8ky2rJgef9SuzjSk4iz3SfQELYdAMtM85DhQ5Fs2DzeA61vDnOlQFSW7lAwFXPcXYqqf7s9OeFGlwrUSgIfSe_L71mfPSJa3HKz2GKoYO7rSY0esunLJD-LF4YJk4oWEBmQV1A0ewVfg1BY1aVLInU5rFR-VuEFQFkebhlFxnq5GT-jYtmNaCVAQY24atl1oDbnEwVWaR01VgzU0Et9vde2Tts7GeKgBe2bsgP7MPqHA_c2J9XrhIFE8NFTLMqxzII8RRc

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/accounts/addresses?id=1680
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzBhOGRlZmIxYTgwMzU4Y2ZlOGI5NzFkMjY4NTM4YmY2MzFhYzY2OThkZDYzYmY2ZmUxZDUwYTNhNzk0MzliODM0NzNkYjYwOWFlZGI0ZTIiLCJpYXQiOjE2ODAyNTE5MDYuNjUzNCwibmJmIjoxNjgwMjUxOTA2LjY1MzQsImV4cCI6MTY4MDMzODMwNi41Mzk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.Y7Sp7SgOe3pq3oGoQLw7JcYKjfIfBrAI9XLM_iVw1xMSWic3VgAkSffWr_s3Mv8oVPSTfXcuoyyHiuKTenY5yhdhRl4Zelj_v7alUBddAokXC0I1jUBxy2-UkoqGFwUXUPlgjnIEiM3QSx0DEr7T8EKVsVmfi0nvD2qFs_D5hm06f0cJGiYXVLU1c_4C4xMewMTTDExO8L4V_69SAU8MmM3ihVCU0R87DQ2q8eH6oH42F5cFw9ENh_Q5HObp5s4IeX26FrGi49QHKhYgv8Szw-z1ve-J8yyAgoaORHR-LhBJCBmnCsqt9aQmGMs1RIGmBUBX6Ci3i9iKba7VaAa5h_aksB3-q99ZcqPq4C9WzfS2-LJhaEjqd3t9GiXJw4Al6bmnOU037k_kbnkevuFPztyFoVZt1QrY-41Ll8ky2rJgef9SuzjSk4iz3SfQELYdAMtM85DhQ5Fs2DzeA61vDnOlQFSW7lAwFXPcXYqqf7s9OeFGlwrUSgIfSe_L71mfPSJa3HKz2GKoYO7rSY0esunLJD-LF4YJk4oWEBmQV1A0ewVfg1BY1aVLInU5rFR-VuEFQFkebhlFxnq5GT-jYtmNaCVAQY24atl1oDbnEwVWaR01VgzU0Et9vde2Tts7GeKgBe2bsgP7MPqHA_c2J9XrhIFE8NFTLMqxzII8RRc

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/accounts/addresses/contact_relations
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzBhOGRlZmIxYTgwMzU4Y2ZlOGI5NzFkMjY4NTM4YmY2MzFhYzY2OThkZDYzYmY2ZmUxZDUwYTNhNzk0MzliODM0NzNkYjYwOWFlZGI0ZTIiLCJpYXQiOjE2ODAyNTE5MDYuNjUzNCwibmJmIjoxNjgwMjUxOTA2LjY1MzQsImV4cCI6MTY4MDMzODMwNi41Mzk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.Y7Sp7SgOe3pq3oGoQLw7JcYKjfIfBrAI9XLM_iVw1xMSWic3VgAkSffWr_s3Mv8oVPSTfXcuoyyHiuKTenY5yhdhRl4Zelj_v7alUBddAokXC0I1jUBxy2-UkoqGFwUXUPlgjnIEiM3QSx0DEr7T8EKVsVmfi0nvD2qFs_D5hm06f0cJGiYXVLU1c_4C4xMewMTTDExO8L4V_69SAU8MmM3ihVCU0R87DQ2q8eH6oH42F5cFw9ENh_Q5HObp5s4IeX26FrGi49QHKhYgv8Szw-z1ve-J8yyAgoaORHR-LhBJCBmnCsqt9aQmGMs1RIGmBUBX6Ci3i9iKba7VaAa5h_aksB3-q99ZcqPq4C9WzfS2-LJhaEjqd3t9GiXJw4Al6bmnOU037k_kbnkevuFPztyFoVZt1QrY-41Ll8ky2rJgef9SuzjSk4iz3SfQELYdAMtM85DhQ5Fs2DzeA61vDnOlQFSW7lAwFXPcXYqqf7s9OeFGlwrUSgIfSe_L71mfPSJa3HKz2GKoYO7rSY0esunLJD-LF4YJk4oWEBmQV1A0ewVfg1BY1aVLInU5rFR-VuEFQFkebhlFxnq5GT-jYtmNaCVAQY24atl1oDbnEwVWaR01VgzU0Et9vde2Tts7GeKgBe2bsgP7MPqHA_c2J9XrhIFE8NFTLMqxzII8RRc

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/accounts/addresses/contact_relations/3
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzBhOGRlZmIxYTgwMzU4Y2ZlOGI5NzFkMjY4NTM4YmY2MzFhYzY2OThkZDYzYmY2ZmUxZDUwYTNhNzk0MzliODM0NzNkYjYwOWFlZGI0ZTIiLCJpYXQiOjE2ODAyNTE5MDYuNjUzNCwibmJmIjoxNjgwMjUxOTA2LjY1MzQsImV4cCI6MTY4MDMzODMwNi41Mzk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.Y7Sp7SgOe3pq3oGoQLw7JcYKjfIfBrAI9XLM_iVw1xMSWic3VgAkSffWr_s3Mv8oVPSTfXcuoyyHiuKTenY5yhdhRl4Zelj_v7alUBddAokXC0I1jUBxy2-UkoqGFwUXUPlgjnIEiM3QSx0DEr7T8EKVsVmfi0nvD2qFs_D5hm06f0cJGiYXVLU1c_4C4xMewMTTDExO8L4V_69SAU8MmM3ihVCU0R87DQ2q8eH6oH42F5cFw9ENh_Q5HObp5s4IeX26FrGi49QHKhYgv8Szw-z1ve-J8yyAgoaORHR-LhBJCBmnCsqt9aQmGMs1RIGmBUBX6Ci3i9iKba7VaAa5h_aksB3-q99ZcqPq4C9WzfS2-LJhaEjqd3t9GiXJw4Al6bmnOU037k_kbnkevuFPztyFoVZt1QrY-41Ll8ky2rJgef9SuzjSk4iz3SfQELYdAMtM85DhQ5Fs2DzeA61vDnOlQFSW7lAwFXPcXYqqf7s9OeFGlwrUSgIfSe_L71mfPSJa3HKz2GKoYO7rSY0esunLJD-LF4YJk4oWEBmQV1A0ewVfg1BY1aVLInU5rFR-VuEFQFkebhlFxnq5GT-jYtmNaCVAQY24atl1oDbnEwVWaR01VgzU0Et9vde2Tts7GeKgBe2bsgP7MPqHA_c2J9XrhIFE8NFTLMqxzII8RRc

### ~ /rest/accounts/addresses/options/{optionId}
GET https://skorohoda.plentymarkets-cloud02.com/rest/accounts/addresses/options/47
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzBhOGRlZmIxYTgwMzU4Y2ZlOGI5NzFkMjY4NTM4YmY2MzFhYzY2OThkZDYzYmY2ZmUxZDUwYTNhNzk0MzliODM0NzNkYjYwOWFlZGI0ZTIiLCJpYXQiOjE2ODAyNTE5MDYuNjUzNCwibmJmIjoxNjgwMjUxOTA2LjY1MzQsImV4cCI6MTY4MDMzODMwNi41Mzk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.Y7Sp7SgOe3pq3oGoQLw7JcYKjfIfBrAI9XLM_iVw1xMSWic3VgAkSffWr_s3Mv8oVPSTfXcuoyyHiuKTenY5yhdhRl4Zelj_v7alUBddAokXC0I1jUBxy2-UkoqGFwUXUPlgjnIEiM3QSx0DEr7T8EKVsVmfi0nvD2qFs_D5hm06f0cJGiYXVLU1c_4C4xMewMTTDExO8L4V_69SAU8MmM3ihVCU0R87DQ2q8eH6oH42F5cFw9ENh_Q5HObp5s4IeX26FrGi49QHKhYgv8Szw-z1ve-J8yyAgoaORHR-LhBJCBmnCsqt9aQmGMs1RIGmBUBX6Ci3i9iKba7VaAa5h_aksB3-q99ZcqPq4C9WzfS2-LJhaEjqd3t9GiXJw4Al6bmnOU037k_kbnkevuFPztyFoVZt1QrY-41Ll8ky2rJgef9SuzjSk4iz3SfQELYdAMtM85DhQ5Fs2DzeA61vDnOlQFSW7lAwFXPcXYqqf7s9OeFGlwrUSgIfSe_L71mfPSJa3HKz2GKoYO7rSY0esunLJD-LF4YJk4oWEBmQV1A0ewVfg1BY1aVLInU5rFR-VuEFQFkebhlFxnq5GT-jYtmNaCVAQY24atl1oDbnEwVWaR01VgzU0Et9vde2Tts7GeKgBe2bsgP7MPqHA_c2J9XrhIFE8NFTLMqxzII8RRc

### ~ accounts/addresses/option_types
GET https://skorohoda.plentymarkets-cloud02.com/rest/accounts/addresses/option_types
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzBhOGRlZmIxYTgwMzU4Y2ZlOGI5NzFkMjY4NTM4YmY2MzFhYzY2OThkZDYzYmY2ZmUxZDUwYTNhNzk0MzliODM0NzNkYjYwOWFlZGI0ZTIiLCJpYXQiOjE2ODAyNTE5MDYuNjUzNCwibmJmIjoxNjgwMjUxOTA2LjY1MzQsImV4cCI6MTY4MDMzODMwNi41Mzk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.Y7Sp7SgOe3pq3oGoQLw7JcYKjfIfBrAI9XLM_iVw1xMSWic3VgAkSffWr_s3Mv8oVPSTfXcuoyyHiuKTenY5yhdhRl4Zelj_v7alUBddAokXC0I1jUBxy2-UkoqGFwUXUPlgjnIEiM3QSx0DEr7T8EKVsVmfi0nvD2qFs_D5hm06f0cJGiYXVLU1c_4C4xMewMTTDExO8L4V_69SAU8MmM3ihVCU0R87DQ2q8eH6oH42F5cFw9ENh_Q5HObp5s4IeX26FrGi49QHKhYgv8Szw-z1ve-J8yyAgoaORHR-LhBJCBmnCsqt9aQmGMs1RIGmBUBX6Ci3i9iKba7VaAa5h_aksB3-q99ZcqPq4C9WzfS2-LJhaEjqd3t9GiXJw4Al6bmnOU037k_kbnkevuFPztyFoVZt1QrY-41Ll8ky2rJgef9SuzjSk4iz3SfQELYdAMtM85DhQ5Fs2DzeA61vDnOlQFSW7lAwFXPcXYqqf7s9OeFGlwrUSgIfSe_L71mfPSJa3HKz2GKoYO7rSY0esunLJD-LF4YJk4oWEBmQV1A0ewVfg1BY1aVLInU5rFR-VuEFQFkebhlFxnq5GT-jYtmNaCVAQY24atl1oDbnEwVWaR01VgzU0Et9vde2Tts7GeKgBe2bsgP7MPqHA_c2J9XrhIFE8NFTLMqxzII8RRc

### POST ~ accounts/addresses/option_types
POST https://skorohoda.plentymarkets-cloud02.com/rest/accounts/addresses/option_types
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzBhOGRlZmIxYTgwMzU4Y2ZlOGI5NzFkMjY4NTM4YmY2MzFhYzY2OThkZDYzYmY2ZmUxZDUwYTNhNzk0MzliODM0NzNkYjYwOWFlZGI0ZTIiLCJpYXQiOjE2ODAyNTE5MDYuNjUzNCwibmJmIjoxNjgwMjUxOTA2LjY1MzQsImV4cCI6MTY4MDMzODMwNi41Mzk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.Y7Sp7SgOe3pq3oGoQLw7JcYKjfIfBrAI9XLM_iVw1xMSWic3VgAkSffWr_s3Mv8oVPSTfXcuoyyHiuKTenY5yhdhRl4Zelj_v7alUBddAokXC0I1jUBxy2-UkoqGFwUXUPlgjnIEiM3QSx0DEr7T8EKVsVmfi0nvD2qFs_D5hm06f0cJGiYXVLU1c_4C4xMewMTTDExO8L4V_69SAU8MmM3ihVCU0R87DQ2q8eH6oH42F5cFw9ENh_Q5HObp5s4IeX26FrGi49QHKhYgv8Szw-z1ve-J8yyAgoaORHR-LhBJCBmnCsqt9aQmGMs1RIGmBUBX6Ci3i9iKba7VaAa5h_aksB3-q99ZcqPq4C9WzfS2-LJhaEjqd3t9GiXJw4Al6bmnOU037k_kbnkevuFPztyFoVZt1QrY-41Ll8ky2rJgef9SuzjSk4iz3SfQELYdAMtM85DhQ5Fs2DzeA61vDnOlQFSW7lAwFXPcXYqqf7s9OeFGlwrUSgIfSe_L71mfPSJa3HKz2GKoYO7rSY0esunLJD-LF4YJk4oWEBmQV1A0ewVfg1BY1aVLInU5rFR-VuEFQFkebhlFxnq5GT-jYtmNaCVAQY24atl1oDbnEwVWaR01VgzU0Et9vde2Tts7GeKgBe2bsgP7MPqHA_c2J9XrhIFE8NFTLMqxzII8RRc

{
    "names": [
        {
            "lang": "en",
            "name": "test_option_type2EN"
        },
        {
            "lang": "en",
            "name": "test_option_type2DE"
        }
    ]
}

### DELETE ~ accounts/addresses/option_types
DELETE https://skorohoda.plentymarkets-cloud02.com/rest/accounts/addresses/option_types/49
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzBhOGRlZmIxYTgwMzU4Y2ZlOGI5NzFkMjY4NTM4YmY2MzFhYzY2OThkZDYzYmY2ZmUxZDUwYTNhNzk0MzliODM0NzNkYjYwOWFlZGI0ZTIiLCJpYXQiOjE2ODAyNTE5MDYuNjUzNCwibmJmIjoxNjgwMjUxOTA2LjY1MzQsImV4cCI6MTY4MDMzODMwNi41Mzk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.Y7Sp7SgOe3pq3oGoQLw7JcYKjfIfBrAI9XLM_iVw1xMSWic3VgAkSffWr_s3Mv8oVPSTfXcuoyyHiuKTenY5yhdhRl4Zelj_v7alUBddAokXC0I1jUBxy2-UkoqGFwUXUPlgjnIEiM3QSx0DEr7T8EKVsVmfi0nvD2qFs_D5hm06f0cJGiYXVLU1c_4C4xMewMTTDExO8L4V_69SAU8MmM3ihVCU0R87DQ2q8eH6oH42F5cFw9ENh_Q5HObp5s4IeX26FrGi49QHKhYgv8Szw-z1ve-J8yyAgoaORHR-LhBJCBmnCsqt9aQmGMs1RIGmBUBX6Ci3i9iKba7VaAa5h_aksB3-q99ZcqPq4C9WzfS2-LJhaEjqd3t9GiXJw4Al6bmnOU037k_kbnkevuFPztyFoVZt1QrY-41Ll8ky2rJgef9SuzjSk4iz3SfQELYdAMtM85DhQ5Fs2DzeA61vDnOlQFSW7lAwFXPcXYqqf7s9OeFGlwrUSgIfSe_L71mfPSJa3HKz2GKoYO7rSY0esunLJD-LF4YJk4oWEBmQV1A0ewVfg1BY1aVLInU5rFR-VuEFQFkebhlFxnq5GT-jYtmNaCVAQY24atl1oDbnEwVWaR01VgzU0Et9vde2Tts7GeKgBe2bsgP7MPqHA_c2J9XrhIFE8NFTLMqxzII8RRc

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/accounts/addresses/options/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzBhOGRlZmIxYTgwMzU4Y2ZlOGI5NzFkMjY4NTM4YmY2MzFhYzY2OThkZDYzYmY2ZmUxZDUwYTNhNzk0MzliODM0NzNkYjYwOWFlZGI0ZTIiLCJpYXQiOjE2ODAyNTE5MDYuNjUzNCwibmJmIjoxNjgwMjUxOTA2LjY1MzQsImV4cCI6MTY4MDMzODMwNi41Mzk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.Y7Sp7SgOe3pq3oGoQLw7JcYKjfIfBrAI9XLM_iVw1xMSWic3VgAkSffWr_s3Mv8oVPSTfXcuoyyHiuKTenY5yhdhRl4Zelj_v7alUBddAokXC0I1jUBxy2-UkoqGFwUXUPlgjnIEiM3QSx0DEr7T8EKVsVmfi0nvD2qFs_D5hm06f0cJGiYXVLU1c_4C4xMewMTTDExO8L4V_69SAU8MmM3ihVCU0R87DQ2q8eH6oH42F5cFw9ENh_Q5HObp5s4IeX26FrGi49QHKhYgv8Szw-z1ve-J8yyAgoaORHR-LhBJCBmnCsqt9aQmGMs1RIGmBUBX6Ci3i9iKba7VaAa5h_aksB3-q99ZcqPq4C9WzfS2-LJhaEjqd3t9GiXJw4Al6bmnOU037k_kbnkevuFPztyFoVZt1QrY-41Ll8ky2rJgef9SuzjSk4iz3SfQELYdAMtM85DhQ5Fs2DzeA61vDnOlQFSW7lAwFXPcXYqqf7s9OeFGlwrUSgIfSe_L71mfPSJa3HKz2GKoYO7rSY0esunLJD-LF4YJk4oWEBmQV1A0ewVfg1BY1aVLInU5rFR-VuEFQFkebhlFxnq5GT-jYtmNaCVAQY24atl1oDbnEwVWaR01VgzU0Et9vde2Tts7GeKgBe2bsgP7MPqHA_c2J9XrhIFE8NFTLMqxzII8RRc

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/accounts/addresses/pos_relations
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzBhOGRlZmIxYTgwMzU4Y2ZlOGI5NzFkMjY4NTM4YmY2MzFhYzY2OThkZDYzYmY2ZmUxZDUwYTNhNzk0MzliODM0NzNkYjYwOWFlZGI0ZTIiLCJpYXQiOjE2ODAyNTE5MDYuNjUzNCwibmJmIjoxNjgwMjUxOTA2LjY1MzQsImV4cCI6MTY4MDMzODMwNi41Mzk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.Y7Sp7SgOe3pq3oGoQLw7JcYKjfIfBrAI9XLM_iVw1xMSWic3VgAkSffWr_s3Mv8oVPSTfXcuoyyHiuKTenY5yhdhRl4Zelj_v7alUBddAokXC0I1jUBxy2-UkoqGFwUXUPlgjnIEiM3QSx0DEr7T8EKVsVmfi0nvD2qFs_D5hm06f0cJGiYXVLU1c_4C4xMewMTTDExO8L4V_69SAU8MmM3ihVCU0R87DQ2q8eH6oH42F5cFw9ENh_Q5HObp5s4IeX26FrGi49QHKhYgv8Szw-z1ve-J8yyAgoaORHR-LhBJCBmnCsqt9aQmGMs1RIGmBUBX6Ci3i9iKba7VaAa5h_aksB3-q99ZcqPq4C9WzfS2-LJhaEjqd3t9GiXJw4Al6bmnOU037k_kbnkevuFPztyFoVZt1QrY-41Ll8ky2rJgef9SuzjSk4iz3SfQELYdAMtM85DhQ5Fs2DzeA61vDnOlQFSW7lAwFXPcXYqqf7s9OeFGlwrUSgIfSe_L71mfPSJa3HKz2GKoYO7rSY0esunLJD-LF4YJk4oWEBmQV1A0ewVfg1BY1aVLInU5rFR-VuEFQFkebhlFxnq5GT-jYtmNaCVAQY24atl1oDbnEwVWaR01VgzU0Et9vde2Tts7GeKgBe2bsgP7MPqHA_c2J9XrhIFE8NFTLMqxzII8RRc

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/accounts/addresses/relation_types
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzBhOGRlZmIxYTgwMzU4Y2ZlOGI5NzFkMjY4NTM4YmY2MzFhYzY2OThkZDYzYmY2ZmUxZDUwYTNhNzk0MzliODM0NzNkYjYwOWFlZGI0ZTIiLCJpYXQiOjE2ODAyNTE5MDYuNjUzNCwibmJmIjoxNjgwMjUxOTA2LjY1MzQsImV4cCI6MTY4MDMzODMwNi41Mzk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.Y7Sp7SgOe3pq3oGoQLw7JcYKjfIfBrAI9XLM_iVw1xMSWic3VgAkSffWr_s3Mv8oVPSTfXcuoyyHiuKTenY5yhdhRl4Zelj_v7alUBddAokXC0I1jUBxy2-UkoqGFwUXUPlgjnIEiM3QSx0DEr7T8EKVsVmfi0nvD2qFs_D5hm06f0cJGiYXVLU1c_4C4xMewMTTDExO8L4V_69SAU8MmM3ihVCU0R87DQ2q8eH6oH42F5cFw9ENh_Q5HObp5s4IeX26FrGi49QHKhYgv8Szw-z1ve-J8yyAgoaORHR-LhBJCBmnCsqt9aQmGMs1RIGmBUBX6Ci3i9iKba7VaAa5h_aksB3-q99ZcqPq4C9WzfS2-LJhaEjqd3t9GiXJw4Al6bmnOU037k_kbnkevuFPztyFoVZt1QrY-41Ll8ky2rJgef9SuzjSk4iz3SfQELYdAMtM85DhQ5Fs2DzeA61vDnOlQFSW7lAwFXPcXYqqf7s9OeFGlwrUSgIfSe_L71mfPSJa3HKz2GKoYO7rSY0esunLJD-LF4YJk4oWEBmQV1A0ewVfg1BY1aVLInU5rFR-VuEFQFkebhlFxnq5GT-jYtmNaCVAQY24atl1oDbnEwVWaR01VgzU0Et9vde2Tts7GeKgBe2bsgP7MPqHA_c2J9XrhIFE8NFTLMqxzII8RRc

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/accounts/addresses/102/options
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzBhOGRlZmIxYTgwMzU4Y2ZlOGI5NzFkMjY4NTM4YmY2MzFhYzY2OThkZDYzYmY2ZmUxZDUwYTNhNzk0MzliODM0NzNkYjYwOWFlZGI0ZTIiLCJpYXQiOjE2ODAyNTE5MDYuNjUzNCwibmJmIjoxNjgwMjUxOTA2LjY1MzQsImV4cCI6MTY4MDMzODMwNi41Mzk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.Y7Sp7SgOe3pq3oGoQLw7JcYKjfIfBrAI9XLM_iVw1xMSWic3VgAkSffWr_s3Mv8oVPSTfXcuoyyHiuKTenY5yhdhRl4Zelj_v7alUBddAokXC0I1jUBxy2-UkoqGFwUXUPlgjnIEiM3QSx0DEr7T8EKVsVmfi0nvD2qFs_D5hm06f0cJGiYXVLU1c_4C4xMewMTTDExO8L4V_69SAU8MmM3ihVCU0R87DQ2q8eH6oH42F5cFw9ENh_Q5HObp5s4IeX26FrGi49QHKhYgv8Szw-z1ve-J8yyAgoaORHR-LhBJCBmnCsqt9aQmGMs1RIGmBUBX6Ci3i9iKba7VaAa5h_aksB3-q99ZcqPq4C9WzfS2-LJhaEjqd3t9GiXJw4Al6bmnOU037k_kbnkevuFPztyFoVZt1QrY-41Ll8ky2rJgef9SuzjSk4iz3SfQELYdAMtM85DhQ5Fs2DzeA61vDnOlQFSW7lAwFXPcXYqqf7s9OeFGlwrUSgIfSe_L71mfPSJa3HKz2GKoYO7rSY0esunLJD-LF4YJk4oWEBmQV1A0ewVfg1BY1aVLInU5rFR-VuEFQFkebhlFxnq5GT-jYtmNaCVAQY24atl1oDbnEwVWaR01VgzU0Et9vde2Tts7GeKgBe2bsgP7MPqHA_c2J9XrhIFE8NFTLMqxzII8RRc

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/accounts/addresses/{addressId}/related_data
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzBhOGRlZmIxYTgwMzU4Y2ZlOGI5NzFkMjY4NTM4YmY2MzFhYzY2OThkZDYzYmY2ZmUxZDUwYTNhNzk0MzliODM0NzNkYjYwOWFlZGI0ZTIiLCJpYXQiOjE2ODAyNTE5MDYuNjUzNCwibmJmIjoxNjgwMjUxOTA2LjY1MzQsImV4cCI6MTY4MDMzODMwNi41Mzk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.Y7Sp7SgOe3pq3oGoQLw7JcYKjfIfBrAI9XLM_iVw1xMSWic3VgAkSffWr_s3Mv8oVPSTfXcuoyyHiuKTenY5yhdhRl4Zelj_v7alUBddAokXC0I1jUBxy2-UkoqGFwUXUPlgjnIEiM3QSx0DEr7T8EKVsVmfi0nvD2qFs_D5hm06f0cJGiYXVLU1c_4C4xMewMTTDExO8L4V_69SAU8MmM3ihVCU0R87DQ2q8eH6oH42F5cFw9ENh_Q5HObp5s4IeX26FrGi49QHKhYgv8Szw-z1ve-J8yyAgoaORHR-LhBJCBmnCsqt9aQmGMs1RIGmBUBX6Ci3i9iKba7VaAa5h_aksB3-q99ZcqPq4C9WzfS2-LJhaEjqd3t9GiXJw4Al6bmnOU037k_kbnkevuFPztyFoVZt1QrY-41Ll8ky2rJgef9SuzjSk4iz3SfQELYdAMtM85DhQ5Fs2DzeA61vDnOlQFSW7lAwFXPcXYqqf7s9OeFGlwrUSgIfSe_L71mfPSJa3HKz2GKoYO7rSY0esunLJD-LF4YJk4oWEBmQV1A0ewVfg1BY1aVLInU5rFR-VuEFQFkebhlFxnq5GT-jYtmNaCVAQY24atl1oDbnEwVWaR01VgzU0Et9vde2Tts7GeKgBe2bsgP7MPqHA_c2J9XrhIFE8NFTLMqxzII8RRc

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/accounts/contact_relations/{accountContactRelationId}
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzBhOGRlZmIxYTgwMzU4Y2ZlOGI5NzFkMjY4NTM4YmY2MzFhYzY2OThkZDYzYmY2ZmUxZDUwYTNhNzk0MzliODM0NzNkYjYwOWFlZGI0ZTIiLCJpYXQiOjE2ODAyNTE5MDYuNjUzNCwibmJmIjoxNjgwMjUxOTA2LjY1MzQsImV4cCI6MTY4MDMzODMwNi41Mzk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.Y7Sp7SgOe3pq3oGoQLw7JcYKjfIfBrAI9XLM_iVw1xMSWic3VgAkSffWr_s3Mv8oVPSTfXcuoyyHiuKTenY5yhdhRl4Zelj_v7alUBddAokXC0I1jUBxy2-UkoqGFwUXUPlgjnIEiM3QSx0DEr7T8EKVsVmfi0nvD2qFs_D5hm06f0cJGiYXVLU1c_4C4xMewMTTDExO8L4V_69SAU8MmM3ihVCU0R87DQ2q8eH6oH42F5cFw9ENh_Q5HObp5s4IeX26FrGi49QHKhYgv8Szw-z1ve-J8yyAgoaORHR-LhBJCBmnCsqt9aQmGMs1RIGmBUBX6Ci3i9iKba7VaAa5h_aksB3-q99ZcqPq4C9WzfS2-LJhaEjqd3t9GiXJw4Al6bmnOU037k_kbnkevuFPztyFoVZt1QrY-41Ll8ky2rJgef9SuzjSk4iz3SfQELYdAMtM85DhQ5Fs2DzeA61vDnOlQFSW7lAwFXPcXYqqf7s9OeFGlwrUSgIfSe_L71mfPSJa3HKz2GKoYO7rSY0esunLJD-LF4YJk4oWEBmQV1A0ewVfg1BY1aVLInU5rFR-VuEFQFkebhlFxnq5GT-jYtmNaCVAQY24atl1oDbnEwVWaR01VgzU0Et9vde2Tts7GeKgBe2bsgP7MPqHA_c2J9XrhIFE8NFTLMqxzII8RRc


### ORDER PROPERTY CREATE
GET https://skorohoda.plentymarkets-cloud02.com/rest/batch
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzBhOGRlZmIxYTgwMzU4Y2ZlOGI5NzFkMjY4NTM4YmY2MzFhYzY2OThkZDYzYmY2ZmUxZDUwYTNhNzk0MzliODM0NzNkYjYwOWFlZGI0ZTIiLCJpYXQiOjE2ODAyNTE5MDYuNjUzNCwibmJmIjoxNjgwMjUxOTA2LjY1MzQsImV4cCI6MTY4MDMzODMwNi41Mzk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.Y7Sp7SgOe3pq3oGoQLw7JcYKjfIfBrAI9XLM_iVw1xMSWic3VgAkSffWr_s3Mv8oVPSTfXcuoyyHiuKTenY5yhdhRl4Zelj_v7alUBddAokXC0I1jUBxy2-UkoqGFwUXUPlgjnIEiM3QSx0DEr7T8EKVsVmfi0nvD2qFs_D5hm06f0cJGiYXVLU1c_4C4xMewMTTDExO8L4V_69SAU8MmM3ihVCU0R87DQ2q8eH6oH42F5cFw9ENh_Q5HObp5s4IeX26FrGi49QHKhYgv8Szw-z1ve-J8yyAgoaORHR-LhBJCBmnCsqt9aQmGMs1RIGmBUBX6Ci3i9iKba7VaAa5h_aksB3-q99ZcqPq4C9WzfS2-LJhaEjqd3t9GiXJw4Al6bmnOU037k_kbnkevuFPztyFoVZt1QrY-41Ll8ky2rJgef9SuzjSk4iz3SfQELYdAMtM85DhQ5Fs2DzeA61vDnOlQFSW7lAwFXPcXYqqf7s9OeFGlwrUSgIfSe_L71mfPSJa3HKz2GKoYO7rSY0esunLJD-LF4YJk4oWEBmQV1A0ewVfg1BY1aVLInU5rFR-VuEFQFkebhlFxnq5GT-jYtmNaCVAQY24atl1oDbnEwVWaR01VgzU0Et9vde2Tts7GeKgBe2bsgP7MPqHA_c2J9XrhIFE8NFTLMqxzII8RRc

{
    "payloads": [
        {
            "resource": "/rest/accounts/addresses/1007",
            "method": "GET",
            "body": {
            }
        },
        {
            "resource": "/rest/accounts/addresses/1008",
            "method": "GET",
            "body": {
            }
        }
    ]
}

###
DELETE https://skorohoda.plentymarkets-cloud02.com/rest/accounts/addresses/5229
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzBhOGRlZmIxYTgwMzU4Y2ZlOGI5NzFkMjY4NTM4YmY2MzFhYzY2OThkZDYzYmY2ZmUxZDUwYTNhNzk0MzliODM0NzNkYjYwOWFlZGI0ZTIiLCJpYXQiOjE2ODAyNTE5MDYuNjUzNCwibmJmIjoxNjgwMjUxOTA2LjY1MzQsImV4cCI6MTY4MDMzODMwNi41Mzk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.Y7Sp7SgOe3pq3oGoQLw7JcYKjfIfBrAI9XLM_iVw1xMSWic3VgAkSffWr_s3Mv8oVPSTfXcuoyyHiuKTenY5yhdhRl4Zelj_v7alUBddAokXC0I1jUBxy2-UkoqGFwUXUPlgjnIEiM3QSx0DEr7T8EKVsVmfi0nvD2qFs_D5hm06f0cJGiYXVLU1c_4C4xMewMTTDExO8L4V_69SAU8MmM3ihVCU0R87DQ2q8eH6oH42F5cFw9ENh_Q5HObp5s4IeX26FrGi49QHKhYgv8Szw-z1ve-J8yyAgoaORHR-LhBJCBmnCsqt9aQmGMs1RIGmBUBX6Ci3i9iKba7VaAa5h_aksB3-q99ZcqPq4C9WzfS2-LJhaEjqd3t9GiXJw4Al6bmnOU037k_kbnkevuFPztyFoVZt1QrY-41Ll8ky2rJgef9SuzjSk4iz3SfQELYdAMtM85DhQ5Fs2DzeA61vDnOlQFSW7lAwFXPcXYqqf7s9OeFGlwrUSgIfSe_L71mfPSJa3HKz2GKoYO7rSY0esunLJD-LF4YJk4oWEBmQV1A0ewVfg1BY1aVLInU5rFR-VuEFQFkebhlFxnq5GT-jYtmNaCVAQY24atl1oDbnEwVWaR01VgzU0Et9vde2Tts7GeKgBe2bsgP7MPqHA_c2J9XrhIFE8NFTLMqxzII8RRc
