###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/attributes
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGYzOGNmNGJjMmFmMDk1NWZiYWQ5ZjFhNzliYjg3ZjEzOTk4NTA0MDdjYTk3ZDcyMWZlNDZhMTZjY2YzNjIzM2IxMzk4NWVhODNlNGE1ZTMiLCJpYXQiOjE2NDY2NDcyMDcsIm5iZiI6MTY0NjY0NzIwNywiZXhwIjoxNjQ2NzMzNjA3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.LgklF-LKwBAv-elPTqbO-cFMSHWUI-s3NCnLRmhfArHP-IKW3iBvlL4c3DXtssSvZqkUfwj-NE2W7feOxiRyOBVyCgSMVN1IdNvGa4_FZjCQDRlHL4JXj69Ng38f8qXxib_xuMKSalIZIKE9OiCIFGFuRladEaOnxpqsdlxp08Yw-EJ58f1D0j3N4Oi1HK5XGAT8w7S2ybh9tyv2vLuXbMkwbby6EoJFYOcuN4-gvsM3zXoCTuQ6uCqJlyw50lNlsZDJLmD1MSYAz4WBjgePA7gVVPhm6mIfL9T2KX13_iWZetFdH-_SPyTk3NSbi5ETHw-CUWrtqfC4ROyxTVNn8pBFYTYSFL0S40CwnLrRwJmjvp3GuHvH-bUaodTXrM7JX5gHLtoxuW8QsguWqm3QZ29cbxi5Yyg9Kt1i-fWpgtV2_F6vhTqN5SGkA_XZgyN-sZjoTocyXx904VT3gRzypKwiGCI092QzwTU8SSiqnoKqrMAZh58Ik4pldaR_ptNHFC-sr3QpzPyEioX33SEItBoU8iCctQ1cFlmX4g-Y9ngoSN5-ZVSoGNdGKuSBmB9iN3SUbvXV_m8weqJQ6Uv6wEFQSjm-kffE4R-Z6r00h-kBnFG4NouwozrTlTVX9G4uL4wzT7xuhgHiFNPBQn4G-8LRJRjw2YpSJsRAFQf6YHA

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/attributes?name=color
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGYzOGNmNGJjMmFmMDk1NWZiYWQ5ZjFhNzliYjg3ZjEzOTk4NTA0MDdjYTk3ZDcyMWZlNDZhMTZjY2YzNjIzM2IxMzk4NWVhODNlNGE1ZTMiLCJpYXQiOjE2NDY2NDcyMDcsIm5iZiI6MTY0NjY0NzIwNywiZXhwIjoxNjQ2NzMzNjA3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.LgklF-LKwBAv-elPTqbO-cFMSHWUI-s3NCnLRmhfArHP-IKW3iBvlL4c3DXtssSvZqkUfwj-NE2W7feOxiRyOBVyCgSMVN1IdNvGa4_FZjCQDRlHL4JXj69Ng38f8qXxib_xuMKSalIZIKE9OiCIFGFuRladEaOnxpqsdlxp08Yw-EJ58f1D0j3N4Oi1HK5XGAT8w7S2ybh9tyv2vLuXbMkwbby6EoJFYOcuN4-gvsM3zXoCTuQ6uCqJlyw50lNlsZDJLmD1MSYAz4WBjgePA7gVVPhm6mIfL9T2KX13_iWZetFdH-_SPyTk3NSbi5ETHw-CUWrtqfC4ROyxTVNn8pBFYTYSFL0S40CwnLrRwJmjvp3GuHvH-bUaodTXrM7JX5gHLtoxuW8QsguWqm3QZ29cbxi5Yyg9Kt1i-fWpgtV2_F6vhTqN5SGkA_XZgyN-sZjoTocyXx904VT3gRzypKwiGCI092QzwTU8SSiqnoKqrMAZh58Ik4pldaR_ptNHFC-sr3QpzPyEioX33SEItBoU8iCctQ1cFlmX4g-Y9ngoSN5-ZVSoGNdGKuSBmB9iN3SUbvXV_m8weqJQ6Uv6wEFQSjm-kffE4R-Z6r00h-kBnFG4NouwozrTlTVX9G4uL4wzT7xuhgHiFNPBQn4G-8LRJRjw2YpSJsRAFQf6YHA

###
