###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/sales_prices
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYzgyMWNjNDNiYjA2YTljZDZkZTRlYzMzYWVjOTU5Njc5MjUzMzc2MjI3ODEyYjhjY2RiNGQ1YmRmZWYzYTI3MWIwYTU0ZmM1MTIyYjYxOWYiLCJpYXQiOjE2MDQzMjgxMTksIm5iZiI6MTYwNDMyODExOSwiZXhwIjoxNjA0NDE0NTE5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.AN2f3lZuAFD_GawRuqXun_7iFvSiGzDu4_xHknPEP8KhAUwgtGB7udupPuVvLE3JjWvsKL-R4mzHDqDeKsSdU2l8BbYE63hBtzQkZBonLwsu-RVrQjnnwFXsYTp506tZC8aa_iSxHJQHXSoOoqHoRBrWecZAN2db9DAWojr-YsZfJnOQpvtRM-IZJpNY_e4Brw_PS72JLmAV4vlbfUyniD3KZ7noSKHMXdV1t8uqASIxA_WwuKk59grvHATiH1n-XV7_kMvOG6mF_A8FaatnEPCTYGLcAa7fMTajDGhYZBFUTRzvlK3iiYMHtU8Y5vGqh2NVn8Tv9Hnk5wvqoCquk2X1Tatn2oghj3ehSGPwx8yYpQvpvA05Vis7HXsyJh1bWA_-zUDs4mSx1ao4NC_mAFsZc_Vr7gHPtq3BclMUMOv8IznLm1HSvQArCsguzNj8w_GnjJBR8dNjRTm8sZkXCy0gAkGD75gYcQJw4KtwNUDtAqskYSrDAjth_VALb8xqnr9rx8sYHRk-errcKoe3ggHmlMU6Ev7UsgFVGT_j7KZ_ahAYJ216MU0qQ_bnD3Y5rI4NZUfBxO1sFZTKA5i5TI7DUsGPl510-0UuPKflijdgPzuFYnIQSGwKOdJsEJYNn0e2eAuwfcm6oZZNBpv_zVESe_JX1kgsuqAcSA-XVag

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/sales_prices/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYzgyMWNjNDNiYjA2YTljZDZkZTRlYzMzYWVjOTU5Njc5MjUzMzc2MjI3ODEyYjhjY2RiNGQ1YmRmZWYzYTI3MWIwYTU0ZmM1MTIyYjYxOWYiLCJpYXQiOjE2MDQzMjgxMTksIm5iZiI6MTYwNDMyODExOSwiZXhwIjoxNjA0NDE0NTE5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.AN2f3lZuAFD_GawRuqXun_7iFvSiGzDu4_xHknPEP8KhAUwgtGB7udupPuVvLE3JjWvsKL-R4mzHDqDeKsSdU2l8BbYE63hBtzQkZBonLwsu-RVrQjnnwFXsYTp506tZC8aa_iSxHJQHXSoOoqHoRBrWecZAN2db9DAWojr-YsZfJnOQpvtRM-IZJpNY_e4Brw_PS72JLmAV4vlbfUyniD3KZ7noSKHMXdV1t8uqASIxA_WwuKk59grvHATiH1n-XV7_kMvOG6mF_A8FaatnEPCTYGLcAa7fMTajDGhYZBFUTRzvlK3iiYMHtU8Y5vGqh2NVn8Tv9Hnk5wvqoCquk2X1Tatn2oghj3ehSGPwx8yYpQvpvA05Vis7HXsyJh1bWA_-zUDs4mSx1ao4NC_mAFsZc_Vr7gHPtq3BclMUMOv8IznLm1HSvQArCsguzNj8w_GnjJBR8dNjRTm8sZkXCy0gAkGD75gYcQJw4KtwNUDtAqskYSrDAjth_VALb8xqnr9rx8sYHRk-errcKoe3ggHmlMU6Ev7UsgFVGT_j7KZ_ahAYJ216MU0qQ_bnD3Y5rI4NZUfBxO1sFZTKA5i5TI7DUsGPl510-0UuPKflijdgPzuFYnIQSGwKOdJsEJYNn0e2eAuwfcm6oZZNBpv_zVESe_JX1kgsuqAcSA-XVag
