###
GET https://skorohoda.plentymarkets-cloud02.com/rest/accounts/contacts/classes
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMWU4MTEyMGNhOTdmNWZhNDhiZTg0NzQ3ZTBiNzg3MjQyY2Y3OGM4MDUxNmIyOGJjZjc0YjcwYzgwZThjM2NkNDk5YzkwODRjZDM0ZTIyMDciLCJpYXQiOjE2MTk3MDYwMDMsIm5iZiI6MTYxOTcwNjAwMywiZXhwIjoxNjE5NzkyNDAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.mtxF4nrVlb1TOw0VWDqEGvAYdbxy5GrZpyz8PqIXJysSVq2G6w8k1f-4wgWFE5a_zggY2l05n_Gt9eoPmIMBJsHczI6ZghdRta5kO4Kxwk_V1QEi2PSfqhWSWKLXFi1Scs6vrR2pxCxeTuf4zkJHlhawnlndWRafrV0OsSa_BpiSp5vqvz3FX_w-ZJPzhT8R9xXtDUE4kD-XY7cuOc1jBY6-_pPeBsUYwd4-DooHPCm2klXI_MUxpaRjRmdl6zsmonipTUmOErJOx9ntFJWUiFxX8-R854mB5A4qqpt4-_ozZDj369AGbC8cT5CPb8f6lMkwzE28w1rbKyVxqalw5Dvn-S5Yu9ya7P6N1W_JqmzSLZjh3xyJdsObywBCzrxi_bmR4e2yeuPUJMtc6xGtyxPQgMW77h1b69oGGiJ_UlEIL0mdV5MWSdhDcIL8j2ekuzNCi3RqHKC_kEd-s0FMKfPRWVZ12tGegcAb39qll2z-rjATkIlDFXkzQYfbxbmYgw5XI30A56T-sLSFYnd_mG-ER7ps5FWqsBu5nzZJmYT925y5hXmAD6C978aFK4XYTa_GB3PSZrYGaCW1VEycnlo9LfruDEn4JJFbTc885AZaDHMsiZNNegUl_L4l80YdIKByO3RU0LRftCWd5w-sxSGqcLurK3VdEhQ7m-19nRY

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/accounts/contacts/classes/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMWU4MTEyMGNhOTdmNWZhNDhiZTg0NzQ3ZTBiNzg3MjQyY2Y3OGM4MDUxNmIyOGJjZjc0YjcwYzgwZThjM2NkNDk5YzkwODRjZDM0ZTIyMDciLCJpYXQiOjE2MTk3MDYwMDMsIm5iZiI6MTYxOTcwNjAwMywiZXhwIjoxNjE5NzkyNDAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.mtxF4nrVlb1TOw0VWDqEGvAYdbxy5GrZpyz8PqIXJysSVq2G6w8k1f-4wgWFE5a_zggY2l05n_Gt9eoPmIMBJsHczI6ZghdRta5kO4Kxwk_V1QEi2PSfqhWSWKLXFi1Scs6vrR2pxCxeTuf4zkJHlhawnlndWRafrV0OsSa_BpiSp5vqvz3FX_w-ZJPzhT8R9xXtDUE4kD-XY7cuOc1jBY6-_pPeBsUYwd4-DooHPCm2klXI_MUxpaRjRmdl6zsmonipTUmOErJOx9ntFJWUiFxX8-R854mB5A4qqpt4-_ozZDj369AGbC8cT5CPb8f6lMkwzE28w1rbKyVxqalw5Dvn-S5Yu9ya7P6N1W_JqmzSLZjh3xyJdsObywBCzrxi_bmR4e2yeuPUJMtc6xGtyxPQgMW77h1b69oGGiJ_UlEIL0mdV5MWSdhDcIL8j2ekuzNCi3RqHKC_kEd-s0FMKfPRWVZ12tGegcAb39qll2z-rjATkIlDFXkzQYfbxbmYgw5XI30A56T-sLSFYnd_mG-ER7ps5FWqsBu5nzZJmYT925y5hXmAD6C978aFK4XYTa_GB3PSZrYGaCW1VEycnlo9LfruDEn4JJFbTc885AZaDHMsiZNNegUl_L4l80YdIKByO3RU0LRftCWd5w-sxSGqcLurK3VdEhQ7m-19nRY

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/accounts/contacts/classesWithData
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMWU4MTEyMGNhOTdmNWZhNDhiZTg0NzQ3ZTBiNzg3MjQyY2Y3OGM4MDUxNmIyOGJjZjc0YjcwYzgwZThjM2NkNDk5YzkwODRjZDM0ZTIyMDciLCJpYXQiOjE2MTk3MDYwMDMsIm5iZiI6MTYxOTcwNjAwMywiZXhwIjoxNjE5NzkyNDAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.mtxF4nrVlb1TOw0VWDqEGvAYdbxy5GrZpyz8PqIXJysSVq2G6w8k1f-4wgWFE5a_zggY2l05n_Gt9eoPmIMBJsHczI6ZghdRta5kO4Kxwk_V1QEi2PSfqhWSWKLXFi1Scs6vrR2pxCxeTuf4zkJHlhawnlndWRafrV0OsSa_BpiSp5vqvz3FX_w-ZJPzhT8R9xXtDUE4kD-XY7cuOc1jBY6-_pPeBsUYwd4-DooHPCm2klXI_MUxpaRjRmdl6zsmonipTUmOErJOx9ntFJWUiFxX8-R854mB5A4qqpt4-_ozZDj369AGbC8cT5CPb8f6lMkwzE28w1rbKyVxqalw5Dvn-S5Yu9ya7P6N1W_JqmzSLZjh3xyJdsObywBCzrxi_bmR4e2yeuPUJMtc6xGtyxPQgMW77h1b69oGGiJ_UlEIL0mdV5MWSdhDcIL8j2ekuzNCi3RqHKC_kEd-s0FMKfPRWVZ12tGegcAb39qll2z-rjATkIlDFXkzQYfbxbmYgw5XI30A56T-sLSFYnd_mG-ER7ps5FWqsBu5nzZJmYT925y5hXmAD6C978aFK4XYTa_GB3PSZrYGaCW1VEycnlo9LfruDEn4JJFbTc885AZaDHMsiZNNegUl_L4l80YdIKByO3RU0LRftCWd5w-sxSGqcLurK3VdEhQ7m-19nRY
