###
GET https://skorohoda.plentymarkets-cloud02.com/rest/vat
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZTBjYzlkODViNzdhNzJlMmIzYjQ2MmVmYWE0Nzg5MjZlMzcwOTA0MzQ2ZTIxN2ViZDcxOGQ2ZGQwMGU4MzRkNjk5OTFhNGU4ZjI5MmNkZmYiLCJpYXQiOjE2MzY2NDU0NjIsIm5iZiI6MTYzNjY0NTQ2MiwiZXhwIjoxNjM2NzMxODYyLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.vRW0jLvFtHq-R8_NDujcIHct_a_o64Nb3HiPZ2nHIX634hblFSwo6-IvGgk8655sFNSUl-NaP6n4j_sNqqEWEg9RfS_WaKKu0v2HEktjEv0J0ppeVcRw5qJXoGAXCokkQNUGcNw31xqmTIaKv9JTv1lmmqygxku3fpill6SqEbugIALJf3DBdFHRxNHMfPoE7lrzDUc5CRgMwDMhMox4XvZEF0Ch-RTJgLm-0RKUwLPDGeaB7MnEmD9vYSfvI1RlCsgQxm6bLd8f9loMmsf740tXemMvePr_ZaEU8KgAeaSUpKcmD1LBI6T_IyJmbQXkNitJpEoB0CETICcXXeDF-S3x6tm4rRw2A7I2jacVQdBa85wgPAcL4fpJXu5DXbhoI4BsgQfcjDXkqqK9tnupAcIcKydhm4vp7jAT2hKdPS3AJfZQkrjOtzohGK33kr0L2Amh9N-Zb-QEIoqcoe8vsEe03ieTsy-kKsC4bJfQImHYlojMNpmJuKXyTR2gx-1Kp7AVbld_2Rz_1pLD9Po9spi-mg4_e3mGQZ54FHHyhgiGGIM2M67ecNKjXLze_VAVi682HZ7YMApN5ytE7awMUsqsRRscWYERIjs1xnThG_NTEOASXn7j0j8y69Fb4yKQ1mt9WI5iBKBzn2f4XlEvI5APEgMSAxq0xakJNzfBgTc

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/accounting/locations/existing_accounts
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZTBjYzlkODViNzdhNzJlMmIzYjQ2MmVmYWE0Nzg5MjZlMzcwOTA0MzQ2ZTIxN2ViZDcxOGQ2ZGQwMGU4MzRkNjk5OTFhNGU4ZjI5MmNkZmYiLCJpYXQiOjE2MzY2NDU0NjIsIm5iZiI6MTYzNjY0NTQ2MiwiZXhwIjoxNjM2NzMxODYyLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.vRW0jLvFtHq-R8_NDujcIHct_a_o64Nb3HiPZ2nHIX634hblFSwo6-IvGgk8655sFNSUl-NaP6n4j_sNqqEWEg9RfS_WaKKu0v2HEktjEv0J0ppeVcRw5qJXoGAXCokkQNUGcNw31xqmTIaKv9JTv1lmmqygxku3fpill6SqEbugIALJf3DBdFHRxNHMfPoE7lrzDUc5CRgMwDMhMox4XvZEF0Ch-RTJgLm-0RKUwLPDGeaB7MnEmD9vYSfvI1RlCsgQxm6bLd8f9loMmsf740tXemMvePr_ZaEU8KgAeaSUpKcmD1LBI6T_IyJmbQXkNitJpEoB0CETICcXXeDF-S3x6tm4rRw2A7I2jacVQdBa85wgPAcL4fpJXu5DXbhoI4BsgQfcjDXkqqK9tnupAcIcKydhm4vp7jAT2hKdPS3AJfZQkrjOtzohGK33kr0L2Amh9N-Zb-QEIoqcoe8vsEe03ieTsy-kKsC4bJfQImHYlojMNpmJuKXyTR2gx-1Kp7AVbld_2Rz_1pLD9Po9spi-mg4_e3mGQZ54FHHyhgiGGIM2M67ecNKjXLze_VAVi682HZ7YMApN5ytE7awMUsqsRRscWYERIjs1xnThG_NTEOASXn7j0j8y69Fb4yKQ1mt9WI5iBKBzn2f4XlEvI5APEgMSAxq0xakJNzfBgTc

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/accounting/locations/posting_accounts
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZTBjYzlkODViNzdhNzJlMmIzYjQ2MmVmYWE0Nzg5MjZlMzcwOTA0MzQ2ZTIxN2ViZDcxOGQ2ZGQwMGU4MzRkNjk5OTFhNGU4ZjI5MmNkZmYiLCJpYXQiOjE2MzY2NDU0NjIsIm5iZiI6MTYzNjY0NTQ2MiwiZXhwIjoxNjM2NzMxODYyLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.vRW0jLvFtHq-R8_NDujcIHct_a_o64Nb3HiPZ2nHIX634hblFSwo6-IvGgk8655sFNSUl-NaP6n4j_sNqqEWEg9RfS_WaKKu0v2HEktjEv0J0ppeVcRw5qJXoGAXCokkQNUGcNw31xqmTIaKv9JTv1lmmqygxku3fpill6SqEbugIALJf3DBdFHRxNHMfPoE7lrzDUc5CRgMwDMhMox4XvZEF0Ch-RTJgLm-0RKUwLPDGeaB7MnEmD9vYSfvI1RlCsgQxm6bLd8f9loMmsf740tXemMvePr_ZaEU8KgAeaSUpKcmD1LBI6T_IyJmbQXkNitJpEoB0CETICcXXeDF-S3x6tm4rRw2A7I2jacVQdBa85wgPAcL4fpJXu5DXbhoI4BsgQfcjDXkqqK9tnupAcIcKydhm4vp7jAT2hKdPS3AJfZQkrjOtzohGK33kr0L2Amh9N-Zb-QEIoqcoe8vsEe03ieTsy-kKsC4bJfQImHYlojMNpmJuKXyTR2gx-1Kp7AVbld_2Rz_1pLD9Po9spi-mg4_e3mGQZ54FHHyhgiGGIM2M67ecNKjXLze_VAVi682HZ7YMApN5ytE7awMUsqsRRscWYERIjs1xnThG_NTEOASXn7j0j8y69Fb4yKQ1mt9WI5iBKBzn2f4XlEvI5APEgMSAxq0xakJNzfBgTc

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/accounting/stores/locations
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZTBjYzlkODViNzdhNzJlMmIzYjQ2MmVmYWE0Nzg5MjZlMzcwOTA0MzQ2ZTIxN2ViZDcxOGQ2ZGQwMGU4MzRkNjk5OTFhNGU4ZjI5MmNkZmYiLCJpYXQiOjE2MzY2NDU0NjIsIm5iZiI6MTYzNjY0NTQ2MiwiZXhwIjoxNjM2NzMxODYyLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.vRW0jLvFtHq-R8_NDujcIHct_a_o64Nb3HiPZ2nHIX634hblFSwo6-IvGgk8655sFNSUl-NaP6n4j_sNqqEWEg9RfS_WaKKu0v2HEktjEv0J0ppeVcRw5qJXoGAXCokkQNUGcNw31xqmTIaKv9JTv1lmmqygxku3fpill6SqEbugIALJf3DBdFHRxNHMfPoE7lrzDUc5CRgMwDMhMox4XvZEF0Ch-RTJgLm-0RKUwLPDGeaB7MnEmD9vYSfvI1RlCsgQxm6bLd8f9loMmsf740tXemMvePr_ZaEU8KgAeaSUpKcmD1LBI6T_IyJmbQXkNitJpEoB0CETICcXXeDF-S3x6tm4rRw2A7I2jacVQdBa85wgPAcL4fpJXu5DXbhoI4BsgQfcjDXkqqK9tnupAcIcKydhm4vp7jAT2hKdPS3AJfZQkrjOtzohGK33kr0L2Amh9N-Zb-QEIoqcoe8vsEe03ieTsy-kKsC4bJfQImHYlojMNpmJuKXyTR2gx-1Kp7AVbld_2Rz_1pLD9Po9spi-mg4_e3mGQZ54FHHyhgiGGIM2M67ecNKjXLze_VAVi682HZ7YMApN5ytE7awMUsqsRRscWYERIjs1xnThG_NTEOASXn7j0j8y69Fb4yKQ1mt9WI5iBKBzn2f4XlEvI5APEgMSAxq0xakJNzfBgTc

