###
GET https://skorohoda.plentymarkets-cloud02.com/rest/accounts/addresses/5229
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMTg4YzAzNTE1ZmRlMmM1NDY4YjYwYjUyNDhiNjUyYzczOTE3OTFjYTY3OTg5NTcyODdiNGNjNTExOTcwN2VmZGFiOThmZTQ2MTRhNWQzZmQiLCJpYXQiOjE2NDUyNzMwODcsIm5iZiI6MTY0NTI3MzA4NywiZXhwIjoxNjQ1MzU5NDg3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.PdAcefWGFASaipYKHExu7z5o5njY9iNHPzx5GI4O7csa9P_j9kyVGawGGDzb1myaVFspyBBe6kx4hGNSaHRiDzsXkRKeZdpZ_twwCnRF9plBCnkQSjty63l_k2BHg1QiWd98hsv06vzn8i5DGiEIGFM92HXyuvuu4rGWZEUhQePu0pzQofA5PmckqMXECQTldvg0VBx24sETqUXRGv_i0MQoLnCTY47i6m66eI_2ahJXq2ufHY3cMOBZcvgLxrZr0YkwTnawc20kU-ACZkHWQ0GRifLqyrxfobwy_T5QeaBeMnoISOBne7FhDgy8LIAzC2T8qG8gyOcwYmRHRyQ2lUShiG6r1qJKdOMb4WLW1-eKBM-RVtt-Qbgf7RhRiFS9FWK0spozbGQnqUPvUKH9NnDBfA3i1s1AibpeOY9mi_WMfXwzBwRstZmAuqDw-BFQv8Y4Z34EN8DOiRvCk2k9azNBlfpYXXbcd2Ydva-GTJhOewBuQyghqIKuMQaVLI9eU8jVH6cO3cJLfadIikYKZc2zjl3Bn_Of9uo_w18Ge5h7J_vilFoVulHkmJ4JQ5dwHvGh0IlQaX3iWbS72t0TuEBQJgWPAFKKTbu7vGTH6VcNAn8FUOWIuO4VjpJrhvNPF8ehh5CnJLLZ_21cz30M14f6ReYeFOm_S04XzIOzHj4

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/accounts/addresses/option_types
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMTg4YzAzNTE1ZmRlMmM1NDY4YjYwYjUyNDhiNjUyYzczOTE3OTFjYTY3OTg5NTcyODdiNGNjNTExOTcwN2VmZGFiOThmZTQ2MTRhNWQzZmQiLCJpYXQiOjE2NDUyNzMwODcsIm5iZiI6MTY0NTI3MzA4NywiZXhwIjoxNjQ1MzU5NDg3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.PdAcefWGFASaipYKHExu7z5o5njY9iNHPzx5GI4O7csa9P_j9kyVGawGGDzb1myaVFspyBBe6kx4hGNSaHRiDzsXkRKeZdpZ_twwCnRF9plBCnkQSjty63l_k2BHg1QiWd98hsv06vzn8i5DGiEIGFM92HXyuvuu4rGWZEUhQePu0pzQofA5PmckqMXECQTldvg0VBx24sETqUXRGv_i0MQoLnCTY47i6m66eI_2ahJXq2ufHY3cMOBZcvgLxrZr0YkwTnawc20kU-ACZkHWQ0GRifLqyrxfobwy_T5QeaBeMnoISOBne7FhDgy8LIAzC2T8qG8gyOcwYmRHRyQ2lUShiG6r1qJKdOMb4WLW1-eKBM-RVtt-Qbgf7RhRiFS9FWK0spozbGQnqUPvUKH9NnDBfA3i1s1AibpeOY9mi_WMfXwzBwRstZmAuqDw-BFQv8Y4Z34EN8DOiRvCk2k9azNBlfpYXXbcd2Ydva-GTJhOewBuQyghqIKuMQaVLI9eU8jVH6cO3cJLfadIikYKZc2zjl3Bn_Of9uo_w18Ge5h7J_vilFoVulHkmJ4JQ5dwHvGh0IlQaX3iWbS72t0TuEBQJgWPAFKKTbu7vGTH6VcNAn8FUOWIuO4VjpJrhvNPF8ehh5CnJLLZ_21cz30M14f6ReYeFOm_S04XzIOzHj4

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/accounts/addresses/options
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMTg4YzAzNTE1ZmRlMmM1NDY4YjYwYjUyNDhiNjUyYzczOTE3OTFjYTY3OTg5NTcyODdiNGNjNTExOTcwN2VmZGFiOThmZTQ2MTRhNWQzZmQiLCJpYXQiOjE2NDUyNzMwODcsIm5iZiI6MTY0NTI3MzA4NywiZXhwIjoxNjQ1MzU5NDg3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.PdAcefWGFASaipYKHExu7z5o5njY9iNHPzx5GI4O7csa9P_j9kyVGawGGDzb1myaVFspyBBe6kx4hGNSaHRiDzsXkRKeZdpZ_twwCnRF9plBCnkQSjty63l_k2BHg1QiWd98hsv06vzn8i5DGiEIGFM92HXyuvuu4rGWZEUhQePu0pzQofA5PmckqMXECQTldvg0VBx24sETqUXRGv_i0MQoLnCTY47i6m66eI_2ahJXq2ufHY3cMOBZcvgLxrZr0YkwTnawc20kU-ACZkHWQ0GRifLqyrxfobwy_T5QeaBeMnoISOBne7FhDgy8LIAzC2T8qG8gyOcwYmRHRyQ2lUShiG6r1qJKdOMb4WLW1-eKBM-RVtt-Qbgf7RhRiFS9FWK0spozbGQnqUPvUKH9NnDBfA3i1s1AibpeOY9mi_WMfXwzBwRstZmAuqDw-BFQv8Y4Z34EN8DOiRvCk2k9azNBlfpYXXbcd2Ydva-GTJhOewBuQyghqIKuMQaVLI9eU8jVH6cO3cJLfadIikYKZc2zjl3Bn_Of9uo_w18Ge5h7J_vilFoVulHkmJ4JQ5dwHvGh0IlQaX3iWbS72t0TuEBQJgWPAFKKTbu7vGTH6VcNAn8FUOWIuO4VjpJrhvNPF8ehh5CnJLLZ_21cz30M14f6ReYeFOm_S04XzIOzHj4

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/accounts/contacts/103/addresses
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMTg4YzAzNTE1ZmRlMmM1NDY4YjYwYjUyNDhiNjUyYzczOTE3OTFjYTY3OTg5NTcyODdiNGNjNTExOTcwN2VmZGFiOThmZTQ2MTRhNWQzZmQiLCJpYXQiOjE2NDUyNzMwODcsIm5iZiI6MTY0NTI3MzA4NywiZXhwIjoxNjQ1MzU5NDg3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.PdAcefWGFASaipYKHExu7z5o5njY9iNHPzx5GI4O7csa9P_j9kyVGawGGDzb1myaVFspyBBe6kx4hGNSaHRiDzsXkRKeZdpZ_twwCnRF9plBCnkQSjty63l_k2BHg1QiWd98hsv06vzn8i5DGiEIGFM92HXyuvuu4rGWZEUhQePu0pzQofA5PmckqMXECQTldvg0VBx24sETqUXRGv_i0MQoLnCTY47i6m66eI_2ahJXq2ufHY3cMOBZcvgLxrZr0YkwTnawc20kU-ACZkHWQ0GRifLqyrxfobwy_T5QeaBeMnoISOBne7FhDgy8LIAzC2T8qG8gyOcwYmRHRyQ2lUShiG6r1qJKdOMb4WLW1-eKBM-RVtt-Qbgf7RhRiFS9FWK0spozbGQnqUPvUKH9NnDBfA3i1s1AibpeOY9mi_WMfXwzBwRstZmAuqDw-BFQv8Y4Z34EN8DOiRvCk2k9azNBlfpYXXbcd2Ydva-GTJhOewBuQyghqIKuMQaVLI9eU8jVH6cO3cJLfadIikYKZc2zjl3Bn_Of9uo_w18Ge5h7J_vilFoVulHkmJ4JQ5dwHvGh0IlQaX3iWbS72t0TuEBQJgWPAFKKTbu7vGTH6VcNAn8FUOWIuO4VjpJrhvNPF8ehh5CnJLLZ_21cz30M14f6ReYeFOm_S04XzIOzHj4

### -- create address and contact relations
### POST https://skorohoda.plentymarkets-cloud02.com/rest/accounts/contacts/561/addresses
POST https://skorohoda.plentymarkets-cloud02.com/rest/accounts/addresses
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMTg4YzAzNTE1ZmRlMmM1NDY4YjYwYjUyNDhiNjUyYzczOTE3OTFjYTY3OTg5NTcyODdiNGNjNTExOTcwN2VmZGFiOThmZTQ2MTRhNWQzZmQiLCJpYXQiOjE2NDUyNzMwODcsIm5iZiI6MTY0NTI3MzA4NywiZXhwIjoxNjQ1MzU5NDg3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.PdAcefWGFASaipYKHExu7z5o5njY9iNHPzx5GI4O7csa9P_j9kyVGawGGDzb1myaVFspyBBe6kx4hGNSaHRiDzsXkRKeZdpZ_twwCnRF9plBCnkQSjty63l_k2BHg1QiWd98hsv06vzn8i5DGiEIGFM92HXyuvuu4rGWZEUhQePu0pzQofA5PmckqMXECQTldvg0VBx24sETqUXRGv_i0MQoLnCTY47i6m66eI_2ahJXq2ufHY3cMOBZcvgLxrZr0YkwTnawc20kU-ACZkHWQ0GRifLqyrxfobwy_T5QeaBeMnoISOBne7FhDgy8LIAzC2T8qG8gyOcwYmRHRyQ2lUShiG6r1qJKdOMb4WLW1-eKBM-RVtt-Qbgf7RhRiFS9FWK0spozbGQnqUPvUKH9NnDBfA3i1s1AibpeOY9mi_WMfXwzBwRstZmAuqDw-BFQv8Y4Z34EN8DOiRvCk2k9azNBlfpYXXbcd2Ydva-GTJhOewBuQyghqIKuMQaVLI9eU8jVH6cO3cJLfadIikYKZc2zjl3Bn_Of9uo_w18Ge5h7J_vilFoVulHkmJ4JQ5dwHvGh0IlQaX3iWbS72t0TuEBQJgWPAFKKTbu7vGTH6VcNAn8FUOWIuO4VjpJrhvNPF8ehh5CnJLLZ_21cz30M14f6ReYeFOm_S04XzIOzHj4

{
    "gender":"male",
    "name1":"Shipping and Billing 2",
    "name2":"Serhiy 1414 2",
    "name3":"K 1414 2",
    "name4":"",
    "address1":"222 Shipping and billing",
    "address2":"",
    "address3":"",
    "address4":"",
    "postalCode":"W1S 222",
    "town":"London",
    "stateId":null,
    "countryId":12,
    "options":[{"typeId":2,"value":"1672854"},{"typeId":5,"value":"shipping-billing@softcommerce.co.uk"}],
    "contactRelations":[{"contactId":1414,"typeId":1}, {"contactId":1414,"typeId":2}]
}

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/accounts/addresses/contact_relations
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMTg4YzAzNTE1ZmRlMmM1NDY4YjYwYjUyNDhiNjUyYzczOTE3OTFjYTY3OTg5NTcyODdiNGNjNTExOTcwN2VmZGFiOThmZTQ2MTRhNWQzZmQiLCJpYXQiOjE2NDUyNzMwODcsIm5iZiI6MTY0NTI3MzA4NywiZXhwIjoxNjQ1MzU5NDg3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.PdAcefWGFASaipYKHExu7z5o5njY9iNHPzx5GI4O7csa9P_j9kyVGawGGDzb1myaVFspyBBe6kx4hGNSaHRiDzsXkRKeZdpZ_twwCnRF9plBCnkQSjty63l_k2BHg1QiWd98hsv06vzn8i5DGiEIGFM92HXyuvuu4rGWZEUhQePu0pzQofA5PmckqMXECQTldvg0VBx24sETqUXRGv_i0MQoLnCTY47i6m66eI_2ahJXq2ufHY3cMOBZcvgLxrZr0YkwTnawc20kU-ACZkHWQ0GRifLqyrxfobwy_T5QeaBeMnoISOBne7FhDgy8LIAzC2T8qG8gyOcwYmRHRyQ2lUShiG6r1qJKdOMb4WLW1-eKBM-RVtt-Qbgf7RhRiFS9FWK0spozbGQnqUPvUKH9NnDBfA3i1s1AibpeOY9mi_WMfXwzBwRstZmAuqDw-BFQv8Y4Z34EN8DOiRvCk2k9azNBlfpYXXbcd2Ydva-GTJhOewBuQyghqIKuMQaVLI9eU8jVH6cO3cJLfadIikYKZc2zjl3Bn_Of9uo_w18Ge5h7J_vilFoVulHkmJ4JQ5dwHvGh0IlQaX3iWbS72t0TuEBQJgWPAFKKTbu7vGTH6VcNAn8FUOWIuO4VjpJrhvNPF8ehh5CnJLLZ_21cz30M14f6ReYeFOm_S04XzIOzHj4

###
POST https://skorohoda.plentymarkets-cloud02.com/rest/accounts/addresses/contact_relations
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMTg4YzAzNTE1ZmRlMmM1NDY4YjYwYjUyNDhiNjUyYzczOTE3OTFjYTY3OTg5NTcyODdiNGNjNTExOTcwN2VmZGFiOThmZTQ2MTRhNWQzZmQiLCJpYXQiOjE2NDUyNzMwODcsIm5iZiI6MTY0NTI3MzA4NywiZXhwIjoxNjQ1MzU5NDg3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.PdAcefWGFASaipYKHExu7z5o5njY9iNHPzx5GI4O7csa9P_j9kyVGawGGDzb1myaVFspyBBe6kx4hGNSaHRiDzsXkRKeZdpZ_twwCnRF9plBCnkQSjty63l_k2BHg1QiWd98hsv06vzn8i5DGiEIGFM92HXyuvuu4rGWZEUhQePu0pzQofA5PmckqMXECQTldvg0VBx24sETqUXRGv_i0MQoLnCTY47i6m66eI_2ahJXq2ufHY3cMOBZcvgLxrZr0YkwTnawc20kU-ACZkHWQ0GRifLqyrxfobwy_T5QeaBeMnoISOBne7FhDgy8LIAzC2T8qG8gyOcwYmRHRyQ2lUShiG6r1qJKdOMb4WLW1-eKBM-RVtt-Qbgf7RhRiFS9FWK0spozbGQnqUPvUKH9NnDBfA3i1s1AibpeOY9mi_WMfXwzBwRstZmAuqDw-BFQv8Y4Z34EN8DOiRvCk2k9azNBlfpYXXbcd2Ydva-GTJhOewBuQyghqIKuMQaVLI9eU8jVH6cO3cJLfadIikYKZc2zjl3Bn_Of9uo_w18Ge5h7J_vilFoVulHkmJ4JQ5dwHvGh0IlQaX3iWbS72t0TuEBQJgWPAFKKTbu7vGTH6VcNAn8FUOWIuO4VjpJrhvNPF8ehh5CnJLLZ_21cz30M14f6ReYeFOm_S04XzIOzHj4

[{"contactId":479,"typeId":2,"addressId":910}]

### {"mage_order_id":"000000090","gender":"male","name1":"Flag Billing Ltd2","name2":"Serhiy2","name3":"Flag Billing2","name4":"","address1":"100 Flag Billing2","address2":"","address3":"","address4":"","postalCode":"FL01 0BL2","town":"Flag Billing2","stateId":null,"countryId":12,"options":[{"typeId":4,"value":"03282308230808"},{"typeId":5,"value":"serhiy-flag2@softcommerce.co.uk"}],"contactRelations":[{"contactId":479,"typeId":1}]}
### {"mage_order_id":"000000090","gender":"male","name1":"Flag Shipping Ltd2","name2":"Serhiy2","name3":"Flag Shipping2","name4":"","address1":"100 Flag Shipping2","address2":"","address3":"","address4":"","postalCode":"FL01 0SH2","town":"Flag Shipping2","stateId":null,"countryId":12,"options":[{"typeId":4,"value":"03282308230808"},{"typeId":5,"value":"serhiy-flag2@softcommerce.co.uk"}],"contactRelations":[{"contactId":479,"typeId":2}]}

###
POST https://skorohoda.plentymarkets-cloud02.com/rest/batch
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMTg4YzAzNTE1ZmRlMmM1NDY4YjYwYjUyNDhiNjUyYzczOTE3OTFjYTY3OTg5NTcyODdiNGNjNTExOTcwN2VmZGFiOThmZTQ2MTRhNWQzZmQiLCJpYXQiOjE2NDUyNzMwODcsIm5iZiI6MTY0NTI3MzA4NywiZXhwIjoxNjQ1MzU5NDg3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.PdAcefWGFASaipYKHExu7z5o5njY9iNHPzx5GI4O7csa9P_j9kyVGawGGDzb1myaVFspyBBe6kx4hGNSaHRiDzsXkRKeZdpZ_twwCnRF9plBCnkQSjty63l_k2BHg1QiWd98hsv06vzn8i5DGiEIGFM92HXyuvuu4rGWZEUhQePu0pzQofA5PmckqMXECQTldvg0VBx24sETqUXRGv_i0MQoLnCTY47i6m66eI_2ahJXq2ufHY3cMOBZcvgLxrZr0YkwTnawc20kU-ACZkHWQ0GRifLqyrxfobwy_T5QeaBeMnoISOBne7FhDgy8LIAzC2T8qG8gyOcwYmRHRyQ2lUShiG6r1qJKdOMb4WLW1-eKBM-RVtt-Qbgf7RhRiFS9FWK0spozbGQnqUPvUKH9NnDBfA3i1s1AibpeOY9mi_WMfXwzBwRstZmAuqDw-BFQv8Y4Z34EN8DOiRvCk2k9azNBlfpYXXbcd2Ydva-GTJhOewBuQyghqIKuMQaVLI9eU8jVH6cO3cJLfadIikYKZc2zjl3Bn_Of9uo_w18Ge5h7J_vilFoVulHkmJ4JQ5dwHvGh0IlQaX3iWbS72t0TuEBQJgWPAFKKTbu7vGTH6VcNAn8FUOWIuO4VjpJrhvNPF8ehh5CnJLLZ_21cz30M14f6ReYeFOm_S04XzIOzHj4

{
  "payloads": [
    {
      "resource": "https://skorohoda.plentymarkets-cloud02.com/rest/accounts/addresses/contact_relations",
      "method": "POST",
      "body": [
          {"contactId":479,"typeId":1,"addressId":908},
          {"contactId":479,"typeId":2,"addressId":908}
      ]
    }
  ]
}

###
DELETE https://skorohoda.plentymarkets-cloud02.com/rest/accounts/addresses/5233
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMTg4YzAzNTE1ZmRlMmM1NDY4YjYwYjUyNDhiNjUyYzczOTE3OTFjYTY3OTg5NTcyODdiNGNjNTExOTcwN2VmZGFiOThmZTQ2MTRhNWQzZmQiLCJpYXQiOjE2NDUyNzMwODcsIm5iZiI6MTY0NTI3MzA4NywiZXhwIjoxNjQ1MzU5NDg3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.PdAcefWGFASaipYKHExu7z5o5njY9iNHPzx5GI4O7csa9P_j9kyVGawGGDzb1myaVFspyBBe6kx4hGNSaHRiDzsXkRKeZdpZ_twwCnRF9plBCnkQSjty63l_k2BHg1QiWd98hsv06vzn8i5DGiEIGFM92HXyuvuu4rGWZEUhQePu0pzQofA5PmckqMXECQTldvg0VBx24sETqUXRGv_i0MQoLnCTY47i6m66eI_2ahJXq2ufHY3cMOBZcvgLxrZr0YkwTnawc20kU-ACZkHWQ0GRifLqyrxfobwy_T5QeaBeMnoISOBne7FhDgy8LIAzC2T8qG8gyOcwYmRHRyQ2lUShiG6r1qJKdOMb4WLW1-eKBM-RVtt-Qbgf7RhRiFS9FWK0spozbGQnqUPvUKH9NnDBfA3i1s1AibpeOY9mi_WMfXwzBwRstZmAuqDw-BFQv8Y4Z34EN8DOiRvCk2k9azNBlfpYXXbcd2Ydva-GTJhOewBuQyghqIKuMQaVLI9eU8jVH6cO3cJLfadIikYKZc2zjl3Bn_Of9uo_w18Ge5h7J_vilFoVulHkmJ4JQ5dwHvGh0IlQaX3iWbS72t0TuEBQJgWPAFKKTbu7vGTH6VcNAn8FUOWIuO4VjpJrhvNPF8ehh5CnJLLZ_21cz30M14f6ReYeFOm_S04XzIOzHj4
