###
GET https://skorohoda.plentymarkets-cloud02.com/rest/documents
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiODVjOTRiMjAzMmUxMTE2MjVlZTZjYmExZGViYmIxOWI0OWNlOGFkZGVmMjNmZjJiNjE1ZTc3MmE2Mjk5YTFlNjU4ZWNkZGFjYjdhM2Q5NTgiLCJpYXQiOjE2NzU1MjEyNjAuNzE0NCwibmJmIjoxNjc1NTIxMjYwLjcxNDQsImV4cCI6MTY3NTYwNzY2MC43MTI4LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.cQctmlGu9F_3gbEaOAGL1FJnWtQhqkWtxzO3eoQ5SLkW1gMFyj_-JL8In0ZUodMFjgm2eCg2Uo7WEavlZBTmextDgGpJAYKhUAB1DCE03bN3Zne8h-QwDMv98tjIq10uYDCzF4iy8dRFKx6GQXZ7ZfVPCidynefjD8RViDrOq0fmENEkm8sEZFElKYHhTZryfN1uJh4CkFapEjU-fmb6KcOLYCb42djTuDNH-afKseMklQUHemz_B4mAMwVVS7FYIxQSP4JJdKFNu9M0zWpOckgoIL_Wp_nCryTrfbLBPtr7gOpXCDjz7oxvd77pSlYikjjLTLi8p2P9EMXEbDsb-q3QoJSINCTANol7n9Ej84hl-tNmlAKMBnZW263dkicvUyYyHTWSP_emRz_i3GFX2DpAJeNDlx45r2hOvbMw4PAvFsEELsinADVjwDvIDMn6mjaIGwD8sNGvUVvginybkaPT1pFXVMUGPjX0myG2iqyiRbAScKMfhOsAFJePCCksepmCIK3NqHCb_EqZo6tW4Iv0QM1ypymNNFPNKqeajy4FGk2YX1pmHd1jvLiR4W7Lbr15yoTf97Ed9b4yHsHDkUH8v_tpAAB_kUOpwbbt24XeILiiM9Ne-hk1kLqeNsPIXXz_TDdLIeJV4oDEGi4em7-M3EtJTOJyh1A5cdFY-Bg

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/documents/78
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiODVjOTRiMjAzMmUxMTE2MjVlZTZjYmExZGViYmIxOWI0OWNlOGFkZGVmMjNmZjJiNjE1ZTc3MmE2Mjk5YTFlNjU4ZWNkZGFjYjdhM2Q5NTgiLCJpYXQiOjE2NzU1MjEyNjAuNzE0NCwibmJmIjoxNjc1NTIxMjYwLjcxNDQsImV4cCI6MTY3NTYwNzY2MC43MTI4LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.cQctmlGu9F_3gbEaOAGL1FJnWtQhqkWtxzO3eoQ5SLkW1gMFyj_-JL8In0ZUodMFjgm2eCg2Uo7WEavlZBTmextDgGpJAYKhUAB1DCE03bN3Zne8h-QwDMv98tjIq10uYDCzF4iy8dRFKx6GQXZ7ZfVPCidynefjD8RViDrOq0fmENEkm8sEZFElKYHhTZryfN1uJh4CkFapEjU-fmb6KcOLYCb42djTuDNH-afKseMklQUHemz_B4mAMwVVS7FYIxQSP4JJdKFNu9M0zWpOckgoIL_Wp_nCryTrfbLBPtr7gOpXCDjz7oxvd77pSlYikjjLTLi8p2P9EMXEbDsb-q3QoJSINCTANol7n9Ej84hl-tNmlAKMBnZW263dkicvUyYyHTWSP_emRz_i3GFX2DpAJeNDlx45r2hOvbMw4PAvFsEELsinADVjwDvIDMn6mjaIGwD8sNGvUVvginybkaPT1pFXVMUGPjX0myG2iqyiRbAScKMfhOsAFJePCCksepmCIK3NqHCb_EqZo6tW4Iv0QM1ypymNNFPNKqeajy4FGk2YX1pmHd1jvLiR4W7Lbr15yoTf97Ed9b4yHsHDkUH8v_tpAAB_kUOpwbbt24XeILiiM9Ne-hk1kLqeNsPIXXz_TDdLIeJV4oDEGi4em7-M3EtJTOJyh1A5cdFY-Bg

###
POST https://skorohoda.plentymarkets-cloud02.com/rest/orders/7006/documents/invoice/generate
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiODVjOTRiMjAzMmUxMTE2MjVlZTZjYmExZGViYmIxOWI0OWNlOGFkZGVmMjNmZjJiNjE1ZTc3MmE2Mjk5YTFlNjU4ZWNkZGFjYjdhM2Q5NTgiLCJpYXQiOjE2NzU1MjEyNjAuNzE0NCwibmJmIjoxNjc1NTIxMjYwLjcxNDQsImV4cCI6MTY3NTYwNzY2MC43MTI4LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.cQctmlGu9F_3gbEaOAGL1FJnWtQhqkWtxzO3eoQ5SLkW1gMFyj_-JL8In0ZUodMFjgm2eCg2Uo7WEavlZBTmextDgGpJAYKhUAB1DCE03bN3Zne8h-QwDMv98tjIq10uYDCzF4iy8dRFKx6GQXZ7ZfVPCidynefjD8RViDrOq0fmENEkm8sEZFElKYHhTZryfN1uJh4CkFapEjU-fmb6KcOLYCb42djTuDNH-afKseMklQUHemz_B4mAMwVVS7FYIxQSP4JJdKFNu9M0zWpOckgoIL_Wp_nCryTrfbLBPtr7gOpXCDjz7oxvd77pSlYikjjLTLi8p2P9EMXEbDsb-q3QoJSINCTANol7n9Ej84hl-tNmlAKMBnZW263dkicvUyYyHTWSP_emRz_i3GFX2DpAJeNDlx45r2hOvbMw4PAvFsEELsinADVjwDvIDMn6mjaIGwD8sNGvUVvginybkaPT1pFXVMUGPjX0myG2iqyiRbAScKMfhOsAFJePCCksepmCIK3NqHCb_EqZo6tW4Iv0QM1ypymNNFPNKqeajy4FGk2YX1pmHd1jvLiR4W7Lbr15yoTf97Ed9b4yHsHDkUH8v_tpAAB_kUOpwbbt24XeILiiM9Ne-hk1kLqeNsPIXXz_TDdLIeJV4oDEGi4em7-M3EtJTOJyh1A5cdFY-Bg

{
    "orderId": "7006",
    "comment": "COMMENT TEST"
}

###
POST https://skorohoda.plentymarkets-cloud02.com/rest/orders/7005/documents/multi_invoice/generate
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiODVjOTRiMjAzMmUxMTE2MjVlZTZjYmExZGViYmIxOWI0OWNlOGFkZGVmMjNmZjJiNjE1ZTc3MmE2Mjk5YTFlNjU4ZWNkZGFjYjdhM2Q5NTgiLCJpYXQiOjE2NzU1MjEyNjAuNzE0NCwibmJmIjoxNjc1NTIxMjYwLjcxNDQsImV4cCI6MTY3NTYwNzY2MC43MTI4LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.cQctmlGu9F_3gbEaOAGL1FJnWtQhqkWtxzO3eoQ5SLkW1gMFyj_-JL8In0ZUodMFjgm2eCg2Uo7WEavlZBTmextDgGpJAYKhUAB1DCE03bN3Zne8h-QwDMv98tjIq10uYDCzF4iy8dRFKx6GQXZ7ZfVPCidynefjD8RViDrOq0fmENEkm8sEZFElKYHhTZryfN1uJh4CkFapEjU-fmb6KcOLYCb42djTuDNH-afKseMklQUHemz_B4mAMwVVS7FYIxQSP4JJdKFNu9M0zWpOckgoIL_Wp_nCryTrfbLBPtr7gOpXCDjz7oxvd77pSlYikjjLTLi8p2P9EMXEbDsb-q3QoJSINCTANol7n9Ej84hl-tNmlAKMBnZW263dkicvUyYyHTWSP_emRz_i3GFX2DpAJeNDlx45r2hOvbMw4PAvFsEELsinADVjwDvIDMn6mjaIGwD8sNGvUVvginybkaPT1pFXVMUGPjX0myG2iqyiRbAScKMfhOsAFJePCCksepmCIK3NqHCb_EqZo6tW4Iv0QM1ypymNNFPNKqeajy4FGk2YX1pmHd1jvLiR4W7Lbr15yoTf97Ed9b4yHsHDkUH8v_tpAAB_kUOpwbbt24XeILiiM9Ne-hk1kLqeNsPIXXz_TDdLIeJV4oDEGi4em7-M3EtJTOJyh1A5cdFY-Bg
