GET https://skorohoda.plentymarkets-cloud02.com/rest/items/8343/variations/34372/variation_warehouses
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMTY4NGY2NDgzMjc2YTNjZTU0MGEzNmFmNzNmZDQ0YzgzNmE1Mzg0Yzg5N2UyODRjMDRlYWJmMTc4NWMzNTBhMjIwNDk2MmNiZGZkNTMzZjIiLCJpYXQiOjE1OTQ2MzE0MDUsIm5iZiI6MTU5NDYzMTQwNSwiZXhwIjoxNTk0NzE3ODA1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.1sKAaDvBMSbHRiXorMuAaNFAVhMO8K-iuWEecSvS3B9HAtSnfYPvgWOG_XOGINr7RFAXhZCbQv4_6QgibODgLdnk68rc5iF8pTfY3QDlyfH-wQfnzCZu6MQxd9b1de9jwq18QM3c6mae9kgbUxZ86kuwfEVWyFuOmG5FzZI9rQuYjHoSQXzT0wexV3KqVeYognASXumZdd1eFpJSgkqNKZly20jz2y3P-0X5rieZHLmUF7NuuUATnhYHV3vp5FUdbqlKViQd1GVrgtbvd3vWXwR4duoMg3qi4eZlifcPBCgPDR87qTBHEmM_Qkrm0HegRDHRNPeP2TKy1ygXqHUNvx0RpavUVvahNIYsW-4ODE4ufbWK3lB2AU1-mvphTpGbtOU9eb5BEILC7gQjiDnKl4-tICU-Uf3H06KJ0y-vnkCKrkD1yUF2cykSCowoWPXsGAHBLjL5t5VAdqgvPg06YxTW4BWCyMRM6N-gjn8zQ0EaQj3HukeT-pHuYWbSx-xbiP7P92G89GLH0NFmR-MzYcRmwu26Nw-cvFT6oYFVyGFgcw3fEef0QrkAr-hh_N2992CreIrVsgcC80EG4x9XV9V1t7P1s7bhR8WmBUjwt6dxjIgJKcTv0Ndn9Xh9cAusfqIy3NWXrZJrxjdcK22CqOxWAntRvqIens8FI-ERfAM

###
POST https://skorohoda.plentymarkets-cloud02.com/rest/items/8341/variations/34365/variation_warehouses
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMTY4NGY2NDgzMjc2YTNjZTU0MGEzNmFmNzNmZDQ0YzgzNmE1Mzg0Yzg5N2UyODRjMDRlYWJmMTc4NWMzNTBhMjIwNDk2MmNiZGZkNTMzZjIiLCJpYXQiOjE1OTQ2MzE0MDUsIm5iZiI6MTU5NDYzMTQwNSwiZXhwIjoxNTk0NzE3ODA1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.1sKAaDvBMSbHRiXorMuAaNFAVhMO8K-iuWEecSvS3B9HAtSnfYPvgWOG_XOGINr7RFAXhZCbQv4_6QgibODgLdnk68rc5iF8pTfY3QDlyfH-wQfnzCZu6MQxd9b1de9jwq18QM3c6mae9kgbUxZ86kuwfEVWyFuOmG5FzZI9rQuYjHoSQXzT0wexV3KqVeYognASXumZdd1eFpJSgkqNKZly20jz2y3P-0X5rieZHLmUF7NuuUATnhYHV3vp5FUdbqlKViQd1GVrgtbvd3vWXwR4duoMg3qi4eZlifcPBCgPDR87qTBHEmM_Qkrm0HegRDHRNPeP2TKy1ygXqHUNvx0RpavUVvahNIYsW-4ODE4ufbWK3lB2AU1-mvphTpGbtOU9eb5BEILC7gQjiDnKl4-tICU-Uf3H06KJ0y-vnkCKrkD1yUF2cykSCowoWPXsGAHBLjL5t5VAdqgvPg06YxTW4BWCyMRM6N-gjn8zQ0EaQj3HukeT-pHuYWbSx-xbiP7P92G89GLH0NFmR-MzYcRmwu26Nw-cvFT6oYFVyGFgcw3fEef0QrkAr-hh_N2992CreIrVsgcC80EG4x9XV9V1t7P1s7bhR8WmBUjwt6dxjIgJKcTv0Ndn9Xh9cAusfqIy3NWXrZJrxjdcK22CqOxWAntRvqIens8FI-ERfAM

{
      "warehouseId": 1
}
