GET https://skorohoda.plentymarkets-cloud02.com/rest/items/properties
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzJmYjUxYWVmMjlhZGViNGM2MjkyMTdjNjk0ODhhNTc1NTA0OTg2MjE0N2JjN2YyOWZhN2U3MDY1ZDFiYmY2OGMyNDY0MzhkZDI0MDdiNjIiLCJpYXQiOjE2MjI4MjcyMDMsIm5iZiI6MTYyMjgyNzIwMywiZXhwIjoxNjIyOTEzNjAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.lo4_PXp9L7d8KNADBmyM1iJd4onYjEMrs0bcviyz9CGmTPl-E4p3JJhK_doDeWMFV0HDK5UbVoeZNTS7RmvaVNtPbvyMUx1Ae5KjdyUiKp3eUyQYQd0FsbjspPBqRVUk_Mjtmy6OaOl9xXQZQq6aexnqH--qxepc0Ft177AQSW75w2h7D_flHieuPEBFfMWBT9H2wlwMv2Bpko9O2ZjgZ1qKZhNDyLyaYgtytwhyW2IitwHH4XD7E3W77YK3zoWD2OuTDmDv9D6WonklK1jsbyrn-isVH066UKKWN00L5YvBfCSSsmPt5pgezKkPfWN4mm9ILRSsrfIfK1WIG7hBOffRtg-vbMEdE2-nwOZW0-vnQtglYiJ6qDooO3Z7ckYtpcjaJxFePm3gmhz9BNtrV0cJlQ_WXRp4A_eqLZxDCnTj14EUw2fKW8Q713GOa2pwDR38IQFeQ5VPARW6g-FpJup5RVgXG6LbBDe2FlDObNDG_AVvCbqPU5YEUktcJUForMddbncsFJNraznhdow8RsRcxl6ap32S4ZJ-bg8fIgr53KIhuvlHWG0284nKlm0_BgfWLcNyyUj0OTFY7Sejiy5MZmnqcezcG5vD-Wvq8lORt0UdVVRrP1oYXlZ2Mu09GGf7bHv16HeaftQ6v7uDye_4I7ar_mT25JlQhEiwS4I

###
