GET https://skorohoda.plentymarkets-cloud02.com/rest/items/manufacturers?id=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNzMzOThlZTVmZTlmNDM0N2MxYzUxODYyZGUzMWZmN2Q3NGRmZGE4NDgyYTU1MTQ0MmM0YTE5YzZhZDhiMDU3MzI3YTlkMTA1MGNjMWEzZTYiLCJpYXQiOjE2MjEyNzUwNzMsIm5iZiI6MTYyMTI3NTA3MywiZXhwIjoxNjIxMzYxNDczLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.sQRnSesYUdyadIodcYId1Eix8hgsPwGaYVAua7xfLgLaBsLFIVl7gHgHoQLlHutdqgHW1pa5bM4e3_uitqGcmdIOsrwCMWA8JyaTQGAvypIwPHSR3uqtMAtY_wdOOgUZGCL26GOmijH4Y7iPR9G9tyx6rOCwsnsqtNVzABJQt6xgfUaCGh5sWiNEcvEzzUTUUe2hVXmt2WKk5W6rzXcJF-Pqx2CSJVKvv_8KSZq_U6cQ2JVuy6bIOO8mnU2kJ8r217Xq27rajocbDJ5dKhULB-Lk2FtE_8zaRcwFEC-XEbfnASFd4bCAIfb1N01XB-Dzsf1EOyWlvQRj1WRr1Oh05j2uUu4qiN8SNKefxRsRgQ4hGCZKUgreigDlYKUWQMAB7BVsArJlfXN1uPYObLCXW7G8n5bPKxsjbRNfJaLcfDlO9lLVKSTCjWzJWWNvCq6GwweUQqf99oNavzNVdpSuZf1ZytrPJAiRkZpePjwLZsrpJyBUaZByjqi3nDe7cx46gPbPpDEHBwNBM_wUvzwT-t6ljH7HWI69RomahOBmO-Lrp-OeT3Xsaiko_S8YVnUnMaGTCo2rjYLqnRmn7QtwkiVpNO-UPvuUAQijKDmU3ZdIx8gujvJ-m69ecCShM2d_kibnlvlKPoB3qizaceSfyMh1wPDZjGxQGQ3MQ399-j8

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/manufacturers/4?with=commissions,externals
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNzMzOThlZTVmZTlmNDM0N2MxYzUxODYyZGUzMWZmN2Q3NGRmZGE4NDgyYTU1MTQ0MmM0YTE5YzZhZDhiMDU3MzI3YTlkMTA1MGNjMWEzZTYiLCJpYXQiOjE2MjEyNzUwNzMsIm5iZiI6MTYyMTI3NTA3MywiZXhwIjoxNjIxMzYxNDczLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.sQRnSesYUdyadIodcYId1Eix8hgsPwGaYVAua7xfLgLaBsLFIVl7gHgHoQLlHutdqgHW1pa5bM4e3_uitqGcmdIOsrwCMWA8JyaTQGAvypIwPHSR3uqtMAtY_wdOOgUZGCL26GOmijH4Y7iPR9G9tyx6rOCwsnsqtNVzABJQt6xgfUaCGh5sWiNEcvEzzUTUUe2hVXmt2WKk5W6rzXcJF-Pqx2CSJVKvv_8KSZq_U6cQ2JVuy6bIOO8mnU2kJ8r217Xq27rajocbDJ5dKhULB-Lk2FtE_8zaRcwFEC-XEbfnASFd4bCAIfb1N01XB-Dzsf1EOyWlvQRj1WRr1Oh05j2uUu4qiN8SNKefxRsRgQ4hGCZKUgreigDlYKUWQMAB7BVsArJlfXN1uPYObLCXW7G8n5bPKxsjbRNfJaLcfDlO9lLVKSTCjWzJWWNvCq6GwweUQqf99oNavzNVdpSuZf1ZytrPJAiRkZpePjwLZsrpJyBUaZByjqi3nDe7cx46gPbPpDEHBwNBM_wUvzwT-t6ljH7HWI69RomahOBmO-Lrp-OeT3Xsaiko_S8YVnUnMaGTCo2rjYLqnRmn7QtwkiVpNO-UPvuUAQijKDmU3ZdIx8gujvJ-m69ecCShM2d_kibnlvlKPoB3qizaceSfyMh1wPDZjGxQGQ3MQ399-j8
