GET https://skorohoda.plentymarkets-cloud02.com/rest/items/7769/variations/29044/variation_barcodes
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGIxMDEwZjU5ZjM5NDRhM2Y3ZjVlMDU1NDM1M2JjOGI0OGVlYzg3MWNmODcxMzk4ZWZhZjQxOTFlNDRhZmVhZWU0MjVkZGVmY2VlZjY4MzAiLCJpYXQiOjE2NDU0NDU3NDMsIm5iZiI6MTY0NTQ0NTc0MywiZXhwIjoxNjQ1NTMyMTQzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.aKus7eW2eGN2FOY3AgK109-84avf32bRwiK8GJL_HXok9UERQmDOMOXtwHvwMU8eA67ZXbtcaPVASr4Si7kZl7ar6dH8xdxukLIeM6kPxO6AShbq5_lb6U6TAG0Mf1p9m_NQvIzcM96JiyZkrrAznI2LbjJOdWbfXyujoFXLMiF0KZiEQTSdqBDg9fORD6WyNze92297nNmPMxiTXaQs2K6LQd3LusnImUIPPIuFA0ymybSwHjogHCBlD_SCa1-dZoB5tPJN3V4v8KWGChcva8iXZP2V3ZnhD4ZuZRp1jfdu68IFlM33aC47p7w9js8xiaUvegBclLMDujr4bw0XsNyhRvWLT6TYWqD9rsmis368ie34wXsO5_N-1IyPImaR3hZtJAZhrPGxIDqR6TW2jO6bOZEKOUsS9UVAYUwUHP0DOS6-czZxjsHZoQdbtbGAXGLHS6Q4I_sXEES3K64RM79IpeiooL_p2ZPtkzZKYGgW3Dj46fImXXS2-vKLA_fvbjXWvoFuMNegLQ8wYKCz5399qwR5whNAN1FJOvn8OsYKEWVFPiO0fDevTTLO7d5hQ5xiLXm0mbdwIk8zbaHIAExOde-aFR2muY0QRXq-CvQNnjpodP3YX1j2-CBXMRTPMCl_30U24pNTzcIWwArPcsJIN3Jda4kQczoqF1x6_tY

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/barcodes
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGIxMDEwZjU5ZjM5NDRhM2Y3ZjVlMDU1NDM1M2JjOGI0OGVlYzg3MWNmODcxMzk4ZWZhZjQxOTFlNDRhZmVhZWU0MjVkZGVmY2VlZjY4MzAiLCJpYXQiOjE2NDU0NDU3NDMsIm5iZiI6MTY0NTQ0NTc0MywiZXhwIjoxNjQ1NTMyMTQzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.aKus7eW2eGN2FOY3AgK109-84avf32bRwiK8GJL_HXok9UERQmDOMOXtwHvwMU8eA67ZXbtcaPVASr4Si7kZl7ar6dH8xdxukLIeM6kPxO6AShbq5_lb6U6TAG0Mf1p9m_NQvIzcM96JiyZkrrAznI2LbjJOdWbfXyujoFXLMiF0KZiEQTSdqBDg9fORD6WyNze92297nNmPMxiTXaQs2K6LQd3LusnImUIPPIuFA0ymybSwHjogHCBlD_SCa1-dZoB5tPJN3V4v8KWGChcva8iXZP2V3ZnhD4ZuZRp1jfdu68IFlM33aC47p7w9js8xiaUvegBclLMDujr4bw0XsNyhRvWLT6TYWqD9rsmis368ie34wXsO5_N-1IyPImaR3hZtJAZhrPGxIDqR6TW2jO6bOZEKOUsS9UVAYUwUHP0DOS6-czZxjsHZoQdbtbGAXGLHS6Q4I_sXEES3K64RM79IpeiooL_p2ZPtkzZKYGgW3Dj46fImXXS2-vKLA_fvbjXWvoFuMNegLQ8wYKCz5399qwR5whNAN1FJOvn8OsYKEWVFPiO0fDevTTLO7d5hQ5xiLXm0mbdwIk8zbaHIAExOde-aFR2muY0QRXq-CvQNnjpodP3YX1j2-CBXMRTPMCl_30U24pNTzcIWwArPcsJIN3Jda4kQczoqF1x6_tY

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/7791/variations?with=variationBarcodes
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGIxMDEwZjU5ZjM5NDRhM2Y3ZjVlMDU1NDM1M2JjOGI0OGVlYzg3MWNmODcxMzk4ZWZhZjQxOTFlNDRhZmVhZWU0MjVkZGVmY2VlZjY4MzAiLCJpYXQiOjE2NDU0NDU3NDMsIm5iZiI6MTY0NTQ0NTc0MywiZXhwIjoxNjQ1NTMyMTQzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.aKus7eW2eGN2FOY3AgK109-84avf32bRwiK8GJL_HXok9UERQmDOMOXtwHvwMU8eA67ZXbtcaPVASr4Si7kZl7ar6dH8xdxukLIeM6kPxO6AShbq5_lb6U6TAG0Mf1p9m_NQvIzcM96JiyZkrrAznI2LbjJOdWbfXyujoFXLMiF0KZiEQTSdqBDg9fORD6WyNze92297nNmPMxiTXaQs2K6LQd3LusnImUIPPIuFA0ymybSwHjogHCBlD_SCa1-dZoB5tPJN3V4v8KWGChcva8iXZP2V3ZnhD4ZuZRp1jfdu68IFlM33aC47p7w9js8xiaUvegBclLMDujr4bw0XsNyhRvWLT6TYWqD9rsmis368ie34wXsO5_N-1IyPImaR3hZtJAZhrPGxIDqR6TW2jO6bOZEKOUsS9UVAYUwUHP0DOS6-czZxjsHZoQdbtbGAXGLHS6Q4I_sXEES3K64RM79IpeiooL_p2ZPtkzZKYGgW3Dj46fImXXS2-vKLA_fvbjXWvoFuMNegLQ8wYKCz5399qwR5whNAN1FJOvn8OsYKEWVFPiO0fDevTTLO7d5hQ5xiLXm0mbdwIk8zbaHIAExOde-aFR2muY0QRXq-CvQNnjpodP3YX1j2-CBXMRTPMCl_30U24pNTzcIWwArPcsJIN3Jda4kQczoqF1x6_tY

###

