GET https://skorohoda.plentymarkets-cloud02.com/rest/items/8366?with=itemImages
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTBlMzRmZDIwN2JlY2Y2NjM3NGVlZjcyNDBkMjhmNGQ4Y2UzNzUxYzQwOTVmOGJkMDkyMWMwOWM3YjQwNjU2YjM4ZTIxNmFmZTJmMjFjY2IiLCJpYXQiOjE2MjI5MTM5NzAsIm5iZiI6MTYyMjkxMzk3MCwiZXhwIjoxNjIzMDAwMzY5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.wdeNHBO2MXZE2tRE7QdYZotS-iW3rF8NBYS6hCDmDI_XsFt036Mczs9YLpizIMwzXob7vpyUqqaFGtF_jUgzJYKTkgaKWhuhZqAyOH3d_0_H7XAnbFspr465U_3UrLPqs3fX_rvFmr33rBvVkHUekspIgkAUJQc5R-FF5qQsQP4HlT1mW6NnMV2z8hr3N_g8LP1Oha8vlBkiimu8UD9WT8OWZpoWvRVojJoGeKzZqjsQBOF3y4ARCyHmIL_JuOhMsgQOvBVfa7GEcI6-rdSoEZIa12TEXrUov-eFH6sNh-SDoKCud0EdpPvHUL6qWSVcacmyN0HwBHDIQEYka4y987-RK66Z8oeW60iOFgPoYSUuIOBaZ52LpUeGHyvS9ldb-BAdN_L9lku0diAm5aLHwrHZtKJOHgpg-p_dVj18T3WKe_wZPlpTk2n_CQjAkKZeM-UyX6WLtJlbWFqmtKhq-4bx2YPPGaDtGLcTkf3HvD98xVZ_owZ8nuB65Chr0d6bTxlwhOnVCwhmHvclMJMhuNi5zKY3qFShZlPEBfxi_o0LxMAuf1Na4zzfNYxr4p2sCytLm8LI0FYVC4K9YJ-dtUYkW6tP-2QcLIoNwLFER64Dr_0u_Vjv5b6zlROpgWKu4UL4zg5S4QfSq62U69zJoLKzZzTU0aAt93yw9CIDmpk

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/variations?with=itemImages&itemsPerPage=10&page=4
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTBlMzRmZDIwN2JlY2Y2NjM3NGVlZjcyNDBkMjhmNGQ4Y2UzNzUxYzQwOTVmOGJkMDkyMWMwOWM3YjQwNjU2YjM4ZTIxNmFmZTJmMjFjY2IiLCJpYXQiOjE2MjI5MTM5NzAsIm5iZiI6MTYyMjkxMzk3MCwiZXhwIjoxNjIzMDAwMzY5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.wdeNHBO2MXZE2tRE7QdYZotS-iW3rF8NBYS6hCDmDI_XsFt036Mczs9YLpizIMwzXob7vpyUqqaFGtF_jUgzJYKTkgaKWhuhZqAyOH3d_0_H7XAnbFspr465U_3UrLPqs3fX_rvFmr33rBvVkHUekspIgkAUJQc5R-FF5qQsQP4HlT1mW6NnMV2z8hr3N_g8LP1Oha8vlBkiimu8UD9WT8OWZpoWvRVojJoGeKzZqjsQBOF3y4ARCyHmIL_JuOhMsgQOvBVfa7GEcI6-rdSoEZIa12TEXrUov-eFH6sNh-SDoKCud0EdpPvHUL6qWSVcacmyN0HwBHDIQEYka4y987-RK66Z8oeW60iOFgPoYSUuIOBaZ52LpUeGHyvS9ldb-BAdN_L9lku0diAm5aLHwrHZtKJOHgpg-p_dVj18T3WKe_wZPlpTk2n_CQjAkKZeM-UyX6WLtJlbWFqmtKhq-4bx2YPPGaDtGLcTkf3HvD98xVZ_owZ8nuB65Chr0d6bTxlwhOnVCwhmHvclMJMhuNi5zKY3qFShZlPEBfxi_o0LxMAuf1Na4zzfNYxr4p2sCytLm8LI0FYVC4K9YJ-dtUYkW6tP-2QcLIoNwLFER64Dr_0u_Vjv5b6zlROpgWKu4UL4zg5S4QfSq62U69zJoLKzZzTU0aAt93yw9CIDmpk

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/8088/images
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTBlMzRmZDIwN2JlY2Y2NjM3NGVlZjcyNDBkMjhmNGQ4Y2UzNzUxYzQwOTVmOGJkMDkyMWMwOWM3YjQwNjU2YjM4ZTIxNmFmZTJmMjFjY2IiLCJpYXQiOjE2MjI5MTM5NzAsIm5iZiI6MTYyMjkxMzk3MCwiZXhwIjoxNjIzMDAwMzY5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.wdeNHBO2MXZE2tRE7QdYZotS-iW3rF8NBYS6hCDmDI_XsFt036Mczs9YLpizIMwzXob7vpyUqqaFGtF_jUgzJYKTkgaKWhuhZqAyOH3d_0_H7XAnbFspr465U_3UrLPqs3fX_rvFmr33rBvVkHUekspIgkAUJQc5R-FF5qQsQP4HlT1mW6NnMV2z8hr3N_g8LP1Oha8vlBkiimu8UD9WT8OWZpoWvRVojJoGeKzZqjsQBOF3y4ARCyHmIL_JuOhMsgQOvBVfa7GEcI6-rdSoEZIa12TEXrUov-eFH6sNh-SDoKCud0EdpPvHUL6qWSVcacmyN0HwBHDIQEYka4y987-RK66Z8oeW60iOFgPoYSUuIOBaZ52LpUeGHyvS9ldb-BAdN_L9lku0diAm5aLHwrHZtKJOHgpg-p_dVj18T3WKe_wZPlpTk2n_CQjAkKZeM-UyX6WLtJlbWFqmtKhq-4bx2YPPGaDtGLcTkf3HvD98xVZ_owZ8nuB65Chr0d6bTxlwhOnVCwhmHvclMJMhuNi5zKY3qFShZlPEBfxi_o0LxMAuf1Na4zzfNYxr4p2sCytLm8LI0FYVC4K9YJ-dtUYkW6tP-2QcLIoNwLFER64Dr_0u_Vjv5b6zlROpgWKu4UL4zg5S4QfSq62U69zJoLKzZzTU0aAt93yw9CIDmpk

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/8044/variations?with=images
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTBlMzRmZDIwN2JlY2Y2NjM3NGVlZjcyNDBkMjhmNGQ4Y2UzNzUxYzQwOTVmOGJkMDkyMWMwOWM3YjQwNjU2YjM4ZTIxNmFmZTJmMjFjY2IiLCJpYXQiOjE2MjI5MTM5NzAsIm5iZiI6MTYyMjkxMzk3MCwiZXhwIjoxNjIzMDAwMzY5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.wdeNHBO2MXZE2tRE7QdYZotS-iW3rF8NBYS6hCDmDI_XsFt036Mczs9YLpizIMwzXob7vpyUqqaFGtF_jUgzJYKTkgaKWhuhZqAyOH3d_0_H7XAnbFspr465U_3UrLPqs3fX_rvFmr33rBvVkHUekspIgkAUJQc5R-FF5qQsQP4HlT1mW6NnMV2z8hr3N_g8LP1Oha8vlBkiimu8UD9WT8OWZpoWvRVojJoGeKzZqjsQBOF3y4ARCyHmIL_JuOhMsgQOvBVfa7GEcI6-rdSoEZIa12TEXrUov-eFH6sNh-SDoKCud0EdpPvHUL6qWSVcacmyN0HwBHDIQEYka4y987-RK66Z8oeW60iOFgPoYSUuIOBaZ52LpUeGHyvS9ldb-BAdN_L9lku0diAm5aLHwrHZtKJOHgpg-p_dVj18T3WKe_wZPlpTk2n_CQjAkKZeM-UyX6WLtJlbWFqmtKhq-4bx2YPPGaDtGLcTkf3HvD98xVZ_owZ8nuB65Chr0d6bTxlwhOnVCwhmHvclMJMhuNi5zKY3qFShZlPEBfxi_o0LxMAuf1Na4zzfNYxr4p2sCytLm8LI0FYVC4K9YJ-dtUYkW6tP-2QcLIoNwLFER64Dr_0u_Vjv5b6zlROpgWKu4UL4zg5S4QfSq62U69zJoLKzZzTU0aAt93yw9CIDmpk

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/8044/variations/30910?with=images
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTBlMzRmZDIwN2JlY2Y2NjM3NGVlZjcyNDBkMjhmNGQ4Y2UzNzUxYzQwOTVmOGJkMDkyMWMwOWM3YjQwNjU2YjM4ZTIxNmFmZTJmMjFjY2IiLCJpYXQiOjE2MjI5MTM5NzAsIm5iZiI6MTYyMjkxMzk3MCwiZXhwIjoxNjIzMDAwMzY5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.wdeNHBO2MXZE2tRE7QdYZotS-iW3rF8NBYS6hCDmDI_XsFt036Mczs9YLpizIMwzXob7vpyUqqaFGtF_jUgzJYKTkgaKWhuhZqAyOH3d_0_H7XAnbFspr465U_3UrLPqs3fX_rvFmr33rBvVkHUekspIgkAUJQc5R-FF5qQsQP4HlT1mW6NnMV2z8hr3N_g8LP1Oha8vlBkiimu8UD9WT8OWZpoWvRVojJoGeKzZqjsQBOF3y4ARCyHmIL_JuOhMsgQOvBVfa7GEcI6-rdSoEZIa12TEXrUov-eFH6sNh-SDoKCud0EdpPvHUL6qWSVcacmyN0HwBHDIQEYka4y987-RK66Z8oeW60iOFgPoYSUuIOBaZ52LpUeGHyvS9ldb-BAdN_L9lku0diAm5aLHwrHZtKJOHgpg-p_dVj18T3WKe_wZPlpTk2n_CQjAkKZeM-UyX6WLtJlbWFqmtKhq-4bx2YPPGaDtGLcTkf3HvD98xVZ_owZ8nuB65Chr0d6bTxlwhOnVCwhmHvclMJMhuNi5zKY3qFShZlPEBfxi_o0LxMAuf1Na4zzfNYxr4p2sCytLm8LI0FYVC4K9YJ-dtUYkW6tP-2QcLIoNwLFER64Dr_0u_Vjv5b6zlROpgWKu4UL4zg5S4QfSq62U69zJoLKzZzTU0aAt93yw9CIDmpk

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/8044/variations/30910/variation_images
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTBlMzRmZDIwN2JlY2Y2NjM3NGVlZjcyNDBkMjhmNGQ4Y2UzNzUxYzQwOTVmOGJkMDkyMWMwOWM3YjQwNjU2YjM4ZTIxNmFmZTJmMjFjY2IiLCJpYXQiOjE2MjI5MTM5NzAsIm5iZiI6MTYyMjkxMzk3MCwiZXhwIjoxNjIzMDAwMzY5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.wdeNHBO2MXZE2tRE7QdYZotS-iW3rF8NBYS6hCDmDI_XsFt036Mczs9YLpizIMwzXob7vpyUqqaFGtF_jUgzJYKTkgaKWhuhZqAyOH3d_0_H7XAnbFspr465U_3UrLPqs3fX_rvFmr33rBvVkHUekspIgkAUJQc5R-FF5qQsQP4HlT1mW6NnMV2z8hr3N_g8LP1Oha8vlBkiimu8UD9WT8OWZpoWvRVojJoGeKzZqjsQBOF3y4ARCyHmIL_JuOhMsgQOvBVfa7GEcI6-rdSoEZIa12TEXrUov-eFH6sNh-SDoKCud0EdpPvHUL6qWSVcacmyN0HwBHDIQEYka4y987-RK66Z8oeW60iOFgPoYSUuIOBaZ52LpUeGHyvS9ldb-BAdN_L9lku0diAm5aLHwrHZtKJOHgpg-p_dVj18T3WKe_wZPlpTk2n_CQjAkKZeM-UyX6WLtJlbWFqmtKhq-4bx2YPPGaDtGLcTkf3HvD98xVZ_owZ8nuB65Chr0d6bTxlwhOnVCwhmHvclMJMhuNi5zKY3qFShZlPEBfxi_o0LxMAuf1Na4zzfNYxr4p2sCytLm8LI0FYVC4K9YJ-dtUYkW6tP-2QcLIoNwLFER64Dr_0u_Vjv5b6zlROpgWKu4UL4zg5S4QfSq62U69zJoLKzZzTU0aAt93yw9CIDmpk

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/8369/variation_images
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTBlMzRmZDIwN2JlY2Y2NjM3NGVlZjcyNDBkMjhmNGQ4Y2UzNzUxYzQwOTVmOGJkMDkyMWMwOWM3YjQwNjU2YjM4ZTIxNmFmZTJmMjFjY2IiLCJpYXQiOjE2MjI5MTM5NzAsIm5iZiI6MTYyMjkxMzk3MCwiZXhwIjoxNjIzMDAwMzY5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.wdeNHBO2MXZE2tRE7QdYZotS-iW3rF8NBYS6hCDmDI_XsFt036Mczs9YLpizIMwzXob7vpyUqqaFGtF_jUgzJYKTkgaKWhuhZqAyOH3d_0_H7XAnbFspr465U_3UrLPqs3fX_rvFmr33rBvVkHUekspIgkAUJQc5R-FF5qQsQP4HlT1mW6NnMV2z8hr3N_g8LP1Oha8vlBkiimu8UD9WT8OWZpoWvRVojJoGeKzZqjsQBOF3y4ARCyHmIL_JuOhMsgQOvBVfa7GEcI6-rdSoEZIa12TEXrUov-eFH6sNh-SDoKCud0EdpPvHUL6qWSVcacmyN0HwBHDIQEYka4y987-RK66Z8oeW60iOFgPoYSUuIOBaZ52LpUeGHyvS9ldb-BAdN_L9lku0diAm5aLHwrHZtKJOHgpg-p_dVj18T3WKe_wZPlpTk2n_CQjAkKZeM-UyX6WLtJlbWFqmtKhq-4bx2YPPGaDtGLcTkf3HvD98xVZ_owZ8nuB65Chr0d6bTxlwhOnVCwhmHvclMJMhuNi5zKY3qFShZlPEBfxi_o0LxMAuf1Na4zzfNYxr4p2sCytLm8LI0FYVC4K9YJ-dtUYkW6tP-2QcLIoNwLFER64Dr_0u_Vjv5b6zlROpgWKu4UL4zg5S4QfSq62U69zJoLKzZzTU0aAt93yw9CIDmpk


###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/8044/variation_images
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTBlMzRmZDIwN2JlY2Y2NjM3NGVlZjcyNDBkMjhmNGQ4Y2UzNzUxYzQwOTVmOGJkMDkyMWMwOWM3YjQwNjU2YjM4ZTIxNmFmZTJmMjFjY2IiLCJpYXQiOjE2MjI5MTM5NzAsIm5iZiI6MTYyMjkxMzk3MCwiZXhwIjoxNjIzMDAwMzY5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.wdeNHBO2MXZE2tRE7QdYZotS-iW3rF8NBYS6hCDmDI_XsFt036Mczs9YLpizIMwzXob7vpyUqqaFGtF_jUgzJYKTkgaKWhuhZqAyOH3d_0_H7XAnbFspr465U_3UrLPqs3fX_rvFmr33rBvVkHUekspIgkAUJQc5R-FF5qQsQP4HlT1mW6NnMV2z8hr3N_g8LP1Oha8vlBkiimu8UD9WT8OWZpoWvRVojJoGeKzZqjsQBOF3y4ARCyHmIL_JuOhMsgQOvBVfa7GEcI6-rdSoEZIa12TEXrUov-eFH6sNh-SDoKCud0EdpPvHUL6qWSVcacmyN0HwBHDIQEYka4y987-RK66Z8oeW60iOFgPoYSUuIOBaZ52LpUeGHyvS9ldb-BAdN_L9lku0diAm5aLHwrHZtKJOHgpg-p_dVj18T3WKe_wZPlpTk2n_CQjAkKZeM-UyX6WLtJlbWFqmtKhq-4bx2YPPGaDtGLcTkf3HvD98xVZ_owZ8nuB65Chr0d6bTxlwhOnVCwhmHvclMJMhuNi5zKY3qFShZlPEBfxi_o0LxMAuf1Na4zzfNYxr4p2sCytLm8LI0FYVC4K9YJ-dtUYkW6tP-2QcLIoNwLFER64Dr_0u_Vjv5b6zlROpgWKu4UL4zg5S4QfSq62U69zJoLKzZzTU0aAt93yw9CIDmpk


###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/8044/images/attribute_value_markets
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTBlMzRmZDIwN2JlY2Y2NjM3NGVlZjcyNDBkMjhmNGQ4Y2UzNzUxYzQwOTVmOGJkMDkyMWMwOWM3YjQwNjU2YjM4ZTIxNmFmZTJmMjFjY2IiLCJpYXQiOjE2MjI5MTM5NzAsIm5iZiI6MTYyMjkxMzk3MCwiZXhwIjoxNjIzMDAwMzY5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.wdeNHBO2MXZE2tRE7QdYZotS-iW3rF8NBYS6hCDmDI_XsFt036Mczs9YLpizIMwzXob7vpyUqqaFGtF_jUgzJYKTkgaKWhuhZqAyOH3d_0_H7XAnbFspr465U_3UrLPqs3fX_rvFmr33rBvVkHUekspIgkAUJQc5R-FF5qQsQP4HlT1mW6NnMV2z8hr3N_g8LP1Oha8vlBkiimu8UD9WT8OWZpoWvRVojJoGeKzZqjsQBOF3y4ARCyHmIL_JuOhMsgQOvBVfa7GEcI6-rdSoEZIa12TEXrUov-eFH6sNh-SDoKCud0EdpPvHUL6qWSVcacmyN0HwBHDIQEYka4y987-RK66Z8oeW60iOFgPoYSUuIOBaZ52LpUeGHyvS9ldb-BAdN_L9lku0diAm5aLHwrHZtKJOHgpg-p_dVj18T3WKe_wZPlpTk2n_CQjAkKZeM-UyX6WLtJlbWFqmtKhq-4bx2YPPGaDtGLcTkf3HvD98xVZ_owZ8nuB65Chr0d6bTxlwhOnVCwhmHvclMJMhuNi5zKY3qFShZlPEBfxi_o0LxMAuf1Na4zzfNYxr4p2sCytLm8LI0FYVC4K9YJ-dtUYkW6tP-2QcLIoNwLFER64Dr_0u_Vjv5b6zlROpgWKu4UL4zg5S4QfSq62U69zJoLKzZzTU0aAt93yw9CIDmpk

