###
GET https://skorohoda.plentymarkets-cloud02.com/rest/listings
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTA2YjQxODMzMTQyM2E2M2M1YmJiZGJkNGU5MTEyNzNmNTUwZjA5Y2FiZmU4ZjMzYjM2ZThkMWZhZjg2N2VhYTllYzczMWFiZTJkYzgwMDYiLCJpYXQiOjE2MTU2NDc2MDMsIm5iZiI6MTYxNTY0NzYwMywiZXhwIjoxNjE1NzM0MDAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.jxGvBvxx3yzzWp-81-rhPBO6VkTDPr_xRNWP3glkL-TZPmf5zWLTEBmWJgwVzGLxs8yYKHJ3FIu5x6RVAfm8xnplI46HzHzu1GWSyEAnTQ-ZuK_fbipEjSSXk9z-zdR1k88fbllqycLLq7Bvwyu5XIkYP1-GEEW_z-2ut3SZYfu1wdOmfBee9eau70Xe5QvXy2ysvGBjwRkKDeOGjjTLqJug5epbsU19QpXWwnq9AYcom1b2Zt7GGt-QR0HefXXi5e4ReNJGbs15wOo6WtAprX865IH583gscikhcO45fdgdq2Je28gPmLxFoKu8EHyUuol4aOU3lwgYaAJPVc832xHLm10hMF66vi-yv6xGl0XVANKlJBlWYH0uQFQRKG0o00p_xdkSwHQT5hFuiJuF8F_f8E1s_LYXG14Kvp2GmMhCYiO6ShyNGqqOM1TPXnVjytfLUZ5OyEUmufPCAMjqryH_EF9Jhl3qdEl15dABaQfSdzhfIb6KyP0gmHSacruRS-TgOOEC9efaNvAMhDDk1ETU5zXnmbeN79w_zt7G9K2EfDtxA8iAU2s5a0AX9eN-VRYOWyCPBP-UtaEqG8hzXNvGqsviHJmNQPLCAqSxu_AXRT2qeq6LrBICs0iOX9TwjI9XBvupbuTvv5PoFsuEvqPorwsJyY-_k7QECRRUMJg

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/listings/markets
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTA2YjQxODMzMTQyM2E2M2M1YmJiZGJkNGU5MTEyNzNmNTUwZjA5Y2FiZmU4ZjMzYjM2ZThkMWZhZjg2N2VhYTllYzczMWFiZTJkYzgwMDYiLCJpYXQiOjE2MTU2NDc2MDMsIm5iZiI6MTYxNTY0NzYwMywiZXhwIjoxNjE1NzM0MDAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.jxGvBvxx3yzzWp-81-rhPBO6VkTDPr_xRNWP3glkL-TZPmf5zWLTEBmWJgwVzGLxs8yYKHJ3FIu5x6RVAfm8xnplI46HzHzu1GWSyEAnTQ-ZuK_fbipEjSSXk9z-zdR1k88fbllqycLLq7Bvwyu5XIkYP1-GEEW_z-2ut3SZYfu1wdOmfBee9eau70Xe5QvXy2ysvGBjwRkKDeOGjjTLqJug5epbsU19QpXWwnq9AYcom1b2Zt7GGt-QR0HefXXi5e4ReNJGbs15wOo6WtAprX865IH583gscikhcO45fdgdq2Je28gPmLxFoKu8EHyUuol4aOU3lwgYaAJPVc832xHLm10hMF66vi-yv6xGl0XVANKlJBlWYH0uQFQRKG0o00p_xdkSwHQT5hFuiJuF8F_f8E1s_LYXG14Kvp2GmMhCYiO6ShyNGqqOM1TPXnVjytfLUZ5OyEUmufPCAMjqryH_EF9Jhl3qdEl15dABaQfSdzhfIb6KyP0gmHSacruRS-TgOOEC9efaNvAMhDDk1ETU5zXnmbeN79w_zt7G9K2EfDtxA8iAU2s5a0AX9eN-VRYOWyCPBP-UtaEqG8hzXNvGqsviHJmNQPLCAqSxu_AXRT2qeq6LrBICs0iOX9TwjI9XBvupbuTvv5PoFsuEvqPorwsJyY-_k7QECRRUMJg

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/listings/types
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTA2YjQxODMzMTQyM2E2M2M1YmJiZGJkNGU5MTEyNzNmNTUwZjA5Y2FiZmU4ZjMzYjM2ZThkMWZhZjg2N2VhYTllYzczMWFiZTJkYzgwMDYiLCJpYXQiOjE2MTU2NDc2MDMsIm5iZiI6MTYxNTY0NzYwMywiZXhwIjoxNjE1NzM0MDAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.jxGvBvxx3yzzWp-81-rhPBO6VkTDPr_xRNWP3glkL-TZPmf5zWLTEBmWJgwVzGLxs8yYKHJ3FIu5x6RVAfm8xnplI46HzHzu1GWSyEAnTQ-ZuK_fbipEjSSXk9z-zdR1k88fbllqycLLq7Bvwyu5XIkYP1-GEEW_z-2ut3SZYfu1wdOmfBee9eau70Xe5QvXy2ysvGBjwRkKDeOGjjTLqJug5epbsU19QpXWwnq9AYcom1b2Zt7GGt-QR0HefXXi5e4ReNJGbs15wOo6WtAprX865IH583gscikhcO45fdgdq2Je28gPmLxFoKu8EHyUuol4aOU3lwgYaAJPVc832xHLm10hMF66vi-yv6xGl0XVANKlJBlWYH0uQFQRKG0o00p_xdkSwHQT5hFuiJuF8F_f8E1s_LYXG14Kvp2GmMhCYiO6ShyNGqqOM1TPXnVjytfLUZ5OyEUmufPCAMjqryH_EF9Jhl3qdEl15dABaQfSdzhfIb6KyP0gmHSacruRS-TgOOEC9efaNvAMhDDk1ETU5zXnmbeN79w_zt7G9K2EfDtxA8iAU2s5a0AX9eN-VRYOWyCPBP-UtaEqG8hzXNvGqsviHJmNQPLCAqSxu_AXRT2qeq6LrBICs0iOX9TwjI9XBvupbuTvv5PoFsuEvqPorwsJyY-_k7QECRRUMJg

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/listings/stock_dependence_types
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTA2YjQxODMzMTQyM2E2M2M1YmJiZGJkNGU5MTEyNzNmNTUwZjA5Y2FiZmU4ZjMzYjM2ZThkMWZhZjg2N2VhYTllYzczMWFiZTJkYzgwMDYiLCJpYXQiOjE2MTU2NDc2MDMsIm5iZiI6MTYxNTY0NzYwMywiZXhwIjoxNjE1NzM0MDAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.jxGvBvxx3yzzWp-81-rhPBO6VkTDPr_xRNWP3glkL-TZPmf5zWLTEBmWJgwVzGLxs8yYKHJ3FIu5x6RVAfm8xnplI46HzHzu1GWSyEAnTQ-ZuK_fbipEjSSXk9z-zdR1k88fbllqycLLq7Bvwyu5XIkYP1-GEEW_z-2ut3SZYfu1wdOmfBee9eau70Xe5QvXy2ysvGBjwRkKDeOGjjTLqJug5epbsU19QpXWwnq9AYcom1b2Zt7GGt-QR0HefXXi5e4ReNJGbs15wOo6WtAprX865IH583gscikhcO45fdgdq2Je28gPmLxFoKu8EHyUuol4aOU3lwgYaAJPVc832xHLm10hMF66vi-yv6xGl0XVANKlJBlWYH0uQFQRKG0o00p_xdkSwHQT5hFuiJuF8F_f8E1s_LYXG14Kvp2GmMhCYiO6ShyNGqqOM1TPXnVjytfLUZ5OyEUmufPCAMjqryH_EF9Jhl3qdEl15dABaQfSdzhfIb6KyP0gmHSacruRS-TgOOEC9efaNvAMhDDk1ETU5zXnmbeN79w_zt7G9K2EfDtxA8iAU2s5a0AX9eN-VRYOWyCPBP-UtaEqG8hzXNvGqsviHJmNQPLCAqSxu_AXRT2qeq6LrBICs0iOX9TwjI9XBvupbuTvv5PoFsuEvqPorwsJyY-_k7QECRRUMJg

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/listings/shipping_profiles
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTA2YjQxODMzMTQyM2E2M2M1YmJiZGJkNGU5MTEyNzNmNTUwZjA5Y2FiZmU4ZjMzYjM2ZThkMWZhZjg2N2VhYTllYzczMWFiZTJkYzgwMDYiLCJpYXQiOjE2MTU2NDc2MDMsIm5iZiI6MTYxNTY0NzYwMywiZXhwIjoxNjE1NzM0MDAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.jxGvBvxx3yzzWp-81-rhPBO6VkTDPr_xRNWP3glkL-TZPmf5zWLTEBmWJgwVzGLxs8yYKHJ3FIu5x6RVAfm8xnplI46HzHzu1GWSyEAnTQ-ZuK_fbipEjSSXk9z-zdR1k88fbllqycLLq7Bvwyu5XIkYP1-GEEW_z-2ut3SZYfu1wdOmfBee9eau70Xe5QvXy2ysvGBjwRkKDeOGjjTLqJug5epbsU19QpXWwnq9AYcom1b2Zt7GGt-QR0HefXXi5e4ReNJGbs15wOo6WtAprX865IH583gscikhcO45fdgdq2Je28gPmLxFoKu8EHyUuol4aOU3lwgYaAJPVc832xHLm10hMF66vi-yv6xGl0XVANKlJBlWYH0uQFQRKG0o00p_xdkSwHQT5hFuiJuF8F_f8E1s_LYXG14Kvp2GmMhCYiO6ShyNGqqOM1TPXnVjytfLUZ5OyEUmufPCAMjqryH_EF9Jhl3qdEl15dABaQfSdzhfIb6KyP0gmHSacruRS-TgOOEC9efaNvAMhDDk1ETU5zXnmbeN79w_zt7G9K2EfDtxA8iAU2s5a0AX9eN-VRYOWyCPBP-UtaEqG8hzXNvGqsviHJmNQPLCAqSxu_AXRT2qeq6LrBICs0iOX9TwjI9XBvupbuTvv5PoFsuEvqPorwsJyY-_k7QECRRUMJg

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/listings/option_templates/preview
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTA2YjQxODMzMTQyM2E2M2M1YmJiZGJkNGU5MTEyNzNmNTUwZjA5Y2FiZmU4ZjMzYjM2ZThkMWZhZjg2N2VhYTllYzczMWFiZTJkYzgwMDYiLCJpYXQiOjE2MTU2NDc2MDMsIm5iZiI6MTYxNTY0NzYwMywiZXhwIjoxNjE1NzM0MDAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.jxGvBvxx3yzzWp-81-rhPBO6VkTDPr_xRNWP3glkL-TZPmf5zWLTEBmWJgwVzGLxs8yYKHJ3FIu5x6RVAfm8xnplI46HzHzu1GWSyEAnTQ-ZuK_fbipEjSSXk9z-zdR1k88fbllqycLLq7Bvwyu5XIkYP1-GEEW_z-2ut3SZYfu1wdOmfBee9eau70Xe5QvXy2ysvGBjwRkKDeOGjjTLqJug5epbsU19QpXWwnq9AYcom1b2Zt7GGt-QR0HefXXi5e4ReNJGbs15wOo6WtAprX865IH583gscikhcO45fdgdq2Je28gPmLxFoKu8EHyUuol4aOU3lwgYaAJPVc832xHLm10hMF66vi-yv6xGl0XVANKlJBlWYH0uQFQRKG0o00p_xdkSwHQT5hFuiJuF8F_f8E1s_LYXG14Kvp2GmMhCYiO6ShyNGqqOM1TPXnVjytfLUZ5OyEUmufPCAMjqryH_EF9Jhl3qdEl15dABaQfSdzhfIb6KyP0gmHSacruRS-TgOOEC9efaNvAMhDDk1ETU5zXnmbeN79w_zt7G9K2EfDtxA8iAU2s5a0AX9eN-VRYOWyCPBP-UtaEqG8hzXNvGqsviHJmNQPLCAqSxu_AXRT2qeq6LrBICs0iOX9TwjI9XBvupbuTvv5PoFsuEvqPorwsJyY-_k7QECRRUMJg



