###
GET https://skorohoda.plentymarkets-cloud02.com/rest/delete_log
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNzMwOTI5NDhmNmNjZWYzMGRhNjYxZGM3OGZmMjViYzhkNDFjMTk2YTY4MTgxN2RlMTEzYTRjMjIzZjNmMDQ4N2VlY2RjZGMyNTQzMmEzNDAiLCJpYXQiOjE2OTQwNjYyNDMuNDk0NCwibmJmIjoxNjk0MDY2MjQzLjQ5NDQsImV4cCI6MTY5NDE1MjY0My40ODMsInN1YiI6IjYiLCJzY29wZXMiOlsiKiJdfQ.oe8kCvI1zjWR4sOILV2a0FxSo9JqRbexFqY6aiAFWoPFn0w1kJU2Aewvcw-XEWYqya86UFVkNCmlG1pV7pYbz9haU0nncANGGYdK3OzQSZG4v2XUGRVNUjP1gt-n95HhBtSQ7JbyKivqVg-J6FFUkuZVJNZmWsopQpY6Q7qAKgNKEDLWlJuhL3Yv3mcmPxfibdtbozirnY1X9rkJqifkHCJZhSYoZCCCnLA-VGqWJQ73jGUmtqtUuf2iHSsolYvBZOtkcwwVEPD2bs6vGpQbVpXR9MXuDuC7DulAlXs-N8DDQHR_o-Atyp-eL_cKDcavPjSsC3-uMKZkH3CD5x6luN8pmYALDNDEzvXD-NrQ4xpESVQSUztDMvfqcesniN8C9VPGVJTaRdSZ0xCPHjXusIMEprwz_72Ph4r9a0Xbu9_fw_Nhyw8YfxgHD77FsQUzsd_YGmyTMk5mAwK4Rd9bfEiUqmLoZ-YYWOnGKaicVhdQs9Ls2NWIp7asep4f3yd4UThslMhQ3qiAtYEbnVqDVHcdRaJS4Y3Npr8Fa7awMQM3kO52Ze4PSRT5-TymWmOHTnhhYwg4jMe1EHet7Wj-ocxZ8Qeg288tS3Hn_l7Z8GTwavM0gjINZcaJfle8QfZJ4idGePpqWvuARlVOM5Hk_GpW-kVXmLOKBeyXH1CVTis

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/delete_log?referenceType=6
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNzMwOTI5NDhmNmNjZWYzMGRhNjYxZGM3OGZmMjViYzhkNDFjMTk2YTY4MTgxN2RlMTEzYTRjMjIzZjNmMDQ4N2VlY2RjZGMyNTQzMmEzNDAiLCJpYXQiOjE2OTQwNjYyNDMuNDk0NCwibmJmIjoxNjk0MDY2MjQzLjQ5NDQsImV4cCI6MTY5NDE1MjY0My40ODMsInN1YiI6IjYiLCJzY29wZXMiOlsiKiJdfQ.oe8kCvI1zjWR4sOILV2a0FxSo9JqRbexFqY6aiAFWoPFn0w1kJU2Aewvcw-XEWYqya86UFVkNCmlG1pV7pYbz9haU0nncANGGYdK3OzQSZG4v2XUGRVNUjP1gt-n95HhBtSQ7JbyKivqVg-J6FFUkuZVJNZmWsopQpY6Q7qAKgNKEDLWlJuhL3Yv3mcmPxfibdtbozirnY1X9rkJqifkHCJZhSYoZCCCnLA-VGqWJQ73jGUmtqtUuf2iHSsolYvBZOtkcwwVEPD2bs6vGpQbVpXR9MXuDuC7DulAlXs-N8DDQHR_o-Atyp-eL_cKDcavPjSsC3-uMKZkH3CD5x6luN8pmYALDNDEzvXD-NrQ4xpESVQSUztDMvfqcesniN8C9VPGVJTaRdSZ0xCPHjXusIMEprwz_72Ph4r9a0Xbu9_fw_Nhyw8YfxgHD77FsQUzsd_YGmyTMk5mAwK4Rd9bfEiUqmLoZ-YYWOnGKaicVhdQs9Ls2NWIp7asep4f3yd4UThslMhQ3qiAtYEbnVqDVHcdRaJS4Y3Npr8Fa7awMQM3kO52Ze4PSRT5-TymWmOHTnhhYwg4jMe1EHet7Wj-ocxZ8Qeg288tS3Hn_l7Z8GTwavM0gjINZcaJfle8QfZJ4idGePpqWvuARlVOM5Hk_GpW-kVXmLOKBeyXH1CVTis

### -- updatedBetween=2022-05-16 12:25:05
GET https://skorohoda.plentymarkets-cloud02.com/rest/delete_log?updatedBetween=2022-05-16
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNzMwOTI5NDhmNmNjZWYzMGRhNjYxZGM3OGZmMjViYzhkNDFjMTk2YTY4MTgxN2RlMTEzYTRjMjIzZjNmMDQ4N2VlY2RjZGMyNTQzMmEzNDAiLCJpYXQiOjE2OTQwNjYyNDMuNDk0NCwibmJmIjoxNjk0MDY2MjQzLjQ5NDQsImV4cCI6MTY5NDE1MjY0My40ODMsInN1YiI6IjYiLCJzY29wZXMiOlsiKiJdfQ.oe8kCvI1zjWR4sOILV2a0FxSo9JqRbexFqY6aiAFWoPFn0w1kJU2Aewvcw-XEWYqya86UFVkNCmlG1pV7pYbz9haU0nncANGGYdK3OzQSZG4v2XUGRVNUjP1gt-n95HhBtSQ7JbyKivqVg-J6FFUkuZVJNZmWsopQpY6Q7qAKgNKEDLWlJuhL3Yv3mcmPxfibdtbozirnY1X9rkJqifkHCJZhSYoZCCCnLA-VGqWJQ73jGUmtqtUuf2iHSsolYvBZOtkcwwVEPD2bs6vGpQbVpXR9MXuDuC7DulAlXs-N8DDQHR_o-Atyp-eL_cKDcavPjSsC3-uMKZkH3CD5x6luN8pmYALDNDEzvXD-NrQ4xpESVQSUztDMvfqcesniN8C9VPGVJTaRdSZ0xCPHjXusIMEprwz_72Ph4r9a0Xbu9_fw_Nhyw8YfxgHD77FsQUzsd_YGmyTMk5mAwK4Rd9bfEiUqmLoZ-YYWOnGKaicVhdQs9Ls2NWIp7asep4f3yd4UThslMhQ3qiAtYEbnVqDVHcdRaJS4Y3Npr8Fa7awMQM3kO52Ze4PSRT5-TymWmOHTnhhYwg4jMe1EHet7Wj-ocxZ8Qeg288tS3Hn_l7Z8GTwavM0gjINZcaJfle8QfZJ4idGePpqWvuARlVOM5Hk_GpW-kVXmLOKBeyXH1CVTis



###
GET https://skorohoda.plentymarkets-cloud02.com/rest/delete_log?page=813
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNzMwOTI5NDhmNmNjZWYzMGRhNjYxZGM3OGZmMjViYzhkNDFjMTk2YTY4MTgxN2RlMTEzYTRjMjIzZjNmMDQ4N2VlY2RjZGMyNTQzMmEzNDAiLCJpYXQiOjE2OTQwNjYyNDMuNDk0NCwibmJmIjoxNjk0MDY2MjQzLjQ5NDQsImV4cCI6MTY5NDE1MjY0My40ODMsInN1YiI6IjYiLCJzY29wZXMiOlsiKiJdfQ.oe8kCvI1zjWR4sOILV2a0FxSo9JqRbexFqY6aiAFWoPFn0w1kJU2Aewvcw-XEWYqya86UFVkNCmlG1pV7pYbz9haU0nncANGGYdK3OzQSZG4v2XUGRVNUjP1gt-n95HhBtSQ7JbyKivqVg-J6FFUkuZVJNZmWsopQpY6Q7qAKgNKEDLWlJuhL3Yv3mcmPxfibdtbozirnY1X9rkJqifkHCJZhSYoZCCCnLA-VGqWJQ73jGUmtqtUuf2iHSsolYvBZOtkcwwVEPD2bs6vGpQbVpXR9MXuDuC7DulAlXs-N8DDQHR_o-Atyp-eL_cKDcavPjSsC3-uMKZkH3CD5x6luN8pmYALDNDEzvXD-NrQ4xpESVQSUztDMvfqcesniN8C9VPGVJTaRdSZ0xCPHjXusIMEprwz_72Ph4r9a0Xbu9_fw_Nhyw8YfxgHD77FsQUzsd_YGmyTMk5mAwK4Rd9bfEiUqmLoZ-YYWOnGKaicVhdQs9Ls2NWIp7asep4f3yd4UThslMhQ3qiAtYEbnVqDVHcdRaJS4Y3Npr8Fa7awMQM3kO52Ze4PSRT5-TymWmOHTnhhYwg4jMe1EHet7Wj-ocxZ8Qeg288tS3Hn_l7Z8GTwavM0gjINZcaJfle8QfZJ4idGePpqWvuARlVOM5Hk_GpW-kVXmLOKBeyXH1CVTis


###
GET https://skorohoda.plentymarkets-cloud02.com/rest/logs?page=200
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNzMwOTI5NDhmNmNjZWYzMGRhNjYxZGM3OGZmMjViYzhkNDFjMTk2YTY4MTgxN2RlMTEzYTRjMjIzZjNmMDQ4N2VlY2RjZGMyNTQzMmEzNDAiLCJpYXQiOjE2OTQwNjYyNDMuNDk0NCwibmJmIjoxNjk0MDY2MjQzLjQ5NDQsImV4cCI6MTY5NDE1MjY0My40ODMsInN1YiI6IjYiLCJzY29wZXMiOlsiKiJdfQ.oe8kCvI1zjWR4sOILV2a0FxSo9JqRbexFqY6aiAFWoPFn0w1kJU2Aewvcw-XEWYqya86UFVkNCmlG1pV7pYbz9haU0nncANGGYdK3OzQSZG4v2XUGRVNUjP1gt-n95HhBtSQ7JbyKivqVg-J6FFUkuZVJNZmWsopQpY6Q7qAKgNKEDLWlJuhL3Yv3mcmPxfibdtbozirnY1X9rkJqifkHCJZhSYoZCCCnLA-VGqWJQ73jGUmtqtUuf2iHSsolYvBZOtkcwwVEPD2bs6vGpQbVpXR9MXuDuC7DulAlXs-N8DDQHR_o-Atyp-eL_cKDcavPjSsC3-uMKZkH3CD5x6luN8pmYALDNDEzvXD-NrQ4xpESVQSUztDMvfqcesniN8C9VPGVJTaRdSZ0xCPHjXusIMEprwz_72Ph4r9a0Xbu9_fw_Nhyw8YfxgHD77FsQUzsd_YGmyTMk5mAwK4Rd9bfEiUqmLoZ-YYWOnGKaicVhdQs9Ls2NWIp7asep4f3yd4UThslMhQ3qiAtYEbnVqDVHcdRaJS4Y3Npr8Fa7awMQM3kO52Ze4PSRT5-TymWmOHTnhhYwg4jMe1EHet7Wj-ocxZ8Qeg288tS3Hn_l7Z8GTwavM0gjINZcaJfle8QfZJ4idGePpqWvuARlVOM5Hk_GpW-kVXmLOKBeyXH1CVTis

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/logs/integration_keys
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNzMwOTI5NDhmNmNjZWYzMGRhNjYxZGM3OGZmMjViYzhkNDFjMTk2YTY4MTgxN2RlMTEzYTRjMjIzZjNmMDQ4N2VlY2RjZGMyNTQzMmEzNDAiLCJpYXQiOjE2OTQwNjYyNDMuNDk0NCwibmJmIjoxNjk0MDY2MjQzLjQ5NDQsImV4cCI6MTY5NDE1MjY0My40ODMsInN1YiI6IjYiLCJzY29wZXMiOlsiKiJdfQ.oe8kCvI1zjWR4sOILV2a0FxSo9JqRbexFqY6aiAFWoPFn0w1kJU2Aewvcw-XEWYqya86UFVkNCmlG1pV7pYbz9haU0nncANGGYdK3OzQSZG4v2XUGRVNUjP1gt-n95HhBtSQ7JbyKivqVg-J6FFUkuZVJNZmWsopQpY6Q7qAKgNKEDLWlJuhL3Yv3mcmPxfibdtbozirnY1X9rkJqifkHCJZhSYoZCCCnLA-VGqWJQ73jGUmtqtUuf2iHSsolYvBZOtkcwwVEPD2bs6vGpQbVpXR9MXuDuC7DulAlXs-N8DDQHR_o-Atyp-eL_cKDcavPjSsC3-uMKZkH3CD5x6luN8pmYALDNDEzvXD-NrQ4xpESVQSUztDMvfqcesniN8C9VPGVJTaRdSZ0xCPHjXusIMEprwz_72Ph4r9a0Xbu9_fw_Nhyw8YfxgHD77FsQUzsd_YGmyTMk5mAwK4Rd9bfEiUqmLoZ-YYWOnGKaicVhdQs9Ls2NWIp7asep4f3yd4UThslMhQ3qiAtYEbnVqDVHcdRaJS4Y3Npr8Fa7awMQM3kO52Ze4PSRT5-TymWmOHTnhhYwg4jMe1EHet7Wj-ocxZ8Qeg288tS3Hn_l7Z8GTwavM0gjINZcaJfle8QfZJ4idGePpqWvuARlVOM5Hk_GpW-kVXmLOKBeyXH1CVTis

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/logs/reference_types
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNzMwOTI5NDhmNmNjZWYzMGRhNjYxZGM3OGZmMjViYzhkNDFjMTk2YTY4MTgxN2RlMTEzYTRjMjIzZjNmMDQ4N2VlY2RjZGMyNTQzMmEzNDAiLCJpYXQiOjE2OTQwNjYyNDMuNDk0NCwibmJmIjoxNjk0MDY2MjQzLjQ5NDQsImV4cCI6MTY5NDE1MjY0My40ODMsInN1YiI6IjYiLCJzY29wZXMiOlsiKiJdfQ.oe8kCvI1zjWR4sOILV2a0FxSo9JqRbexFqY6aiAFWoPFn0w1kJU2Aewvcw-XEWYqya86UFVkNCmlG1pV7pYbz9haU0nncANGGYdK3OzQSZG4v2XUGRVNUjP1gt-n95HhBtSQ7JbyKivqVg-J6FFUkuZVJNZmWsopQpY6Q7qAKgNKEDLWlJuhL3Yv3mcmPxfibdtbozirnY1X9rkJqifkHCJZhSYoZCCCnLA-VGqWJQ73jGUmtqtUuf2iHSsolYvBZOtkcwwVEPD2bs6vGpQbVpXR9MXuDuC7DulAlXs-N8DDQHR_o-Atyp-eL_cKDcavPjSsC3-uMKZkH3CD5x6luN8pmYALDNDEzvXD-NrQ4xpESVQSUztDMvfqcesniN8C9VPGVJTaRdSZ0xCPHjXusIMEprwz_72Ph4r9a0Xbu9_fw_Nhyw8YfxgHD77FsQUzsd_YGmyTMk5mAwK4Rd9bfEiUqmLoZ-YYWOnGKaicVhdQs9Ls2NWIp7asep4f3yd4UThslMhQ3qiAtYEbnVqDVHcdRaJS4Y3Npr8Fa7awMQM3kO52Ze4PSRT5-TymWmOHTnhhYwg4jMe1EHet7Wj-ocxZ8Qeg288tS3Hn_l7Z8GTwavM0gjINZcaJfle8QfZJ4idGePpqWvuARlVOM5Hk_GpW-kVXmLOKBeyXH1CVTis

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/logs/settings
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNzMwOTI5NDhmNmNjZWYzMGRhNjYxZGM3OGZmMjViYzhkNDFjMTk2YTY4MTgxN2RlMTEzYTRjMjIzZjNmMDQ4N2VlY2RjZGMyNTQzMmEzNDAiLCJpYXQiOjE2OTQwNjYyNDMuNDk0NCwibmJmIjoxNjk0MDY2MjQzLjQ5NDQsImV4cCI6MTY5NDE1MjY0My40ODMsInN1YiI6IjYiLCJzY29wZXMiOlsiKiJdfQ.oe8kCvI1zjWR4sOILV2a0FxSo9JqRbexFqY6aiAFWoPFn0w1kJU2Aewvcw-XEWYqya86UFVkNCmlG1pV7pYbz9haU0nncANGGYdK3OzQSZG4v2XUGRVNUjP1gt-n95HhBtSQ7JbyKivqVg-J6FFUkuZVJNZmWsopQpY6Q7qAKgNKEDLWlJuhL3Yv3mcmPxfibdtbozirnY1X9rkJqifkHCJZhSYoZCCCnLA-VGqWJQ73jGUmtqtUuf2iHSsolYvBZOtkcwwVEPD2bs6vGpQbVpXR9MXuDuC7DulAlXs-N8DDQHR_o-Atyp-eL_cKDcavPjSsC3-uMKZkH3CD5x6luN8pmYALDNDEzvXD-NrQ4xpESVQSUztDMvfqcesniN8C9VPGVJTaRdSZ0xCPHjXusIMEprwz_72Ph4r9a0Xbu9_fw_Nhyw8YfxgHD77FsQUzsd_YGmyTMk5mAwK4Rd9bfEiUqmLoZ-YYWOnGKaicVhdQs9Ls2NWIp7asep4f3yd4UThslMhQ3qiAtYEbnVqDVHcdRaJS4Y3Npr8Fa7awMQM3kO52Ze4PSRT5-TymWmOHTnhhYwg4jMe1EHet7Wj-ocxZ8Qeg288tS3Hn_l7Z8GTwavM0gjINZcaJfle8QfZJ4idGePpqWvuARlVOM5Hk_GpW-kVXmLOKBeyXH1CVTis
