###
GET https://skorohoda.plentymarkets-cloud02.com/rest/accounts/order_summaries
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZWQ3ZmRiZTQxNmI2MmZkYjBmZjgyMDM0YjExYWYyM2JmNDdlNWE1ZTNlNzIwOTQzMzM3ZGVlMjdhODlkNzIwYzQ2MGMwY2I4MTZlYTc4OWQiLCJpYXQiOjE2MTE4MzI1MDQsIm5iZiI6MTYxMTgzMjUwNCwiZXhwIjoxNjExOTE4OTA0LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.NngsWVP8_yC7oy0j02EBiZL3o7iaPALabhqE1zzTgqoOQ_k0YITDUWt4DlB_7MHSfYr1SNxdpz5SjPdvw-sxX7nQkVWiYuw4OzvJFxgX3J9aHbFteN5-CX_XRUwEhx0xK4E7dklNG8Mmgl5Db6LLL7jSljQTdQf-wcjK00xL4qb_aGYTJB8hCFokdUwAphwbNgfefQHyfM3ui-erOZrelbDpU9bzI3gcwyZIeb5lLZmkxVeVnYnl9T3oZ6a1iobAdRJ_k34aEnAzRWHTIVTE1DQJtOBbQ2Fypslpthd4yO2aB8FhpZc67nvE5exD6cWGszUPUh9lG7rxEfJqqAQY0fR264IBTM4hG_L8Rvp9tmcytBT_etnSZACViRypu_ZXP5MA3m2SJjLuSOSa7YQ6jsCYXhwN6q10R7emLFpXlhCMioXfHvvV3uPCzCokrwEfnmC-P7-xdaRr3zHRhlQBjPCE4i0j4FPJaReFVmvk9je-6DnVXwOnRav_cMSI1EtruvbMZM4aq0O_u2_9YgOhChduE-eNZe4kYQVt6pF72YTnSX-mPN-rNUkln7sCe5xGlDDw29NnQwtyjrA8Gpa9GjxMT7JlUNcv70g8ytdhwPHlhoblq2ssdHNlxAha2016xTNT0WlxcmPyJKJjyLyyO6CZYkHZsLvwarkK-MYqAuI

### referrerId=10.00
GET https://skorohoda.plentymarkets-cloud02.com/rest/orders?externalOrderId=000000044,000000045
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZWQ3ZmRiZTQxNmI2MmZkYjBmZjgyMDM0YjExYWYyM2JmNDdlNWE1ZTNlNzIwOTQzMzM3ZGVlMjdhODlkNzIwYzQ2MGMwY2I4MTZlYTc4OWQiLCJpYXQiOjE2MTE4MzI1MDQsIm5iZiI6MTYxMTgzMjUwNCwiZXhwIjoxNjExOTE4OTA0LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.NngsWVP8_yC7oy0j02EBiZL3o7iaPALabhqE1zzTgqoOQ_k0YITDUWt4DlB_7MHSfYr1SNxdpz5SjPdvw-sxX7nQkVWiYuw4OzvJFxgX3J9aHbFteN5-CX_XRUwEhx0xK4E7dklNG8Mmgl5Db6LLL7jSljQTdQf-wcjK00xL4qb_aGYTJB8hCFokdUwAphwbNgfefQHyfM3ui-erOZrelbDpU9bzI3gcwyZIeb5lLZmkxVeVnYnl9T3oZ6a1iobAdRJ_k34aEnAzRWHTIVTE1DQJtOBbQ2Fypslpthd4yO2aB8FhpZc67nvE5exD6cWGszUPUh9lG7rxEfJqqAQY0fR264IBTM4hG_L8Rvp9tmcytBT_etnSZACViRypu_ZXP5MA3m2SJjLuSOSa7YQ6jsCYXhwN6q10R7emLFpXlhCMioXfHvvV3uPCzCokrwEfnmC-P7-xdaRr3zHRhlQBjPCE4i0j4FPJaReFVmvk9je-6DnVXwOnRav_cMSI1EtruvbMZM4aq0O_u2_9YgOhChduE-eNZe4kYQVt6pF72YTnSX-mPN-rNUkln7sCe5xGlDDw29NnQwtyjrA8Gpa9GjxMT7JlUNcv70g8ytdhwPHlhoblq2ssdHNlxAha2016xTNT0WlxcmPyJKJjyLyyO6CZYkHZsLvwarkK-MYqAuI
