###
GET https://skorohoda.plentymarkets-cloud02.com/rest/orders/6653/addresses/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNDdhNjViYTg4YzU2YWZkNDMwZmNmN2Y1OGM1YmIzMmY0MTBjMGNiNGFlNWY5MThmYTg3ZTg0ODg2NTBlNzMzMWI3ZWNjOWJlZWM1OGJmNzgiLCJpYXQiOjE2NDQyMTU4MjcsIm5iZiI6MTY0NDIxNTgyNywiZXhwIjoxNjQ0MzAyMjI3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.CpKhYHX8kJwi-xG4sy-iyAWpWHFzTOclI2IoMQMb1ZHJ2HbZZGZYhSNVHZp2f92ouqzKwVFFG4yCrrfvHM8rKnlkhAgXO82fVfweNQ60OSzOYu-r0ztMJoVP30cDpqtK6oHdqgIPMCAtjIrY1xx_NqqETgH2wumVW6gieZCzgUwRsBY3zZimjwLTxPyF50SdoVMtgelEnIO1E8CknffkxIQExDikomqAutx4TtEITSOW1tKL-SUZoaYxYU2MM_yX1XC2luoWomYGKbuKyUsbcxwAbTRIXPZUdUHtleKLtvHmY8JxwSueEU77y7fxg-QC4Y31NvgrRd4VLCFsKtyjphhCpEfuWn_tsIzOwNRNKj1HNXAnbJ3AqTLC1ZizwBlknolrn8uAHq9JEQ1OKBKZuQ9k8VFthJmTQkrdgb-IZzMKmkYIrUQqOUPRgQGajUm3Xz4qPaFANEpaycaS_Ndls5ieVZvxhBvS_bJ-jdRMM2rW2lh0Ox_05DVlxxnWU8PwE-hbCtoAPitwLrDOaXnpHgfKAHmnqHfj0A7kTmKMGt0NRwkgKKUAm-TnsAq_OQiQdPgwNk_J6AvQpoRtvOonXTdJzG67K08jghDva5VhqJQ_c14RmKhwBJUnuVt6l1JfKFr2i7nYvZMVMe4i8R3F1Wrb4oUlRkAM-4XzyTOCx_g

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/orders/6653/addresses/32
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNDdhNjViYTg4YzU2YWZkNDMwZmNmN2Y1OGM1YmIzMmY0MTBjMGNiNGFlNWY5MThmYTg3ZTg0ODg2NTBlNzMzMWI3ZWNjOWJlZWM1OGJmNzgiLCJpYXQiOjE2NDQyMTU4MjcsIm5iZiI6MTY0NDIxNTgyNywiZXhwIjoxNjQ0MzAyMjI3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.CpKhYHX8kJwi-xG4sy-iyAWpWHFzTOclI2IoMQMb1ZHJ2HbZZGZYhSNVHZp2f92ouqzKwVFFG4yCrrfvHM8rKnlkhAgXO82fVfweNQ60OSzOYu-r0ztMJoVP30cDpqtK6oHdqgIPMCAtjIrY1xx_NqqETgH2wumVW6gieZCzgUwRsBY3zZimjwLTxPyF50SdoVMtgelEnIO1E8CknffkxIQExDikomqAutx4TtEITSOW1tKL-SUZoaYxYU2MM_yX1XC2luoWomYGKbuKyUsbcxwAbTRIXPZUdUHtleKLtvHmY8JxwSueEU77y7fxg-QC4Y31NvgrRd4VLCFsKtyjphhCpEfuWn_tsIzOwNRNKj1HNXAnbJ3AqTLC1ZizwBlknolrn8uAHq9JEQ1OKBKZuQ9k8VFthJmTQkrdgb-IZzMKmkYIrUQqOUPRgQGajUm3Xz4qPaFANEpaycaS_Ndls5ieVZvxhBvS_bJ-jdRMM2rW2lh0Ox_05DVlxxnWU8PwE-hbCtoAPitwLrDOaXnpHgfKAHmnqHfj0A7kTmKMGt0NRwkgKKUAm-TnsAq_OQiQdPgwNk_J6AvQpoRtvOonXTdJzG67K08jghDva5VhqJQ_c14RmKhwBJUnuVt6l1JfKFr2i7nYvZMVMe4i8R3F1Wrb4oUlRkAM-4XzyTOCx_g

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/accounts/addresses/1008
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNDdhNjViYTg4YzU2YWZkNDMwZmNmN2Y1OGM1YmIzMmY0MTBjMGNiNGFlNWY5MThmYTg3ZTg0ODg2NTBlNzMzMWI3ZWNjOWJlZWM1OGJmNzgiLCJpYXQiOjE2NDQyMTU4MjcsIm5iZiI6MTY0NDIxNTgyNywiZXhwIjoxNjQ0MzAyMjI3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.CpKhYHX8kJwi-xG4sy-iyAWpWHFzTOclI2IoMQMb1ZHJ2HbZZGZYhSNVHZp2f92ouqzKwVFFG4yCrrfvHM8rKnlkhAgXO82fVfweNQ60OSzOYu-r0ztMJoVP30cDpqtK6oHdqgIPMCAtjIrY1xx_NqqETgH2wumVW6gieZCzgUwRsBY3zZimjwLTxPyF50SdoVMtgelEnIO1E8CknffkxIQExDikomqAutx4TtEITSOW1tKL-SUZoaYxYU2MM_yX1XC2luoWomYGKbuKyUsbcxwAbTRIXPZUdUHtleKLtvHmY8JxwSueEU77y7fxg-QC4Y31NvgrRd4VLCFsKtyjphhCpEfuWn_tsIzOwNRNKj1HNXAnbJ3AqTLC1ZizwBlknolrn8uAHq9JEQ1OKBKZuQ9k8VFthJmTQkrdgb-IZzMKmkYIrUQqOUPRgQGajUm3Xz4qPaFANEpaycaS_Ndls5ieVZvxhBvS_bJ-jdRMM2rW2lh0Ox_05DVlxxnWU8PwE-hbCtoAPitwLrDOaXnpHgfKAHmnqHfj0A7kTmKMGt0NRwkgKKUAm-TnsAq_OQiQdPgwNk_J6AvQpoRtvOonXTdJzG67K08jghDva5VhqJQ_c14RmKhwBJUnuVt6l1JfKFr2i7nYvZMVMe4i8R3F1Wrb4oUlRkAM-4XzyTOCx_g


###
POST https://skorohoda.plentymarkets-cloud02.com/rest/orders/addresses
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNDdhNjViYTg4YzU2YWZkNDMwZmNmN2Y1OGM1YmIzMmY0MTBjMGNiNGFlNWY5MThmYTg3ZTg0ODg2NTBlNzMzMWI3ZWNjOWJlZWM1OGJmNzgiLCJpYXQiOjE2NDQyMTU4MjcsIm5iZiI6MTY0NDIxNTgyNywiZXhwIjoxNjQ0MzAyMjI3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.CpKhYHX8kJwi-xG4sy-iyAWpWHFzTOclI2IoMQMb1ZHJ2HbZZGZYhSNVHZp2f92ouqzKwVFFG4yCrrfvHM8rKnlkhAgXO82fVfweNQ60OSzOYu-r0ztMJoVP30cDpqtK6oHdqgIPMCAtjIrY1xx_NqqETgH2wumVW6gieZCzgUwRsBY3zZimjwLTxPyF50SdoVMtgelEnIO1E8CknffkxIQExDikomqAutx4TtEITSOW1tKL-SUZoaYxYU2MM_yX1XC2luoWomYGKbuKyUsbcxwAbTRIXPZUdUHtleKLtvHmY8JxwSueEU77y7fxg-QC4Y31NvgrRd4VLCFsKtyjphhCpEfuWn_tsIzOwNRNKj1HNXAnbJ3AqTLC1ZizwBlknolrn8uAHq9JEQ1OKBKZuQ9k8VFthJmTQkrdgb-IZzMKmkYIrUQqOUPRgQGajUm3Xz4qPaFANEpaycaS_Ndls5ieVZvxhBvS_bJ-jdRMM2rW2lh0Ox_05DVlxxnWU8PwE-hbCtoAPitwLrDOaXnpHgfKAHmnqHfj0A7kTmKMGt0NRwkgKKUAm-TnsAq_OQiQdPgwNk_J6AvQpoRtvOonXTdJzG67K08jghDva5VhqJQ_c14RmKhwBJUnuVt6l1JfKFr2i7nYvZMVMe4i8R3F1Wrb4oUlRkAM-4XzyTOCx_g

{
    "orderId": 3857,
    "typeId": 1,
    "addressId": 959
}

