###
GET https://skorohoda.plentymarkets-cloud02.com/rest/orders/shipping/countries
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDA1YjRkYTBiMzA3OGU1NWYxZWJlYzljZWVhY2M3ZDk0ZTFhODJhZTU3NDQ0OTQwYzU5NjRmZTU5NWIzMjI0NDA2NjVjZDIwOWZiNTBlYjYiLCJpYXQiOjE2NDUxODk1NDcsIm5iZiI6MTY0NTE4OTU0NywiZXhwIjoxNjQ1Mjc1OTQ3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.QLz4vdlgdpE_AwbfVz5cpIj5yZ2vtyST3KG2-FvSNO4Wm6r0fDiZdaMZzNYQQ11z5KEaCZoi6OCLFIv4Bd7wkoNvrNNFv1fWmzJxv3SxRU9HdURpjiptwh-6eB1LzQNfexcyyhDSLrwNk3KwrV9gzpbdEN-oLbVP_uOcjXHe7Fh-K6WzFQU36ZOotnkmRZH7bMyEUg-AXX2_4sFGNDuOCBQXZ-XUSyRnO7lE8d4tazUjiNI-_D7yte2ZyNl9WlLrgazfvHCK92e8FrCyt72mdE2hRxm_ceg63dgDAj6PzfP4-GF3-fbvDVByLZFIEu7uKWnH-2h7ur6QGpPX9lpxzfefo6SasuCAE9HJ_XIM2QCzwHTJqUZJVo2lmVlTWbuVD78D7yA-7wxWkWM08OgcgNv7P7kzxPM4qmvDH3vANh3UnIiaBa-R0czgCruSlsgzMLgMOW4ySTHGmZSD_B8eTvPxMD6rtn4QZFPPI5F74P8p70q0srBsO-AjhnkYGI20h4F3uxSH1JzjD8u7d8Dzxu23AIwNqMdgyLx2Zv9Ar5cjNMLcMEESC8w4LgsJyFYu6YY2gjHtaeulg5HDtT6np7jyVGphlFMlE3gXv2sNwtla6r2Pjd-yRe067YXngk_6IQU_R0GdeurtjydJYxMDWh7NcfmPjykiuCbcD-6giPU

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/orders/shipping/countries?with=states
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDA1YjRkYTBiMzA3OGU1NWYxZWJlYzljZWVhY2M3ZDk0ZTFhODJhZTU3NDQ0OTQwYzU5NjRmZTU5NWIzMjI0NDA2NjVjZDIwOWZiNTBlYjYiLCJpYXQiOjE2NDUxODk1NDcsIm5iZiI6MTY0NTE4OTU0NywiZXhwIjoxNjQ1Mjc1OTQ3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.QLz4vdlgdpE_AwbfVz5cpIj5yZ2vtyST3KG2-FvSNO4Wm6r0fDiZdaMZzNYQQ11z5KEaCZoi6OCLFIv4Bd7wkoNvrNNFv1fWmzJxv3SxRU9HdURpjiptwh-6eB1LzQNfexcyyhDSLrwNk3KwrV9gzpbdEN-oLbVP_uOcjXHe7Fh-K6WzFQU36ZOotnkmRZH7bMyEUg-AXX2_4sFGNDuOCBQXZ-XUSyRnO7lE8d4tazUjiNI-_D7yte2ZyNl9WlLrgazfvHCK92e8FrCyt72mdE2hRxm_ceg63dgDAj6PzfP4-GF3-fbvDVByLZFIEu7uKWnH-2h7ur6QGpPX9lpxzfefo6SasuCAE9HJ_XIM2QCzwHTJqUZJVo2lmVlTWbuVD78D7yA-7wxWkWM08OgcgNv7P7kzxPM4qmvDH3vANh3UnIiaBa-R0czgCruSlsgzMLgMOW4ySTHGmZSD_B8eTvPxMD6rtn4QZFPPI5F74P8p70q0srBsO-AjhnkYGI20h4F3uxSH1JzjD8u7d8Dzxu23AIwNqMdgyLx2Zv9Ar5cjNMLcMEESC8w4LgsJyFYu6YY2gjHtaeulg5HDtT6np7jyVGphlFMlE3gXv2sNwtla6r2Pjd-yRe067YXngk_6IQU_R0GdeurtjydJYxMDWh7NcfmPjykiuCbcD-6giPU

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/orders/shipping/presets
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDA1YjRkYTBiMzA3OGU1NWYxZWJlYzljZWVhY2M3ZDk0ZTFhODJhZTU3NDQ0OTQwYzU5NjRmZTU5NWIzMjI0NDA2NjVjZDIwOWZiNTBlYjYiLCJpYXQiOjE2NDUxODk1NDcsIm5iZiI6MTY0NTE4OTU0NywiZXhwIjoxNjQ1Mjc1OTQ3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.QLz4vdlgdpE_AwbfVz5cpIj5yZ2vtyST3KG2-FvSNO4Wm6r0fDiZdaMZzNYQQ11z5KEaCZoi6OCLFIv4Bd7wkoNvrNNFv1fWmzJxv3SxRU9HdURpjiptwh-6eB1LzQNfexcyyhDSLrwNk3KwrV9gzpbdEN-oLbVP_uOcjXHe7Fh-K6WzFQU36ZOotnkmRZH7bMyEUg-AXX2_4sFGNDuOCBQXZ-XUSyRnO7lE8d4tazUjiNI-_D7yte2ZyNl9WlLrgazfvHCK92e8FrCyt72mdE2hRxm_ceg63dgDAj6PzfP4-GF3-fbvDVByLZFIEu7uKWnH-2h7ur6QGpPX9lpxzfefo6SasuCAE9HJ_XIM2QCzwHTJqUZJVo2lmVlTWbuVD78D7yA-7wxWkWM08OgcgNv7P7kzxPM4qmvDH3vANh3UnIiaBa-R0czgCruSlsgzMLgMOW4ySTHGmZSD_B8eTvPxMD6rtn4QZFPPI5F74P8p70q0srBsO-AjhnkYGI20h4F3uxSH1JzjD8u7d8Dzxu23AIwNqMdgyLx2Zv9Ar5cjNMLcMEESC8w4LgsJyFYu6YY2gjHtaeulg5HDtT6np7jyVGphlFMlE3gXv2sNwtla6r2Pjd-yRe067YXngk_6IQU_R0GdeurtjydJYxMDWh7NcfmPjykiuCbcD-6giPU


