### PROPERTY TYPES
GET https://skorohoda.plentymarkets-cloud02.com/rest/orders/properties/types
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZTQ3ZjVmYmI1OGI0ODhkYWQ1YmUyOGQ3M2VmNTU4NDU2OGYyNjFhOTM0YjBkYzIwOTMwN2FkMGFlYTUxNjBlYmRlZDQzYzk0ZTgyNDAwNjkiLCJpYXQiOjE2OTM5MjY3NTQuNTM2LCJuYmYiOjE2OTM5MjY3NTQuNTM2LCJleHAiOjE2OTQwMTMxNTQuNTIzNSwic3ViIjoiNiIsInNjb3BlcyI6WyIqIl19.WukVdqCTvTOmzUPhdqPxYAKKM7wxsIO5GxCBAhtnqkizCy8H3n5YwOtbiipEa25QDc0KuoAqldIMLC7cVLazjc8LsXPPO98Bzyp4maQWIfPPAqHSOb-3fXwq6bY0aw3LHLzdHdpjrm_1zP7IwXoGLQG5h_RIu7IEyuFWS24GmqPcBdOJopn8wWBajA0RIygUX1Wk0NMs2lXLpBsVRDZ3DtiRi7VulJF5XL-1o1H7INPZTHSZYxqzV1pUxDaD3zI40HDFCQMioMbo8uFKtX71cUPtrp-uRzQds-1b8yecoeJfDvwTXYHSmwPt5Z15zGTlVyGaU33A2hVDDFppX4Rp6I3WqVQAHCEkI-sGUKSXlsTrsNcFlYo3Fq83g2PlSlva4-mVQ1XOwcrKiKGoImqKW38NA6nu3eBcg10Eq7lc5YY4SggMmZVvIwsMB0NrO0RqBwBAYyim-4h3UYZRej8ACicl42yIv6uAOZ09k-ciE4dRFkeSDbdgiZ9FrHtgLU7WI0GrhlxM_QmsGFHEdmmYQwJjA2Hukn1ok2mxd2ThyiM1TcVZTH5bRl2E2cI0edhSIhbgU8Y1eCJBS53lHGCbGqDngup76E4dii971czzD5IDR1qpqZLIMnfr7pz3tblvrcdDr8T8D-99k9bOVe8zFpVpG4MCMp_AS4zxaF3L8Co

### PROPERTY TYPES
GET https://skorohoda.plentymarkets-cloud02.com/rest/orders/items/properties/4
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZTQ3ZjVmYmI1OGI0ODhkYWQ1YmUyOGQ3M2VmNTU4NDU2OGYyNjFhOTM0YjBkYzIwOTMwN2FkMGFlYTUxNjBlYmRlZDQzYzk0ZTgyNDAwNjkiLCJpYXQiOjE2OTM5MjY3NTQuNTM2LCJuYmYiOjE2OTM5MjY3NTQuNTM2LCJleHAiOjE2OTQwMTMxNTQuNTIzNSwic3ViIjoiNiIsInNjb3BlcyI6WyIqIl19.WukVdqCTvTOmzUPhdqPxYAKKM7wxsIO5GxCBAhtnqkizCy8H3n5YwOtbiipEa25QDc0KuoAqldIMLC7cVLazjc8LsXPPO98Bzyp4maQWIfPPAqHSOb-3fXwq6bY0aw3LHLzdHdpjrm_1zP7IwXoGLQG5h_RIu7IEyuFWS24GmqPcBdOJopn8wWBajA0RIygUX1Wk0NMs2lXLpBsVRDZ3DtiRi7VulJF5XL-1o1H7INPZTHSZYxqzV1pUxDaD3zI40HDFCQMioMbo8uFKtX71cUPtrp-uRzQds-1b8yecoeJfDvwTXYHSmwPt5Z15zGTlVyGaU33A2hVDDFppX4Rp6I3WqVQAHCEkI-sGUKSXlsTrsNcFlYo3Fq83g2PlSlva4-mVQ1XOwcrKiKGoImqKW38NA6nu3eBcg10Eq7lc5YY4SggMmZVvIwsMB0NrO0RqBwBAYyim-4h3UYZRej8ACicl42yIv6uAOZ09k-ciE4dRFkeSDbdgiZ9FrHtgLU7WI0GrhlxM_QmsGFHEdmmYQwJjA2Hukn1ok2mxd2ThyiM1TcVZTH5bRl2E2cI0edhSIhbgU8Y1eCJBS53lHGCbGqDngup76E4dii971czzD5IDR1qpqZLIMnfr7pz3tblvrcdDr8T8D-99k9bOVe8zFpVpG4MCMp_AS4zxaF3L8Co

###
POST https://skorohoda.plentymarkets-cloud02.com/rest/orders/properties/types
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZTQ3ZjVmYmI1OGI0ODhkYWQ1YmUyOGQ3M2VmNTU4NDU2OGYyNjFhOTM0YjBkYzIwOTMwN2FkMGFlYTUxNjBlYmRlZDQzYzk0ZTgyNDAwNjkiLCJpYXQiOjE2OTM5MjY3NTQuNTM2LCJuYmYiOjE2OTM5MjY3NTQuNTM2LCJleHAiOjE2OTQwMTMxNTQuNTIzNSwic3ViIjoiNiIsInNjb3BlcyI6WyIqIl19.WukVdqCTvTOmzUPhdqPxYAKKM7wxsIO5GxCBAhtnqkizCy8H3n5YwOtbiipEa25QDc0KuoAqldIMLC7cVLazjc8LsXPPO98Bzyp4maQWIfPPAqHSOb-3fXwq6bY0aw3LHLzdHdpjrm_1zP7IwXoGLQG5h_RIu7IEyuFWS24GmqPcBdOJopn8wWBajA0RIygUX1Wk0NMs2lXLpBsVRDZ3DtiRi7VulJF5XL-1o1H7INPZTHSZYxqzV1pUxDaD3zI40HDFCQMioMbo8uFKtX71cUPtrp-uRzQds-1b8yecoeJfDvwTXYHSmwPt5Z15zGTlVyGaU33A2hVDDFppX4Rp6I3WqVQAHCEkI-sGUKSXlsTrsNcFlYo3Fq83g2PlSlva4-mVQ1XOwcrKiKGoImqKW38NA6nu3eBcg10Eq7lc5YY4SggMmZVvIwsMB0NrO0RqBwBAYyim-4h3UYZRej8ACicl42yIv6uAOZ09k-ciE4dRFkeSDbdgiZ9FrHtgLU7WI0GrhlxM_QmsGFHEdmmYQwJjA2Hukn1ok2mxd2ThyiM1TcVZTH5bRl2E2cI0edhSIhbgU8Y1eCJBS53lHGCbGqDngup76E4dii971czzD5IDR1qpqZLIMnfr7pz3tblvrcdDr8T8D-99k9bOVe8zFpVpG4MCMp_AS4zxaF3L8Co

{
    "position": 20,
    "cast": "numeric",
    "names": [
        {
            "lang": "en",
            "name": "test numeric 0001"
        }
    ]
}

###
DELETE https://skorohoda.plentymarkets-cloud02.com/rest/orders/properties/types/1052
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZTQ3ZjVmYmI1OGI0ODhkYWQ1YmUyOGQ3M2VmNTU4NDU2OGYyNjFhOTM0YjBkYzIwOTMwN2FkMGFlYTUxNjBlYmRlZDQzYzk0ZTgyNDAwNjkiLCJpYXQiOjE2OTM5MjY3NTQuNTM2LCJuYmYiOjE2OTM5MjY3NTQuNTM2LCJleHAiOjE2OTQwMTMxNTQuNTIzNSwic3ViIjoiNiIsInNjb3BlcyI6WyIqIl19.WukVdqCTvTOmzUPhdqPxYAKKM7wxsIO5GxCBAhtnqkizCy8H3n5YwOtbiipEa25QDc0KuoAqldIMLC7cVLazjc8LsXPPO98Bzyp4maQWIfPPAqHSOb-3fXwq6bY0aw3LHLzdHdpjrm_1zP7IwXoGLQG5h_RIu7IEyuFWS24GmqPcBdOJopn8wWBajA0RIygUX1Wk0NMs2lXLpBsVRDZ3DtiRi7VulJF5XL-1o1H7INPZTHSZYxqzV1pUxDaD3zI40HDFCQMioMbo8uFKtX71cUPtrp-uRzQds-1b8yecoeJfDvwTXYHSmwPt5Z15zGTlVyGaU33A2hVDDFppX4Rp6I3WqVQAHCEkI-sGUKSXlsTrsNcFlYo3Fq83g2PlSlva4-mVQ1XOwcrKiKGoImqKW38NA6nu3eBcg10Eq7lc5YY4SggMmZVvIwsMB0NrO0RqBwBAYyim-4h3UYZRej8ACicl42yIv6uAOZ09k-ciE4dRFkeSDbdgiZ9FrHtgLU7WI0GrhlxM_QmsGFHEdmmYQwJjA2Hukn1ok2mxd2ThyiM1TcVZTH5bRl2E2cI0edhSIhbgU8Y1eCJBS53lHGCbGqDngup76E4dii971czzD5IDR1qpqZLIMnfr7pz3tblvrcdDr8T8D-99k9bOVe8zFpVpG4MCMp_AS4zxaF3L8Co
