###
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations?ids=34464&with=variationBarcodes
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYjAzMWJlNzhhYjA5OWNhYjdkMGFiNzUzMDI1NDc0Y2RlMjVjZTY4Y2RiYTdmZjk4ZTE2ZGU0MDkyMGNlMWUzNWIwYjRhM2Y4ODI3YTUxNDEiLCJpYXQiOjE2MjI3ODQ1NTEsIm5iZiI6MTYyMjc4NDU1MSwiZXhwIjoxNjIyODcwOTUxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.kVx_4oZ06BwZzGOoyoFmHgrN9HG-LLJ7IvFavTFWIo3b5983osIx3HHjQP55MbSFkmmT5lYtx5QGt9YNzwWxxumZ6Tnl-hvmuA7tveClFUPgrJZ4FHfzz-76D2khZSrAYCTdn-14mgZ8qI5TYVlPxCWu9NiNtvh6MeAXWXm3zWJkuswq7odZXDDdv5SmqV7ZwK9M_Kxn8yDm2RclwOIZ1GQh7FxudWbJYKa4bj3wPEsA7FxsAawy4umQx43dffVXOsit8MNV80fcHwkQWW9B524o4KZmEDwce2f0IPORIHoWIcadm991dYgGblCIbJdOYKRxrABwsF1Lt5FU2aoO3pGkLH8qJlMV9bLBGh4GdSZcxR-rebJMSNk02ZSaKaCbRaBHmSUIZlaSx7g1f5GOfIdDP2zFheUpEJX3ua9xBfoEo1jErtQlj-gJ43YfnQOQ36q6IuI-75VwIW-q01yyREwgQ9QS2bRgXARGBfLaWWgKtw9htcj_hkbsCubiNlxrRyN8h77PQNxgu-Q0TR2A46QxWDoskj4S8_aK4U7ixPXnZA4mMcLWR72uBsTXomR6CtiTCU7IMT0fZFzEE9UcFa6AGUy3Gl5W2FvkxSe6DIr5sgb3ozv-PkEVrT9-nz_95ttQ7eStmF-Sld-QtDjKUvAugGxew6q3Ms28cf6e_7o

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations?ids=34464&with=barcodes.barcode
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYjAzMWJlNzhhYjA5OWNhYjdkMGFiNzUzMDI1NDc0Y2RlMjVjZTY4Y2RiYTdmZjk4ZTE2ZGU0MDkyMGNlMWUzNWIwYjRhM2Y4ODI3YTUxNDEiLCJpYXQiOjE2MjI3ODQ1NTEsIm5iZiI6MTYyMjc4NDU1MSwiZXhwIjoxNjIyODcwOTUxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.kVx_4oZ06BwZzGOoyoFmHgrN9HG-LLJ7IvFavTFWIo3b5983osIx3HHjQP55MbSFkmmT5lYtx5QGt9YNzwWxxumZ6Tnl-hvmuA7tveClFUPgrJZ4FHfzz-76D2khZSrAYCTdn-14mgZ8qI5TYVlPxCWu9NiNtvh6MeAXWXm3zWJkuswq7odZXDDdv5SmqV7ZwK9M_Kxn8yDm2RclwOIZ1GQh7FxudWbJYKa4bj3wPEsA7FxsAawy4umQx43dffVXOsit8MNV80fcHwkQWW9B524o4KZmEDwce2f0IPORIHoWIcadm991dYgGblCIbJdOYKRxrABwsF1Lt5FU2aoO3pGkLH8qJlMV9bLBGh4GdSZcxR-rebJMSNk02ZSaKaCbRaBHmSUIZlaSx7g1f5GOfIdDP2zFheUpEJX3ua9xBfoEo1jErtQlj-gJ43YfnQOQ36q6IuI-75VwIW-q01yyREwgQ9QS2bRgXARGBfLaWWgKtw9htcj_hkbsCubiNlxrRyN8h77PQNxgu-Q0TR2A46QxWDoskj4S8_aK4U7ixPXnZA4mMcLWR72uBsTXomR6CtiTCU7IMT0fZFzEE9UcFa6AGUy3Gl5W2FvkxSe6DIr5sgb3ozv-PkEVrT9-nz_95ttQ7eStmF-Sld-QtDjKUvAugGxew6q3Ms28cf6e_7o
