###
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMjhlYmY1ZmU5NjExYmZhZWMxYjQ3ODI2NTIwNTIxYjZkMzlhMGM3ODAyNjIwM2I3YjE3ZjE1NzJjZmJmYWE4OGY3ODcyNGU2YmZhZDMwOTIiLCJpYXQiOjE2MzIzNzM3MzEsIm5iZiI6MTYzMjM3MzczMSwiZXhwIjoxNjMyNDYwMTMxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.wXnNhRW7BSAbjp9anJUdrn_6F-okFbA_0GUsQqwRcL5SPTXuXIRfstxxGQU0BXn4blyr3qW-_zw1j75YWo_9GM9UydDaZpATE0SlHQ6K_g3lTIAz4ZmWoDiG5o0hCgtKkkUbbwws75eOFu_72FmsLHK14TxW2F1lCIyb2g-DvnDRgwbPOPW7iqI-ubb4wD3U4xvXXTi0--p4-DatirtM9nUXe-ZsO9dJMV30z-a9O5i1nPI2Q3_8QCguhSm5rcJWPsnGvQiU3fA9hz-61HhnbJ6OixUULIjPtFszVjwdryZgqXTDUpSwIVvZFkC7xtQ_RrnHbA2o4mVc_q9I0q5vhE4ZBdm6BJsdJUhNWxBlMdphqjRgELD-P-QDkuplJKXa5l0rqBdHI398FGGWDB1IsdLNORduklvtVVdeBt6k08AXf0pYajrj-xnD3ZByXKOBz2dbX_BM43z7HeWKNqVUSoTP0S4oQ3Fj470BjbHKPAy6NnODs7kP4TXsP82Qkcj8MkoA1fkqTN7_npUUe55fVZyrL35IqykIQyBzvHTxawDEUIBuKXeS3HonJ3KnawCEQmrhN5t4sE-1ZKQOQz8Uu2rJ8cG0ImwojfIBwSjzbwriaRFu7-6ZBUhPuV9XODv2eRxQN26tW3FSVHssTVfi3Ix4sjLDynguetPRH8WlxTU

### 34494 / variation 34450
### --- additionalSkus,attributeValues,attributeValues.attribute,attributeValues.attributeValue,barcodes,barcodes.barcode,base,base.item,base.itemSerialNumber,base.feedback,base.characteristics,base.crossSelling,base.texts,base.availability',base.images,base.shippingProfiles,base.stock,base.stockStorageLocations,bundleComponents,categories,categories.category,categories.categoryBranch,clients,defaultCategories,defaultCategories.category,images,images.image,markets,marketIdentNumbers,salesPrices,salesPrices.salesPrice,skus,supplier,supplier.supplier,timestamps,warehouses,warehouses.warehouse,unit,unit.unit,tags,tags.tag,properties,properties.property
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations?ids=34494&with=base.item,properties,properties.property
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMjhlYmY1ZmU5NjExYmZhZWMxYjQ3ODI2NTIwNTIxYjZkMzlhMGM3ODAyNjIwM2I3YjE3ZjE1NzJjZmJmYWE4OGY3ODcyNGU2YmZhZDMwOTIiLCJpYXQiOjE2MzIzNzM3MzEsIm5iZiI6MTYzMjM3MzczMSwiZXhwIjoxNjMyNDYwMTMxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.wXnNhRW7BSAbjp9anJUdrn_6F-okFbA_0GUsQqwRcL5SPTXuXIRfstxxGQU0BXn4blyr3qW-_zw1j75YWo_9GM9UydDaZpATE0SlHQ6K_g3lTIAz4ZmWoDiG5o0hCgtKkkUbbwws75eOFu_72FmsLHK14TxW2F1lCIyb2g-DvnDRgwbPOPW7iqI-ubb4wD3U4xvXXTi0--p4-DatirtM9nUXe-ZsO9dJMV30z-a9O5i1nPI2Q3_8QCguhSm5rcJWPsnGvQiU3fA9hz-61HhnbJ6OixUULIjPtFszVjwdryZgqXTDUpSwIVvZFkC7xtQ_RrnHbA2o4mVc_q9I0q5vhE4ZBdm6BJsdJUhNWxBlMdphqjRgELD-P-QDkuplJKXa5l0rqBdHI398FGGWDB1IsdLNORduklvtVVdeBt6k08AXf0pYajrj-xnD3ZByXKOBz2dbX_BM43z7HeWKNqVUSoTP0S4oQ3Fj470BjbHKPAy6NnODs7kP4TXsP82Qkcj8MkoA1fkqTN7_npUUe55fVZyrL35IqykIQyBzvHTxawDEUIBuKXeS3HonJ3KnawCEQmrhN5t4sE-1ZKQOQz8Uu2rJ8cG0ImwojfIBwSjzbwriaRFu7-6ZBUhPuV9XODv2eRxQN26tW3FSVHssTVfi3Ix4sjLDynguetPRH8WlxTU

### 34494 / 34584
### --- additionalSkus,attributeValues,attributeValues.attribute,attributeValues.attributeValue,barcodes,barcodes.barcode,base,base.item,base.itemSerialNumber,base.feedback,base.characteristics,base.crossSelling,base.texts,base.availability',base.images,base.shippingProfiles,base.stock,base.stockStorageLocations,bundleComponents,categories,categories.category,categories.categoryBranch,clients,defaultCategories,defaultCategories.category,images,images.image,markets,marketIdentNumbers,salesPrices,salesPrices.salesPrice,skus,supplier,supplier.supplier,timestamps,warehouses,warehouses.warehouse,unit,unit.unit,tags,tags.tag,properties,properties.property
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations?ids=34584&with=properties,properties.property
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMjhlYmY1ZmU5NjExYmZhZWMxYjQ3ODI2NTIwNTIxYjZkMzlhMGM3ODAyNjIwM2I3YjE3ZjE1NzJjZmJmYWE4OGY3ODcyNGU2YmZhZDMwOTIiLCJpYXQiOjE2MzIzNzM3MzEsIm5iZiI6MTYzMjM3MzczMSwiZXhwIjoxNjMyNDYwMTMxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.wXnNhRW7BSAbjp9anJUdrn_6F-okFbA_0GUsQqwRcL5SPTXuXIRfstxxGQU0BXn4blyr3qW-_zw1j75YWo_9GM9UydDaZpATE0SlHQ6K_g3lTIAz4ZmWoDiG5o0hCgtKkkUbbwws75eOFu_72FmsLHK14TxW2F1lCIyb2g-DvnDRgwbPOPW7iqI-ubb4wD3U4xvXXTi0--p4-DatirtM9nUXe-ZsO9dJMV30z-a9O5i1nPI2Q3_8QCguhSm5rcJWPsnGvQiU3fA9hz-61HhnbJ6OixUULIjPtFszVjwdryZgqXTDUpSwIVvZFkC7xtQ_RrnHbA2o4mVc_q9I0q5vhE4ZBdm6BJsdJUhNWxBlMdphqjRgELD-P-QDkuplJKXa5l0rqBdHI398FGGWDB1IsdLNORduklvtVVdeBt6k08AXf0pYajrj-xnD3ZByXKOBz2dbX_BM43z7HeWKNqVUSoTP0S4oQ3Fj470BjbHKPAy6NnODs7kP4TXsP82Qkcj8MkoA1fkqTN7_npUUe55fVZyrL35IqykIQyBzvHTxawDEUIBuKXeS3HonJ3KnawCEQmrhN5t4sE-1ZKQOQz8Uu2rJ8cG0ImwojfIBwSjzbwriaRFu7-6ZBUhPuV9XODv2eRxQN26tW3FSVHssTVfi3Ix4sjLDynguetPRH8WlxTU
