###
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations/scroll
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGNkYTNhOGZmNmRjNWIyOGUwYzg5NGQwMmJlOTBiY2Y3ZDViNDlmYjdmMmFhOTgxMTNkZGE4NzdjZjZjZjM3NThmZjJlZTMzZjkzYjhkNzEiLCJpYXQiOjE2NjA1NTAzMjEuMDE0MywibmJmIjoxNjYwNTUwMzIxLjAxNDMsImV4cCI6MTY2MDYzNjcyMS4wMDQyLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.BPbyxuRl0osL9jJeKhShOKZuIa6w47n6XxpE90SBi267d-esmV5JnsY_AhqtJ_D6irefLkVC5Qj6m1AxPES_RCIl49HhyZryjl458j_hgMrOATZtUXdPmRwxRVmi9ohf-_g97zwXS_ckDGGk8Fyun5dYL8HwlWVYfCWCiIXujl0J88lt8gd1zx1tKco-QVSqNvldVOCgyaYNI2bUK3qRlCaBQsxwp6BWRXXK0Oyk5U101HUHkbHhZPylrm_Bm0NWRz2guoXK4NjB3al8MwCc00DDrPHJohCklniyh_XFZOrcMUAedoQpKZKvo4pYHrwU8vTSmUzDC84bJvKwRdPw2UrZWMq6TSTUnZiBWB_R2P3jU9dPcSk_q2PCqqwB-9P9GCm0iYOt_CF2eiYmrq4sSPK2CsqVRfdTh0Z4W3XdRucPO2_vydc3Lm9VO4fQvUKxEWmk7qSFpaoCmU3qWVXx_PP6RyMWdxWxAFDCzO5yNL9RWc7WEyYb7QI37Odrlkl8jZxPzTLxHkxoTY3elVfMTp30w1BRKscUOTJRjQpGiSypmwTo-g8MlzK75VT5cVvo2-GodaOCzD09x4Mp53kk7eV0P_CfNmH_-b95yeBN32Ic4yTSmHUp9zKDmaHVEbwdjPpBCsADwOuR9rWupGlliSRlLtcyMPjaxeZlEeVq1Ck

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations/scroll?cursor=WzM0NDQxXQ==
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGNkYTNhOGZmNmRjNWIyOGUwYzg5NGQwMmJlOTBiY2Y3ZDViNDlmYjdmMmFhOTgxMTNkZGE4NzdjZjZjZjM3NThmZjJlZTMzZjkzYjhkNzEiLCJpYXQiOjE2NjA1NTAzMjEuMDE0MywibmJmIjoxNjYwNTUwMzIxLjAxNDMsImV4cCI6MTY2MDYzNjcyMS4wMDQyLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.BPbyxuRl0osL9jJeKhShOKZuIa6w47n6XxpE90SBi267d-esmV5JnsY_AhqtJ_D6irefLkVC5Qj6m1AxPES_RCIl49HhyZryjl458j_hgMrOATZtUXdPmRwxRVmi9ohf-_g97zwXS_ckDGGk8Fyun5dYL8HwlWVYfCWCiIXujl0J88lt8gd1zx1tKco-QVSqNvldVOCgyaYNI2bUK3qRlCaBQsxwp6BWRXXK0Oyk5U101HUHkbHhZPylrm_Bm0NWRz2guoXK4NjB3al8MwCc00DDrPHJohCklniyh_XFZOrcMUAedoQpKZKvo4pYHrwU8vTSmUzDC84bJvKwRdPw2UrZWMq6TSTUnZiBWB_R2P3jU9dPcSk_q2PCqqwB-9P9GCm0iYOt_CF2eiYmrq4sSPK2CsqVRfdTh0Z4W3XdRucPO2_vydc3Lm9VO4fQvUKxEWmk7qSFpaoCmU3qWVXx_PP6RyMWdxWxAFDCzO5yNL9RWc7WEyYb7QI37Odrlkl8jZxPzTLxHkxoTY3elVfMTp30w1BRKscUOTJRjQpGiSypmwTo-g8MlzK75VT5cVvo2-GodaOCzD09x4Mp53kk7eV0P_CfNmH_-b95yeBN32Ic4yTSmHUp9zKDmaHVEbwdjPpBCsADwOuR9rWupGlliSRlLtcyMPjaxeZlEeVq1Ck

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations/scroll?itemsPerPage=2
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGNkYTNhOGZmNmRjNWIyOGUwYzg5NGQwMmJlOTBiY2Y3ZDViNDlmYjdmMmFhOTgxMTNkZGE4NzdjZjZjZjM3NThmZjJlZTMzZjkzYjhkNzEiLCJpYXQiOjE2NjA1NTAzMjEuMDE0MywibmJmIjoxNjYwNTUwMzIxLjAxNDMsImV4cCI6MTY2MDYzNjcyMS4wMDQyLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.BPbyxuRl0osL9jJeKhShOKZuIa6w47n6XxpE90SBi267d-esmV5JnsY_AhqtJ_D6irefLkVC5Qj6m1AxPES_RCIl49HhyZryjl458j_hgMrOATZtUXdPmRwxRVmi9ohf-_g97zwXS_ckDGGk8Fyun5dYL8HwlWVYfCWCiIXujl0J88lt8gd1zx1tKco-QVSqNvldVOCgyaYNI2bUK3qRlCaBQsxwp6BWRXXK0Oyk5U101HUHkbHhZPylrm_Bm0NWRz2guoXK4NjB3al8MwCc00DDrPHJohCklniyh_XFZOrcMUAedoQpKZKvo4pYHrwU8vTSmUzDC84bJvKwRdPw2UrZWMq6TSTUnZiBWB_R2P3jU9dPcSk_q2PCqqwB-9P9GCm0iYOt_CF2eiYmrq4sSPK2CsqVRfdTh0Z4W3XdRucPO2_vydc3Lm9VO4fQvUKxEWmk7qSFpaoCmU3qWVXx_PP6RyMWdxWxAFDCzO5yNL9RWc7WEyYb7QI37Odrlkl8jZxPzTLxHkxoTY3elVfMTp30w1BRKscUOTJRjQpGiSypmwTo-g8MlzK75VT5cVvo2-GodaOCzD09x4Mp53kk7eV0P_CfNmH_-b95yeBN32Ic4yTSmHUp9zKDmaHVEbwdjPpBCsADwOuR9rWupGlliSRlLtcyMPjaxeZlEeVq1Ck

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations/scroll?ids=34494&with=base
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGNkYTNhOGZmNmRjNWIyOGUwYzg5NGQwMmJlOTBiY2Y3ZDViNDlmYjdmMmFhOTgxMTNkZGE4NzdjZjZjZjM3NThmZjJlZTMzZjkzYjhkNzEiLCJpYXQiOjE2NjA1NTAzMjEuMDE0MywibmJmIjoxNjYwNTUwMzIxLjAxNDMsImV4cCI6MTY2MDYzNjcyMS4wMDQyLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.BPbyxuRl0osL9jJeKhShOKZuIa6w47n6XxpE90SBi267d-esmV5JnsY_AhqtJ_D6irefLkVC5Qj6m1AxPES_RCIl49HhyZryjl458j_hgMrOATZtUXdPmRwxRVmi9ohf-_g97zwXS_ckDGGk8Fyun5dYL8HwlWVYfCWCiIXujl0J88lt8gd1zx1tKco-QVSqNvldVOCgyaYNI2bUK3qRlCaBQsxwp6BWRXXK0Oyk5U101HUHkbHhZPylrm_Bm0NWRz2guoXK4NjB3al8MwCc00DDrPHJohCklniyh_XFZOrcMUAedoQpKZKvo4pYHrwU8vTSmUzDC84bJvKwRdPw2UrZWMq6TSTUnZiBWB_R2P3jU9dPcSk_q2PCqqwB-9P9GCm0iYOt_CF2eiYmrq4sSPK2CsqVRfdTh0Z4W3XdRucPO2_vydc3Lm9VO4fQvUKxEWmk7qSFpaoCmU3qWVXx_PP6RyMWdxWxAFDCzO5yNL9RWc7WEyYb7QI37Odrlkl8jZxPzTLxHkxoTY3elVfMTp30w1BRKscUOTJRjQpGiSypmwTo-g8MlzK75VT5cVvo2-GodaOCzD09x4Mp53kk7eV0P_CfNmH_-b95yeBN32Ic4yTSmHUp9zKDmaHVEbwdjPpBCsADwOuR9rWupGlliSRlLtcyMPjaxeZlEeVq1Ck

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations?ids=34449&with=base.item
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGNkYTNhOGZmNmRjNWIyOGUwYzg5NGQwMmJlOTBiY2Y3ZDViNDlmYjdmMmFhOTgxMTNkZGE4NzdjZjZjZjM3NThmZjJlZTMzZjkzYjhkNzEiLCJpYXQiOjE2NjA1NTAzMjEuMDE0MywibmJmIjoxNjYwNTUwMzIxLjAxNDMsImV4cCI6MTY2MDYzNjcyMS4wMDQyLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.BPbyxuRl0osL9jJeKhShOKZuIa6w47n6XxpE90SBi267d-esmV5JnsY_AhqtJ_D6irefLkVC5Qj6m1AxPES_RCIl49HhyZryjl458j_hgMrOATZtUXdPmRwxRVmi9ohf-_g97zwXS_ckDGGk8Fyun5dYL8HwlWVYfCWCiIXujl0J88lt8gd1zx1tKco-QVSqNvldVOCgyaYNI2bUK3qRlCaBQsxwp6BWRXXK0Oyk5U101HUHkbHhZPylrm_Bm0NWRz2guoXK4NjB3al8MwCc00DDrPHJohCklniyh_XFZOrcMUAedoQpKZKvo4pYHrwU8vTSmUzDC84bJvKwRdPw2UrZWMq6TSTUnZiBWB_R2P3jU9dPcSk_q2PCqqwB-9P9GCm0iYOt_CF2eiYmrq4sSPK2CsqVRfdTh0Z4W3XdRucPO2_vydc3Lm9VO4fQvUKxEWmk7qSFpaoCmU3qWVXx_PP6RyMWdxWxAFDCzO5yNL9RWc7WEyYb7QI37Odrlkl8jZxPzTLxHkxoTY3elVfMTp30w1BRKscUOTJRjQpGiSypmwTo-g8MlzK75VT5cVvo2-GodaOCzD09x4Mp53kk7eV0P_CfNmH_-b95yeBN32Ic4yTSmHUp9zKDmaHVEbwdjPpBCsADwOuR9rWupGlliSRlLtcyMPjaxeZlEeVq1Ck

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations?ids=34494&with=base.texts
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGNkYTNhOGZmNmRjNWIyOGUwYzg5NGQwMmJlOTBiY2Y3ZDViNDlmYjdmMmFhOTgxMTNkZGE4NzdjZjZjZjM3NThmZjJlZTMzZjkzYjhkNzEiLCJpYXQiOjE2NjA1NTAzMjEuMDE0MywibmJmIjoxNjYwNTUwMzIxLjAxNDMsImV4cCI6MTY2MDYzNjcyMS4wMDQyLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.BPbyxuRl0osL9jJeKhShOKZuIa6w47n6XxpE90SBi267d-esmV5JnsY_AhqtJ_D6irefLkVC5Qj6m1AxPES_RCIl49HhyZryjl458j_hgMrOATZtUXdPmRwxRVmi9ohf-_g97zwXS_ckDGGk8Fyun5dYL8HwlWVYfCWCiIXujl0J88lt8gd1zx1tKco-QVSqNvldVOCgyaYNI2bUK3qRlCaBQsxwp6BWRXXK0Oyk5U101HUHkbHhZPylrm_Bm0NWRz2guoXK4NjB3al8MwCc00DDrPHJohCklniyh_XFZOrcMUAedoQpKZKvo4pYHrwU8vTSmUzDC84bJvKwRdPw2UrZWMq6TSTUnZiBWB_R2P3jU9dPcSk_q2PCqqwB-9P9GCm0iYOt_CF2eiYmrq4sSPK2CsqVRfdTh0Z4W3XdRucPO2_vydc3Lm9VO4fQvUKxEWmk7qSFpaoCmU3qWVXx_PP6RyMWdxWxAFDCzO5yNL9RWc7WEyYb7QI37Odrlkl8jZxPzTLxHkxoTY3elVfMTp30w1BRKscUOTJRjQpGiSypmwTo-g8MlzK75VT5cVvo2-GodaOCzD09x4Mp53kk7eV0P_CfNmH_-b95yeBN32Ic4yTSmHUp9zKDmaHVEbwdjPpBCsADwOuR9rWupGlliSRlLtcyMPjaxeZlEeVq1Ck

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations/scroll?ids=34494&with=base.item,base.crossSelling,base.texts,base.images
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGNkYTNhOGZmNmRjNWIyOGUwYzg5NGQwMmJlOTBiY2Y3ZDViNDlmYjdmMmFhOTgxMTNkZGE4NzdjZjZjZjM3NThmZjJlZTMzZjkzYjhkNzEiLCJpYXQiOjE2NjA1NTAzMjEuMDE0MywibmJmIjoxNjYwNTUwMzIxLjAxNDMsImV4cCI6MTY2MDYzNjcyMS4wMDQyLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.BPbyxuRl0osL9jJeKhShOKZuIa6w47n6XxpE90SBi267d-esmV5JnsY_AhqtJ_D6irefLkVC5Qj6m1AxPES_RCIl49HhyZryjl458j_hgMrOATZtUXdPmRwxRVmi9ohf-_g97zwXS_ckDGGk8Fyun5dYL8HwlWVYfCWCiIXujl0J88lt8gd1zx1tKco-QVSqNvldVOCgyaYNI2bUK3qRlCaBQsxwp6BWRXXK0Oyk5U101HUHkbHhZPylrm_Bm0NWRz2guoXK4NjB3al8MwCc00DDrPHJohCklniyh_XFZOrcMUAedoQpKZKvo4pYHrwU8vTSmUzDC84bJvKwRdPw2UrZWMq6TSTUnZiBWB_R2P3jU9dPcSk_q2PCqqwB-9P9GCm0iYOt_CF2eiYmrq4sSPK2CsqVRfdTh0Z4W3XdRucPO2_vydc3Lm9VO4fQvUKxEWmk7qSFpaoCmU3qWVXx_PP6RyMWdxWxAFDCzO5yNL9RWc7WEyYb7QI37Odrlkl8jZxPzTLxHkxoTY3elVfMTp30w1BRKscUOTJRjQpGiSypmwTo-g8MlzK75VT5cVvo2-GodaOCzD09x4Mp53kk7eV0P_CfNmH_-b95yeBN32Ic4yTSmHUp9zKDmaHVEbwdjPpBCsADwOuR9rWupGlliSRlLtcyMPjaxeZlEeVq1Ck

### additionalSkus,attributeValues,attributeValues.attribute,attributeValues.attributeValue,barcodes,barcodes.barcode,base,base.item,base.itemSerialNumber,base.feedback,base.characteristics,base.crossSelling,base.texts,base.availability',base.images,base.shippingProfiles,base.stock,base.stockStorageLocations,bundleComponents,categories,categories.category,categories.categoryBranch,clients,defaultCategories,defaultCategories.category,images,images.image,markets,marketIdentNumbers,salesPrices,salesPrices.salesPrice,skus,supplier,supplier.supplier,timestamps,warehouses,warehouses.warehouse,unit,unit.unit,tags,tags.tag,properties,properties.property
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations/scroll?cursor=WzMxMjU2XQ==
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGNkYTNhOGZmNmRjNWIyOGUwYzg5NGQwMmJlOTBiY2Y3ZDViNDlmYjdmMmFhOTgxMTNkZGE4NzdjZjZjZjM3NThmZjJlZTMzZjkzYjhkNzEiLCJpYXQiOjE2NjA1NTAzMjEuMDE0MywibmJmIjoxNjYwNTUwMzIxLjAxNDMsImV4cCI6MTY2MDYzNjcyMS4wMDQyLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.BPbyxuRl0osL9jJeKhShOKZuIa6w47n6XxpE90SBi267d-esmV5JnsY_AhqtJ_D6irefLkVC5Qj6m1AxPES_RCIl49HhyZryjl458j_hgMrOATZtUXdPmRwxRVmi9ohf-_g97zwXS_ckDGGk8Fyun5dYL8HwlWVYfCWCiIXujl0J88lt8gd1zx1tKco-QVSqNvldVOCgyaYNI2bUK3qRlCaBQsxwp6BWRXXK0Oyk5U101HUHkbHhZPylrm_Bm0NWRz2guoXK4NjB3al8MwCc00DDrPHJohCklniyh_XFZOrcMUAedoQpKZKvo4pYHrwU8vTSmUzDC84bJvKwRdPw2UrZWMq6TSTUnZiBWB_R2P3jU9dPcSk_q2PCqqwB-9P9GCm0iYOt_CF2eiYmrq4sSPK2CsqVRfdTh0Z4W3XdRucPO2_vydc3Lm9VO4fQvUKxEWmk7qSFpaoCmU3qWVXx_PP6RyMWdxWxAFDCzO5yNL9RWc7WEyYb7QI37Odrlkl8jZxPzTLxHkxoTY3elVfMTp30w1BRKscUOTJRjQpGiSypmwTo-g8MlzK75VT5cVvo2-GodaOCzD09x4Mp53kk7eV0P_CfNmH_-b95yeBN32Ic4yTSmHUp9zKDmaHVEbwdjPpBCsADwOuR9rWupGlliSRlLtcyMPjaxeZlEeVq1Ck

### 34494 / variation 34450
### --- additionalSkus,attributeValues,attributeValues.attribute,attributeValues.attributeValue,barcodes,barcodes.barcode,base,base.item,base.itemSerialNumber,base.feedback,base.characteristics,base.crossSelling,base.texts,base.availability',base.images,base.shippingProfiles,base.stock,base.stockStorageLocations,bundleComponents,categories,categories.category,categories.categoryBranch,clients,defaultCategories,defaultCategories.category,images,images.image,markets,marketIdentNumbers,salesPrices,salesPrices.salesPrice,skus,supplier,supplier.supplier,timestamps,warehouses,warehouses.warehouse,unit,unit.unit,tags,tags.tag,properties,properties.property
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations?ids=34450&with=additionalSkus,attributeValues,attributeValues.attribute,attributeValues.attributeValue,barcodes,barcodes.barcode,base,base.item,base.itemSerialNumber,base.feedback,base.characteristics,base.crossSelling,base.texts,base.availability',base.images,base.shippingProfiles,base.stock,base.stockStorageLocations,bundleComponents,categories,categories.category,categories.categoryBranch,clients,defaultCategories,defaultCategories.category,images,images.image,markets,marketIdentNumbers,salesPrices,salesPrices.salesPrice,skus,supplier,supplier.supplier,timestamps,warehouses,warehouses.warehouse,unit,unit.unit,tags,tags.tag,properties,properties.property,comments&itemsPerPage=10
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGNkYTNhOGZmNmRjNWIyOGUwYzg5NGQwMmJlOTBiY2Y3ZDViNDlmYjdmMmFhOTgxMTNkZGE4NzdjZjZjZjM3NThmZjJlZTMzZjkzYjhkNzEiLCJpYXQiOjE2NjA1NTAzMjEuMDE0MywibmJmIjoxNjYwNTUwMzIxLjAxNDMsImV4cCI6MTY2MDYzNjcyMS4wMDQyLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.BPbyxuRl0osL9jJeKhShOKZuIa6w47n6XxpE90SBi267d-esmV5JnsY_AhqtJ_D6irefLkVC5Qj6m1AxPES_RCIl49HhyZryjl458j_hgMrOATZtUXdPmRwxRVmi9ohf-_g97zwXS_ckDGGk8Fyun5dYL8HwlWVYfCWCiIXujl0J88lt8gd1zx1tKco-QVSqNvldVOCgyaYNI2bUK3qRlCaBQsxwp6BWRXXK0Oyk5U101HUHkbHhZPylrm_Bm0NWRz2guoXK4NjB3al8MwCc00DDrPHJohCklniyh_XFZOrcMUAedoQpKZKvo4pYHrwU8vTSmUzDC84bJvKwRdPw2UrZWMq6TSTUnZiBWB_R2P3jU9dPcSk_q2PCqqwB-9P9GCm0iYOt_CF2eiYmrq4sSPK2CsqVRfdTh0Z4W3XdRucPO2_vydc3Lm9VO4fQvUKxEWmk7qSFpaoCmU3qWVXx_PP6RyMWdxWxAFDCzO5yNL9RWc7WEyYb7QI37Odrlkl8jZxPzTLxHkxoTY3elVfMTp30w1BRKscUOTJRjQpGiSypmwTo-g8MlzK75VT5cVvo2-GodaOCzD09x4Mp53kk7eV0P_CfNmH_-b95yeBN32Ic4yTSmHUp9zKDmaHVEbwdjPpBCsADwOuR9rWupGlliSRlLtcyMPjaxeZlEeVq1Ck

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations?page=1&with=base.item,base.itemShippingProfiles,base.images
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGNkYTNhOGZmNmRjNWIyOGUwYzg5NGQwMmJlOTBiY2Y3ZDViNDlmYjdmMmFhOTgxMTNkZGE4NzdjZjZjZjM3NThmZjJlZTMzZjkzYjhkNzEiLCJpYXQiOjE2NjA1NTAzMjEuMDE0MywibmJmIjoxNjYwNTUwMzIxLjAxNDMsImV4cCI6MTY2MDYzNjcyMS4wMDQyLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.BPbyxuRl0osL9jJeKhShOKZuIa6w47n6XxpE90SBi267d-esmV5JnsY_AhqtJ_D6irefLkVC5Qj6m1AxPES_RCIl49HhyZryjl458j_hgMrOATZtUXdPmRwxRVmi9ohf-_g97zwXS_ckDGGk8Fyun5dYL8HwlWVYfCWCiIXujl0J88lt8gd1zx1tKco-QVSqNvldVOCgyaYNI2bUK3qRlCaBQsxwp6BWRXXK0Oyk5U101HUHkbHhZPylrm_Bm0NWRz2guoXK4NjB3al8MwCc00DDrPHJohCklniyh_XFZOrcMUAedoQpKZKvo4pYHrwU8vTSmUzDC84bJvKwRdPw2UrZWMq6TSTUnZiBWB_R2P3jU9dPcSk_q2PCqqwB-9P9GCm0iYOt_CF2eiYmrq4sSPK2CsqVRfdTh0Z4W3XdRucPO2_vydc3Lm9VO4fQvUKxEWmk7qSFpaoCmU3qWVXx_PP6RyMWdxWxAFDCzO5yNL9RWc7WEyYb7QI37Odrlkl8jZxPzTLxHkxoTY3elVfMTp30w1BRKscUOTJRjQpGiSypmwTo-g8MlzK75VT5cVvo2-GodaOCzD09x4Mp53kk7eV0P_CfNmH_-b95yeBN32Ic4yTSmHUp9zKDmaHVEbwdjPpBCsADwOuR9rWupGlliSRlLtcyMPjaxeZlEeVq1Ck

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations/scroll?with=additionalSkus%2CattributeValues%2Cbarcodes%2Ccategories%2Ccategories.categoryBranch%2Cbase%2Cbase.item%2Cbase.itemSerialNumber%2Cbase.feedback%2Cbase.crossSelling%2Cbase.texts%2Cbase.availability%2Cbase.images%2Cbase.shippingProfiles%2Cbase.stock%2Cbase.stockStorageLocations%2CbundleComponents%2Cclients%2CdefaultCategories%2Cimages%2Cmarkets%2CmarketIdentNumbers%2CsalesPrices%2Cskus%2Csupplier%2Cwarehouses%2Cunit%2Ctags%2Cproperties%2Ccomments
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGNkYTNhOGZmNmRjNWIyOGUwYzg5NGQwMmJlOTBiY2Y3ZDViNDlmYjdmMmFhOTgxMTNkZGE4NzdjZjZjZjM3NThmZjJlZTMzZjkzYjhkNzEiLCJpYXQiOjE2NjA1NTAzMjEuMDE0MywibmJmIjoxNjYwNTUwMzIxLjAxNDMsImV4cCI6MTY2MDYzNjcyMS4wMDQyLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.BPbyxuRl0osL9jJeKhShOKZuIa6w47n6XxpE90SBi267d-esmV5JnsY_AhqtJ_D6irefLkVC5Qj6m1AxPES_RCIl49HhyZryjl458j_hgMrOATZtUXdPmRwxRVmi9ohf-_g97zwXS_ckDGGk8Fyun5dYL8HwlWVYfCWCiIXujl0J88lt8gd1zx1tKco-QVSqNvldVOCgyaYNI2bUK3qRlCaBQsxwp6BWRXXK0Oyk5U101HUHkbHhZPylrm_Bm0NWRz2guoXK4NjB3al8MwCc00DDrPHJohCklniyh_XFZOrcMUAedoQpKZKvo4pYHrwU8vTSmUzDC84bJvKwRdPw2UrZWMq6TSTUnZiBWB_R2P3jU9dPcSk_q2PCqqwB-9P9GCm0iYOt_CF2eiYmrq4sSPK2CsqVRfdTh0Z4W3XdRucPO2_vydc3Lm9VO4fQvUKxEWmk7qSFpaoCmU3qWVXx_PP6RyMWdxWxAFDCzO5yNL9RWc7WEyYb7QI37Odrlkl8jZxPzTLxHkxoTY3elVfMTp30w1BRKscUOTJRjQpGiSypmwTo-g8MlzK75VT5cVvo2-GodaOCzD09x4Mp53kk7eV0P_CfNmH_-b95yeBN32Ic4yTSmHUp9zKDmaHVEbwdjPpBCsADwOuR9rWupGlliSRlLtcyMPjaxeZlEeVq1Ck





