###
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYTMwZTk5Njg1NmZjZGMyMGU3ZDVjOTUyYTJmMGRmZDBhMDFlMjVkZDhlMWY2NmJmMTllMGY0ZDliZDBiNTczZTNkYjVhODkyOGQxOGQ2NjEiLCJpYXQiOjE2OTI5NTg3MTUuMzU0NCwibmJmIjoxNjkyOTU4NzE1LjM1NDQsImV4cCI6MTY5MzA0NTExNS4zNDQxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.NcEldT8u6MRHsxMsjvAKnXLnLleIFK8Dw0D50eoFUXYn7qmOPlyYIaYoNl9laCIdHgNw278ba2Z7BxjnfSzp0BzjJUNBl_QkyZn4HULsVIdBYX-xL1byTDp-1lQTJRarFIzoyyi85SnNeIVXyq0Oad7m-jjHjc4CcU0Op6MgG55Fu6RiH-4gqeB3tNtfcuInMQp0TyZji6vjqcPc-fduKjFl62wCKkKS52wPgcad-UIE5ybkQu6l0N8qOS3kQnK6TXQGuHTMSDnXBK0foCSygcIiFADFCEoegl5JYlU600bsxTszgDbbJ_5UR3MSXdh0O7IZ7aAweAYREibT4K-I4vmUk73oMc_I-AuYrVTCabSBCXOpWrb2aYF_ydNYX09cctA04SADxYy8GzU1NNGrG4p875Vft6ELK0cRCPy_lhI493Xc6U1EWy7We2TxOpgD_5mrLLeW29bkB4lwKAyl_7dfYT9PeRypJMcu3spToRhT32OeACT_MzzU5Umtk0N2ozc5HoVb7wfJRK9K1MWaUyg2eGxb4vDD6rUF4MePzkWFUUg_LP3tnSAgJwpsPjLZ8u6rygerD-j4gXZI7gvMEZ7ql17h5w-ERliqWafW5co0e3iJ1C1XV8Q_D2Sa1q-HKZR2720wlBuT2EILxz4Kjfv8RBGhkV0YNloX_OxUecI

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations?ids=34595&with=base,categories
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYTMwZTk5Njg1NmZjZGMyMGU3ZDVjOTUyYTJmMGRmZDBhMDFlMjVkZDhlMWY2NmJmMTllMGY0ZDliZDBiNTczZTNkYjVhODkyOGQxOGQ2NjEiLCJpYXQiOjE2OTI5NTg3MTUuMzU0NCwibmJmIjoxNjkyOTU4NzE1LjM1NDQsImV4cCI6MTY5MzA0NTExNS4zNDQxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.NcEldT8u6MRHsxMsjvAKnXLnLleIFK8Dw0D50eoFUXYn7qmOPlyYIaYoNl9laCIdHgNw278ba2Z7BxjnfSzp0BzjJUNBl_QkyZn4HULsVIdBYX-xL1byTDp-1lQTJRarFIzoyyi85SnNeIVXyq0Oad7m-jjHjc4CcU0Op6MgG55Fu6RiH-4gqeB3tNtfcuInMQp0TyZji6vjqcPc-fduKjFl62wCKkKS52wPgcad-UIE5ybkQu6l0N8qOS3kQnK6TXQGuHTMSDnXBK0foCSygcIiFADFCEoegl5JYlU600bsxTszgDbbJ_5UR3MSXdh0O7IZ7aAweAYREibT4K-I4vmUk73oMc_I-AuYrVTCabSBCXOpWrb2aYF_ydNYX09cctA04SADxYy8GzU1NNGrG4p875Vft6ELK0cRCPy_lhI493Xc6U1EWy7We2TxOpgD_5mrLLeW29bkB4lwKAyl_7dfYT9PeRypJMcu3spToRhT32OeACT_MzzU5Umtk0N2ozc5HoVb7wfJRK9K1MWaUyg2eGxb4vDD6rUF4MePzkWFUUg_LP3tnSAgJwpsPjLZ8u6rygerD-j4gXZI7gvMEZ7ql17h5w-ERliqWafW5co0e3iJ1C1XV8Q_D2Sa1q-HKZR2720wlBuT2EILxz4Kjfv8RBGhkV0YNloX_OxUecI

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations?ids=34494&with=base.item
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYTMwZTk5Njg1NmZjZGMyMGU3ZDVjOTUyYTJmMGRmZDBhMDFlMjVkZDhlMWY2NmJmMTllMGY0ZDliZDBiNTczZTNkYjVhODkyOGQxOGQ2NjEiLCJpYXQiOjE2OTI5NTg3MTUuMzU0NCwibmJmIjoxNjkyOTU4NzE1LjM1NDQsImV4cCI6MTY5MzA0NTExNS4zNDQxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.NcEldT8u6MRHsxMsjvAKnXLnLleIFK8Dw0D50eoFUXYn7qmOPlyYIaYoNl9laCIdHgNw278ba2Z7BxjnfSzp0BzjJUNBl_QkyZn4HULsVIdBYX-xL1byTDp-1lQTJRarFIzoyyi85SnNeIVXyq0Oad7m-jjHjc4CcU0Op6MgG55Fu6RiH-4gqeB3tNtfcuInMQp0TyZji6vjqcPc-fduKjFl62wCKkKS52wPgcad-UIE5ybkQu6l0N8qOS3kQnK6TXQGuHTMSDnXBK0foCSygcIiFADFCEoegl5JYlU600bsxTszgDbbJ_5UR3MSXdh0O7IZ7aAweAYREibT4K-I4vmUk73oMc_I-AuYrVTCabSBCXOpWrb2aYF_ydNYX09cctA04SADxYy8GzU1NNGrG4p875Vft6ELK0cRCPy_lhI493Xc6U1EWy7We2TxOpgD_5mrLLeW29bkB4lwKAyl_7dfYT9PeRypJMcu3spToRhT32OeACT_MzzU5Umtk0N2ozc5HoVb7wfJRK9K1MWaUyg2eGxb4vDD6rUF4MePzkWFUUg_LP3tnSAgJwpsPjLZ8u6rygerD-j4gXZI7gvMEZ7ql17h5w-ERliqWafW5co0e3iJ1C1XV8Q_D2Sa1q-HKZR2720wlBuT2EILxz4Kjfv8RBGhkV0YNloX_OxUecI

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations?ids=34494&with=base.texts
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYTMwZTk5Njg1NmZjZGMyMGU3ZDVjOTUyYTJmMGRmZDBhMDFlMjVkZDhlMWY2NmJmMTllMGY0ZDliZDBiNTczZTNkYjVhODkyOGQxOGQ2NjEiLCJpYXQiOjE2OTI5NTg3MTUuMzU0NCwibmJmIjoxNjkyOTU4NzE1LjM1NDQsImV4cCI6MTY5MzA0NTExNS4zNDQxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.NcEldT8u6MRHsxMsjvAKnXLnLleIFK8Dw0D50eoFUXYn7qmOPlyYIaYoNl9laCIdHgNw278ba2Z7BxjnfSzp0BzjJUNBl_QkyZn4HULsVIdBYX-xL1byTDp-1lQTJRarFIzoyyi85SnNeIVXyq0Oad7m-jjHjc4CcU0Op6MgG55Fu6RiH-4gqeB3tNtfcuInMQp0TyZji6vjqcPc-fduKjFl62wCKkKS52wPgcad-UIE5ybkQu6l0N8qOS3kQnK6TXQGuHTMSDnXBK0foCSygcIiFADFCEoegl5JYlU600bsxTszgDbbJ_5UR3MSXdh0O7IZ7aAweAYREibT4K-I4vmUk73oMc_I-AuYrVTCabSBCXOpWrb2aYF_ydNYX09cctA04SADxYy8GzU1NNGrG4p875Vft6ELK0cRCPy_lhI493Xc6U1EWy7We2TxOpgD_5mrLLeW29bkB4lwKAyl_7dfYT9PeRypJMcu3spToRhT32OeACT_MzzU5Umtk0N2ozc5HoVb7wfJRK9K1MWaUyg2eGxb4vDD6rUF4MePzkWFUUg_LP3tnSAgJwpsPjLZ8u6rygerD-j4gXZI7gvMEZ7ql17h5w-ERliqWafW5co0e3iJ1C1XV8Q_D2Sa1q-HKZR2720wlBuT2EILxz4Kjfv8RBGhkV0YNloX_OxUecI

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations?ids=34494&with=base.item,base.crossSelling,base.texts,base.images
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYTMwZTk5Njg1NmZjZGMyMGU3ZDVjOTUyYTJmMGRmZDBhMDFlMjVkZDhlMWY2NmJmMTllMGY0ZDliZDBiNTczZTNkYjVhODkyOGQxOGQ2NjEiLCJpYXQiOjE2OTI5NTg3MTUuMzU0NCwibmJmIjoxNjkyOTU4NzE1LjM1NDQsImV4cCI6MTY5MzA0NTExNS4zNDQxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.NcEldT8u6MRHsxMsjvAKnXLnLleIFK8Dw0D50eoFUXYn7qmOPlyYIaYoNl9laCIdHgNw278ba2Z7BxjnfSzp0BzjJUNBl_QkyZn4HULsVIdBYX-xL1byTDp-1lQTJRarFIzoyyi85SnNeIVXyq0Oad7m-jjHjc4CcU0Op6MgG55Fu6RiH-4gqeB3tNtfcuInMQp0TyZji6vjqcPc-fduKjFl62wCKkKS52wPgcad-UIE5ybkQu6l0N8qOS3kQnK6TXQGuHTMSDnXBK0foCSygcIiFADFCEoegl5JYlU600bsxTszgDbbJ_5UR3MSXdh0O7IZ7aAweAYREibT4K-I4vmUk73oMc_I-AuYrVTCabSBCXOpWrb2aYF_ydNYX09cctA04SADxYy8GzU1NNGrG4p875Vft6ELK0cRCPy_lhI493Xc6U1EWy7We2TxOpgD_5mrLLeW29bkB4lwKAyl_7dfYT9PeRypJMcu3spToRhT32OeACT_MzzU5Umtk0N2ozc5HoVb7wfJRK9K1MWaUyg2eGxb4vDD6rUF4MePzkWFUUg_LP3tnSAgJwpsPjLZ8u6rygerD-j4gXZI7gvMEZ7ql17h5w-ERliqWafW5co0e3iJ1C1XV8Q_D2Sa1q-HKZR2720wlBuT2EILxz4Kjfv8RBGhkV0YNloX_OxUecI

### -- WITH: with=properties
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations?ids=34370&with=properties
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYTMwZTk5Njg1NmZjZGMyMGU3ZDVjOTUyYTJmMGRmZDBhMDFlMjVkZDhlMWY2NmJmMTllMGY0ZDliZDBiNTczZTNkYjVhODkyOGQxOGQ2NjEiLCJpYXQiOjE2OTI5NTg3MTUuMzU0NCwibmJmIjoxNjkyOTU4NzE1LjM1NDQsImV4cCI6MTY5MzA0NTExNS4zNDQxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.NcEldT8u6MRHsxMsjvAKnXLnLleIFK8Dw0D50eoFUXYn7qmOPlyYIaYoNl9laCIdHgNw278ba2Z7BxjnfSzp0BzjJUNBl_QkyZn4HULsVIdBYX-xL1byTDp-1lQTJRarFIzoyyi85SnNeIVXyq0Oad7m-jjHjc4CcU0Op6MgG55Fu6RiH-4gqeB3tNtfcuInMQp0TyZji6vjqcPc-fduKjFl62wCKkKS52wPgcad-UIE5ybkQu6l0N8qOS3kQnK6TXQGuHTMSDnXBK0foCSygcIiFADFCEoegl5JYlU600bsxTszgDbbJ_5UR3MSXdh0O7IZ7aAweAYREibT4K-I4vmUk73oMc_I-AuYrVTCabSBCXOpWrb2aYF_ydNYX09cctA04SADxYy8GzU1NNGrG4p875Vft6ELK0cRCPy_lhI493Xc6U1EWy7We2TxOpgD_5mrLLeW29bkB4lwKAyl_7dfYT9PeRypJMcu3spToRhT32OeACT_MzzU5Umtk0N2ozc5HoVb7wfJRK9K1MWaUyg2eGxb4vDD6rUF4MePzkWFUUg_LP3tnSAgJwpsPjLZ8u6rygerD-j4gXZI7gvMEZ7ql17h5w-ERliqWafW5co0e3iJ1C1XV8Q_D2Sa1q-HKZR2720wlBuT2EILxz4Kjfv8RBGhkV0YNloX_OxUecI

### -- updatedAt::: updatedAt=gte%3A2022-05-11T12%3A37%3A51%2B00%3A00
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations?updatedAt=gte:2022-05-11T12%3A37%3A17%2B01%3A00&with=base.item,timestamps
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYTMwZTk5Njg1NmZjZGMyMGU3ZDVjOTUyYTJmMGRmZDBhMDFlMjVkZDhlMWY2NmJmMTllMGY0ZDliZDBiNTczZTNkYjVhODkyOGQxOGQ2NjEiLCJpYXQiOjE2OTI5NTg3MTUuMzU0NCwibmJmIjoxNjkyOTU4NzE1LjM1NDQsImV4cCI6MTY5MzA0NTExNS4zNDQxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.NcEldT8u6MRHsxMsjvAKnXLnLleIFK8Dw0D50eoFUXYn7qmOPlyYIaYoNl9laCIdHgNw278ba2Z7BxjnfSzp0BzjJUNBl_QkyZn4HULsVIdBYX-xL1byTDp-1lQTJRarFIzoyyi85SnNeIVXyq0Oad7m-jjHjc4CcU0Op6MgG55Fu6RiH-4gqeB3tNtfcuInMQp0TyZji6vjqcPc-fduKjFl62wCKkKS52wPgcad-UIE5ybkQu6l0N8qOS3kQnK6TXQGuHTMSDnXBK0foCSygcIiFADFCEoegl5JYlU600bsxTszgDbbJ_5UR3MSXdh0O7IZ7aAweAYREibT4K-I4vmUk73oMc_I-AuYrVTCabSBCXOpWrb2aYF_ydNYX09cctA04SADxYy8GzU1NNGrG4p875Vft6ELK0cRCPy_lhI493Xc6U1EWy7We2TxOpgD_5mrLLeW29bkB4lwKAyl_7dfYT9PeRypJMcu3spToRhT32OeACT_MzzU5Umtk0N2ozc5HoVb7wfJRK9K1MWaUyg2eGxb4vDD6rUF4MePzkWFUUg_LP3tnSAgJwpsPjLZ8u6rygerD-j4gXZI7gvMEZ7ql17h5w-ERliqWafW5co0e3iJ1C1XV8Q_D2Sa1q-HKZR2720wlBuT2EILxz4Kjfv8RBGhkV0YNloX_OxUecI

### -- updatedAt::: itemUpdatedAt=gte%3A2022-05-11T12%3A37%3A51%2B00%3A00
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations?itemUpdatedAt=gte%3A2022-05-11T12%3A37%3A51%2B00%3A00&with=base.item,timestamps
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYTMwZTk5Njg1NmZjZGMyMGU3ZDVjOTUyYTJmMGRmZDBhMDFlMjVkZDhlMWY2NmJmMTllMGY0ZDliZDBiNTczZTNkYjVhODkyOGQxOGQ2NjEiLCJpYXQiOjE2OTI5NTg3MTUuMzU0NCwibmJmIjoxNjkyOTU4NzE1LjM1NDQsImV4cCI6MTY5MzA0NTExNS4zNDQxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.NcEldT8u6MRHsxMsjvAKnXLnLleIFK8Dw0D50eoFUXYn7qmOPlyYIaYoNl9laCIdHgNw278ba2Z7BxjnfSzp0BzjJUNBl_QkyZn4HULsVIdBYX-xL1byTDp-1lQTJRarFIzoyyi85SnNeIVXyq0Oad7m-jjHjc4CcU0Op6MgG55Fu6RiH-4gqeB3tNtfcuInMQp0TyZji6vjqcPc-fduKjFl62wCKkKS52wPgcad-UIE5ybkQu6l0N8qOS3kQnK6TXQGuHTMSDnXBK0foCSygcIiFADFCEoegl5JYlU600bsxTszgDbbJ_5UR3MSXdh0O7IZ7aAweAYREibT4K-I4vmUk73oMc_I-AuYrVTCabSBCXOpWrb2aYF_ydNYX09cctA04SADxYy8GzU1NNGrG4p875Vft6ELK0cRCPy_lhI493Xc6U1EWy7We2TxOpgD_5mrLLeW29bkB4lwKAyl_7dfYT9PeRypJMcu3spToRhT32OeACT_MzzU5Umtk0N2ozc5HoVb7wfJRK9K1MWaUyg2eGxb4vDD6rUF4MePzkWFUUg_LP3tnSAgJwpsPjLZ8u6rygerD-j4gXZI7gvMEZ7ql17h5w-ERliqWafW5co0e3iJ1C1XV8Q_D2Sa1q-HKZR2720wlBuT2EILxz4Kjfv8RBGhkV0YNloX_OxUecI

### -- WITH: base
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations?ids=34594&with=base,base.item
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYTMwZTk5Njg1NmZjZGMyMGU3ZDVjOTUyYTJmMGRmZDBhMDFlMjVkZDhlMWY2NmJmMTllMGY0ZDliZDBiNTczZTNkYjVhODkyOGQxOGQ2NjEiLCJpYXQiOjE2OTI5NTg3MTUuMzU0NCwibmJmIjoxNjkyOTU4NzE1LjM1NDQsImV4cCI6MTY5MzA0NTExNS4zNDQxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.NcEldT8u6MRHsxMsjvAKnXLnLleIFK8Dw0D50eoFUXYn7qmOPlyYIaYoNl9laCIdHgNw278ba2Z7BxjnfSzp0BzjJUNBl_QkyZn4HULsVIdBYX-xL1byTDp-1lQTJRarFIzoyyi85SnNeIVXyq0Oad7m-jjHjc4CcU0Op6MgG55Fu6RiH-4gqeB3tNtfcuInMQp0TyZji6vjqcPc-fduKjFl62wCKkKS52wPgcad-UIE5ybkQu6l0N8qOS3kQnK6TXQGuHTMSDnXBK0foCSygcIiFADFCEoegl5JYlU600bsxTszgDbbJ_5UR3MSXdh0O7IZ7aAweAYREibT4K-I4vmUk73oMc_I-AuYrVTCabSBCXOpWrb2aYF_ydNYX09cctA04SADxYy8GzU1NNGrG4p875Vft6ELK0cRCPy_lhI493Xc6U1EWy7We2TxOpgD_5mrLLeW29bkB4lwKAyl_7dfYT9PeRypJMcu3spToRhT32OeACT_MzzU5Umtk0N2ozc5HoVb7wfJRK9K1MWaUyg2eGxb4vDD6rUF4MePzkWFUUg_LP3tnSAgJwpsPjLZ8u6rygerD-j4gXZI7gvMEZ7ql17h5w-ERliqWafW5co0e3iJ1C1XV8Q_D2Sa1q-HKZR2720wlBuT2EILxz4Kjfv8RBGhkV0YNloX_OxUecI

### --- IDs 34494 WITH: additionalSkus,attributeValues,attributeValues.attribute,attributeValues.attributeValue,barcodes,barcodes.barcode,base,base.item,base.itemSerialNumber,base.feedback,base.characteristics,base.crossSelling,base.texts,base.availability',base.images,base.shippingProfiles,base.stock,base.stockStorageLocations,bundleComponents,categories,categories.category,categories.categoryBranch,clients,defaultCategories,defaultCategories.category,images,images.image,markets,marketIdentNumbers,salesPrices,salesPrices.salesPrice,skus,supplier,supplier.supplier,timestamps,warehouses,warehouses.warehouse,unit,unit.unit,tags,tags.tag,properties,properties.property,comments
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations?ids=34597&with=additionalSkus,attributeValues,attributeValues.attribute,attributeValues.attributeValue,barcodes,barcodes.barcode,base,base.item,base.itemSerialNumber,base.feedback,base.characteristics,base.crossSelling,base.texts,base.availability',base.images,base.shippingProfiles,base.stock,base.stockStorageLocations,bundleComponents,categories,categories.category,categories.categoryBranch,clients,defaultCategories,defaultCategories.category,images,images.image,markets,marketIdentNumbers,salesPrices,salesPrices.salesPrice,skus,supplier,supplier.supplier,timestamps,warehouses,warehouses.warehouse,unit,unit.unit,tags,tags.tag,properties,properties.property,comments&itemsPerPage=10
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYTMwZTk5Njg1NmZjZGMyMGU3ZDVjOTUyYTJmMGRmZDBhMDFlMjVkZDhlMWY2NmJmMTllMGY0ZDliZDBiNTczZTNkYjVhODkyOGQxOGQ2NjEiLCJpYXQiOjE2OTI5NTg3MTUuMzU0NCwibmJmIjoxNjkyOTU4NzE1LjM1NDQsImV4cCI6MTY5MzA0NTExNS4zNDQxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.NcEldT8u6MRHsxMsjvAKnXLnLleIFK8Dw0D50eoFUXYn7qmOPlyYIaYoNl9laCIdHgNw278ba2Z7BxjnfSzp0BzjJUNBl_QkyZn4HULsVIdBYX-xL1byTDp-1lQTJRarFIzoyyi85SnNeIVXyq0Oad7m-jjHjc4CcU0Op6MgG55Fu6RiH-4gqeB3tNtfcuInMQp0TyZji6vjqcPc-fduKjFl62wCKkKS52wPgcad-UIE5ybkQu6l0N8qOS3kQnK6TXQGuHTMSDnXBK0foCSygcIiFADFCEoegl5JYlU600bsxTszgDbbJ_5UR3MSXdh0O7IZ7aAweAYREibT4K-I4vmUk73oMc_I-AuYrVTCabSBCXOpWrb2aYF_ydNYX09cctA04SADxYy8GzU1NNGrG4p875Vft6ELK0cRCPy_lhI493Xc6U1EWy7We2TxOpgD_5mrLLeW29bkB4lwKAyl_7dfYT9PeRypJMcu3spToRhT32OeACT_MzzU5Umtk0N2ozc5HoVb7wfJRK9K1MWaUyg2eGxb4vDD6rUF4MePzkWFUUg_LP3tnSAgJwpsPjLZ8u6rygerD-j4gXZI7gvMEZ7ql17h5w-ERliqWafW5co0e3iJ1C1XV8Q_D2Sa1q-HKZR2720wlBuT2EILxz4Kjfv8RBGhkV0YNloX_OxUecI

### --- item IDs: 8398 WITH: additionalSkus,attributeValues,attributeValues.attribute,attributeValues.attributeValue,barcodes,barcodes.barcode,base,base.item,base.itemSerialNumber,base.feedback,base.characteristics,base.crossSelling,base.texts,base.availability',base.images,base.shippingProfiles,base.stock,base.stockStorageLocations,bundleComponents,categories,categories.category,categories.categoryBranch,clients,defaultCategories,defaultCategories.category,images,images.image,markets,marketIdentNumbers,salesPrices,salesPrices.salesPrice,skus,supplier,supplier.supplier,timestamps,warehouses,warehouses.warehouse,unit,unit.unit,tags,tags.tag,properties,properties.property,comments
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations?itemIds=8411&with=additionalSkus,attributeValues,attributeValues.attribute,attributeValues.attributeValue,barcodes,barcodes.barcode,base,base.item,base.itemSerialNumber,base.feedback,base.characteristics,base.crossSelling,base.texts,base.availability',base.images,base.shippingProfiles,base.stock,base.stockStorageLocations,bundleComponents,categories,categories.category,categories.categoryBranch,clients,defaultCategories,defaultCategories.category,images,images.image,markets,marketIdentNumbers,salesPrices,salesPrices.salesPrice,skus,supplier,supplier.supplier,timestamps,warehouses,warehouses.warehouse,unit,unit.unit,tags,tags.tag,properties,properties.property,comments&itemsPerPage=10
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYTMwZTk5Njg1NmZjZGMyMGU3ZDVjOTUyYTJmMGRmZDBhMDFlMjVkZDhlMWY2NmJmMTllMGY0ZDliZDBiNTczZTNkYjVhODkyOGQxOGQ2NjEiLCJpYXQiOjE2OTI5NTg3MTUuMzU0NCwibmJmIjoxNjkyOTU4NzE1LjM1NDQsImV4cCI6MTY5MzA0NTExNS4zNDQxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.NcEldT8u6MRHsxMsjvAKnXLnLleIFK8Dw0D50eoFUXYn7qmOPlyYIaYoNl9laCIdHgNw278ba2Z7BxjnfSzp0BzjJUNBl_QkyZn4HULsVIdBYX-xL1byTDp-1lQTJRarFIzoyyi85SnNeIVXyq0Oad7m-jjHjc4CcU0Op6MgG55Fu6RiH-4gqeB3tNtfcuInMQp0TyZji6vjqcPc-fduKjFl62wCKkKS52wPgcad-UIE5ybkQu6l0N8qOS3kQnK6TXQGuHTMSDnXBK0foCSygcIiFADFCEoegl5JYlU600bsxTszgDbbJ_5UR3MSXdh0O7IZ7aAweAYREibT4K-I4vmUk73oMc_I-AuYrVTCabSBCXOpWrb2aYF_ydNYX09cctA04SADxYy8GzU1NNGrG4p875Vft6ELK0cRCPy_lhI493Xc6U1EWy7We2TxOpgD_5mrLLeW29bkB4lwKAyl_7dfYT9PeRypJMcu3spToRhT32OeACT_MzzU5Umtk0N2ozc5HoVb7wfJRK9K1MWaUyg2eGxb4vDD6rUF4MePzkWFUUg_LP3tnSAgJwpsPjLZ8u6rygerD-j4gXZI7gvMEZ7ql17h5w-ERliqWafW5co0e3iJ1C1XV8Q_D2Sa1q-HKZR2720wlBuT2EILxz4Kjfv8RBGhkV0YNloX_OxUecI

### --- item IDs: 8398 WITH: properties,properties.property
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations?ids=34370&with=properties,properties.property
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYTMwZTk5Njg1NmZjZGMyMGU3ZDVjOTUyYTJmMGRmZDBhMDFlMjVkZDhlMWY2NmJmMTllMGY0ZDliZDBiNTczZTNkYjVhODkyOGQxOGQ2NjEiLCJpYXQiOjE2OTI5NTg3MTUuMzU0NCwibmJmIjoxNjkyOTU4NzE1LjM1NDQsImV4cCI6MTY5MzA0NTExNS4zNDQxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.NcEldT8u6MRHsxMsjvAKnXLnLleIFK8Dw0D50eoFUXYn7qmOPlyYIaYoNl9laCIdHgNw278ba2Z7BxjnfSzp0BzjJUNBl_QkyZn4HULsVIdBYX-xL1byTDp-1lQTJRarFIzoyyi85SnNeIVXyq0Oad7m-jjHjc4CcU0Op6MgG55Fu6RiH-4gqeB3tNtfcuInMQp0TyZji6vjqcPc-fduKjFl62wCKkKS52wPgcad-UIE5ybkQu6l0N8qOS3kQnK6TXQGuHTMSDnXBK0foCSygcIiFADFCEoegl5JYlU600bsxTszgDbbJ_5UR3MSXdh0O7IZ7aAweAYREibT4K-I4vmUk73oMc_I-AuYrVTCabSBCXOpWrb2aYF_ydNYX09cctA04SADxYy8GzU1NNGrG4p875Vft6ELK0cRCPy_lhI493Xc6U1EWy7We2TxOpgD_5mrLLeW29bkB4lwKAyl_7dfYT9PeRypJMcu3spToRhT32OeACT_MzzU5Umtk0N2ozc5HoVb7wfJRK9K1MWaUyg2eGxb4vDD6rUF4MePzkWFUUg_LP3tnSAgJwpsPjLZ8u6rygerD-j4gXZI7gvMEZ7ql17h5w-ERliqWafW5co0e3iJ1C1XV8Q_D2Sa1q-HKZR2720wlBuT2EILxz4Kjfv8RBGhkV0YNloX_OxUecI

### -- NUMBER: & WITH: base
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations?number=24-MB04&with=base
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYTMwZTk5Njg1NmZjZGMyMGU3ZDVjOTUyYTJmMGRmZDBhMDFlMjVkZDhlMWY2NmJmMTllMGY0ZDliZDBiNTczZTNkYjVhODkyOGQxOGQ2NjEiLCJpYXQiOjE2OTI5NTg3MTUuMzU0NCwibmJmIjoxNjkyOTU4NzE1LjM1NDQsImV4cCI6MTY5MzA0NTExNS4zNDQxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.NcEldT8u6MRHsxMsjvAKnXLnLleIFK8Dw0D50eoFUXYn7qmOPlyYIaYoNl9laCIdHgNw278ba2Z7BxjnfSzp0BzjJUNBl_QkyZn4HULsVIdBYX-xL1byTDp-1lQTJRarFIzoyyi85SnNeIVXyq0Oad7m-jjHjc4CcU0Op6MgG55Fu6RiH-4gqeB3tNtfcuInMQp0TyZji6vjqcPc-fduKjFl62wCKkKS52wPgcad-UIE5ybkQu6l0N8qOS3kQnK6TXQGuHTMSDnXBK0foCSygcIiFADFCEoegl5JYlU600bsxTszgDbbJ_5UR3MSXdh0O7IZ7aAweAYREibT4K-I4vmUk73oMc_I-AuYrVTCabSBCXOpWrb2aYF_ydNYX09cctA04SADxYy8GzU1NNGrG4p875Vft6ELK0cRCPy_lhI493Xc6U1EWy7We2TxOpgD_5mrLLeW29bkB4lwKAyl_7dfYT9PeRypJMcu3spToRhT32OeACT_MzzU5Umtk0N2ozc5HoVb7wfJRK9K1MWaUyg2eGxb4vDD6rUF4MePzkWFUUg_LP3tnSAgJwpsPjLZ8u6rygerD-j4gXZI7gvMEZ7ql17h5w-ERliqWafW5co0e3iJ1C1XV8Q_D2Sa1q-HKZR2720wlBuT2EILxz4Kjfv8RBGhkV0YNloX_OxUecI

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations?itemId=8358&page=1&with=base.item
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYTMwZTk5Njg1NmZjZGMyMGU3ZDVjOTUyYTJmMGRmZDBhMDFlMjVkZDhlMWY2NmJmMTllMGY0ZDliZDBiNTczZTNkYjVhODkyOGQxOGQ2NjEiLCJpYXQiOjE2OTI5NTg3MTUuMzU0NCwibmJmIjoxNjkyOTU4NzE1LjM1NDQsImV4cCI6MTY5MzA0NTExNS4zNDQxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.NcEldT8u6MRHsxMsjvAKnXLnLleIFK8Dw0D50eoFUXYn7qmOPlyYIaYoNl9laCIdHgNw278ba2Z7BxjnfSzp0BzjJUNBl_QkyZn4HULsVIdBYX-xL1byTDp-1lQTJRarFIzoyyi85SnNeIVXyq0Oad7m-jjHjc4CcU0Op6MgG55Fu6RiH-4gqeB3tNtfcuInMQp0TyZji6vjqcPc-fduKjFl62wCKkKS52wPgcad-UIE5ybkQu6l0N8qOS3kQnK6TXQGuHTMSDnXBK0foCSygcIiFADFCEoegl5JYlU600bsxTszgDbbJ_5UR3MSXdh0O7IZ7aAweAYREibT4K-I4vmUk73oMc_I-AuYrVTCabSBCXOpWrb2aYF_ydNYX09cctA04SADxYy8GzU1NNGrG4p875Vft6ELK0cRCPy_lhI493Xc6U1EWy7We2TxOpgD_5mrLLeW29bkB4lwKAyl_7dfYT9PeRypJMcu3spToRhT32OeACT_MzzU5Umtk0N2ozc5HoVb7wfJRK9K1MWaUyg2eGxb4vDD6rUF4MePzkWFUUg_LP3tnSAgJwpsPjLZ8u6rygerD-j4gXZI7gvMEZ7ql17h5w-ERliqWafW5co0e3iJ1C1XV8Q_D2Sa1q-HKZR2720wlBuT2EILxz4Kjfv8RBGhkV0YNloX_OxUecI

###
PUT https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYTMwZTk5Njg1NmZjZGMyMGU3ZDVjOTUyYTJmMGRmZDBhMDFlMjVkZDhlMWY2NmJmMTllMGY0ZDliZDBiNTczZTNkYjVhODkyOGQxOGQ2NjEiLCJpYXQiOjE2OTI5NTg3MTUuMzU0NCwibmJmIjoxNjkyOTU4NzE1LjM1NDQsImV4cCI6MTY5MzA0NTExNS4zNDQxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.NcEldT8u6MRHsxMsjvAKnXLnLleIFK8Dw0D50eoFUXYn7qmOPlyYIaYoNl9laCIdHgNw278ba2Z7BxjnfSzp0BzjJUNBl_QkyZn4HULsVIdBYX-xL1byTDp-1lQTJRarFIzoyyi85SnNeIVXyq0Oad7m-jjHjc4CcU0Op6MgG55Fu6RiH-4gqeB3tNtfcuInMQp0TyZji6vjqcPc-fduKjFl62wCKkKS52wPgcad-UIE5ybkQu6l0N8qOS3kQnK6TXQGuHTMSDnXBK0foCSygcIiFADFCEoegl5JYlU600bsxTszgDbbJ_5UR3MSXdh0O7IZ7aAweAYREibT4K-I4vmUk73oMc_I-AuYrVTCabSBCXOpWrb2aYF_ydNYX09cctA04SADxYy8GzU1NNGrG4p875Vft6ELK0cRCPy_lhI493Xc6U1EWy7We2TxOpgD_5mrLLeW29bkB4lwKAyl_7dfYT9PeRypJMcu3spToRhT32OeACT_MzzU5Umtk0N2ozc5HoVb7wfJRK9K1MWaUyg2eGxb4vDD6rUF4MePzkWFUUg_LP3tnSAgJwpsPjLZ8u6rygerD-j4gXZI7gvMEZ7ql17h5w-ERliqWafW5co0e3iJ1C1XV8Q_D2Sa1q-HKZR2720wlBuT2EILxz4Kjfv8RBGhkV0YNloX_OxUecI

[
    {
        "base": {
            "isMain": false,
            "itemId": 8445,
            "position": 72,
            "isActive": false,
            "number": "NEW-6512-10",
            "model": "molestias",
            "externalId": null,
            "availability": 1,
            "estimatedAvailableAt": "2021-12-20T11:23:19+0100",
            "purchasePrice": 63.84,
            "createdAt": "2021-11-06T21:36:32+0100",
            "updatedAt": "2021-11-26T23:48:43+0100",
            "relatedUpdatedAt": "2021-11-27T00:00:16+0100",
            "priceCalculationId": null,
            "picking": null,
            "stockLimitation": 1,
            "isVisibleIfNetStockIsPositive": true,
            "isInvisibleIfNetStockIsNotPositive": false,
            "isAvailableIfNetStockIsPositive": true,
            "isUnavailableIfNetStockIsNotPositive": true,
            "mainWarehouseId": 1,
            "maximumOrderQuantity": 91.21,
            "minimumOrderQuantity": 45.82,
            "intervalOrderQuantity": 29.63,
            "availableUntil": "2021-12-22T06:05:29+0100",
            "releasedAt": "2021-11-26T00:19:53+0100",
            "name": "Test Client CL1 7",
            "weightG": 2,
            "weightNetG": 1,
            "widthMM": 2,
            "lengthMM": 3,
            "heightMM": 8,
            "extraShippingCharge1": 12.83,
            "extraShippingCharge2": 5.26,
            "unitsContained": 4,
            "palletTypeId": 1,
            "packingUnits": 6,
            "packingUnitTypeId": 1,
            "transportationCosts": 35.5,
            "storageCosts": 75.29,
            "customs": 32.16,
            "operatingCosts": 9.64,
            "vatId": 1,
            "automaticClientVisibility": 0,
            "isHiddenInCategoryList": 0,
            "texts": [
                {
                    "lang": "en",
                    "name1": "Test xxx xxx",
                    "name2": "",
                    "name3": "",
                    "shortDescription": "EN Trek high CHANGE",
                    "metaDescription": "<p>Summit Watch&nbsp;Summit Watch&nbsp;Summit Watch&nbsp;Summit Watch<\/p>",
                    "description": "<p>EN Trek high and low in the attractive Summit Watch, which features a digital LED display with time and date, stopwatch, lap counter, and 3-second backlight. It can also calculate the number of steps taken and calories burned.<\/p>",
                    "technicalData": "xxx xxx xxxx xxx",
                    "urlPath": "magento-category-map\/collections\/summit-watch",
                    "keywords": ""
                }
            ]
        },
        "attributeValues": [
            {
                "attributeId": 1,
                "attributeValueSetId": 96,
                "valueId": 3
            },
            {
                "attributeId": 2,
                "attributeValueSetId": 96,
                "valueId": 5
            }
        ],
        "barcodes": [
            {
                "barcodeId": 1,
                "code": "3600829387510-2xxx"
            },
            {
                "barcodeId": 2,
                "code": "5897540534240-2xxx"
            }
        ],
        "categories": [
            {
                "categoryId": 600
            },
            {
                "categoryId": 947
            }
        ],
        "clients": [
            {
                "plentyId": 31241
            }
        ],
        "properties": [
            {
                "propertyId": 260,
                "value": "test 1",
                "groupId": 27
            }
        ],
        "salesPrices": [
            {
                "salesPriceId": 1,
                "price": 92
            },
            {
                "salesPriceId": 5,
                "price": 62
            }
        ],
        "unit": {
            "unitId": 1,
            "unitCombinationId": 1,
            "content": 1
        }
    }
]

### -- price update
PUT https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYTMwZTk5Njg1NmZjZGMyMGU3ZDVjOTUyYTJmMGRmZDBhMDFlMjVkZDhlMWY2NmJmMTllMGY0ZDliZDBiNTczZTNkYjVhODkyOGQxOGQ2NjEiLCJpYXQiOjE2OTI5NTg3MTUuMzU0NCwibmJmIjoxNjkyOTU4NzE1LjM1NDQsImV4cCI6MTY5MzA0NTExNS4zNDQxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.NcEldT8u6MRHsxMsjvAKnXLnLleIFK8Dw0D50eoFUXYn7qmOPlyYIaYoNl9laCIdHgNw278ba2Z7BxjnfSzp0BzjJUNBl_QkyZn4HULsVIdBYX-xL1byTDp-1lQTJRarFIzoyyi85SnNeIVXyq0Oad7m-jjHjc4CcU0Op6MgG55Fu6RiH-4gqeB3tNtfcuInMQp0TyZji6vjqcPc-fduKjFl62wCKkKS52wPgcad-UIE5ybkQu6l0N8qOS3kQnK6TXQGuHTMSDnXBK0foCSygcIiFADFCEoegl5JYlU600bsxTszgDbbJ_5UR3MSXdh0O7IZ7aAweAYREibT4K-I4vmUk73oMc_I-AuYrVTCabSBCXOpWrb2aYF_ydNYX09cctA04SADxYy8GzU1NNGrG4p875Vft6ELK0cRCPy_lhI493Xc6U1EWy7We2TxOpgD_5mrLLeW29bkB4lwKAyl_7dfYT9PeRypJMcu3spToRhT32OeACT_MzzU5Umtk0N2ozc5HoVb7wfJRK9K1MWaUyg2eGxb4vDD6rUF4MePzkWFUUg_LP3tnSAgJwpsPjLZ8u6rygerD-j4gXZI7gvMEZ7ql17h5w-ERliqWafW5co0e3iJ1C1XV8Q_D2Sa1q-HKZR2720wlBuT2EILxz4Kjfv8RBGhkV0YNloX_OxUecI

[
    {
        "id": 34595,
        "base": {
            "isMain": true,
            "itemId": 8409,
            "position": 72,
            "isActive": true,
            "number": "NEW-6512",
            "model": "molestias",
            "externalId": null,
            "availability": 1,
            "estimatedAvailableAt": "2021-12-20T11:23:19+0100",
            "purchasePrice": 63.84,
            "createdAt": "2021-11-06T21:36:32+0100",
            "updatedAt": "2021-11-26T23:48:43+0100",
            "relatedUpdatedAt": "2021-11-27T00:00:16+0100",
            "priceCalculationId": null,
            "picking": null,
            "stockLimitation": 1,
            "isVisibleIfNetStockIsPositive": true,
            "isInvisibleIfNetStockIsNotPositive": false,
            "isAvailableIfNetStockIsPositive": true,
            "isUnavailableIfNetStockIsNotPositive": true,
            "mainWarehouseId": 1,
            "maximumOrderQuantity": 91.21,
            "minimumOrderQuantity": 45.82,
            "intervalOrderQuantity": 29.63,
            "availableUntil": "2021-12-22T06:05:29+0100",
            "releasedAt": "2021-11-26T00:19:53+0100",
            "name": "Product-Export-Test-001-simple",
            "weightG": 2,
            "weightNetG": 1,
            "widthMM": 2,
            "lengthMM": 3,
            "heightMM": 8,
            "extraShippingCharge1": 12.83,
            "extraShippingCharge2": 5.26,
            "unitsContained": 4,
            "palletTypeId": 1,
            "packingUnits": 6,
            "packingUnitTypeId": 1,
            "transportationCosts": 35.5,
            "storageCosts": 75.29,
            "customs": 32.16,
            "operatingCosts": 9.64,
            "vatId": 1,
            "automaticClientVisibility": 0,
            "isHiddenInCategoryList": 0
        },
        "barcodes": [
            {
                "barcodeId": 1,
                "code": "3600829387510-2"
            },
            {
                "barcodeId": 2,
                "code": "5897540534240-2"
            }
        ],
        "categories": [
            {
                "categoryId": 600
            },
            {
                "categoryId": 947
            }
        ],
        "clients": [
            {
                "plentyId": 31241
            }
        ],
        "properties": [
            {
                "propertyId": 260,
                "value": "test 1",
                "groupId": 27
            }
        ],
        "salesPrices": [
            {
                "salesPriceId": 1,
                "price": 92
            },
            {
                "salesPriceId": 5,
                "price": 84
            }
        ],
        "unit": {
            "unitId": 1,
            "unitCombinationId": 1,
            "content": 1
        }
    }
]
