###
GET https://skorohoda.plentymarkets-cloud02.com/rest/categories
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDlmNTc0MGEwNmE3MTYwZWM5MjZhN2MzMGIyOGFkNzBhMWNkMTc1Y2U3ZDgwMzQ1YWUyYTUxYzcyOTY1MmJlY2U0NzJjMmI5OTM0MzVkYTciLCJpYXQiOjE2NDI0MDUyODEsIm5iZiI6MTY0MjQwNTI4MSwiZXhwIjoxNjQyNDkxNjgxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.DaJeLw1Evf8hv8Iz3Ll5pxvf1Uxzn7XSr74OnuTXWsflsunFzHzIFDdM5-k4UeHYuVOM2KpA4miaV6W-njC84mEvt23EC2fA7QvcD0zoqloo34ZDh3FbsRvIeHrp6NHpBruaSaYGjFtXqjC0riBuxVJAQWpaXQYpSczcLEf55s2O1Xyfqn5KI70pib4fD9Oqt7kipSPdC8yynJd-Y33Oj6tcGHfusk1gVYApbYJE5MDWWYRVKoQaMVEGfBnU6Vr5-ZikaGbs5iveEQD3upevVwRm5f6QnN56UhUgfqvkGaj1ErYRZh7oTURnCM8542VClzYpEGRweaTM9_ds18tLUgwggvWXpZCYJeAqX3PsXiTarA4Zw7xKGozOClstbbi1YZ8gaFBsT6HFv4qR6TZxSIvBLA6TxtXqfPmXZj5M0D7nfjHS58n3jiWSN3g5F0rBxLY1-at1_5fQN7-q4hINyNVz-xQ9mnJ0Gu6JIi9HNfoxh24A-h5lcH2ihrlfe9ndG95KQZPjbK5bwo9cHWmwGk9NRIRtAtN2XQkkEJttJD__OWc2EghRdnrHSr4Aiv99G2-IGkXeiy7zy5mgrE7SERXfi30jBRiuKWk-3rje3mtin5T184WStQENZtEkTTRWnNLddZpOvg_Vw7j3YSoguaeMbxiCstma_ROrD0gqCyY

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/categories/1082
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDlmNTc0MGEwNmE3MTYwZWM5MjZhN2MzMGIyOGFkNzBhMWNkMTc1Y2U3ZDgwMzQ1YWUyYTUxYzcyOTY1MmJlY2U0NzJjMmI5OTM0MzVkYTciLCJpYXQiOjE2NDI0MDUyODEsIm5iZiI6MTY0MjQwNTI4MSwiZXhwIjoxNjQyNDkxNjgxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.DaJeLw1Evf8hv8Iz3Ll5pxvf1Uxzn7XSr74OnuTXWsflsunFzHzIFDdM5-k4UeHYuVOM2KpA4miaV6W-njC84mEvt23EC2fA7QvcD0zoqloo34ZDh3FbsRvIeHrp6NHpBruaSaYGjFtXqjC0riBuxVJAQWpaXQYpSczcLEf55s2O1Xyfqn5KI70pib4fD9Oqt7kipSPdC8yynJd-Y33Oj6tcGHfusk1gVYApbYJE5MDWWYRVKoQaMVEGfBnU6Vr5-ZikaGbs5iveEQD3upevVwRm5f6QnN56UhUgfqvkGaj1ErYRZh7oTURnCM8542VClzYpEGRweaTM9_ds18tLUgwggvWXpZCYJeAqX3PsXiTarA4Zw7xKGozOClstbbi1YZ8gaFBsT6HFv4qR6TZxSIvBLA6TxtXqfPmXZj5M0D7nfjHS58n3jiWSN3g5F0rBxLY1-at1_5fQN7-q4hINyNVz-xQ9mnJ0Gu6JIi9HNfoxh24A-h5lcH2ihrlfe9ndG95KQZPjbK5bwo9cHWmwGk9NRIRtAtN2XQkkEJttJD__OWc2EghRdnrHSr4Aiv99G2-IGkXeiy7zy5mgrE7SERXfi30jBRiuKWk-3rje3mtin5T184WStQENZtEkTTRWnNLddZpOvg_Vw7j3YSoguaeMbxiCstma_ROrD0gqCyY

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/categories?ids=600,820
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDlmNTc0MGEwNmE3MTYwZWM5MjZhN2MzMGIyOGFkNzBhMWNkMTc1Y2U3ZDgwMzQ1YWUyYTUxYzcyOTY1MmJlY2U0NzJjMmI5OTM0MzVkYTciLCJpYXQiOjE2NDI0MDUyODEsIm5iZiI6MTY0MjQwNTI4MSwiZXhwIjoxNjQyNDkxNjgxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.DaJeLw1Evf8hv8Iz3Ll5pxvf1Uxzn7XSr74OnuTXWsflsunFzHzIFDdM5-k4UeHYuVOM2KpA4miaV6W-njC84mEvt23EC2fA7QvcD0zoqloo34ZDh3FbsRvIeHrp6NHpBruaSaYGjFtXqjC0riBuxVJAQWpaXQYpSczcLEf55s2O1Xyfqn5KI70pib4fD9Oqt7kipSPdC8yynJd-Y33Oj6tcGHfusk1gVYApbYJE5MDWWYRVKoQaMVEGfBnU6Vr5-ZikaGbs5iveEQD3upevVwRm5f6QnN56UhUgfqvkGaj1ErYRZh7oTURnCM8542VClzYpEGRweaTM9_ds18tLUgwggvWXpZCYJeAqX3PsXiTarA4Zw7xKGozOClstbbi1YZ8gaFBsT6HFv4qR6TZxSIvBLA6TxtXqfPmXZj5M0D7nfjHS58n3jiWSN3g5F0rBxLY1-at1_5fQN7-q4hINyNVz-xQ9mnJ0Gu6JIi9HNfoxh24A-h5lcH2ihrlfe9ndG95KQZPjbK5bwo9cHWmwGk9NRIRtAtN2XQkkEJttJD__OWc2EghRdnrHSr4Aiv99G2-IGkXeiy7zy5mgrE7SERXfi30jBRiuKWk-3rje3mtin5T184WStQENZtEkTTRWnNLddZpOvg_Vw7j3YSoguaeMbxiCstma_ROrD0gqCyY

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/categories?with=details,clients,branch,tagRelationship,elmarCategories
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDlmNTc0MGEwNmE3MTYwZWM5MjZhN2MzMGIyOGFkNzBhMWNkMTc1Y2U3ZDgwMzQ1YWUyYTUxYzcyOTY1MmJlY2U0NzJjMmI5OTM0MzVkYTciLCJpYXQiOjE2NDI0MDUyODEsIm5iZiI6MTY0MjQwNTI4MSwiZXhwIjoxNjQyNDkxNjgxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.DaJeLw1Evf8hv8Iz3Ll5pxvf1Uxzn7XSr74OnuTXWsflsunFzHzIFDdM5-k4UeHYuVOM2KpA4miaV6W-njC84mEvt23EC2fA7QvcD0zoqloo34ZDh3FbsRvIeHrp6NHpBruaSaYGjFtXqjC0riBuxVJAQWpaXQYpSczcLEf55s2O1Xyfqn5KI70pib4fD9Oqt7kipSPdC8yynJd-Y33Oj6tcGHfusk1gVYApbYJE5MDWWYRVKoQaMVEGfBnU6Vr5-ZikaGbs5iveEQD3upevVwRm5f6QnN56UhUgfqvkGaj1ErYRZh7oTURnCM8542VClzYpEGRweaTM9_ds18tLUgwggvWXpZCYJeAqX3PsXiTarA4Zw7xKGozOClstbbi1YZ8gaFBsT6HFv4qR6TZxSIvBLA6TxtXqfPmXZj5M0D7nfjHS58n3jiWSN3g5F0rBxLY1-at1_5fQN7-q4hINyNVz-xQ9mnJ0Gu6JIi9HNfoxh24A-h5lcH2ihrlfe9ndG95KQZPjbK5bwo9cHWmwGk9NRIRtAtN2XQkkEJttJD__OWc2EghRdnrHSr4Aiv99G2-IGkXeiy7zy5mgrE7SERXfi30jBRiuKWk-3rje3mtin5T184WStQENZtEkTTRWnNLddZpOvg_Vw7j3YSoguaeMbxiCstma_ROrD0gqCyY

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/categories?with=details,clients,branch
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDlmNTc0MGEwNmE3MTYwZWM5MjZhN2MzMGIyOGFkNzBhMWNkMTc1Y2U3ZDgwMzQ1YWUyYTUxYzcyOTY1MmJlY2U0NzJjMmI5OTM0MzVkYTciLCJpYXQiOjE2NDI0MDUyODEsIm5iZiI6MTY0MjQwNTI4MSwiZXhwIjoxNjQyNDkxNjgxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.DaJeLw1Evf8hv8Iz3Ll5pxvf1Uxzn7XSr74OnuTXWsflsunFzHzIFDdM5-k4UeHYuVOM2KpA4miaV6W-njC84mEvt23EC2fA7QvcD0zoqloo34ZDh3FbsRvIeHrp6NHpBruaSaYGjFtXqjC0riBuxVJAQWpaXQYpSczcLEf55s2O1Xyfqn5KI70pib4fD9Oqt7kipSPdC8yynJd-Y33Oj6tcGHfusk1gVYApbYJE5MDWWYRVKoQaMVEGfBnU6Vr5-ZikaGbs5iveEQD3upevVwRm5f6QnN56UhUgfqvkGaj1ErYRZh7oTURnCM8542VClzYpEGRweaTM9_ds18tLUgwggvWXpZCYJeAqX3PsXiTarA4Zw7xKGozOClstbbi1YZ8gaFBsT6HFv4qR6TZxSIvBLA6TxtXqfPmXZj5M0D7nfjHS58n3jiWSN3g5F0rBxLY1-at1_5fQN7-q4hINyNVz-xQ9mnJ0Gu6JIi9HNfoxh24A-h5lcH2ihrlfe9ndG95KQZPjbK5bwo9cHWmwGk9NRIRtAtN2XQkkEJttJD__OWc2EghRdnrHSr4Aiv99G2-IGkXeiy7zy5mgrE7SERXfi30jBRiuKWk-3rje3mtin5T184WStQENZtEkTTRWnNLddZpOvg_Vw7j3YSoguaeMbxiCstma_ROrD0gqCyY

###
DELETE https://skorohoda.plentymarkets-cloud02.com/rest/categories/1082
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDlmNTc0MGEwNmE3MTYwZWM5MjZhN2MzMGIyOGFkNzBhMWNkMTc1Y2U3ZDgwMzQ1YWUyYTUxYzcyOTY1MmJlY2U0NzJjMmI5OTM0MzVkYTciLCJpYXQiOjE2NDI0MDUyODEsIm5iZiI6MTY0MjQwNTI4MSwiZXhwIjoxNjQyNDkxNjgxLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.DaJeLw1Evf8hv8Iz3Ll5pxvf1Uxzn7XSr74OnuTXWsflsunFzHzIFDdM5-k4UeHYuVOM2KpA4miaV6W-njC84mEvt23EC2fA7QvcD0zoqloo34ZDh3FbsRvIeHrp6NHpBruaSaYGjFtXqjC0riBuxVJAQWpaXQYpSczcLEf55s2O1Xyfqn5KI70pib4fD9Oqt7kipSPdC8yynJd-Y33Oj6tcGHfusk1gVYApbYJE5MDWWYRVKoQaMVEGfBnU6Vr5-ZikaGbs5iveEQD3upevVwRm5f6QnN56UhUgfqvkGaj1ErYRZh7oTURnCM8542VClzYpEGRweaTM9_ds18tLUgwggvWXpZCYJeAqX3PsXiTarA4Zw7xKGozOClstbbi1YZ8gaFBsT6HFv4qR6TZxSIvBLA6TxtXqfPmXZj5M0D7nfjHS58n3jiWSN3g5F0rBxLY1-at1_5fQN7-q4hINyNVz-xQ9mnJ0Gu6JIi9HNfoxh24A-h5lcH2ihrlfe9ndG95KQZPjbK5bwo9cHWmwGk9NRIRtAtN2XQkkEJttJD__OWc2EghRdnrHSr4Aiv99G2-IGkXeiy7zy5mgrE7SERXfi30jBRiuKWk-3rje3mtin5T184WStQENZtEkTTRWnNLddZpOvg_Vw7j3YSoguaeMbxiCstma_ROrD0gqCyY
