GET https://skorohoda.plentymarkets-cloud02.com/rest/v2/properties
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmI3Yzc3MWJjNjdiMDAzNzBmMDcyZjUxYzg2N2NlZTE4N2E3ZDEyM2YwNmJhODM3NDI0ODFlYjBiY2IwMmZmMWMyZDhkODQ4M2I4ZmM0MTkiLCJpYXQiOjE2NDk4NDYyODguMjg0NSwibmJmIjoxNjQ5ODQ2Mjg4LjI4NDUsImV4cCI6MTY0OTkzMjY4OC4yNzE5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.T5e9mmk6wmuGg4vRF9vxUW4k6EypI6_psnTdaNGPP3_J_AbNDdb9IDH9Kgoa90B7TNqPd1K3JdA-pB511QBDe8MPwaxO4WJl1X5VSiscFO99oBHS5mTqcgGy-BEWEVJII8PNNLP7JtYG3DXpySda2lzQdkyARo3mh0m3Vj0qUNLwJeiPfzS0U36pYSYiGxM_4GxWcNKAHjqqvRWOPBFTgaNJa5JQb4lXCoW_NXQr3Zy7mHpbn_VyibBQwJup8f8oI5ufjGaAjurjDM4e3NJoGaQsqj0hYDnjcTHPrY1Si9ZPZDBGgextTFtVocxOSu2B6SNH4X6h7nrkQpG5kUTJ23ZFf-T2MKbQEfjDWBGCWe9Xv6cWjbsvyXSKC2fIW-lUZK2Y5J_QGF80mmz5fy27C0wNX36_ZZ041cSKhUdogBxSeITcLfIdYUUMcH1_4OmTfari-47ywtdi_nwB78xKRiOsqXiSRO4GfyJqvKiYpAqPaNMC-p-T_G6U9bux-4gvAbV-PMYrvQymF_kYJrWEaDUAM2M44StEOkObfj94m3tejfZcL69TIsu8R0Bd1RHHJqoImV6xOkgArmhdBZnRgjQebOvIIrZ-AUY2APcdiolD2EUIg1c1Yl1Y8N8OhA0nhqCgSnHqy4JFqf7JyX0KjkvtpTM_z0DjTzU5tjc72BU

### Page filter
GET https://skorohoda.plentymarkets-cloud02.com/rest/v2/properties?page=2
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmI3Yzc3MWJjNjdiMDAzNzBmMDcyZjUxYzg2N2NlZTE4N2E3ZDEyM2YwNmJhODM3NDI0ODFlYjBiY2IwMmZmMWMyZDhkODQ4M2I4ZmM0MTkiLCJpYXQiOjE2NDk4NDYyODguMjg0NSwibmJmIjoxNjQ5ODQ2Mjg4LjI4NDUsImV4cCI6MTY0OTkzMjY4OC4yNzE5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.T5e9mmk6wmuGg4vRF9vxUW4k6EypI6_psnTdaNGPP3_J_AbNDdb9IDH9Kgoa90B7TNqPd1K3JdA-pB511QBDe8MPwaxO4WJl1X5VSiscFO99oBHS5mTqcgGy-BEWEVJII8PNNLP7JtYG3DXpySda2lzQdkyARo3mh0m3Vj0qUNLwJeiPfzS0U36pYSYiGxM_4GxWcNKAHjqqvRWOPBFTgaNJa5JQb4lXCoW_NXQr3Zy7mHpbn_VyibBQwJup8f8oI5ufjGaAjurjDM4e3NJoGaQsqj0hYDnjcTHPrY1Si9ZPZDBGgextTFtVocxOSu2B6SNH4X6h7nrkQpG5kUTJ23ZFf-T2MKbQEfjDWBGCWe9Xv6cWjbsvyXSKC2fIW-lUZK2Y5J_QGF80mmz5fy27C0wNX36_ZZ041cSKhUdogBxSeITcLfIdYUUMcH1_4OmTfari-47ywtdi_nwB78xKRiOsqXiSRO4GfyJqvKiYpAqPaNMC-p-T_G6U9bux-4gvAbV-PMYrvQymF_kYJrWEaDUAM2M44StEOkObfj94m3tejfZcL69TIsu8R0Bd1RHHJqoImV6xOkgArmhdBZnRgjQebOvIIrZ-AUY2APcdiolD2EUIg1c1Yl1Y8N8OhA0nhqCgSnHqy4JFqf7JyX0KjkvtpTM_z0DjTzU5tjc72BU

### ID filter
GET https://skorohoda.plentymarkets-cloud02.com/rest/v2/properties?id=244
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmI3Yzc3MWJjNjdiMDAzNzBmMDcyZjUxYzg2N2NlZTE4N2E3ZDEyM2YwNmJhODM3NDI0ODFlYjBiY2IwMmZmMWMyZDhkODQ4M2I4ZmM0MTkiLCJpYXQiOjE2NDk4NDYyODguMjg0NSwibmJmIjoxNjQ5ODQ2Mjg4LjI4NDUsImV4cCI6MTY0OTkzMjY4OC4yNzE5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.T5e9mmk6wmuGg4vRF9vxUW4k6EypI6_psnTdaNGPP3_J_AbNDdb9IDH9Kgoa90B7TNqPd1K3JdA-pB511QBDe8MPwaxO4WJl1X5VSiscFO99oBHS5mTqcgGy-BEWEVJII8PNNLP7JtYG3DXpySda2lzQdkyARo3mh0m3Vj0qUNLwJeiPfzS0U36pYSYiGxM_4GxWcNKAHjqqvRWOPBFTgaNJa5JQb4lXCoW_NXQr3Zy7mHpbn_VyibBQwJup8f8oI5ufjGaAjurjDM4e3NJoGaQsqj0hYDnjcTHPrY1Si9ZPZDBGgextTFtVocxOSu2B6SNH4X6h7nrkQpG5kUTJ23ZFf-T2MKbQEfjDWBGCWe9Xv6cWjbsvyXSKC2fIW-lUZK2Y5J_QGF80mmz5fy27C0wNX36_ZZ041cSKhUdogBxSeITcLfIdYUUMcH1_4OmTfari-47ywtdi_nwB78xKRiOsqXiSRO4GfyJqvKiYpAqPaNMC-p-T_G6U9bux-4gvAbV-PMYrvQymF_kYJrWEaDUAM2M44StEOkObfj94m3tejfZcL69TIsu8R0Bd1RHHJqoImV6xOkgArmhdBZnRgjQebOvIIrZ-AUY2APcdiolD2EUIg1c1Yl1Y8N8OhA0nhqCgSnHqy4JFqf7JyX0KjkvtpTM_z0DjTzU5tjc72BU

### type: STOCK
GET https://skorohoda.plentymarkets-cloud02.com/rest/v2/properties/relations?type=stock
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmI3Yzc3MWJjNjdiMDAzNzBmMDcyZjUxYzg2N2NlZTE4N2E3ZDEyM2YwNmJhODM3NDI0ODFlYjBiY2IwMmZmMWMyZDhkODQ4M2I4ZmM0MTkiLCJpYXQiOjE2NDk4NDYyODguMjg0NSwibmJmIjoxNjQ5ODQ2Mjg4LjI4NDUsImV4cCI6MTY0OTkzMjY4OC4yNzE5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.T5e9mmk6wmuGg4vRF9vxUW4k6EypI6_psnTdaNGPP3_J_AbNDdb9IDH9Kgoa90B7TNqPd1K3JdA-pB511QBDe8MPwaxO4WJl1X5VSiscFO99oBHS5mTqcgGy-BEWEVJII8PNNLP7JtYG3DXpySda2lzQdkyARo3mh0m3Vj0qUNLwJeiPfzS0U36pYSYiGxM_4GxWcNKAHjqqvRWOPBFTgaNJa5JQb4lXCoW_NXQr3Zy7mHpbn_VyibBQwJup8f8oI5ufjGaAjurjDM4e3NJoGaQsqj0hYDnjcTHPrY1Si9ZPZDBGgextTFtVocxOSu2B6SNH4X6h7nrkQpG5kUTJ23ZFf-T2MKbQEfjDWBGCWe9Xv6cWjbsvyXSKC2fIW-lUZK2Y5J_QGF80mmz5fy27C0wNX36_ZZ041cSKhUdogBxSeITcLfIdYUUMcH1_4OmTfari-47ywtdi_nwB78xKRiOsqXiSRO4GfyJqvKiYpAqPaNMC-p-T_G6U9bux-4gvAbV-PMYrvQymF_kYJrWEaDUAM2M44StEOkObfj94m3tejfZcL69TIsu8R0Bd1RHHJqoImV6xOkgArmhdBZnRgjQebOvIIrZ-AUY2APcdiolD2EUIg1c1Yl1Y8N8OhA0nhqCgSnHqy4JFqf7JyX0KjkvtpTM_z0DjTzU5tjc72BU

### type: CONTACT
GET https://skorohoda.plentymarkets-cloud02.com/rest/v2/properties/relations?type=contact
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmI3Yzc3MWJjNjdiMDAzNzBmMDcyZjUxYzg2N2NlZTE4N2E3ZDEyM2YwNmJhODM3NDI0ODFlYjBiY2IwMmZmMWMyZDhkODQ4M2I4ZmM0MTkiLCJpYXQiOjE2NDk4NDYyODguMjg0NSwibmJmIjoxNjQ5ODQ2Mjg4LjI4NDUsImV4cCI6MTY0OTkzMjY4OC4yNzE5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.T5e9mmk6wmuGg4vRF9vxUW4k6EypI6_psnTdaNGPP3_J_AbNDdb9IDH9Kgoa90B7TNqPd1K3JdA-pB511QBDe8MPwaxO4WJl1X5VSiscFO99oBHS5mTqcgGy-BEWEVJII8PNNLP7JtYG3DXpySda2lzQdkyARo3mh0m3Vj0qUNLwJeiPfzS0U36pYSYiGxM_4GxWcNKAHjqqvRWOPBFTgaNJa5JQb4lXCoW_NXQr3Zy7mHpbn_VyibBQwJup8f8oI5ufjGaAjurjDM4e3NJoGaQsqj0hYDnjcTHPrY1Si9ZPZDBGgextTFtVocxOSu2B6SNH4X6h7nrkQpG5kUTJ23ZFf-T2MKbQEfjDWBGCWe9Xv6cWjbsvyXSKC2fIW-lUZK2Y5J_QGF80mmz5fy27C0wNX36_ZZ041cSKhUdogBxSeITcLfIdYUUMcH1_4OmTfari-47ywtdi_nwB78xKRiOsqXiSRO4GfyJqvKiYpAqPaNMC-p-T_G6U9bux-4gvAbV-PMYrvQymF_kYJrWEaDUAM2M44StEOkObfj94m3tejfZcL69TIsu8R0Bd1RHHJqoImV6xOkgArmhdBZnRgjQebOvIIrZ-AUY2APcdiolD2EUIg1c1Yl1Y8N8OhA0nhqCgSnHqy4JFqf7JyX0KjkvtpTM_z0DjTzU5tjc72BU

### ID: 244,324 || With: groups,groups.names,options,names,selections,selections.names
GET https://skorohoda.plentymarkets-cloud02.com/rest/v2/properties?id=in:324&with=groups,groups.names,options,names,selections,selections.names
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmI3Yzc3MWJjNjdiMDAzNzBmMDcyZjUxYzg2N2NlZTE4N2E3ZDEyM2YwNmJhODM3NDI0ODFlYjBiY2IwMmZmMWMyZDhkODQ4M2I4ZmM0MTkiLCJpYXQiOjE2NDk4NDYyODguMjg0NSwibmJmIjoxNjQ5ODQ2Mjg4LjI4NDUsImV4cCI6MTY0OTkzMjY4OC4yNzE5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.T5e9mmk6wmuGg4vRF9vxUW4k6EypI6_psnTdaNGPP3_J_AbNDdb9IDH9Kgoa90B7TNqPd1K3JdA-pB511QBDe8MPwaxO4WJl1X5VSiscFO99oBHS5mTqcgGy-BEWEVJII8PNNLP7JtYG3DXpySda2lzQdkyARo3mh0m3Vj0qUNLwJeiPfzS0U36pYSYiGxM_4GxWcNKAHjqqvRWOPBFTgaNJa5JQb4lXCoW_NXQr3Zy7mHpbn_VyibBQwJup8f8oI5ufjGaAjurjDM4e3NJoGaQsqj0hYDnjcTHPrY1Si9ZPZDBGgextTFtVocxOSu2B6SNH4X6h7nrkQpG5kUTJ23ZFf-T2MKbQEfjDWBGCWe9Xv6cWjbsvyXSKC2fIW-lUZK2Y5J_QGF80mmz5fy27C0wNX36_ZZ041cSKhUdogBxSeITcLfIdYUUMcH1_4OmTfari-47ywtdi_nwB78xKRiOsqXiSRO4GfyJqvKiYpAqPaNMC-p-T_G6U9bux-4gvAbV-PMYrvQymF_kYJrWEaDUAM2M44StEOkObfj94m3tejfZcL69TIsu8R0Bd1RHHJqoImV6xOkgArmhdBZnRgjQebOvIIrZ-AUY2APcdiolD2EUIg1c1Yl1Y8N8OhA0nhqCgSnHqy4JFqf7JyX0KjkvtpTM_z0DjTzU5tjc72BU

### -- with filter: groups,groups.names,options,names,selections,selections.names
GET https://skorohoda.plentymarkets-cloud02.com/rest/v2/properties?with=groups,groups.names,groups.options,options,names,selections,selections.names
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmI3Yzc3MWJjNjdiMDAzNzBmMDcyZjUxYzg2N2NlZTE4N2E3ZDEyM2YwNmJhODM3NDI0ODFlYjBiY2IwMmZmMWMyZDhkODQ4M2I4ZmM0MTkiLCJpYXQiOjE2NDk4NDYyODguMjg0NSwibmJmIjoxNjQ5ODQ2Mjg4LjI4NDUsImV4cCI6MTY0OTkzMjY4OC4yNzE5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.T5e9mmk6wmuGg4vRF9vxUW4k6EypI6_psnTdaNGPP3_J_AbNDdb9IDH9Kgoa90B7TNqPd1K3JdA-pB511QBDe8MPwaxO4WJl1X5VSiscFO99oBHS5mTqcgGy-BEWEVJII8PNNLP7JtYG3DXpySda2lzQdkyARo3mh0m3Vj0qUNLwJeiPfzS0U36pYSYiGxM_4GxWcNKAHjqqvRWOPBFTgaNJa5JQb4lXCoW_NXQr3Zy7mHpbn_VyibBQwJup8f8oI5ufjGaAjurjDM4e3NJoGaQsqj0hYDnjcTHPrY1Si9ZPZDBGgextTFtVocxOSu2B6SNH4X6h7nrkQpG5kUTJ23ZFf-T2MKbQEfjDWBGCWe9Xv6cWjbsvyXSKC2fIW-lUZK2Y5J_QGF80mmz5fy27C0wNX36_ZZ041cSKhUdogBxSeITcLfIdYUUMcH1_4OmTfari-47ywtdi_nwB78xKRiOsqXiSRO4GfyJqvKiYpAqPaNMC-p-T_G6U9bux-4gvAbV-PMYrvQymF_kYJrWEaDUAM2M44StEOkObfj94m3tejfZcL69TIsu8R0Bd1RHHJqoImV6xOkgArmhdBZnRgjQebOvIIrZ-AUY2APcdiolD2EUIg1c1Yl1Y8N8OhA0nhqCgSnHqy4JFqf7JyX0KjkvtpTM_z0DjTzU5tjc72BU

### property names
GET https://skorohoda.plentymarkets-cloud02.com/rest/v2/properties/names
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmI3Yzc3MWJjNjdiMDAzNzBmMDcyZjUxYzg2N2NlZTE4N2E3ZDEyM2YwNmJhODM3NDI0ODFlYjBiY2IwMmZmMWMyZDhkODQ4M2I4ZmM0MTkiLCJpYXQiOjE2NDk4NDYyODguMjg0NSwibmJmIjoxNjQ5ODQ2Mjg4LjI4NDUsImV4cCI6MTY0OTkzMjY4OC4yNzE5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.T5e9mmk6wmuGg4vRF9vxUW4k6EypI6_psnTdaNGPP3_J_AbNDdb9IDH9Kgoa90B7TNqPd1K3JdA-pB511QBDe8MPwaxO4WJl1X5VSiscFO99oBHS5mTqcgGy-BEWEVJII8PNNLP7JtYG3DXpySda2lzQdkyARo3mh0m3Vj0qUNLwJeiPfzS0U36pYSYiGxM_4GxWcNKAHjqqvRWOPBFTgaNJa5JQb4lXCoW_NXQr3Zy7mHpbn_VyibBQwJup8f8oI5ufjGaAjurjDM4e3NJoGaQsqj0hYDnjcTHPrY1Si9ZPZDBGgextTFtVocxOSu2B6SNH4X6h7nrkQpG5kUTJ23ZFf-T2MKbQEfjDWBGCWe9Xv6cWjbsvyXSKC2fIW-lUZK2Y5J_QGF80mmz5fy27C0wNX36_ZZ041cSKhUdogBxSeITcLfIdYUUMcH1_4OmTfari-47ywtdi_nwB78xKRiOsqXiSRO4GfyJqvKiYpAqPaNMC-p-T_G6U9bux-4gvAbV-PMYrvQymF_kYJrWEaDUAM2M44StEOkObfj94m3tejfZcL69TIsu8R0Bd1RHHJqoImV6xOkgArmhdBZnRgjQebOvIIrZ-AUY2APcdiolD2EUIg1c1Yl1Y8N8OhA0nhqCgSnHqy4JFqf7JyX0KjkvtpTM_z0DjTzU5tjc72BU

### -- groups
GET https://skorohoda.plentymarkets-cloud02.com/rest/v2/properties/groups
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmI3Yzc3MWJjNjdiMDAzNzBmMDcyZjUxYzg2N2NlZTE4N2E3ZDEyM2YwNmJhODM3NDI0ODFlYjBiY2IwMmZmMWMyZDhkODQ4M2I4ZmM0MTkiLCJpYXQiOjE2NDk4NDYyODguMjg0NSwibmJmIjoxNjQ5ODQ2Mjg4LjI4NDUsImV4cCI6MTY0OTkzMjY4OC4yNzE5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.T5e9mmk6wmuGg4vRF9vxUW4k6EypI6_psnTdaNGPP3_J_AbNDdb9IDH9Kgoa90B7TNqPd1K3JdA-pB511QBDe8MPwaxO4WJl1X5VSiscFO99oBHS5mTqcgGy-BEWEVJII8PNNLP7JtYG3DXpySda2lzQdkyARo3mh0m3Vj0qUNLwJeiPfzS0U36pYSYiGxM_4GxWcNKAHjqqvRWOPBFTgaNJa5JQb4lXCoW_NXQr3Zy7mHpbn_VyibBQwJup8f8oI5ufjGaAjurjDM4e3NJoGaQsqj0hYDnjcTHPrY1Si9ZPZDBGgextTFtVocxOSu2B6SNH4X6h7nrkQpG5kUTJ23ZFf-T2MKbQEfjDWBGCWe9Xv6cWjbsvyXSKC2fIW-lUZK2Y5J_QGF80mmz5fy27C0wNX36_ZZ041cSKhUdogBxSeITcLfIdYUUMcH1_4OmTfari-47ywtdi_nwB78xKRiOsqXiSRO4GfyJqvKiYpAqPaNMC-p-T_G6U9bux-4gvAbV-PMYrvQymF_kYJrWEaDUAM2M44StEOkObfj94m3tejfZcL69TIsu8R0Bd1RHHJqoImV6xOkgArmhdBZnRgjQebOvIIrZ-AUY2APcdiolD2EUIg1c1Yl1Y8N8OhA0nhqCgSnHqy4JFqf7JyX0KjkvtpTM_z0DjTzU5tjc72BU

### -- groups WITH: names,options
GET https://skorohoda.plentymarkets-cloud02.com/rest/v2/properties/groups?with=names,options
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmI3Yzc3MWJjNjdiMDAzNzBmMDcyZjUxYzg2N2NlZTE4N2E3ZDEyM2YwNmJhODM3NDI0ODFlYjBiY2IwMmZmMWMyZDhkODQ4M2I4ZmM0MTkiLCJpYXQiOjE2NDk4NDYyODguMjg0NSwibmJmIjoxNjQ5ODQ2Mjg4LjI4NDUsImV4cCI6MTY0OTkzMjY4OC4yNzE5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.T5e9mmk6wmuGg4vRF9vxUW4k6EypI6_psnTdaNGPP3_J_AbNDdb9IDH9Kgoa90B7TNqPd1K3JdA-pB511QBDe8MPwaxO4WJl1X5VSiscFO99oBHS5mTqcgGy-BEWEVJII8PNNLP7JtYG3DXpySda2lzQdkyARo3mh0m3Vj0qUNLwJeiPfzS0U36pYSYiGxM_4GxWcNKAHjqqvRWOPBFTgaNJa5JQb4lXCoW_NXQr3Zy7mHpbn_VyibBQwJup8f8oI5ufjGaAjurjDM4e3NJoGaQsqj0hYDnjcTHPrY1Si9ZPZDBGgextTFtVocxOSu2B6SNH4X6h7nrkQpG5kUTJ23ZFf-T2MKbQEfjDWBGCWe9Xv6cWjbsvyXSKC2fIW-lUZK2Y5J_QGF80mmz5fy27C0wNX36_ZZ041cSKhUdogBxSeITcLfIdYUUMcH1_4OmTfari-47ywtdi_nwB78xKRiOsqXiSRO4GfyJqvKiYpAqPaNMC-p-T_G6U9bux-4gvAbV-PMYrvQymF_kYJrWEaDUAM2M44StEOkObfj94m3tejfZcL69TIsu8R0Bd1RHHJqoImV6xOkgArmhdBZnRgjQebOvIIrZ-AUY2APcdiolD2EUIg1c1Yl1Y8N8OhA0nhqCgSnHqy4JFqf7JyX0KjkvtpTM_z0DjTzU5tjc72BU

### -- groups: names
GET https://skorohoda.plentymarkets-cloud02.com/rest/v2/properties/groups/names
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmI3Yzc3MWJjNjdiMDAzNzBmMDcyZjUxYzg2N2NlZTE4N2E3ZDEyM2YwNmJhODM3NDI0ODFlYjBiY2IwMmZmMWMyZDhkODQ4M2I4ZmM0MTkiLCJpYXQiOjE2NDk4NDYyODguMjg0NSwibmJmIjoxNjQ5ODQ2Mjg4LjI4NDUsImV4cCI6MTY0OTkzMjY4OC4yNzE5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.T5e9mmk6wmuGg4vRF9vxUW4k6EypI6_psnTdaNGPP3_J_AbNDdb9IDH9Kgoa90B7TNqPd1K3JdA-pB511QBDe8MPwaxO4WJl1X5VSiscFO99oBHS5mTqcgGy-BEWEVJII8PNNLP7JtYG3DXpySda2lzQdkyARo3mh0m3Vj0qUNLwJeiPfzS0U36pYSYiGxM_4GxWcNKAHjqqvRWOPBFTgaNJa5JQb4lXCoW_NXQr3Zy7mHpbn_VyibBQwJup8f8oI5ufjGaAjurjDM4e3NJoGaQsqj0hYDnjcTHPrY1Si9ZPZDBGgextTFtVocxOSu2B6SNH4X6h7nrkQpG5kUTJ23ZFf-T2MKbQEfjDWBGCWe9Xv6cWjbsvyXSKC2fIW-lUZK2Y5J_QGF80mmz5fy27C0wNX36_ZZ041cSKhUdogBxSeITcLfIdYUUMcH1_4OmTfari-47ywtdi_nwB78xKRiOsqXiSRO4GfyJqvKiYpAqPaNMC-p-T_G6U9bux-4gvAbV-PMYrvQymF_kYJrWEaDUAM2M44StEOkObfj94m3tejfZcL69TIsu8R0Bd1RHHJqoImV6xOkgArmhdBZnRgjQebOvIIrZ-AUY2APcdiolD2EUIg1c1Yl1Y8N8OhA0nhqCgSnHqy4JFqf7JyX0KjkvtpTM_z0DjTzU5tjc72BU

### -- selections
GET https://skorohoda.plentymarkets-cloud02.com/rest/properties/selections/590
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmI3Yzc3MWJjNjdiMDAzNzBmMDcyZjUxYzg2N2NlZTE4N2E3ZDEyM2YwNmJhODM3NDI0ODFlYjBiY2IwMmZmMWMyZDhkODQ4M2I4ZmM0MTkiLCJpYXQiOjE2NDk4NDYyODguMjg0NSwibmJmIjoxNjQ5ODQ2Mjg4LjI4NDUsImV4cCI6MTY0OTkzMjY4OC4yNzE5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.T5e9mmk6wmuGg4vRF9vxUW4k6EypI6_psnTdaNGPP3_J_AbNDdb9IDH9Kgoa90B7TNqPd1K3JdA-pB511QBDe8MPwaxO4WJl1X5VSiscFO99oBHS5mTqcgGy-BEWEVJII8PNNLP7JtYG3DXpySda2lzQdkyARo3mh0m3Vj0qUNLwJeiPfzS0U36pYSYiGxM_4GxWcNKAHjqqvRWOPBFTgaNJa5JQb4lXCoW_NXQr3Zy7mHpbn_VyibBQwJup8f8oI5ufjGaAjurjDM4e3NJoGaQsqj0hYDnjcTHPrY1Si9ZPZDBGgextTFtVocxOSu2B6SNH4X6h7nrkQpG5kUTJ23ZFf-T2MKbQEfjDWBGCWe9Xv6cWjbsvyXSKC2fIW-lUZK2Y5J_QGF80mmz5fy27C0wNX36_ZZ041cSKhUdogBxSeITcLfIdYUUMcH1_4OmTfari-47ywtdi_nwB78xKRiOsqXiSRO4GfyJqvKiYpAqPaNMC-p-T_G6U9bux-4gvAbV-PMYrvQymF_kYJrWEaDUAM2M44StEOkObfj94m3tejfZcL69TIsu8R0Bd1RHHJqoImV6xOkgArmhdBZnRgjQebOvIIrZ-AUY2APcdiolD2EUIg1c1Yl1Y8N8OhA0nhqCgSnHqy4JFqf7JyX0KjkvtpTM_z0DjTzU5tjc72BU

### -- relations || with=property,group,values,selectionValues
GET https://skorohoda.plentymarkets-cloud02.com/rest/v2/properties/relations?with=values,selectionValues&propertyId=244
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmI3Yzc3MWJjNjdiMDAzNzBmMDcyZjUxYzg2N2NlZTE4N2E3ZDEyM2YwNmJhODM3NDI0ODFlYjBiY2IwMmZmMWMyZDhkODQ4M2I4ZmM0MTkiLCJpYXQiOjE2NDk4NDYyODguMjg0NSwibmJmIjoxNjQ5ODQ2Mjg4LjI4NDUsImV4cCI6MTY0OTkzMjY4OC4yNzE5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.T5e9mmk6wmuGg4vRF9vxUW4k6EypI6_psnTdaNGPP3_J_AbNDdb9IDH9Kgoa90B7TNqPd1K3JdA-pB511QBDe8MPwaxO4WJl1X5VSiscFO99oBHS5mTqcgGy-BEWEVJII8PNNLP7JtYG3DXpySda2lzQdkyARo3mh0m3Vj0qUNLwJeiPfzS0U36pYSYiGxM_4GxWcNKAHjqqvRWOPBFTgaNJa5JQb4lXCoW_NXQr3Zy7mHpbn_VyibBQwJup8f8oI5ufjGaAjurjDM4e3NJoGaQsqj0hYDnjcTHPrY1Si9ZPZDBGgextTFtVocxOSu2B6SNH4X6h7nrkQpG5kUTJ23ZFf-T2MKbQEfjDWBGCWe9Xv6cWjbsvyXSKC2fIW-lUZK2Y5J_QGF80mmz5fy27C0wNX36_ZZ041cSKhUdogBxSeITcLfIdYUUMcH1_4OmTfari-47ywtdi_nwB78xKRiOsqXiSRO4GfyJqvKiYpAqPaNMC-p-T_G6U9bux-4gvAbV-PMYrvQymF_kYJrWEaDUAM2M44StEOkObfj94m3tejfZcL69TIsu8R0Bd1RHHJqoImV6xOkgArmhdBZnRgjQebOvIIrZ-AUY2APcdiolD2EUIg1c1Yl1Y8N8OhA0nhqCgSnHqy4JFqf7JyX0KjkvtpTM_z0DjTzU5tjc72BU

### -- relations || with=property,property.names,group,group.names,values,selectionValues
GET https://skorohoda.plentymarkets-cloud02.com/rest/v2/properties/relations?targetId=in:34595&with=property,property.names,group,group.names,values,selectionValues
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmI3Yzc3MWJjNjdiMDAzNzBmMDcyZjUxYzg2N2NlZTE4N2E3ZDEyM2YwNmJhODM3NDI0ODFlYjBiY2IwMmZmMWMyZDhkODQ4M2I4ZmM0MTkiLCJpYXQiOjE2NDk4NDYyODguMjg0NSwibmJmIjoxNjQ5ODQ2Mjg4LjI4NDUsImV4cCI6MTY0OTkzMjY4OC4yNzE5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.T5e9mmk6wmuGg4vRF9vxUW4k6EypI6_psnTdaNGPP3_J_AbNDdb9IDH9Kgoa90B7TNqPd1K3JdA-pB511QBDe8MPwaxO4WJl1X5VSiscFO99oBHS5mTqcgGy-BEWEVJII8PNNLP7JtYG3DXpySda2lzQdkyARo3mh0m3Vj0qUNLwJeiPfzS0U36pYSYiGxM_4GxWcNKAHjqqvRWOPBFTgaNJa5JQb4lXCoW_NXQr3Zy7mHpbn_VyibBQwJup8f8oI5ufjGaAjurjDM4e3NJoGaQsqj0hYDnjcTHPrY1Si9ZPZDBGgextTFtVocxOSu2B6SNH4X6h7nrkQpG5kUTJ23ZFf-T2MKbQEfjDWBGCWe9Xv6cWjbsvyXSKC2fIW-lUZK2Y5J_QGF80mmz5fy27C0wNX36_ZZ041cSKhUdogBxSeITcLfIdYUUMcH1_4OmTfari-47ywtdi_nwB78xKRiOsqXiSRO4GfyJqvKiYpAqPaNMC-p-T_G6U9bux-4gvAbV-PMYrvQymF_kYJrWEaDUAM2M44StEOkObfj94m3tejfZcL69TIsu8R0Bd1RHHJqoImV6xOkgArmhdBZnRgjQebOvIIrZ-AUY2APcdiolD2EUIg1c1Yl1Y8N8OhA0nhqCgSnHqy4JFqf7JyX0KjkvtpTM_z0DjTzU5tjc72BU

### -- relation values
GET https://skorohoda.plentymarkets-cloud02.com/rest/v2/properties/relations/values/4043
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmI3Yzc3MWJjNjdiMDAzNzBmMDcyZjUxYzg2N2NlZTE4N2E3ZDEyM2YwNmJhODM3NDI0ODFlYjBiY2IwMmZmMWMyZDhkODQ4M2I4ZmM0MTkiLCJpYXQiOjE2NDk4NDYyODguMjg0NSwibmJmIjoxNjQ5ODQ2Mjg4LjI4NDUsImV4cCI6MTY0OTkzMjY4OC4yNzE5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.T5e9mmk6wmuGg4vRF9vxUW4k6EypI6_psnTdaNGPP3_J_AbNDdb9IDH9Kgoa90B7TNqPd1K3JdA-pB511QBDe8MPwaxO4WJl1X5VSiscFO99oBHS5mTqcgGy-BEWEVJII8PNNLP7JtYG3DXpySda2lzQdkyARo3mh0m3Vj0qUNLwJeiPfzS0U36pYSYiGxM_4GxWcNKAHjqqvRWOPBFTgaNJa5JQb4lXCoW_NXQr3Zy7mHpbn_VyibBQwJup8f8oI5ufjGaAjurjDM4e3NJoGaQsqj0hYDnjcTHPrY1Si9ZPZDBGgextTFtVocxOSu2B6SNH4X6h7nrkQpG5kUTJ23ZFf-T2MKbQEfjDWBGCWe9Xv6cWjbsvyXSKC2fIW-lUZK2Y5J_QGF80mmz5fy27C0wNX36_ZZ041cSKhUdogBxSeITcLfIdYUUMcH1_4OmTfari-47ywtdi_nwB78xKRiOsqXiSRO4GfyJqvKiYpAqPaNMC-p-T_G6U9bux-4gvAbV-PMYrvQymF_kYJrWEaDUAM2M44StEOkObfj94m3tejfZcL69TIsu8R0Bd1RHHJqoImV6xOkgArmhdBZnRgjQebOvIIrZ-AUY2APcdiolD2EUIg1c1Yl1Y8N8OhA0nhqCgSnHqy4JFqf7JyX0KjkvtpTM_z0DjTzU5tjc72BU

### id: 4633 & with: with=values,selectionValues
GET https://skorohoda.plentymarkets-cloud02.com/rest/v2/properties/relations?with=values,selectionValues&id=4635
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmI3Yzc3MWJjNjdiMDAzNzBmMDcyZjUxYzg2N2NlZTE4N2E3ZDEyM2YwNmJhODM3NDI0ODFlYjBiY2IwMmZmMWMyZDhkODQ4M2I4ZmM0MTkiLCJpYXQiOjE2NDk4NDYyODguMjg0NSwibmJmIjoxNjQ5ODQ2Mjg4LjI4NDUsImV4cCI6MTY0OTkzMjY4OC4yNzE5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.T5e9mmk6wmuGg4vRF9vxUW4k6EypI6_psnTdaNGPP3_J_AbNDdb9IDH9Kgoa90B7TNqPd1K3JdA-pB511QBDe8MPwaxO4WJl1X5VSiscFO99oBHS5mTqcgGy-BEWEVJII8PNNLP7JtYG3DXpySda2lzQdkyARo3mh0m3Vj0qUNLwJeiPfzS0U36pYSYiGxM_4GxWcNKAHjqqvRWOPBFTgaNJa5JQb4lXCoW_NXQr3Zy7mHpbn_VyibBQwJup8f8oI5ufjGaAjurjDM4e3NJoGaQsqj0hYDnjcTHPrY1Si9ZPZDBGgextTFtVocxOSu2B6SNH4X6h7nrkQpG5kUTJ23ZFf-T2MKbQEfjDWBGCWe9Xv6cWjbsvyXSKC2fIW-lUZK2Y5J_QGF80mmz5fy27C0wNX36_ZZ041cSKhUdogBxSeITcLfIdYUUMcH1_4OmTfari-47ywtdi_nwB78xKRiOsqXiSRO4GfyJqvKiYpAqPaNMC-p-T_G6U9bux-4gvAbV-PMYrvQymF_kYJrWEaDUAM2M44StEOkObfj94m3tejfZcL69TIsu8R0Bd1RHHJqoImV6xOkgArmhdBZnRgjQebOvIIrZ-AUY2APcdiolD2EUIg1c1Yl1Y8N8OhA0nhqCgSnHqy4JFqf7JyX0KjkvtpTM_z0DjTzU5tjc72BU

### property selections
GET https://skorohoda.plentymarkets-cloud02.com/rest/v2/properties/selections?propertyId=244
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmI3Yzc3MWJjNjdiMDAzNzBmMDcyZjUxYzg2N2NlZTE4N2E3ZDEyM2YwNmJhODM3NDI0ODFlYjBiY2IwMmZmMWMyZDhkODQ4M2I4ZmM0MTkiLCJpYXQiOjE2NDk4NDYyODguMjg0NSwibmJmIjoxNjQ5ODQ2Mjg4LjI4NDUsImV4cCI6MTY0OTkzMjY4OC4yNzE5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.T5e9mmk6wmuGg4vRF9vxUW4k6EypI6_psnTdaNGPP3_J_AbNDdb9IDH9Kgoa90B7TNqPd1K3JdA-pB511QBDe8MPwaxO4WJl1X5VSiscFO99oBHS5mTqcgGy-BEWEVJII8PNNLP7JtYG3DXpySda2lzQdkyARo3mh0m3Vj0qUNLwJeiPfzS0U36pYSYiGxM_4GxWcNKAHjqqvRWOPBFTgaNJa5JQb4lXCoW_NXQr3Zy7mHpbn_VyibBQwJup8f8oI5ufjGaAjurjDM4e3NJoGaQsqj0hYDnjcTHPrY1Si9ZPZDBGgextTFtVocxOSu2B6SNH4X6h7nrkQpG5kUTJ23ZFf-T2MKbQEfjDWBGCWe9Xv6cWjbsvyXSKC2fIW-lUZK2Y5J_QGF80mmz5fy27C0wNX36_ZZ041cSKhUdogBxSeITcLfIdYUUMcH1_4OmTfari-47ywtdi_nwB78xKRiOsqXiSRO4GfyJqvKiYpAqPaNMC-p-T_G6U9bux-4gvAbV-PMYrvQymF_kYJrWEaDUAM2M44StEOkObfj94m3tejfZcL69TIsu8R0Bd1RHHJqoImV6xOkgArmhdBZnRgjQebOvIIrZ-AUY2APcdiolD2EUIg1c1Yl1Y8N8OhA0nhqCgSnHqy4JFqf7JyX0KjkvtpTM_z0DjTzU5tjc72BU


###
GET https://skorohoda.plentymarkets-cloud02.com/rest/properties/groups/types
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmI3Yzc3MWJjNjdiMDAzNzBmMDcyZjUxYzg2N2NlZTE4N2E3ZDEyM2YwNmJhODM3NDI0ODFlYjBiY2IwMmZmMWMyZDhkODQ4M2I4ZmM0MTkiLCJpYXQiOjE2NDk4NDYyODguMjg0NSwibmJmIjoxNjQ5ODQ2Mjg4LjI4NDUsImV4cCI6MTY0OTkzMjY4OC4yNzE5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.T5e9mmk6wmuGg4vRF9vxUW4k6EypI6_psnTdaNGPP3_J_AbNDdb9IDH9Kgoa90B7TNqPd1K3JdA-pB511QBDe8MPwaxO4WJl1X5VSiscFO99oBHS5mTqcgGy-BEWEVJII8PNNLP7JtYG3DXpySda2lzQdkyARo3mh0m3Vj0qUNLwJeiPfzS0U36pYSYiGxM_4GxWcNKAHjqqvRWOPBFTgaNJa5JQb4lXCoW_NXQr3Zy7mHpbn_VyibBQwJup8f8oI5ufjGaAjurjDM4e3NJoGaQsqj0hYDnjcTHPrY1Si9ZPZDBGgextTFtVocxOSu2B6SNH4X6h7nrkQpG5kUTJ23ZFf-T2MKbQEfjDWBGCWe9Xv6cWjbsvyXSKC2fIW-lUZK2Y5J_QGF80mmz5fy27C0wNX36_ZZ041cSKhUdogBxSeITcLfIdYUUMcH1_4OmTfari-47ywtdi_nwB78xKRiOsqXiSRO4GfyJqvKiYpAqPaNMC-p-T_G6U9bux-4gvAbV-PMYrvQymF_kYJrWEaDUAM2M44StEOkObfj94m3tejfZcL69TIsu8R0Bd1RHHJqoImV6xOkgArmhdBZnRgjQebOvIIrZ-AUY2APcdiolD2EUIg1c1Yl1Y8N8OhA0nhqCgSnHqy4JFqf7JyX0KjkvtpTM_z0DjTzU5tjc72BU

### -- System lang
GET https://skorohoda.plentymarkets-cloud02.com/rest/v2/properties/systemlang
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmI3Yzc3MWJjNjdiMDAzNzBmMDcyZjUxYzg2N2NlZTE4N2E3ZDEyM2YwNmJhODM3NDI0ODFlYjBiY2IwMmZmMWMyZDhkODQ4M2I4ZmM0MTkiLCJpYXQiOjE2NDk4NDYyODguMjg0NSwibmJmIjoxNjQ5ODQ2Mjg4LjI4NDUsImV4cCI6MTY0OTkzMjY4OC4yNzE5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.T5e9mmk6wmuGg4vRF9vxUW4k6EypI6_psnTdaNGPP3_J_AbNDdb9IDH9Kgoa90B7TNqPd1K3JdA-pB511QBDe8MPwaxO4WJl1X5VSiscFO99oBHS5mTqcgGy-BEWEVJII8PNNLP7JtYG3DXpySda2lzQdkyARo3mh0m3Vj0qUNLwJeiPfzS0U36pYSYiGxM_4GxWcNKAHjqqvRWOPBFTgaNJa5JQb4lXCoW_NXQr3Zy7mHpbn_VyibBQwJup8f8oI5ufjGaAjurjDM4e3NJoGaQsqj0hYDnjcTHPrY1Si9ZPZDBGgextTFtVocxOSu2B6SNH4X6h7nrkQpG5kUTJ23ZFf-T2MKbQEfjDWBGCWe9Xv6cWjbsvyXSKC2fIW-lUZK2Y5J_QGF80mmz5fy27C0wNX36_ZZ041cSKhUdogBxSeITcLfIdYUUMcH1_4OmTfari-47ywtdi_nwB78xKRiOsqXiSRO4GfyJqvKiYpAqPaNMC-p-T_G6U9bux-4gvAbV-PMYrvQymF_kYJrWEaDUAM2M44StEOkObfj94m3tejfZcL69TIsu8R0Bd1RHHJqoImV6xOkgArmhdBZnRgjQebOvIIrZ-AUY2APcdiolD2EUIg1c1Yl1Y8N8OhA0nhqCgSnHqy4JFqf7JyX0KjkvtpTM_z0DjTzU5tjc72BU

### -- Create Group
POST https://skorohoda.plentymarkets-cloud02.com/rest/v2/properties/groups
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmI3Yzc3MWJjNjdiMDAzNzBmMDcyZjUxYzg2N2NlZTE4N2E3ZDEyM2YwNmJhODM3NDI0ODFlYjBiY2IwMmZmMWMyZDhkODQ4M2I4ZmM0MTkiLCJpYXQiOjE2NDk4NDYyODguMjg0NSwibmJmIjoxNjQ5ODQ2Mjg4LjI4NDUsImV4cCI6MTY0OTkzMjY4OC4yNzE5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.T5e9mmk6wmuGg4vRF9vxUW4k6EypI6_psnTdaNGPP3_J_AbNDdb9IDH9Kgoa90B7TNqPd1K3JdA-pB511QBDe8MPwaxO4WJl1X5VSiscFO99oBHS5mTqcgGy-BEWEVJII8PNNLP7JtYG3DXpySda2lzQdkyARo3mh0m3Vj0qUNLwJeiPfzS0U36pYSYiGxM_4GxWcNKAHjqqvRWOPBFTgaNJa5JQb4lXCoW_NXQr3Zy7mHpbn_VyibBQwJup8f8oI5ufjGaAjurjDM4e3NJoGaQsqj0hYDnjcTHPrY1Si9ZPZDBGgextTFtVocxOSu2B6SNH4X6h7nrkQpG5kUTJ23ZFf-T2MKbQEfjDWBGCWe9Xv6cWjbsvyXSKC2fIW-lUZK2Y5J_QGF80mmz5fy27C0wNX36_ZZ041cSKhUdogBxSeITcLfIdYUUMcH1_4OmTfari-47ywtdi_nwB78xKRiOsqXiSRO4GfyJqvKiYpAqPaNMC-p-T_G6U9bux-4gvAbV-PMYrvQymF_kYJrWEaDUAM2M44StEOkObfj94m3tejfZcL69TIsu8R0Bd1RHHJqoImV6xOkgArmhdBZnRgjQebOvIIrZ-AUY2APcdiolD2EUIg1c1Yl1Y8N8OhA0nhqCgSnHqy4JFqf7JyX0KjkvtpTM_z0DjTzU5tjc72BU

{
    "position": 10,
    "names": [
        {
            "lang": "en",
            "name": "Test Property Group"
        },
        {
            "lang": "de",
            "name": "Test Property Group DE "
        }
    ]
}


### -- Create property
POST https://skorohoda.plentymarkets-cloud02.com/rest/properties
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmI3Yzc3MWJjNjdiMDAzNzBmMDcyZjUxYzg2N2NlZTE4N2E3ZDEyM2YwNmJhODM3NDI0ODFlYjBiY2IwMmZmMWMyZDhkODQ4M2I4ZmM0MTkiLCJpYXQiOjE2NDk4NDYyODguMjg0NSwibmJmIjoxNjQ5ODQ2Mjg4LjI4NDUsImV4cCI6MTY0OTkzMjY4OC4yNzE5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.T5e9mmk6wmuGg4vRF9vxUW4k6EypI6_psnTdaNGPP3_J_AbNDdb9IDH9Kgoa90B7TNqPd1K3JdA-pB511QBDe8MPwaxO4WJl1X5VSiscFO99oBHS5mTqcgGy-BEWEVJII8PNNLP7JtYG3DXpySda2lzQdkyARo3mh0m3Vj0qUNLwJeiPfzS0U36pYSYiGxM_4GxWcNKAHjqqvRWOPBFTgaNJa5JQb4lXCoW_NXQr3Zy7mHpbn_VyibBQwJup8f8oI5ufjGaAjurjDM4e3NJoGaQsqj0hYDnjcTHPrY1Si9ZPZDBGgextTFtVocxOSu2B6SNH4X6h7nrkQpG5kUTJ23ZFf-T2MKbQEfjDWBGCWe9Xv6cWjbsvyXSKC2fIW-lUZK2Y5J_QGF80mmz5fy27C0wNX36_ZZ041cSKhUdogBxSeITcLfIdYUUMcH1_4OmTfari-47ywtdi_nwB78xKRiOsqXiSRO4GfyJqvKiYpAqPaNMC-p-T_G6U9bux-4gvAbV-PMYrvQymF_kYJrWEaDUAM2M44StEOkObfj94m3tejfZcL69TIsu8R0Bd1RHHJqoImV6xOkgArmhdBZnRgjQebOvIIrZ-AUY2APcdiolD2EUIg1c1Yl1Y8N8OhA0nhqCgSnHqy4JFqf7JyX0KjkvtpTM_z0DjTzU5tjc72BU

{
    "cast": "selection",
    "type": "item",
    "position": 0,
    "names": [
        {
            "lang": "1",
            "name": "test_select_02",
            "description": "test_select_01 Lang 1"
        },
        {
            "lang": "en",
            "name": "test_select_02",
            "description": "test_select_01 Lang EN"
        }
    ]
}

### -- Create property selection values
POST https://skorohoda.plentymarkets-cloud02.com/rest/v2/properties/selections
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmI3Yzc3MWJjNjdiMDAzNzBmMDcyZjUxYzg2N2NlZTE4N2E3ZDEyM2YwNmJhODM3NDI0ODFlYjBiY2IwMmZmMWMyZDhkODQ4M2I4ZmM0MTkiLCJpYXQiOjE2NDk4NDYyODguMjg0NSwibmJmIjoxNjQ5ODQ2Mjg4LjI4NDUsImV4cCI6MTY0OTkzMjY4OC4yNzE5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.T5e9mmk6wmuGg4vRF9vxUW4k6EypI6_psnTdaNGPP3_J_AbNDdb9IDH9Kgoa90B7TNqPd1K3JdA-pB511QBDe8MPwaxO4WJl1X5VSiscFO99oBHS5mTqcgGy-BEWEVJII8PNNLP7JtYG3DXpySda2lzQdkyARo3mh0m3Vj0qUNLwJeiPfzS0U36pYSYiGxM_4GxWcNKAHjqqvRWOPBFTgaNJa5JQb4lXCoW_NXQr3Zy7mHpbn_VyibBQwJup8f8oI5ufjGaAjurjDM4e3NJoGaQsqj0hYDnjcTHPrY1Si9ZPZDBGgextTFtVocxOSu2B6SNH4X6h7nrkQpG5kUTJ23ZFf-T2MKbQEfjDWBGCWe9Xv6cWjbsvyXSKC2fIW-lUZK2Y5J_QGF80mmz5fy27C0wNX36_ZZ041cSKhUdogBxSeITcLfIdYUUMcH1_4OmTfari-47ywtdi_nwB78xKRiOsqXiSRO4GfyJqvKiYpAqPaNMC-p-T_G6U9bux-4gvAbV-PMYrvQymF_kYJrWEaDUAM2M44StEOkObfj94m3tejfZcL69TIsu8R0Bd1RHHJqoImV6xOkgArmhdBZnRgjQebOvIIrZ-AUY2APcdiolD2EUIg1c1Yl1Y8N8OhA0nhqCgSnHqy4JFqf7JyX0KjkvtpTM_z0DjTzU5tjc72BU

{
    "propertyId": 332,
    "position": 0,
    "names": [
        {
            "lang": "en",
            "name": "VALUE 02 en",
            "description": "VALUE 01"
        },
        {
            "lang": "de",
            "name": "VALUE 02 de",
            "description": "VALUE 02"
        }
    ]
}

### -- Create property selection values

### -- Create property selection value relations

####
DELETE https://skorohoda.plentymarkets-cloud02.com/rest/properties/232
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmI3Yzc3MWJjNjdiMDAzNzBmMDcyZjUxYzg2N2NlZTE4N2E3ZDEyM2YwNmJhODM3NDI0ODFlYjBiY2IwMmZmMWMyZDhkODQ4M2I4ZmM0MTkiLCJpYXQiOjE2NDk4NDYyODguMjg0NSwibmJmIjoxNjQ5ODQ2Mjg4LjI4NDUsImV4cCI6MTY0OTkzMjY4OC4yNzE5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.T5e9mmk6wmuGg4vRF9vxUW4k6EypI6_psnTdaNGPP3_J_AbNDdb9IDH9Kgoa90B7TNqPd1K3JdA-pB511QBDe8MPwaxO4WJl1X5VSiscFO99oBHS5mTqcgGy-BEWEVJII8PNNLP7JtYG3DXpySda2lzQdkyARo3mh0m3Vj0qUNLwJeiPfzS0U36pYSYiGxM_4GxWcNKAHjqqvRWOPBFTgaNJa5JQb4lXCoW_NXQr3Zy7mHpbn_VyibBQwJup8f8oI5ufjGaAjurjDM4e3NJoGaQsqj0hYDnjcTHPrY1Si9ZPZDBGgextTFtVocxOSu2B6SNH4X6h7nrkQpG5kUTJ23ZFf-T2MKbQEfjDWBGCWe9Xv6cWjbsvyXSKC2fIW-lUZK2Y5J_QGF80mmz5fy27C0wNX36_ZZ041cSKhUdogBxSeITcLfIdYUUMcH1_4OmTfari-47ywtdi_nwB78xKRiOsqXiSRO4GfyJqvKiYpAqPaNMC-p-T_G6U9bux-4gvAbV-PMYrvQymF_kYJrWEaDUAM2M44StEOkObfj94m3tejfZcL69TIsu8R0Bd1RHHJqoImV6xOkgArmhdBZnRgjQebOvIIrZ-AUY2APcdiolD2EUIg1c1Yl1Y8N8OhA0nhqCgSnHqy4JFqf7JyX0KjkvtpTM_z0DjTzU5tjc72BU

{
    "propertyId": "232"
}

