GET https://skorohoda.plentymarkets-cloud02.com/rest/properties
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGM4YzFlZmRhMWYxMTlkYTBmOTUxYzJmMzNhZGE4OWI4NDcyM2Y2ZjFhNDE4ZGIzODRlNGIzODdiMDQ0MzdmNjI5NDUzNzEyZTk4NDIwNTQiLCJpYXQiOjE2MjY2MjA0MDMsIm5iZiI6MTYyNjYyMDQwMywiZXhwIjoxNjI2NzA2ODAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.xBP7iZcne3oD7jhckW5NyONxKx9LrMSIaoHIan2zmSvvQfVT4EOOAD0lIY2_j82aLTsYqI40l9r3vGPXCUJNIx285iZ-RTXoEsSmLW_3BlLsBZJVN5-vofYPHvXJTsGxgvbFrw8iqmE6VkZh99AYvdW-5xHoQJ9NWT482iBBBqwNzfAggvxTG6ISbwEtZzWqEtz21Dv6TDb5U8rg-0a6OiRx35fIj22my3bDgjyspl7TnyDQIw-E3gYvpw4GSzV712br9i1zHLdM6oeaRQqrBSb-MPjI2hO4LEVjCts4EhK-Ezvfrw8xQIcQTheaQzzVjQ97-Q-tByQ4M6QRniR6tsZ58502IRCbrIavTiHewg53VmBUzH9iozWWPFn_1fLCDnPBTY2nED_JhDmNNyhRsldZ_x-LF9QXe7nMS-SbpvJ0ao1jFPb3HS9ESG39bUh_za4Ew-g1QylO2xsuDbdNd3W0PNPXLxwLS0DeTL1XVK5FmTpMxEhd40IEYMQmmaYWx-Yf7lSG3ITn-L7MP_C9N7ZmzuP4CSpDyPTBaf4klpRmoSKySLGCeVeITdTsNF5410OlK7X5xwpGLCCozNJRNfZI_RtDQrfayFUBfR1rUsyy7_ACNGiJSUq72IVYx51LeUt791Qo7k4YDBzQ6HEwqnI0zrXkX_bkjRrSmy90_sw

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/properties?id=253,246,247
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGM4YzFlZmRhMWYxMTlkYTBmOTUxYzJmMzNhZGE4OWI4NDcyM2Y2ZjFhNDE4ZGIzODRlNGIzODdiMDQ0MzdmNjI5NDUzNzEyZTk4NDIwNTQiLCJpYXQiOjE2MjY2MjA0MDMsIm5iZiI6MTYyNjYyMDQwMywiZXhwIjoxNjI2NzA2ODAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.xBP7iZcne3oD7jhckW5NyONxKx9LrMSIaoHIan2zmSvvQfVT4EOOAD0lIY2_j82aLTsYqI40l9r3vGPXCUJNIx285iZ-RTXoEsSmLW_3BlLsBZJVN5-vofYPHvXJTsGxgvbFrw8iqmE6VkZh99AYvdW-5xHoQJ9NWT482iBBBqwNzfAggvxTG6ISbwEtZzWqEtz21Dv6TDb5U8rg-0a6OiRx35fIj22my3bDgjyspl7TnyDQIw-E3gYvpw4GSzV712br9i1zHLdM6oeaRQqrBSb-MPjI2hO4LEVjCts4EhK-Ezvfrw8xQIcQTheaQzzVjQ97-Q-tByQ4M6QRniR6tsZ58502IRCbrIavTiHewg53VmBUzH9iozWWPFn_1fLCDnPBTY2nED_JhDmNNyhRsldZ_x-LF9QXe7nMS-SbpvJ0ao1jFPb3HS9ESG39bUh_za4Ew-g1QylO2xsuDbdNd3W0PNPXLxwLS0DeTL1XVK5FmTpMxEhd40IEYMQmmaYWx-Yf7lSG3ITn-L7MP_C9N7ZmzuP4CSpDyPTBaf4klpRmoSKySLGCeVeITdTsNF5410OlK7X5xwpGLCCozNJRNfZI_RtDQrfayFUBfR1rUsyy7_ACNGiJSUq72IVYx51LeUt791Qo7k4YDBzQ6HEwqnI0zrXkX_bkjRrSmy90_sw

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/properties?typeIdentifier=item
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGM4YzFlZmRhMWYxMTlkYTBmOTUxYzJmMzNhZGE4OWI4NDcyM2Y2ZjFhNDE4ZGIzODRlNGIzODdiMDQ0MzdmNjI5NDUzNzEyZTk4NDIwNTQiLCJpYXQiOjE2MjY2MjA0MDMsIm5iZiI6MTYyNjYyMDQwMywiZXhwIjoxNjI2NzA2ODAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.xBP7iZcne3oD7jhckW5NyONxKx9LrMSIaoHIan2zmSvvQfVT4EOOAD0lIY2_j82aLTsYqI40l9r3vGPXCUJNIx285iZ-RTXoEsSmLW_3BlLsBZJVN5-vofYPHvXJTsGxgvbFrw8iqmE6VkZh99AYvdW-5xHoQJ9NWT482iBBBqwNzfAggvxTG6ISbwEtZzWqEtz21Dv6TDb5U8rg-0a6OiRx35fIj22my3bDgjyspl7TnyDQIw-E3gYvpw4GSzV712br9i1zHLdM6oeaRQqrBSb-MPjI2hO4LEVjCts4EhK-Ezvfrw8xQIcQTheaQzzVjQ97-Q-tByQ4M6QRniR6tsZ58502IRCbrIavTiHewg53VmBUzH9iozWWPFn_1fLCDnPBTY2nED_JhDmNNyhRsldZ_x-LF9QXe7nMS-SbpvJ0ao1jFPb3HS9ESG39bUh_za4Ew-g1QylO2xsuDbdNd3W0PNPXLxwLS0DeTL1XVK5FmTpMxEhd40IEYMQmmaYWx-Yf7lSG3ITn-L7MP_C9N7ZmzuP4CSpDyPTBaf4klpRmoSKySLGCeVeITdTsNF5410OlK7X5xwpGLCCozNJRNfZI_RtDQrfayFUBfR1rUsyy7_ACNGiJSUq72IVYx51LeUt791Qo7k4YDBzQ6HEwqnI0zrXkX_bkjRrSmy90_sw

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/properties?page1&itemsPerPage=2
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGM4YzFlZmRhMWYxMTlkYTBmOTUxYzJmMzNhZGE4OWI4NDcyM2Y2ZjFhNDE4ZGIzODRlNGIzODdiMDQ0MzdmNjI5NDUzNzEyZTk4NDIwNTQiLCJpYXQiOjE2MjY2MjA0MDMsIm5iZiI6MTYyNjYyMDQwMywiZXhwIjoxNjI2NzA2ODAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.xBP7iZcne3oD7jhckW5NyONxKx9LrMSIaoHIan2zmSvvQfVT4EOOAD0lIY2_j82aLTsYqI40l9r3vGPXCUJNIx285iZ-RTXoEsSmLW_3BlLsBZJVN5-vofYPHvXJTsGxgvbFrw8iqmE6VkZh99AYvdW-5xHoQJ9NWT482iBBBqwNzfAggvxTG6ISbwEtZzWqEtz21Dv6TDb5U8rg-0a6OiRx35fIj22my3bDgjyspl7TnyDQIw-E3gYvpw4GSzV712br9i1zHLdM6oeaRQqrBSb-MPjI2hO4LEVjCts4EhK-Ezvfrw8xQIcQTheaQzzVjQ97-Q-tByQ4M6QRniR6tsZ58502IRCbrIavTiHewg53VmBUzH9iozWWPFn_1fLCDnPBTY2nED_JhDmNNyhRsldZ_x-LF9QXe7nMS-SbpvJ0ao1jFPb3HS9ESG39bUh_za4Ew-g1QylO2xsuDbdNd3W0PNPXLxwLS0DeTL1XVK5FmTpMxEhd40IEYMQmmaYWx-Yf7lSG3ITn-L7MP_C9N7ZmzuP4CSpDyPTBaf4klpRmoSKySLGCeVeITdTsNF5410OlK7X5xwpGLCCozNJRNfZI_RtDQrfayFUBfR1rUsyy7_ACNGiJSUq72IVYx51LeUt791Qo7k4YDBzQ6HEwqnI0zrXkX_bkjRrSmy90_sw

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/properties?page=2&paginate=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGM4YzFlZmRhMWYxMTlkYTBmOTUxYzJmMzNhZGE4OWI4NDcyM2Y2ZjFhNDE4ZGIzODRlNGIzODdiMDQ0MzdmNjI5NDUzNzEyZTk4NDIwNTQiLCJpYXQiOjE2MjY2MjA0MDMsIm5iZiI6MTYyNjYyMDQwMywiZXhwIjoxNjI2NzA2ODAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.xBP7iZcne3oD7jhckW5NyONxKx9LrMSIaoHIan2zmSvvQfVT4EOOAD0lIY2_j82aLTsYqI40l9r3vGPXCUJNIx285iZ-RTXoEsSmLW_3BlLsBZJVN5-vofYPHvXJTsGxgvbFrw8iqmE6VkZh99AYvdW-5xHoQJ9NWT482iBBBqwNzfAggvxTG6ISbwEtZzWqEtz21Dv6TDb5U8rg-0a6OiRx35fIj22my3bDgjyspl7TnyDQIw-E3gYvpw4GSzV712br9i1zHLdM6oeaRQqrBSb-MPjI2hO4LEVjCts4EhK-Ezvfrw8xQIcQTheaQzzVjQ97-Q-tByQ4M6QRniR6tsZ58502IRCbrIavTiHewg53VmBUzH9iozWWPFn_1fLCDnPBTY2nED_JhDmNNyhRsldZ_x-LF9QXe7nMS-SbpvJ0ao1jFPb3HS9ESG39bUh_za4Ew-g1QylO2xsuDbdNd3W0PNPXLxwLS0DeTL1XVK5FmTpMxEhd40IEYMQmmaYWx-Yf7lSG3ITn-L7MP_C9N7ZmzuP4CSpDyPTBaf4klpRmoSKySLGCeVeITdTsNF5410OlK7X5xwpGLCCozNJRNfZI_RtDQrfayFUBfR1rUsyy7_ACNGiJSUq72IVYx51LeUt791Qo7k4YDBzQ6HEwqnI0zrXkX_bkjRrSmy90_sw

### filter by id as paramter instead of direct property call /rest/properties/241
GET https://skorohoda.plentymarkets-cloud02.com/rest/properties?id=244
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGM4YzFlZmRhMWYxMTlkYTBmOTUxYzJmMzNhZGE4OWI4NDcyM2Y2ZjFhNDE4ZGIzODRlNGIzODdiMDQ0MzdmNjI5NDUzNzEyZTk4NDIwNTQiLCJpYXQiOjE2MjY2MjA0MDMsIm5iZiI6MTYyNjYyMDQwMywiZXhwIjoxNjI2NzA2ODAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.xBP7iZcne3oD7jhckW5NyONxKx9LrMSIaoHIan2zmSvvQfVT4EOOAD0lIY2_j82aLTsYqI40l9r3vGPXCUJNIx285iZ-RTXoEsSmLW_3BlLsBZJVN5-vofYPHvXJTsGxgvbFrw8iqmE6VkZh99AYvdW-5xHoQJ9NWT482iBBBqwNzfAggvxTG6ISbwEtZzWqEtz21Dv6TDb5U8rg-0a6OiRx35fIj22my3bDgjyspl7TnyDQIw-E3gYvpw4GSzV712br9i1zHLdM6oeaRQqrBSb-MPjI2hO4LEVjCts4EhK-Ezvfrw8xQIcQTheaQzzVjQ97-Q-tByQ4M6QRniR6tsZ58502IRCbrIavTiHewg53VmBUzH9iozWWPFn_1fLCDnPBTY2nED_JhDmNNyhRsldZ_x-LF9QXe7nMS-SbpvJ0ao1jFPb3HS9ESG39bUh_za4Ew-g1QylO2xsuDbdNd3W0PNPXLxwLS0DeTL1XVK5FmTpMxEhd40IEYMQmmaYWx-Yf7lSG3ITn-L7MP_C9N7ZmzuP4CSpDyPTBaf4klpRmoSKySLGCeVeITdTsNF5410OlK7X5xwpGLCCozNJRNfZI_RtDQrfayFUBfR1rUsyy7_ACNGiJSUq72IVYx51LeUt791Qo7k4YDBzQ6HEwqnI0zrXkX_bkjRrSmy90_sw

### If id is pecified in parameter then all selections are included in response
GET https://skorohoda.plentymarkets-cloud02.com/rest/properties?id=241&with=selections
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGM4YzFlZmRhMWYxMTlkYTBmOTUxYzJmMzNhZGE4OWI4NDcyM2Y2ZjFhNDE4ZGIzODRlNGIzODdiMDQ0MzdmNjI5NDUzNzEyZTk4NDIwNTQiLCJpYXQiOjE2MjY2MjA0MDMsIm5iZiI6MTYyNjYyMDQwMywiZXhwIjoxNjI2NzA2ODAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.xBP7iZcne3oD7jhckW5NyONxKx9LrMSIaoHIan2zmSvvQfVT4EOOAD0lIY2_j82aLTsYqI40l9r3vGPXCUJNIx285iZ-RTXoEsSmLW_3BlLsBZJVN5-vofYPHvXJTsGxgvbFrw8iqmE6VkZh99AYvdW-5xHoQJ9NWT482iBBBqwNzfAggvxTG6ISbwEtZzWqEtz21Dv6TDb5U8rg-0a6OiRx35fIj22my3bDgjyspl7TnyDQIw-E3gYvpw4GSzV712br9i1zHLdM6oeaRQqrBSb-MPjI2hO4LEVjCts4EhK-Ezvfrw8xQIcQTheaQzzVjQ97-Q-tByQ4M6QRniR6tsZ58502IRCbrIavTiHewg53VmBUzH9iozWWPFn_1fLCDnPBTY2nED_JhDmNNyhRsldZ_x-LF9QXe7nMS-SbpvJ0ao1jFPb3HS9ESG39bUh_za4Ew-g1QylO2xsuDbdNd3W0PNPXLxwLS0DeTL1XVK5FmTpMxEhd40IEYMQmmaYWx-Yf7lSG3ITn-L7MP_C9N7ZmzuP4CSpDyPTBaf4klpRmoSKySLGCeVeITdTsNF5410OlK7X5xwpGLCCozNJRNfZI_RtDQrfayFUBfR1rUsyy7_ACNGiJSUq72IVYx51LeUt791Qo7k4YDBzQ6HEwqnI0zrXkX_bkjRrSmy90_sw

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/properties/names
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGM4YzFlZmRhMWYxMTlkYTBmOTUxYzJmMzNhZGE4OWI4NDcyM2Y2ZjFhNDE4ZGIzODRlNGIzODdiMDQ0MzdmNjI5NDUzNzEyZTk4NDIwNTQiLCJpYXQiOjE2MjY2MjA0MDMsIm5iZiI6MTYyNjYyMDQwMywiZXhwIjoxNjI2NzA2ODAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.xBP7iZcne3oD7jhckW5NyONxKx9LrMSIaoHIan2zmSvvQfVT4EOOAD0lIY2_j82aLTsYqI40l9r3vGPXCUJNIx285iZ-RTXoEsSmLW_3BlLsBZJVN5-vofYPHvXJTsGxgvbFrw8iqmE6VkZh99AYvdW-5xHoQJ9NWT482iBBBqwNzfAggvxTG6ISbwEtZzWqEtz21Dv6TDb5U8rg-0a6OiRx35fIj22my3bDgjyspl7TnyDQIw-E3gYvpw4GSzV712br9i1zHLdM6oeaRQqrBSb-MPjI2hO4LEVjCts4EhK-Ezvfrw8xQIcQTheaQzzVjQ97-Q-tByQ4M6QRniR6tsZ58502IRCbrIavTiHewg53VmBUzH9iozWWPFn_1fLCDnPBTY2nED_JhDmNNyhRsldZ_x-LF9QXe7nMS-SbpvJ0ao1jFPb3HS9ESG39bUh_za4Ew-g1QylO2xsuDbdNd3W0PNPXLxwLS0DeTL1XVK5FmTpMxEhd40IEYMQmmaYWx-Yf7lSG3ITn-L7MP_C9N7ZmzuP4CSpDyPTBaf4klpRmoSKySLGCeVeITdTsNF5410OlK7X5xwpGLCCozNJRNfZI_RtDQrfayFUBfR1rUsyy7_ACNGiJSUq72IVYx51LeUt791Qo7k4YDBzQ6HEwqnI0zrXkX_bkjRrSmy90_sw

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/properties/relations?relationTypeIdentifier=stock
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGM4YzFlZmRhMWYxMTlkYTBmOTUxYzJmMzNhZGE4OWI4NDcyM2Y2ZjFhNDE4ZGIzODRlNGIzODdiMDQ0MzdmNjI5NDUzNzEyZTk4NDIwNTQiLCJpYXQiOjE2MjY2MjA0MDMsIm5iZiI6MTYyNjYyMDQwMywiZXhwIjoxNjI2NzA2ODAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.xBP7iZcne3oD7jhckW5NyONxKx9LrMSIaoHIan2zmSvvQfVT4EOOAD0lIY2_j82aLTsYqI40l9r3vGPXCUJNIx285iZ-RTXoEsSmLW_3BlLsBZJVN5-vofYPHvXJTsGxgvbFrw8iqmE6VkZh99AYvdW-5xHoQJ9NWT482iBBBqwNzfAggvxTG6ISbwEtZzWqEtz21Dv6TDb5U8rg-0a6OiRx35fIj22my3bDgjyspl7TnyDQIw-E3gYvpw4GSzV712br9i1zHLdM6oeaRQqrBSb-MPjI2hO4LEVjCts4EhK-Ezvfrw8xQIcQTheaQzzVjQ97-Q-tByQ4M6QRniR6tsZ58502IRCbrIavTiHewg53VmBUzH9iozWWPFn_1fLCDnPBTY2nED_JhDmNNyhRsldZ_x-LF9QXe7nMS-SbpvJ0ao1jFPb3HS9ESG39bUh_za4Ew-g1QylO2xsuDbdNd3W0PNPXLxwLS0DeTL1XVK5FmTpMxEhd40IEYMQmmaYWx-Yf7lSG3ITn-L7MP_C9N7ZmzuP4CSpDyPTBaf4klpRmoSKySLGCeVeITdTsNF5410OlK7X5xwpGLCCozNJRNfZI_RtDQrfayFUBfR1rUsyy7_ACNGiJSUq72IVYx51LeUt791Qo7k4YDBzQ6HEwqnI0zrXkX_bkjRrSmy90_sw

### --- relations
GET https://skorohoda.plentymarkets-cloud02.com/rest/properties/relations/4005?with=values
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGM4YzFlZmRhMWYxMTlkYTBmOTUxYzJmMzNhZGE4OWI4NDcyM2Y2ZjFhNDE4ZGIzODRlNGIzODdiMDQ0MzdmNjI5NDUzNzEyZTk4NDIwNTQiLCJpYXQiOjE2MjY2MjA0MDMsIm5iZiI6MTYyNjYyMDQwMywiZXhwIjoxNjI2NzA2ODAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.xBP7iZcne3oD7jhckW5NyONxKx9LrMSIaoHIan2zmSvvQfVT4EOOAD0lIY2_j82aLTsYqI40l9r3vGPXCUJNIx285iZ-RTXoEsSmLW_3BlLsBZJVN5-vofYPHvXJTsGxgvbFrw8iqmE6VkZh99AYvdW-5xHoQJ9NWT482iBBBqwNzfAggvxTG6ISbwEtZzWqEtz21Dv6TDb5U8rg-0a6OiRx35fIj22my3bDgjyspl7TnyDQIw-E3gYvpw4GSzV712br9i1zHLdM6oeaRQqrBSb-MPjI2hO4LEVjCts4EhK-Ezvfrw8xQIcQTheaQzzVjQ97-Q-tByQ4M6QRniR6tsZ58502IRCbrIavTiHewg53VmBUzH9iozWWPFn_1fLCDnPBTY2nED_JhDmNNyhRsldZ_x-LF9QXe7nMS-SbpvJ0ao1jFPb3HS9ESG39bUh_za4Ew-g1QylO2xsuDbdNd3W0PNPXLxwLS0DeTL1XVK5FmTpMxEhd40IEYMQmmaYWx-Yf7lSG3ITn-L7MP_C9N7ZmzuP4CSpDyPTBaf4klpRmoSKySLGCeVeITdTsNF5410OlK7X5xwpGLCCozNJRNfZI_RtDQrfayFUBfR1rUsyy7_ACNGiJSUq72IVYx51LeUt791Qo7k4YDBzQ6HEwqnI0zrXkX_bkjRrSmy90_sw

### --- relations
GET https://skorohoda.plentymarkets-cloud02.com/rest/properties/relations?paginate=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGM4YzFlZmRhMWYxMTlkYTBmOTUxYzJmMzNhZGE4OWI4NDcyM2Y2ZjFhNDE4ZGIzODRlNGIzODdiMDQ0MzdmNjI5NDUzNzEyZTk4NDIwNTQiLCJpYXQiOjE2MjY2MjA0MDMsIm5iZiI6MTYyNjYyMDQwMywiZXhwIjoxNjI2NzA2ODAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.xBP7iZcne3oD7jhckW5NyONxKx9LrMSIaoHIan2zmSvvQfVT4EOOAD0lIY2_j82aLTsYqI40l9r3vGPXCUJNIx285iZ-RTXoEsSmLW_3BlLsBZJVN5-vofYPHvXJTsGxgvbFrw8iqmE6VkZh99AYvdW-5xHoQJ9NWT482iBBBqwNzfAggvxTG6ISbwEtZzWqEtz21Dv6TDb5U8rg-0a6OiRx35fIj22my3bDgjyspl7TnyDQIw-E3gYvpw4GSzV712br9i1zHLdM6oeaRQqrBSb-MPjI2hO4LEVjCts4EhK-Ezvfrw8xQIcQTheaQzzVjQ97-Q-tByQ4M6QRniR6tsZ58502IRCbrIavTiHewg53VmBUzH9iozWWPFn_1fLCDnPBTY2nED_JhDmNNyhRsldZ_x-LF9QXe7nMS-SbpvJ0ao1jFPb3HS9ESG39bUh_za4Ew-g1QylO2xsuDbdNd3W0PNPXLxwLS0DeTL1XVK5FmTpMxEhd40IEYMQmmaYWx-Yf7lSG3ITn-L7MP_C9N7ZmzuP4CSpDyPTBaf4klpRmoSKySLGCeVeITdTsNF5410OlK7X5xwpGLCCozNJRNfZI_RtDQrfayFUBfR1rUsyy7_ACNGiJSUq72IVYx51LeUt791Qo7k4YDBzQ6HEwqnI0zrXkX_bkjRrSmy90_sw

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/properties/relations/values
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGM4YzFlZmRhMWYxMTlkYTBmOTUxYzJmMzNhZGE4OWI4NDcyM2Y2ZjFhNDE4ZGIzODRlNGIzODdiMDQ0MzdmNjI5NDUzNzEyZTk4NDIwNTQiLCJpYXQiOjE2MjY2MjA0MDMsIm5iZiI6MTYyNjYyMDQwMywiZXhwIjoxNjI2NzA2ODAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.xBP7iZcne3oD7jhckW5NyONxKx9LrMSIaoHIan2zmSvvQfVT4EOOAD0lIY2_j82aLTsYqI40l9r3vGPXCUJNIx285iZ-RTXoEsSmLW_3BlLsBZJVN5-vofYPHvXJTsGxgvbFrw8iqmE6VkZh99AYvdW-5xHoQJ9NWT482iBBBqwNzfAggvxTG6ISbwEtZzWqEtz21Dv6TDb5U8rg-0a6OiRx35fIj22my3bDgjyspl7TnyDQIw-E3gYvpw4GSzV712br9i1zHLdM6oeaRQqrBSb-MPjI2hO4LEVjCts4EhK-Ezvfrw8xQIcQTheaQzzVjQ97-Q-tByQ4M6QRniR6tsZ58502IRCbrIavTiHewg53VmBUzH9iozWWPFn_1fLCDnPBTY2nED_JhDmNNyhRsldZ_x-LF9QXe7nMS-SbpvJ0ao1jFPb3HS9ESG39bUh_za4Ew-g1QylO2xsuDbdNd3W0PNPXLxwLS0DeTL1XVK5FmTpMxEhd40IEYMQmmaYWx-Yf7lSG3ITn-L7MP_C9N7ZmzuP4CSpDyPTBaf4klpRmoSKySLGCeVeITdTsNF5410OlK7X5xwpGLCCozNJRNfZI_RtDQrfayFUBfR1rUsyy7_ACNGiJSUq72IVYx51LeUt791Qo7k4YDBzQ6HEwqnI0zrXkX_bkjRrSmy90_sw

### --- selections
GET https://skorohoda.plentymarkets-cloud02.com/rest/properties/selections
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGM4YzFlZmRhMWYxMTlkYTBmOTUxYzJmMzNhZGE4OWI4NDcyM2Y2ZjFhNDE4ZGIzODRlNGIzODdiMDQ0MzdmNjI5NDUzNzEyZTk4NDIwNTQiLCJpYXQiOjE2MjY2MjA0MDMsIm5iZiI6MTYyNjYyMDQwMywiZXhwIjoxNjI2NzA2ODAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.xBP7iZcne3oD7jhckW5NyONxKx9LrMSIaoHIan2zmSvvQfVT4EOOAD0lIY2_j82aLTsYqI40l9r3vGPXCUJNIx285iZ-RTXoEsSmLW_3BlLsBZJVN5-vofYPHvXJTsGxgvbFrw8iqmE6VkZh99AYvdW-5xHoQJ9NWT482iBBBqwNzfAggvxTG6ISbwEtZzWqEtz21Dv6TDb5U8rg-0a6OiRx35fIj22my3bDgjyspl7TnyDQIw-E3gYvpw4GSzV712br9i1zHLdM6oeaRQqrBSb-MPjI2hO4LEVjCts4EhK-Ezvfrw8xQIcQTheaQzzVjQ97-Q-tByQ4M6QRniR6tsZ58502IRCbrIavTiHewg53VmBUzH9iozWWPFn_1fLCDnPBTY2nED_JhDmNNyhRsldZ_x-LF9QXe7nMS-SbpvJ0ao1jFPb3HS9ESG39bUh_za4Ew-g1QylO2xsuDbdNd3W0PNPXLxwLS0DeTL1XVK5FmTpMxEhd40IEYMQmmaYWx-Yf7lSG3ITn-L7MP_C9N7ZmzuP4CSpDyPTBaf4klpRmoSKySLGCeVeITdTsNF5410OlK7X5xwpGLCCozNJRNfZI_RtDQrfayFUBfR1rUsyy7_ACNGiJSUq72IVYx51LeUt791Qo7k4YDBzQ6HEwqnI0zrXkX_bkjRrSmy90_sw

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/properties/selections
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGM4YzFlZmRhMWYxMTlkYTBmOTUxYzJmMzNhZGE4OWI4NDcyM2Y2ZjFhNDE4ZGIzODRlNGIzODdiMDQ0MzdmNjI5NDUzNzEyZTk4NDIwNTQiLCJpYXQiOjE2MjY2MjA0MDMsIm5iZiI6MTYyNjYyMDQwMywiZXhwIjoxNjI2NzA2ODAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.xBP7iZcne3oD7jhckW5NyONxKx9LrMSIaoHIan2zmSvvQfVT4EOOAD0lIY2_j82aLTsYqI40l9r3vGPXCUJNIx285iZ-RTXoEsSmLW_3BlLsBZJVN5-vofYPHvXJTsGxgvbFrw8iqmE6VkZh99AYvdW-5xHoQJ9NWT482iBBBqwNzfAggvxTG6ISbwEtZzWqEtz21Dv6TDb5U8rg-0a6OiRx35fIj22my3bDgjyspl7TnyDQIw-E3gYvpw4GSzV712br9i1zHLdM6oeaRQqrBSb-MPjI2hO4LEVjCts4EhK-Ezvfrw8xQIcQTheaQzzVjQ97-Q-tByQ4M6QRniR6tsZ58502IRCbrIavTiHewg53VmBUzH9iozWWPFn_1fLCDnPBTY2nED_JhDmNNyhRsldZ_x-LF9QXe7nMS-SbpvJ0ao1jFPb3HS9ESG39bUh_za4Ew-g1QylO2xsuDbdNd3W0PNPXLxwLS0DeTL1XVK5FmTpMxEhd40IEYMQmmaYWx-Yf7lSG3ITn-L7MP_C9N7ZmzuP4CSpDyPTBaf4klpRmoSKySLGCeVeITdTsNF5410OlK7X5xwpGLCCozNJRNfZI_RtDQrfayFUBfR1rUsyy7_ACNGiJSUq72IVYx51LeUt791Qo7k4YDBzQ6HEwqnI0zrXkX_bkjRrSmy90_sw

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/properties/selections?relationTargetId=34494
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGM4YzFlZmRhMWYxMTlkYTBmOTUxYzJmMzNhZGE4OWI4NDcyM2Y2ZjFhNDE4ZGIzODRlNGIzODdiMDQ0MzdmNjI5NDUzNzEyZTk4NDIwNTQiLCJpYXQiOjE2MjY2MjA0MDMsIm5iZiI6MTYyNjYyMDQwMywiZXhwIjoxNjI2NzA2ODAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.xBP7iZcne3oD7jhckW5NyONxKx9LrMSIaoHIan2zmSvvQfVT4EOOAD0lIY2_j82aLTsYqI40l9r3vGPXCUJNIx285iZ-RTXoEsSmLW_3BlLsBZJVN5-vofYPHvXJTsGxgvbFrw8iqmE6VkZh99AYvdW-5xHoQJ9NWT482iBBBqwNzfAggvxTG6ISbwEtZzWqEtz21Dv6TDb5U8rg-0a6OiRx35fIj22my3bDgjyspl7TnyDQIw-E3gYvpw4GSzV712br9i1zHLdM6oeaRQqrBSb-MPjI2hO4LEVjCts4EhK-Ezvfrw8xQIcQTheaQzzVjQ97-Q-tByQ4M6QRniR6tsZ58502IRCbrIavTiHewg53VmBUzH9iozWWPFn_1fLCDnPBTY2nED_JhDmNNyhRsldZ_x-LF9QXe7nMS-SbpvJ0ao1jFPb3HS9ESG39bUh_za4Ew-g1QylO2xsuDbdNd3W0PNPXLxwLS0DeTL1XVK5FmTpMxEhd40IEYMQmmaYWx-Yf7lSG3ITn-L7MP_C9N7ZmzuP4CSpDyPTBaf4klpRmoSKySLGCeVeITdTsNF5410OlK7X5xwpGLCCozNJRNfZI_RtDQrfayFUBfR1rUsyy7_ACNGiJSUq72IVYx51LeUt791Qo7k4YDBzQ6HEwqnI0zrXkX_bkjRrSmy90_sw

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/properties/groups
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGM4YzFlZmRhMWYxMTlkYTBmOTUxYzJmMzNhZGE4OWI4NDcyM2Y2ZjFhNDE4ZGIzODRlNGIzODdiMDQ0MzdmNjI5NDUzNzEyZTk4NDIwNTQiLCJpYXQiOjE2MjY2MjA0MDMsIm5iZiI6MTYyNjYyMDQwMywiZXhwIjoxNjI2NzA2ODAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.xBP7iZcne3oD7jhckW5NyONxKx9LrMSIaoHIan2zmSvvQfVT4EOOAD0lIY2_j82aLTsYqI40l9r3vGPXCUJNIx285iZ-RTXoEsSmLW_3BlLsBZJVN5-vofYPHvXJTsGxgvbFrw8iqmE6VkZh99AYvdW-5xHoQJ9NWT482iBBBqwNzfAggvxTG6ISbwEtZzWqEtz21Dv6TDb5U8rg-0a6OiRx35fIj22my3bDgjyspl7TnyDQIw-E3gYvpw4GSzV712br9i1zHLdM6oeaRQqrBSb-MPjI2hO4LEVjCts4EhK-Ezvfrw8xQIcQTheaQzzVjQ97-Q-tByQ4M6QRniR6tsZ58502IRCbrIavTiHewg53VmBUzH9iozWWPFn_1fLCDnPBTY2nED_JhDmNNyhRsldZ_x-LF9QXe7nMS-SbpvJ0ao1jFPb3HS9ESG39bUh_za4Ew-g1QylO2xsuDbdNd3W0PNPXLxwLS0DeTL1XVK5FmTpMxEhd40IEYMQmmaYWx-Yf7lSG3ITn-L7MP_C9N7ZmzuP4CSpDyPTBaf4klpRmoSKySLGCeVeITdTsNF5410OlK7X5xwpGLCCozNJRNfZI_RtDQrfayFUBfR1rUsyy7_ACNGiJSUq72IVYx51LeUt791Qo7k4YDBzQ6HEwqnI0zrXkX_bkjRrSmy90_sw

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/properties/groups/names
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGM4YzFlZmRhMWYxMTlkYTBmOTUxYzJmMzNhZGE4OWI4NDcyM2Y2ZjFhNDE4ZGIzODRlNGIzODdiMDQ0MzdmNjI5NDUzNzEyZTk4NDIwNTQiLCJpYXQiOjE2MjY2MjA0MDMsIm5iZiI6MTYyNjYyMDQwMywiZXhwIjoxNjI2NzA2ODAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.xBP7iZcne3oD7jhckW5NyONxKx9LrMSIaoHIan2zmSvvQfVT4EOOAD0lIY2_j82aLTsYqI40l9r3vGPXCUJNIx285iZ-RTXoEsSmLW_3BlLsBZJVN5-vofYPHvXJTsGxgvbFrw8iqmE6VkZh99AYvdW-5xHoQJ9NWT482iBBBqwNzfAggvxTG6ISbwEtZzWqEtz21Dv6TDb5U8rg-0a6OiRx35fIj22my3bDgjyspl7TnyDQIw-E3gYvpw4GSzV712br9i1zHLdM6oeaRQqrBSb-MPjI2hO4LEVjCts4EhK-Ezvfrw8xQIcQTheaQzzVjQ97-Q-tByQ4M6QRniR6tsZ58502IRCbrIavTiHewg53VmBUzH9iozWWPFn_1fLCDnPBTY2nED_JhDmNNyhRsldZ_x-LF9QXe7nMS-SbpvJ0ao1jFPb3HS9ESG39bUh_za4Ew-g1QylO2xsuDbdNd3W0PNPXLxwLS0DeTL1XVK5FmTpMxEhd40IEYMQmmaYWx-Yf7lSG3ITn-L7MP_C9N7ZmzuP4CSpDyPTBaf4klpRmoSKySLGCeVeITdTsNF5410OlK7X5xwpGLCCozNJRNfZI_RtDQrfayFUBfR1rUsyy7_ACNGiJSUq72IVYx51LeUt791Qo7k4YDBzQ6HEwqnI0zrXkX_bkjRrSmy90_sw

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/properties/groups/names/29
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGM4YzFlZmRhMWYxMTlkYTBmOTUxYzJmMzNhZGE4OWI4NDcyM2Y2ZjFhNDE4ZGIzODRlNGIzODdiMDQ0MzdmNjI5NDUzNzEyZTk4NDIwNTQiLCJpYXQiOjE2MjY2MjA0MDMsIm5iZiI6MTYyNjYyMDQwMywiZXhwIjoxNjI2NzA2ODAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.xBP7iZcne3oD7jhckW5NyONxKx9LrMSIaoHIan2zmSvvQfVT4EOOAD0lIY2_j82aLTsYqI40l9r3vGPXCUJNIx285iZ-RTXoEsSmLW_3BlLsBZJVN5-vofYPHvXJTsGxgvbFrw8iqmE6VkZh99AYvdW-5xHoQJ9NWT482iBBBqwNzfAggvxTG6ISbwEtZzWqEtz21Dv6TDb5U8rg-0a6OiRx35fIj22my3bDgjyspl7TnyDQIw-E3gYvpw4GSzV712br9i1zHLdM6oeaRQqrBSb-MPjI2hO4LEVjCts4EhK-Ezvfrw8xQIcQTheaQzzVjQ97-Q-tByQ4M6QRniR6tsZ58502IRCbrIavTiHewg53VmBUzH9iozWWPFn_1fLCDnPBTY2nED_JhDmNNyhRsldZ_x-LF9QXe7nMS-SbpvJ0ao1jFPb3HS9ESG39bUh_za4Ew-g1QylO2xsuDbdNd3W0PNPXLxwLS0DeTL1XVK5FmTpMxEhd40IEYMQmmaYWx-Yf7lSG3ITn-L7MP_C9N7ZmzuP4CSpDyPTBaf4klpRmoSKySLGCeVeITdTsNF5410OlK7X5xwpGLCCozNJRNfZI_RtDQrfayFUBfR1rUsyy7_ACNGiJSUq72IVYx51LeUt791Qo7k4YDBzQ6HEwqnI0zrXkX_bkjRrSmy90_sw


###
GET https://skorohoda.plentymarkets-cloud02.com/rest/properties/groups/types
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGM4YzFlZmRhMWYxMTlkYTBmOTUxYzJmMzNhZGE4OWI4NDcyM2Y2ZjFhNDE4ZGIzODRlNGIzODdiMDQ0MzdmNjI5NDUzNzEyZTk4NDIwNTQiLCJpYXQiOjE2MjY2MjA0MDMsIm5iZiI6MTYyNjYyMDQwMywiZXhwIjoxNjI2NzA2ODAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.xBP7iZcne3oD7jhckW5NyONxKx9LrMSIaoHIan2zmSvvQfVT4EOOAD0lIY2_j82aLTsYqI40l9r3vGPXCUJNIx285iZ-RTXoEsSmLW_3BlLsBZJVN5-vofYPHvXJTsGxgvbFrw8iqmE6VkZh99AYvdW-5xHoQJ9NWT482iBBBqwNzfAggvxTG6ISbwEtZzWqEtz21Dv6TDb5U8rg-0a6OiRx35fIj22my3bDgjyspl7TnyDQIw-E3gYvpw4GSzV712br9i1zHLdM6oeaRQqrBSb-MPjI2hO4LEVjCts4EhK-Ezvfrw8xQIcQTheaQzzVjQ97-Q-tByQ4M6QRniR6tsZ58502IRCbrIavTiHewg53VmBUzH9iozWWPFn_1fLCDnPBTY2nED_JhDmNNyhRsldZ_x-LF9QXe7nMS-SbpvJ0ao1jFPb3HS9ESG39bUh_za4Ew-g1QylO2xsuDbdNd3W0PNPXLxwLS0DeTL1XVK5FmTpMxEhd40IEYMQmmaYWx-Yf7lSG3ITn-L7MP_C9N7ZmzuP4CSpDyPTBaf4klpRmoSKySLGCeVeITdTsNF5410OlK7X5xwpGLCCozNJRNfZI_RtDQrfayFUBfR1rUsyy7_ACNGiJSUq72IVYx51LeUt791Qo7k4YDBzQ6HEwqnI0zrXkX_bkjRrSmy90_sw

### -- System lang
GET https://skorohoda.plentymarkets-cloud02.com/rest/properties/systemlang
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGM4YzFlZmRhMWYxMTlkYTBmOTUxYzJmMzNhZGE4OWI4NDcyM2Y2ZjFhNDE4ZGIzODRlNGIzODdiMDQ0MzdmNjI5NDUzNzEyZTk4NDIwNTQiLCJpYXQiOjE2MjY2MjA0MDMsIm5iZiI6MTYyNjYyMDQwMywiZXhwIjoxNjI2NzA2ODAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.xBP7iZcne3oD7jhckW5NyONxKx9LrMSIaoHIan2zmSvvQfVT4EOOAD0lIY2_j82aLTsYqI40l9r3vGPXCUJNIx285iZ-RTXoEsSmLW_3BlLsBZJVN5-vofYPHvXJTsGxgvbFrw8iqmE6VkZh99AYvdW-5xHoQJ9NWT482iBBBqwNzfAggvxTG6ISbwEtZzWqEtz21Dv6TDb5U8rg-0a6OiRx35fIj22my3bDgjyspl7TnyDQIw-E3gYvpw4GSzV712br9i1zHLdM6oeaRQqrBSb-MPjI2hO4LEVjCts4EhK-Ezvfrw8xQIcQTheaQzzVjQ97-Q-tByQ4M6QRniR6tsZ58502IRCbrIavTiHewg53VmBUzH9iozWWPFn_1fLCDnPBTY2nED_JhDmNNyhRsldZ_x-LF9QXe7nMS-SbpvJ0ao1jFPb3HS9ESG39bUh_za4Ew-g1QylO2xsuDbdNd3W0PNPXLxwLS0DeTL1XVK5FmTpMxEhd40IEYMQmmaYWx-Yf7lSG3ITn-L7MP_C9N7ZmzuP4CSpDyPTBaf4klpRmoSKySLGCeVeITdTsNF5410OlK7X5xwpGLCCozNJRNfZI_RtDQrfayFUBfR1rUsyy7_ACNGiJSUq72IVYx51LeUt791Qo7k4YDBzQ6HEwqnI0zrXkX_bkjRrSmy90_sw

### -- Create property
POST https://skorohoda.plentymarkets-cloud02.com/rest/properties
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGM4YzFlZmRhMWYxMTlkYTBmOTUxYzJmMzNhZGE4OWI4NDcyM2Y2ZjFhNDE4ZGIzODRlNGIzODdiMDQ0MzdmNjI5NDUzNzEyZTk4NDIwNTQiLCJpYXQiOjE2MjY2MjA0MDMsIm5iZiI6MTYyNjYyMDQwMywiZXhwIjoxNjI2NzA2ODAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.xBP7iZcne3oD7jhckW5NyONxKx9LrMSIaoHIan2zmSvvQfVT4EOOAD0lIY2_j82aLTsYqI40l9r3vGPXCUJNIx285iZ-RTXoEsSmLW_3BlLsBZJVN5-vofYPHvXJTsGxgvbFrw8iqmE6VkZh99AYvdW-5xHoQJ9NWT482iBBBqwNzfAggvxTG6ISbwEtZzWqEtz21Dv6TDb5U8rg-0a6OiRx35fIj22my3bDgjyspl7TnyDQIw-E3gYvpw4GSzV712br9i1zHLdM6oeaRQqrBSb-MPjI2hO4LEVjCts4EhK-Ezvfrw8xQIcQTheaQzzVjQ97-Q-tByQ4M6QRniR6tsZ58502IRCbrIavTiHewg53VmBUzH9iozWWPFn_1fLCDnPBTY2nED_JhDmNNyhRsldZ_x-LF9QXe7nMS-SbpvJ0ao1jFPb3HS9ESG39bUh_za4Ew-g1QylO2xsuDbdNd3W0PNPXLxwLS0DeTL1XVK5FmTpMxEhd40IEYMQmmaYWx-Yf7lSG3ITn-L7MP_C9N7ZmzuP4CSpDyPTBaf4klpRmoSKySLGCeVeITdTsNF5410OlK7X5xwpGLCCozNJRNfZI_RtDQrfayFUBfR1rUsyy7_ACNGiJSUq72IVYx51LeUt791Qo7k4YDBzQ6HEwqnI0zrXkX_bkjRrSmy90_sw

{
    "cast": "selection",
    "typeIdentifier": "item",
    "position": 0,
    "names": [
        {
            "lang": "1",
            "name": "test_select_01",
            "description": "test_select_01 Lang 1"
        },
        {
            "lang": "en",
            "name": "test_select_01",
            "description": "test_select_01 Lang EN"
        }
    ]
}

### -- Create property selection values
POST https://skorohoda.plentymarkets-cloud02.com/rest/properties/selections
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGM4YzFlZmRhMWYxMTlkYTBmOTUxYzJmMzNhZGE4OWI4NDcyM2Y2ZjFhNDE4ZGIzODRlNGIzODdiMDQ0MzdmNjI5NDUzNzEyZTk4NDIwNTQiLCJpYXQiOjE2MjY2MjA0MDMsIm5iZiI6MTYyNjYyMDQwMywiZXhwIjoxNjI2NzA2ODAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.xBP7iZcne3oD7jhckW5NyONxKx9LrMSIaoHIan2zmSvvQfVT4EOOAD0lIY2_j82aLTsYqI40l9r3vGPXCUJNIx285iZ-RTXoEsSmLW_3BlLsBZJVN5-vofYPHvXJTsGxgvbFrw8iqmE6VkZh99AYvdW-5xHoQJ9NWT482iBBBqwNzfAggvxTG6ISbwEtZzWqEtz21Dv6TDb5U8rg-0a6OiRx35fIj22my3bDgjyspl7TnyDQIw-E3gYvpw4GSzV712br9i1zHLdM6oeaRQqrBSb-MPjI2hO4LEVjCts4EhK-Ezvfrw8xQIcQTheaQzzVjQ97-Q-tByQ4M6QRniR6tsZ58502IRCbrIavTiHewg53VmBUzH9iozWWPFn_1fLCDnPBTY2nED_JhDmNNyhRsldZ_x-LF9QXe7nMS-SbpvJ0ao1jFPb3HS9ESG39bUh_za4Ew-g1QylO2xsuDbdNd3W0PNPXLxwLS0DeTL1XVK5FmTpMxEhd40IEYMQmmaYWx-Yf7lSG3ITn-L7MP_C9N7ZmzuP4CSpDyPTBaf4klpRmoSKySLGCeVeITdTsNF5410OlK7X5xwpGLCCozNJRNfZI_RtDQrfayFUBfR1rUsyy7_ACNGiJSUq72IVYx51LeUt791Qo7k4YDBzQ6HEwqnI0zrXkX_bkjRrSmy90_sw

{
    "propertyId": 242,
    "position": 0,
    "relation": [
        {
            "relationValues": [
                {
                    "lang": "1",
                    "value": "VALUE 01",
                    "description": "VALUE 01"
                },
                {
                    "lang": "en",
                    "value": "VALUE 01",
                    "description": "VALUE 01"
                }
            ]
        }
    ]
}

### -- Create property selection values

### -- Create property selection value relations

###
POST https://skorohoda.plentymarkets-cloud02.com/rest​/properties​/groups​/11​/properties
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGM4YzFlZmRhMWYxMTlkYTBmOTUxYzJmMzNhZGE4OWI4NDcyM2Y2ZjFhNDE4ZGIzODRlNGIzODdiMDQ0MzdmNjI5NDUzNzEyZTk4NDIwNTQiLCJpYXQiOjE2MjY2MjA0MDMsIm5iZiI6MTYyNjYyMDQwMywiZXhwIjoxNjI2NzA2ODAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.xBP7iZcne3oD7jhckW5NyONxKx9LrMSIaoHIan2zmSvvQfVT4EOOAD0lIY2_j82aLTsYqI40l9r3vGPXCUJNIx285iZ-RTXoEsSmLW_3BlLsBZJVN5-vofYPHvXJTsGxgvbFrw8iqmE6VkZh99AYvdW-5xHoQJ9NWT482iBBBqwNzfAggvxTG6ISbwEtZzWqEtz21Dv6TDb5U8rg-0a6OiRx35fIj22my3bDgjyspl7TnyDQIw-E3gYvpw4GSzV712br9i1zHLdM6oeaRQqrBSb-MPjI2hO4LEVjCts4EhK-Ezvfrw8xQIcQTheaQzzVjQ97-Q-tByQ4M6QRniR6tsZ58502IRCbrIavTiHewg53VmBUzH9iozWWPFn_1fLCDnPBTY2nED_JhDmNNyhRsldZ_x-LF9QXe7nMS-SbpvJ0ao1jFPb3HS9ESG39bUh_za4Ew-g1QylO2xsuDbdNd3W0PNPXLxwLS0DeTL1XVK5FmTpMxEhd40IEYMQmmaYWx-Yf7lSG3ITn-L7MP_C9N7ZmzuP4CSpDyPTBaf4klpRmoSKySLGCeVeITdTsNF5410OlK7X5xwpGLCCozNJRNfZI_RtDQrfayFUBfR1rUsyy7_ACNGiJSUq72IVYx51LeUt791Qo7k4YDBzQ6HEwqnI0zrXkX_bkjRrSmy90_sw

[
    {
        "groupId" : 11,
        "propertyId": 101
    },
    {
        "groupId" : 11,
        "propertyId": 102
    },
    {
        "groupId" : 11,
        "propertyId": 103
    }
]

###
POST https://skorohoda.plentymarkets-cloud02.com/rest​/properties​/groups​/11​/properties/102
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGM4YzFlZmRhMWYxMTlkYTBmOTUxYzJmMzNhZGE4OWI4NDcyM2Y2ZjFhNDE4ZGIzODRlNGIzODdiMDQ0MzdmNjI5NDUzNzEyZTk4NDIwNTQiLCJpYXQiOjE2MjY2MjA0MDMsIm5iZiI6MTYyNjYyMDQwMywiZXhwIjoxNjI2NzA2ODAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.xBP7iZcne3oD7jhckW5NyONxKx9LrMSIaoHIan2zmSvvQfVT4EOOAD0lIY2_j82aLTsYqI40l9r3vGPXCUJNIx285iZ-RTXoEsSmLW_3BlLsBZJVN5-vofYPHvXJTsGxgvbFrw8iqmE6VkZh99AYvdW-5xHoQJ9NWT482iBBBqwNzfAggvxTG6ISbwEtZzWqEtz21Dv6TDb5U8rg-0a6OiRx35fIj22my3bDgjyspl7TnyDQIw-E3gYvpw4GSzV712br9i1zHLdM6oeaRQqrBSb-MPjI2hO4LEVjCts4EhK-Ezvfrw8xQIcQTheaQzzVjQ97-Q-tByQ4M6QRniR6tsZ58502IRCbrIavTiHewg53VmBUzH9iozWWPFn_1fLCDnPBTY2nED_JhDmNNyhRsldZ_x-LF9QXe7nMS-SbpvJ0ao1jFPb3HS9ESG39bUh_za4Ew-g1QylO2xsuDbdNd3W0PNPXLxwLS0DeTL1XVK5FmTpMxEhd40IEYMQmmaYWx-Yf7lSG3ITn-L7MP_C9N7ZmzuP4CSpDyPTBaf4klpRmoSKySLGCeVeITdTsNF5410OlK7X5xwpGLCCozNJRNfZI_RtDQrfayFUBfR1rUsyy7_ACNGiJSUq72IVYx51LeUt791Qo7k4YDBzQ6HEwqnI0zrXkX_bkjRrSmy90_sw

####
DELETE https://skorohoda.plentymarkets-cloud02.com/rest​/properties​/232
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGM4YzFlZmRhMWYxMTlkYTBmOTUxYzJmMzNhZGE4OWI4NDcyM2Y2ZjFhNDE4ZGIzODRlNGIzODdiMDQ0MzdmNjI5NDUzNzEyZTk4NDIwNTQiLCJpYXQiOjE2MjY2MjA0MDMsIm5iZiI6MTYyNjYyMDQwMywiZXhwIjoxNjI2NzA2ODAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.xBP7iZcne3oD7jhckW5NyONxKx9LrMSIaoHIan2zmSvvQfVT4EOOAD0lIY2_j82aLTsYqI40l9r3vGPXCUJNIx285iZ-RTXoEsSmLW_3BlLsBZJVN5-vofYPHvXJTsGxgvbFrw8iqmE6VkZh99AYvdW-5xHoQJ9NWT482iBBBqwNzfAggvxTG6ISbwEtZzWqEtz21Dv6TDb5U8rg-0a6OiRx35fIj22my3bDgjyspl7TnyDQIw-E3gYvpw4GSzV712br9i1zHLdM6oeaRQqrBSb-MPjI2hO4LEVjCts4EhK-Ezvfrw8xQIcQTheaQzzVjQ97-Q-tByQ4M6QRniR6tsZ58502IRCbrIavTiHewg53VmBUzH9iozWWPFn_1fLCDnPBTY2nED_JhDmNNyhRsldZ_x-LF9QXe7nMS-SbpvJ0ao1jFPb3HS9ESG39bUh_za4Ew-g1QylO2xsuDbdNd3W0PNPXLxwLS0DeTL1XVK5FmTpMxEhd40IEYMQmmaYWx-Yf7lSG3ITn-L7MP_C9N7ZmzuP4CSpDyPTBaf4klpRmoSKySLGCeVeITdTsNF5410OlK7X5xwpGLCCozNJRNfZI_RtDQrfayFUBfR1rUsyy7_ACNGiJSUq72IVYx51LeUt791Qo7k4YDBzQ6HEwqnI0zrXkX_bkjRrSmy90_sw

{
    "propertyId": "232"
}

###
PUT https://skorohoda.plentymarkets-cloud02.com/rest/properties/names/241
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGM4YzFlZmRhMWYxMTlkYTBmOTUxYzJmMzNhZGE4OWI4NDcyM2Y2ZjFhNDE4ZGIzODRlNGIzODdiMDQ0MzdmNjI5NDUzNzEyZTk4NDIwNTQiLCJpYXQiOjE2MjY2MjA0MDMsIm5iZiI6MTYyNjYyMDQwMywiZXhwIjoxNjI2NzA2ODAzLCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.xBP7iZcne3oD7jhckW5NyONxKx9LrMSIaoHIan2zmSvvQfVT4EOOAD0lIY2_j82aLTsYqI40l9r3vGPXCUJNIx285iZ-RTXoEsSmLW_3BlLsBZJVN5-vofYPHvXJTsGxgvbFrw8iqmE6VkZh99AYvdW-5xHoQJ9NWT482iBBBqwNzfAggvxTG6ISbwEtZzWqEtz21Dv6TDb5U8rg-0a6OiRx35fIj22my3bDgjyspl7TnyDQIw-E3gYvpw4GSzV712br9i1zHLdM6oeaRQqrBSb-MPjI2hO4LEVjCts4EhK-Ezvfrw8xQIcQTheaQzzVjQ97-Q-tByQ4M6QRniR6tsZ58502IRCbrIavTiHewg53VmBUzH9iozWWPFn_1fLCDnPBTY2nED_JhDmNNyhRsldZ_x-LF9QXe7nMS-SbpvJ0ao1jFPb3HS9ESG39bUh_za4Ew-g1QylO2xsuDbdNd3W0PNPXLxwLS0DeTL1XVK5FmTpMxEhd40IEYMQmmaYWx-Yf7lSG3ITn-L7MP_C9N7ZmzuP4CSpDyPTBaf4klpRmoSKySLGCeVeITdTsNF5410OlK7X5xwpGLCCozNJRNfZI_RtDQrfayFUBfR1rUsyy7_ACNGiJSUq72IVYx51LeUt791Qo7k4YDBzQ6HEwqnI0zrXkX_bkjRrSmy90_sw

{
    "lang": "en"
}
