GET https://skorohoda.plentymarkets-cloud02.com/rest/stockmanagement/warehouses
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDliOTQ2NTU1YjBkODI0MzAwZjZmZmFmMzliYWRiZGVkODU0ZTMxYjE0MzA4ZGZhMzY2YmMxNWNlZjMyMmM3MjAwMTZjMDRlOTllYjAzMWEiLCJpYXQiOjE2Njc5MDE4NzMuOTM4NywibmJmIjoxNjY3OTAxODczLjkzODcsImV4cCI6MTY2Nzk4ODI3My45Mjk3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.IRz-Wg8CVE-oDHywOzEf-LnNwhb1AgeJYiqhXA5kgfUl9Yg14NswWlysMC55H40K3NCqFgkpLWPNB67qkD36J65Wt3xTEQaTgtKFsvIyzjHMN8A18U0E77yAyDyzu9OJrIowl8S4uYbF7MMiVv_GijFoLilnv_UwHOzlqTfzG6AF8M4qxQ7JzDn3qYuyKzr4KSZy_JBSEtQ6qpO9zwtfnx-ZU-kpGxt6V8wCFpBxzG28iBsQ4Er_mvydHd4y8A4vnQeEvyYe18_OSiegaqu7Wg3dxbCNVBgKIcGeGZYXZ4XzUNivTQ1x02y2AilhG_1vKyRkTbVKUbO_SGsaniXCfh-MLqw-dc1wI39Q7jSGEXiv4k_rcOZ_BorHBvt6O88Wfu1cKvjMgQx0HMTvDcUS_-gfO5qUWM65dKh_hgXRqJBzDAFw0VAnv9gDfbVBjs-uvliK0mWyRHWPCApPb-5kLtu5hm3MsGreTpPz8o8OqQLEDrNAFjbdS7cyeLpq3WP2Fsr5lrzmgD2P29Yclx7xRcVnC6Lc9JUCFBgyEnYuKW7I1yYsDs6a6ny2ksLl9AMuKRzza08DgLHRUcsUfHtfs5IVhvCpqMjs-kFbNPow43j3PdVZDD5B0zP8KyeH02BUOJsOAFBDY34DL-93TAEhSZ9dGlfX9-3VlfEtuY5GXPY

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/stockmanagement/warehouses/103/management/racks
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDliOTQ2NTU1YjBkODI0MzAwZjZmZmFmMzliYWRiZGVkODU0ZTMxYjE0MzA4ZGZhMzY2YmMxNWNlZjMyMmM3MjAwMTZjMDRlOTllYjAzMWEiLCJpYXQiOjE2Njc5MDE4NzMuOTM4NywibmJmIjoxNjY3OTAxODczLjkzODcsImV4cCI6MTY2Nzk4ODI3My45Mjk3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.IRz-Wg8CVE-oDHywOzEf-LnNwhb1AgeJYiqhXA5kgfUl9Yg14NswWlysMC55H40K3NCqFgkpLWPNB67qkD36J65Wt3xTEQaTgtKFsvIyzjHMN8A18U0E77yAyDyzu9OJrIowl8S4uYbF7MMiVv_GijFoLilnv_UwHOzlqTfzG6AF8M4qxQ7JzDn3qYuyKzr4KSZy_JBSEtQ6qpO9zwtfnx-ZU-kpGxt6V8wCFpBxzG28iBsQ4Er_mvydHd4y8A4vnQeEvyYe18_OSiegaqu7Wg3dxbCNVBgKIcGeGZYXZ4XzUNivTQ1x02y2AilhG_1vKyRkTbVKUbO_SGsaniXCfh-MLqw-dc1wI39Q7jSGEXiv4k_rcOZ_BorHBvt6O88Wfu1cKvjMgQx0HMTvDcUS_-gfO5qUWM65dKh_hgXRqJBzDAFw0VAnv9gDfbVBjs-uvliK0mWyRHWPCApPb-5kLtu5hm3MsGreTpPz8o8OqQLEDrNAFjbdS7cyeLpq3WP2Fsr5lrzmgD2P29Yclx7xRcVnC6Lc9JUCFBgyEnYuKW7I1yYsDs6a6ny2ksLl9AMuKRzza08DgLHRUcsUfHtfs5IVhvCpqMjs-kFbNPow43j3PdVZDD5B0zP8KyeH02BUOJsOAFBDY34DL-93TAEhSZ9dGlfX9-3VlfEtuY5GXPY

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/stockmanagement/warehouses/1/management/racks/1/shelves
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDliOTQ2NTU1YjBkODI0MzAwZjZmZmFmMzliYWRiZGVkODU0ZTMxYjE0MzA4ZGZhMzY2YmMxNWNlZjMyMmM3MjAwMTZjMDRlOTllYjAzMWEiLCJpYXQiOjE2Njc5MDE4NzMuOTM4NywibmJmIjoxNjY3OTAxODczLjkzODcsImV4cCI6MTY2Nzk4ODI3My45Mjk3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.IRz-Wg8CVE-oDHywOzEf-LnNwhb1AgeJYiqhXA5kgfUl9Yg14NswWlysMC55H40K3NCqFgkpLWPNB67qkD36J65Wt3xTEQaTgtKFsvIyzjHMN8A18U0E77yAyDyzu9OJrIowl8S4uYbF7MMiVv_GijFoLilnv_UwHOzlqTfzG6AF8M4qxQ7JzDn3qYuyKzr4KSZy_JBSEtQ6qpO9zwtfnx-ZU-kpGxt6V8wCFpBxzG28iBsQ4Er_mvydHd4y8A4vnQeEvyYe18_OSiegaqu7Wg3dxbCNVBgKIcGeGZYXZ4XzUNivTQ1x02y2AilhG_1vKyRkTbVKUbO_SGsaniXCfh-MLqw-dc1wI39Q7jSGEXiv4k_rcOZ_BorHBvt6O88Wfu1cKvjMgQx0HMTvDcUS_-gfO5qUWM65dKh_hgXRqJBzDAFw0VAnv9gDfbVBjs-uvliK0mWyRHWPCApPb-5kLtu5hm3MsGreTpPz8o8OqQLEDrNAFjbdS7cyeLpq3WP2Fsr5lrzmgD2P29Yclx7xRcVnC6Lc9JUCFBgyEnYuKW7I1yYsDs6a6ny2ksLl9AMuKRzza08DgLHRUcsUfHtfs5IVhvCpqMjs-kFbNPow43j3PdVZDD5B0zP8KyeH02BUOJsOAFBDY34DL-93TAEhSZ9dGlfX9-3VlfEtuY5GXPY

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/stockmanagement/warehouses/1/management/racks/1/shelves/13/storageLocations
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDliOTQ2NTU1YjBkODI0MzAwZjZmZmFmMzliYWRiZGVkODU0ZTMxYjE0MzA4ZGZhMzY2YmMxNWNlZjMyMmM3MjAwMTZjMDRlOTllYjAzMWEiLCJpYXQiOjE2Njc5MDE4NzMuOTM4NywibmJmIjoxNjY3OTAxODczLjkzODcsImV4cCI6MTY2Nzk4ODI3My45Mjk3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.IRz-Wg8CVE-oDHywOzEf-LnNwhb1AgeJYiqhXA5kgfUl9Yg14NswWlysMC55H40K3NCqFgkpLWPNB67qkD36J65Wt3xTEQaTgtKFsvIyzjHMN8A18U0E77yAyDyzu9OJrIowl8S4uYbF7MMiVv_GijFoLilnv_UwHOzlqTfzG6AF8M4qxQ7JzDn3qYuyKzr4KSZy_JBSEtQ6qpO9zwtfnx-ZU-kpGxt6V8wCFpBxzG28iBsQ4Er_mvydHd4y8A4vnQeEvyYe18_OSiegaqu7Wg3dxbCNVBgKIcGeGZYXZ4XzUNivTQ1x02y2AilhG_1vKyRkTbVKUbO_SGsaniXCfh-MLqw-dc1wI39Q7jSGEXiv4k_rcOZ_BorHBvt6O88Wfu1cKvjMgQx0HMTvDcUS_-gfO5qUWM65dKh_hgXRqJBzDAFw0VAnv9gDfbVBjs-uvliK0mWyRHWPCApPb-5kLtu5hm3MsGreTpPz8o8OqQLEDrNAFjbdS7cyeLpq3WP2Fsr5lrzmgD2P29Yclx7xRcVnC6Lc9JUCFBgyEnYuKW7I1yYsDs6a6ny2ksLl9AMuKRzza08DgLHRUcsUfHtfs5IVhvCpqMjs-kFbNPow43j3PdVZDD5B0zP8KyeH02BUOJsOAFBDY34DL-93TAEhSZ9dGlfX9-3VlfEtuY5GXPY

### with 'warehouse', 'rack' and 'shelf'.
GET https://skorohoda.plentymarkets-cloud02.com/rest/stockmanagement/warehouses/1/management/storageLocations
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDliOTQ2NTU1YjBkODI0MzAwZjZmZmFmMzliYWRiZGVkODU0ZTMxYjE0MzA4ZGZhMzY2YmMxNWNlZjMyMmM3MjAwMTZjMDRlOTllYjAzMWEiLCJpYXQiOjE2Njc5MDE4NzMuOTM4NywibmJmIjoxNjY3OTAxODczLjkzODcsImV4cCI6MTY2Nzk4ODI3My45Mjk3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.IRz-Wg8CVE-oDHywOzEf-LnNwhb1AgeJYiqhXA5kgfUl9Yg14NswWlysMC55H40K3NCqFgkpLWPNB67qkD36J65Wt3xTEQaTgtKFsvIyzjHMN8A18U0E77yAyDyzu9OJrIowl8S4uYbF7MMiVv_GijFoLilnv_UwHOzlqTfzG6AF8M4qxQ7JzDn3qYuyKzr4KSZy_JBSEtQ6qpO9zwtfnx-ZU-kpGxt6V8wCFpBxzG28iBsQ4Er_mvydHd4y8A4vnQeEvyYe18_OSiegaqu7Wg3dxbCNVBgKIcGeGZYXZ4XzUNivTQ1x02y2AilhG_1vKyRkTbVKUbO_SGsaniXCfh-MLqw-dc1wI39Q7jSGEXiv4k_rcOZ_BorHBvt6O88Wfu1cKvjMgQx0HMTvDcUS_-gfO5qUWM65dKh_hgXRqJBzDAFw0VAnv9gDfbVBjs-uvliK0mWyRHWPCApPb-5kLtu5hm3MsGreTpPz8o8OqQLEDrNAFjbdS7cyeLpq3WP2Fsr5lrzmgD2P29Yclx7xRcVnC6Lc9JUCFBgyEnYuKW7I1yYsDs6a6ny2ksLl9AMuKRzza08DgLHRUcsUfHtfs5IVhvCpqMjs-kFbNPow43j3PdVZDD5B0zP8KyeH02BUOJsOAFBDY34DL-93TAEhSZ9dGlfX9-3VlfEtuY5GXPY

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/stockmanagement/warehouses/1/management/storageLocations/13
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDliOTQ2NTU1YjBkODI0MzAwZjZmZmFmMzliYWRiZGVkODU0ZTMxYjE0MzA4ZGZhMzY2YmMxNWNlZjMyMmM3MjAwMTZjMDRlOTllYjAzMWEiLCJpYXQiOjE2Njc5MDE4NzMuOTM4NywibmJmIjoxNjY3OTAxODczLjkzODcsImV4cCI6MTY2Nzk4ODI3My45Mjk3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.IRz-Wg8CVE-oDHywOzEf-LnNwhb1AgeJYiqhXA5kgfUl9Yg14NswWlysMC55H40K3NCqFgkpLWPNB67qkD36J65Wt3xTEQaTgtKFsvIyzjHMN8A18U0E77yAyDyzu9OJrIowl8S4uYbF7MMiVv_GijFoLilnv_UwHOzlqTfzG6AF8M4qxQ7JzDn3qYuyKzr4KSZy_JBSEtQ6qpO9zwtfnx-ZU-kpGxt6V8wCFpBxzG28iBsQ4Er_mvydHd4y8A4vnQeEvyYe18_OSiegaqu7Wg3dxbCNVBgKIcGeGZYXZ4XzUNivTQ1x02y2AilhG_1vKyRkTbVKUbO_SGsaniXCfh-MLqw-dc1wI39Q7jSGEXiv4k_rcOZ_BorHBvt6O88Wfu1cKvjMgQx0HMTvDcUS_-gfO5qUWM65dKh_hgXRqJBzDAFw0VAnv9gDfbVBjs-uvliK0mWyRHWPCApPb-5kLtu5hm3MsGreTpPz8o8OqQLEDrNAFjbdS7cyeLpq3WP2Fsr5lrzmgD2P29Yclx7xRcVnC6Lc9JUCFBgyEnYuKW7I1yYsDs6a6ny2ksLl9AMuKRzza08DgLHRUcsUfHtfs5IVhvCpqMjs-kFbNPow43j3PdVZDD5B0zP8KyeH02BUOJsOAFBDY34DL-93TAEhSZ9dGlfX9-3VlfEtuY5GXPY

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/stockmanagement/warehouses/1/stock
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDliOTQ2NTU1YjBkODI0MzAwZjZmZmFmMzliYWRiZGVkODU0ZTMxYjE0MzA4ZGZhMzY2YmMxNWNlZjMyMmM3MjAwMTZjMDRlOTllYjAzMWEiLCJpYXQiOjE2Njc5MDE4NzMuOTM4NywibmJmIjoxNjY3OTAxODczLjkzODcsImV4cCI6MTY2Nzk4ODI3My45Mjk3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.IRz-Wg8CVE-oDHywOzEf-LnNwhb1AgeJYiqhXA5kgfUl9Yg14NswWlysMC55H40K3NCqFgkpLWPNB67qkD36J65Wt3xTEQaTgtKFsvIyzjHMN8A18U0E77yAyDyzu9OJrIowl8S4uYbF7MMiVv_GijFoLilnv_UwHOzlqTfzG6AF8M4qxQ7JzDn3qYuyKzr4KSZy_JBSEtQ6qpO9zwtfnx-ZU-kpGxt6V8wCFpBxzG28iBsQ4Er_mvydHd4y8A4vnQeEvyYe18_OSiegaqu7Wg3dxbCNVBgKIcGeGZYXZ4XzUNivTQ1x02y2AilhG_1vKyRkTbVKUbO_SGsaniXCfh-MLqw-dc1wI39Q7jSGEXiv4k_rcOZ_BorHBvt6O88Wfu1cKvjMgQx0HMTvDcUS_-gfO5qUWM65dKh_hgXRqJBzDAFw0VAnv9gDfbVBjs-uvliK0mWyRHWPCApPb-5kLtu5hm3MsGreTpPz8o8OqQLEDrNAFjbdS7cyeLpq3WP2Fsr5lrzmgD2P29Yclx7xRcVnC6Lc9JUCFBgyEnYuKW7I1yYsDs6a6ny2ksLl9AMuKRzza08DgLHRUcsUfHtfs5IVhvCpqMjs-kFbNPow43j3PdVZDD5B0zP8KyeH02BUOJsOAFBDY34DL-93TAEhSZ9dGlfX9-3VlfEtuY5GXPY

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/stockmanagement/warehouses/1/stock
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDliOTQ2NTU1YjBkODI0MzAwZjZmZmFmMzliYWRiZGVkODU0ZTMxYjE0MzA4ZGZhMzY2YmMxNWNlZjMyMmM3MjAwMTZjMDRlOTllYjAzMWEiLCJpYXQiOjE2Njc5MDE4NzMuOTM4NywibmJmIjoxNjY3OTAxODczLjkzODcsImV4cCI6MTY2Nzk4ODI3My45Mjk3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.IRz-Wg8CVE-oDHywOzEf-LnNwhb1AgeJYiqhXA5kgfUl9Yg14NswWlysMC55H40K3NCqFgkpLWPNB67qkD36J65Wt3xTEQaTgtKFsvIyzjHMN8A18U0E77yAyDyzu9OJrIowl8S4uYbF7MMiVv_GijFoLilnv_UwHOzlqTfzG6AF8M4qxQ7JzDn3qYuyKzr4KSZy_JBSEtQ6qpO9zwtfnx-ZU-kpGxt6V8wCFpBxzG28iBsQ4Er_mvydHd4y8A4vnQeEvyYe18_OSiegaqu7Wg3dxbCNVBgKIcGeGZYXZ4XzUNivTQ1x02y2AilhG_1vKyRkTbVKUbO_SGsaniXCfh-MLqw-dc1wI39Q7jSGEXiv4k_rcOZ_BorHBvt6O88Wfu1cKvjMgQx0HMTvDcUS_-gfO5qUWM65dKh_hgXRqJBzDAFw0VAnv9gDfbVBjs-uvliK0mWyRHWPCApPb-5kLtu5hm3MsGreTpPz8o8OqQLEDrNAFjbdS7cyeLpq3WP2Fsr5lrzmgD2P29Yclx7xRcVnC6Lc9JUCFBgyEnYuKW7I1yYsDs6a6ny2ksLl9AMuKRzza08DgLHRUcsUfHtfs5IVhvCpqMjs-kFbNPow43j3PdVZDD5B0zP8KyeH02BUOJsOAFBDY34DL-93TAEhSZ9dGlfX9-3VlfEtuY5GXPY

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/stockmanagement/warehouses/1/stock/storageLocations?page=42
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDliOTQ2NTU1YjBkODI0MzAwZjZmZmFmMzliYWRiZGVkODU0ZTMxYjE0MzA4ZGZhMzY2YmMxNWNlZjMyMmM3MjAwMTZjMDRlOTllYjAzMWEiLCJpYXQiOjE2Njc5MDE4NzMuOTM4NywibmJmIjoxNjY3OTAxODczLjkzODcsImV4cCI6MTY2Nzk4ODI3My45Mjk3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.IRz-Wg8CVE-oDHywOzEf-LnNwhb1AgeJYiqhXA5kgfUl9Yg14NswWlysMC55H40K3NCqFgkpLWPNB67qkD36J65Wt3xTEQaTgtKFsvIyzjHMN8A18U0E77yAyDyzu9OJrIowl8S4uYbF7MMiVv_GijFoLilnv_UwHOzlqTfzG6AF8M4qxQ7JzDn3qYuyKzr4KSZy_JBSEtQ6qpO9zwtfnx-ZU-kpGxt6V8wCFpBxzG28iBsQ4Er_mvydHd4y8A4vnQeEvyYe18_OSiegaqu7Wg3dxbCNVBgKIcGeGZYXZ4XzUNivTQ1x02y2AilhG_1vKyRkTbVKUbO_SGsaniXCfh-MLqw-dc1wI39Q7jSGEXiv4k_rcOZ_BorHBvt6O88Wfu1cKvjMgQx0HMTvDcUS_-gfO5qUWM65dKh_hgXRqJBzDAFw0VAnv9gDfbVBjs-uvliK0mWyRHWPCApPb-5kLtu5hm3MsGreTpPz8o8OqQLEDrNAFjbdS7cyeLpq3WP2Fsr5lrzmgD2P29Yclx7xRcVnC6Lc9JUCFBgyEnYuKW7I1yYsDs6a6ny2ksLl9AMuKRzza08DgLHRUcsUfHtfs5IVhvCpqMjs-kFbNPow43j3PdVZDD5B0zP8KyeH02BUOJsOAFBDY34DL-93TAEhSZ9dGlfX9-3VlfEtuY5GXPY

### - page
GET https://skorohoda.plentymarkets-cloud02.com/rest/stockmanagement/stock?itemsPerPage=1000
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDliOTQ2NTU1YjBkODI0MzAwZjZmZmFmMzliYWRiZGVkODU0ZTMxYjE0MzA4ZGZhMzY2YmMxNWNlZjMyMmM3MjAwMTZjMDRlOTllYjAzMWEiLCJpYXQiOjE2Njc5MDE4NzMuOTM4NywibmJmIjoxNjY3OTAxODczLjkzODcsImV4cCI6MTY2Nzk4ODI3My45Mjk3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.IRz-Wg8CVE-oDHywOzEf-LnNwhb1AgeJYiqhXA5kgfUl9Yg14NswWlysMC55H40K3NCqFgkpLWPNB67qkD36J65Wt3xTEQaTgtKFsvIyzjHMN8A18U0E77yAyDyzu9OJrIowl8S4uYbF7MMiVv_GijFoLilnv_UwHOzlqTfzG6AF8M4qxQ7JzDn3qYuyKzr4KSZy_JBSEtQ6qpO9zwtfnx-ZU-kpGxt6V8wCFpBxzG28iBsQ4Er_mvydHd4y8A4vnQeEvyYe18_OSiegaqu7Wg3dxbCNVBgKIcGeGZYXZ4XzUNivTQ1x02y2AilhG_1vKyRkTbVKUbO_SGsaniXCfh-MLqw-dc1wI39Q7jSGEXiv4k_rcOZ_BorHBvt6O88Wfu1cKvjMgQx0HMTvDcUS_-gfO5qUWM65dKh_hgXRqJBzDAFw0VAnv9gDfbVBjs-uvliK0mWyRHWPCApPb-5kLtu5hm3MsGreTpPz8o8OqQLEDrNAFjbdS7cyeLpq3WP2Fsr5lrzmgD2P29Yclx7xRcVnC6Lc9JUCFBgyEnYuKW7I1yYsDs6a6ny2ksLl9AMuKRzza08DgLHRUcsUfHtfs5IVhvCpqMjs-kFbNPow43j3PdVZDD5B0zP8KyeH02BUOJsOAFBDY34DL-93TAEhSZ9dGlfX9-3VlfEtuY5GXPY

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/stockmanagement/stock?columns=test_storage_location_001
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDliOTQ2NTU1YjBkODI0MzAwZjZmZmFmMzliYWRiZGVkODU0ZTMxYjE0MzA4ZGZhMzY2YmMxNWNlZjMyMmM3MjAwMTZjMDRlOTllYjAzMWEiLCJpYXQiOjE2Njc5MDE4NzMuOTM4NywibmJmIjoxNjY3OTAxODczLjkzODcsImV4cCI6MTY2Nzk4ODI3My45Mjk3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.IRz-Wg8CVE-oDHywOzEf-LnNwhb1AgeJYiqhXA5kgfUl9Yg14NswWlysMC55H40K3NCqFgkpLWPNB67qkD36J65Wt3xTEQaTgtKFsvIyzjHMN8A18U0E77yAyDyzu9OJrIowl8S4uYbF7MMiVv_GijFoLilnv_UwHOzlqTfzG6AF8M4qxQ7JzDn3qYuyKzr4KSZy_JBSEtQ6qpO9zwtfnx-ZU-kpGxt6V8wCFpBxzG28iBsQ4Er_mvydHd4y8A4vnQeEvyYe18_OSiegaqu7Wg3dxbCNVBgKIcGeGZYXZ4XzUNivTQ1x02y2AilhG_1vKyRkTbVKUbO_SGsaniXCfh-MLqw-dc1wI39Q7jSGEXiv4k_rcOZ_BorHBvt6O88Wfu1cKvjMgQx0HMTvDcUS_-gfO5qUWM65dKh_hgXRqJBzDAFw0VAnv9gDfbVBjs-uvliK0mWyRHWPCApPb-5kLtu5hm3MsGreTpPz8o8OqQLEDrNAFjbdS7cyeLpq3WP2Fsr5lrzmgD2P29Yclx7xRcVnC6Lc9JUCFBgyEnYuKW7I1yYsDs6a6ny2ksLl9AMuKRzza08DgLHRUcsUfHtfs5IVhvCpqMjs-kFbNPow43j3PdVZDD5B0zP8KyeH02BUOJsOAFBDY34DL-93TAEhSZ9dGlfX9-3VlfEtuY5GXPY

### -- params: updatedAtFrom=2022-05-14T09%3A42%3A23%2B01%3A00
GET https://skorohoda.plentymarkets-cloud02.com/rest/stockmanagement/stock?page=1&updatedAtFrom=2020-06-17T09%3A42%3A23%2B01%3A00&itemsPerPage=150
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDliOTQ2NTU1YjBkODI0MzAwZjZmZmFmMzliYWRiZGVkODU0ZTMxYjE0MzA4ZGZhMzY2YmMxNWNlZjMyMmM3MjAwMTZjMDRlOTllYjAzMWEiLCJpYXQiOjE2Njc5MDE4NzMuOTM4NywibmJmIjoxNjY3OTAxODczLjkzODcsImV4cCI6MTY2Nzk4ODI3My45Mjk3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.IRz-Wg8CVE-oDHywOzEf-LnNwhb1AgeJYiqhXA5kgfUl9Yg14NswWlysMC55H40K3NCqFgkpLWPNB67qkD36J65Wt3xTEQaTgtKFsvIyzjHMN8A18U0E77yAyDyzu9OJrIowl8S4uYbF7MMiVv_GijFoLilnv_UwHOzlqTfzG6AF8M4qxQ7JzDn3qYuyKzr4KSZy_JBSEtQ6qpO9zwtfnx-ZU-kpGxt6V8wCFpBxzG28iBsQ4Er_mvydHd4y8A4vnQeEvyYe18_OSiegaqu7Wg3dxbCNVBgKIcGeGZYXZ4XzUNivTQ1x02y2AilhG_1vKyRkTbVKUbO_SGsaniXCfh-MLqw-dc1wI39Q7jSGEXiv4k_rcOZ_BorHBvt6O88Wfu1cKvjMgQx0HMTvDcUS_-gfO5qUWM65dKh_hgXRqJBzDAFw0VAnv9gDfbVBjs-uvliK0mWyRHWPCApPb-5kLtu5hm3MsGreTpPz8o8OqQLEDrNAFjbdS7cyeLpq3WP2Fsr5lrzmgD2P29Yclx7xRcVnC6Lc9JUCFBgyEnYuKW7I1yYsDs6a6ny2ksLl9AMuKRzza08DgLHRUcsUfHtfs5IVhvCpqMjs-kFbNPow43j3PdVZDD5B0zP8KyeH02BUOJsOAFBDY34DL-93TAEhSZ9dGlfX9-3VlfEtuY5GXPY

### ~~ variationId
GET https://skorohoda.plentymarkets-cloud02.com/rest/stockmanagement/stock?variationId=34450,34494
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDliOTQ2NTU1YjBkODI0MzAwZjZmZmFmMzliYWRiZGVkODU0ZTMxYjE0MzA4ZGZhMzY2YmMxNWNlZjMyMmM3MjAwMTZjMDRlOTllYjAzMWEiLCJpYXQiOjE2Njc5MDE4NzMuOTM4NywibmJmIjoxNjY3OTAxODczLjkzODcsImV4cCI6MTY2Nzk4ODI3My45Mjk3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.IRz-Wg8CVE-oDHywOzEf-LnNwhb1AgeJYiqhXA5kgfUl9Yg14NswWlysMC55H40K3NCqFgkpLWPNB67qkD36J65Wt3xTEQaTgtKFsvIyzjHMN8A18U0E77yAyDyzu9OJrIowl8S4uYbF7MMiVv_GijFoLilnv_UwHOzlqTfzG6AF8M4qxQ7JzDn3qYuyKzr4KSZy_JBSEtQ6qpO9zwtfnx-ZU-kpGxt6V8wCFpBxzG28iBsQ4Er_mvydHd4y8A4vnQeEvyYe18_OSiegaqu7Wg3dxbCNVBgKIcGeGZYXZ4XzUNivTQ1x02y2AilhG_1vKyRkTbVKUbO_SGsaniXCfh-MLqw-dc1wI39Q7jSGEXiv4k_rcOZ_BorHBvt6O88Wfu1cKvjMgQx0HMTvDcUS_-gfO5qUWM65dKh_hgXRqJBzDAFw0VAnv9gDfbVBjs-uvliK0mWyRHWPCApPb-5kLtu5hm3MsGreTpPz8o8OqQLEDrNAFjbdS7cyeLpq3WP2Fsr5lrzmgD2P29Yclx7xRcVnC6Lc9JUCFBgyEnYuKW7I1yYsDs6a6ny2ksLl9AMuKRzza08DgLHRUcsUfHtfs5IVhvCpqMjs-kFbNPow43j3PdVZDD5B0zP8KyeH02BUOJsOAFBDY34DL-93TAEhSZ9dGlfX9-3VlfEtuY5GXPY

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/stockmanagement/warehouses/1/stock/movements
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDliOTQ2NTU1YjBkODI0MzAwZjZmZmFmMzliYWRiZGVkODU0ZTMxYjE0MzA4ZGZhMzY2YmMxNWNlZjMyMmM3MjAwMTZjMDRlOTllYjAzMWEiLCJpYXQiOjE2Njc5MDE4NzMuOTM4NywibmJmIjoxNjY3OTAxODczLjkzODcsImV4cCI6MTY2Nzk4ODI3My45Mjk3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.IRz-Wg8CVE-oDHywOzEf-LnNwhb1AgeJYiqhXA5kgfUl9Yg14NswWlysMC55H40K3NCqFgkpLWPNB67qkD36J65Wt3xTEQaTgtKFsvIyzjHMN8A18U0E77yAyDyzu9OJrIowl8S4uYbF7MMiVv_GijFoLilnv_UwHOzlqTfzG6AF8M4qxQ7JzDn3qYuyKzr4KSZy_JBSEtQ6qpO9zwtfnx-ZU-kpGxt6V8wCFpBxzG28iBsQ4Er_mvydHd4y8A4vnQeEvyYe18_OSiegaqu7Wg3dxbCNVBgKIcGeGZYXZ4XzUNivTQ1x02y2AilhG_1vKyRkTbVKUbO_SGsaniXCfh-MLqw-dc1wI39Q7jSGEXiv4k_rcOZ_BorHBvt6O88Wfu1cKvjMgQx0HMTvDcUS_-gfO5qUWM65dKh_hgXRqJBzDAFw0VAnv9gDfbVBjs-uvliK0mWyRHWPCApPb-5kLtu5hm3MsGreTpPz8o8OqQLEDrNAFjbdS7cyeLpq3WP2Fsr5lrzmgD2P29Yclx7xRcVnC6Lc9JUCFBgyEnYuKW7I1yYsDs6a6ny2ksLl9AMuKRzza08DgLHRUcsUfHtfs5IVhvCpqMjs-kFbNPow43j3PdVZDD5B0zP8KyeH02BUOJsOAFBDY34DL-93TAEhSZ9dGlfX9-3VlfEtuY5GXPY

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/stockmanagement/stock/types/sales
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDliOTQ2NTU1YjBkODI0MzAwZjZmZmFmMzliYWRiZGVkODU0ZTMxYjE0MzA4ZGZhMzY2YmMxNWNlZjMyMmM3MjAwMTZjMDRlOTllYjAzMWEiLCJpYXQiOjE2Njc5MDE4NzMuOTM4NywibmJmIjoxNjY3OTAxODczLjkzODcsImV4cCI6MTY2Nzk4ODI3My45Mjk3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.IRz-Wg8CVE-oDHywOzEf-LnNwhb1AgeJYiqhXA5kgfUl9Yg14NswWlysMC55H40K3NCqFgkpLWPNB67qkD36J65Wt3xTEQaTgtKFsvIyzjHMN8A18U0E77yAyDyzu9OJrIowl8S4uYbF7MMiVv_GijFoLilnv_UwHOzlqTfzG6AF8M4qxQ7JzDn3qYuyKzr4KSZy_JBSEtQ6qpO9zwtfnx-ZU-kpGxt6V8wCFpBxzG28iBsQ4Er_mvydHd4y8A4vnQeEvyYe18_OSiegaqu7Wg3dxbCNVBgKIcGeGZYXZ4XzUNivTQ1x02y2AilhG_1vKyRkTbVKUbO_SGsaniXCfh-MLqw-dc1wI39Q7jSGEXiv4k_rcOZ_BorHBvt6O88Wfu1cKvjMgQx0HMTvDcUS_-gfO5qUWM65dKh_hgXRqJBzDAFw0VAnv9gDfbVBjs-uvliK0mWyRHWPCApPb-5kLtu5hm3MsGreTpPz8o8OqQLEDrNAFjbdS7cyeLpq3WP2Fsr5lrzmgD2P29Yclx7xRcVnC6Lc9JUCFBgyEnYuKW7I1yYsDs6a6ny2ksLl9AMuKRzza08DgLHRUcsUfHtfs5IVhvCpqMjs-kFbNPow43j3PdVZDD5B0zP8KyeH02BUOJsOAFBDY34DL-93TAEhSZ9dGlfX9-3VlfEtuY5GXPY

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/audit-log/archive
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDliOTQ2NTU1YjBkODI0MzAwZjZmZmFmMzliYWRiZGVkODU0ZTMxYjE0MzA4ZGZhMzY2YmMxNWNlZjMyMmM3MjAwMTZjMDRlOTllYjAzMWEiLCJpYXQiOjE2Njc5MDE4NzMuOTM4NywibmJmIjoxNjY3OTAxODczLjkzODcsImV4cCI6MTY2Nzk4ODI3My45Mjk3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.IRz-Wg8CVE-oDHywOzEf-LnNwhb1AgeJYiqhXA5kgfUl9Yg14NswWlysMC55H40K3NCqFgkpLWPNB67qkD36J65Wt3xTEQaTgtKFsvIyzjHMN8A18U0E77yAyDyzu9OJrIowl8S4uYbF7MMiVv_GijFoLilnv_UwHOzlqTfzG6AF8M4qxQ7JzDn3qYuyKzr4KSZy_JBSEtQ6qpO9zwtfnx-ZU-kpGxt6V8wCFpBxzG28iBsQ4Er_mvydHd4y8A4vnQeEvyYe18_OSiegaqu7Wg3dxbCNVBgKIcGeGZYXZ4XzUNivTQ1x02y2AilhG_1vKyRkTbVKUbO_SGsaniXCfh-MLqw-dc1wI39Q7jSGEXiv4k_rcOZ_BorHBvt6O88Wfu1cKvjMgQx0HMTvDcUS_-gfO5qUWM65dKh_hgXRqJBzDAFw0VAnv9gDfbVBjs-uvliK0mWyRHWPCApPb-5kLtu5hm3MsGreTpPz8o8OqQLEDrNAFjbdS7cyeLpq3WP2Fsr5lrzmgD2P29Yclx7xRcVnC6Lc9JUCFBgyEnYuKW7I1yYsDs6a6ny2ksLl9AMuKRzza08DgLHRUcsUfHtfs5IVhvCpqMjs-kFbNPow43j3PdVZDD5B0zP8KyeH02BUOJsOAFBDY34DL-93TAEhSZ9dGlfX9-3VlfEtuY5GXPY


### batch
GET https://skorohoda.plentymarkets-cloud02.com/rest/batch
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZDliOTQ2NTU1YjBkODI0MzAwZjZmZmFmMzliYWRiZGVkODU0ZTMxYjE0MzA4ZGZhMzY2YmMxNWNlZjMyMmM3MjAwMTZjMDRlOTllYjAzMWEiLCJpYXQiOjE2Njc5MDE4NzMuOTM4NywibmJmIjoxNjY3OTAxODczLjkzODcsImV4cCI6MTY2Nzk4ODI3My45Mjk3LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.IRz-Wg8CVE-oDHywOzEf-LnNwhb1AgeJYiqhXA5kgfUl9Yg14NswWlysMC55H40K3NCqFgkpLWPNB67qkD36J65Wt3xTEQaTgtKFsvIyzjHMN8A18U0E77yAyDyzu9OJrIowl8S4uYbF7MMiVv_GijFoLilnv_UwHOzlqTfzG6AF8M4qxQ7JzDn3qYuyKzr4KSZy_JBSEtQ6qpO9zwtfnx-ZU-kpGxt6V8wCFpBxzG28iBsQ4Er_mvydHd4y8A4vnQeEvyYe18_OSiegaqu7Wg3dxbCNVBgKIcGeGZYXZ4XzUNivTQ1x02y2AilhG_1vKyRkTbVKUbO_SGsaniXCfh-MLqw-dc1wI39Q7jSGEXiv4k_rcOZ_BorHBvt6O88Wfu1cKvjMgQx0HMTvDcUS_-gfO5qUWM65dKh_hgXRqJBzDAFw0VAnv9gDfbVBjs-uvliK0mWyRHWPCApPb-5kLtu5hm3MsGreTpPz8o8OqQLEDrNAFjbdS7cyeLpq3WP2Fsr5lrzmgD2P29Yclx7xRcVnC6Lc9JUCFBgyEnYuKW7I1yYsDs6a6ny2ksLl9AMuKRzza08DgLHRUcsUfHtfs5IVhvCpqMjs-kFbNPow43j3PdVZDD5B0zP8KyeH02BUOJsOAFBDY34DL-93TAEhSZ9dGlfX9-3VlfEtuY5GXPY

{
    "payloads": [
        {
            "resource": "/rest/stockmanagement/stock?variationId=34450",
            "method": "GET",
            "body": {}
        },
        {
            "resource": "/rest/stockmanagement/stock?variationId=34451",
            "method": "GET",
            "body": {}
        }
    ]
}
