GET https://skorohoda.plentymarkets-cloud02.com/rest/backend/users
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTVlZDMzZTM3OGUwNDBhYTJiMTk5YmJhNjA4ZjM1YjhhMGE3YjAzYzNmMmRiYmZiMzRjNzhiN2M1NGY3ODVjZjAyNTU5OTRkMmQyZDJmNTEiLCJpYXQiOjE2MDQxNDAwNDYsIm5iZiI6MTYwNDE0MDA0NiwiZXhwIjoxNjA0MjI2NDQ2LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.Wuqq4kuXtdGUTObGxLSrI1gAGO_vXKj0gvE4dnK08fbCTwJXng4m-4EXBY6HDUbRRdN8uN_BuUPW46VvQwNk0SEOfTBotBloCbDxrBM5UuXjzTybyDCgY41EbF8xQL1PoyEAavieX-8Q2ApjG86lZ-GWJmhMeNR6pEBV7J5fLvQIfbywpe53x9jAgD6fraRSMJFRK86ub4oVvJ_iBgdzwOyB9GZ_6nwDnXX11WCOT3RlNVbyucWEPEN5nrrW0qTfWe74KvmtKPSwglgh0z-cY-Xjds-OMU83nQtIDpv9chi5QSdj65B4SZuBSqwFGxTjME2MLOTtI_wrpVtphgqSPLFd90BTtx2u3ivkoSCjq32yF1CTUu-cEGZDkSOdoqC6NE6KISrA9ei51OLwj1zHBW2C8wGQgynh7CPXyZ32NZNDcucnzhfl0Q5yeGWewtzmAPDDSg9lhu_u_tUuCG_K5HPNe-bD0dcCBPe48rF1XFrXluUBd5S09sN5VPjFTWiJ0y26w21i31mT6AvnmWdGYNddiJc0TBfd0CEnorJCr8YCeZHu5jFqzMzbsOirIZijmB8eF5NhQ0DrkoMzn21k-GZ5dPUl8-y6yyEUTQzcuJBoijzcZGFM4tXmSV6699jpfy3lbUQ-xgRQ05k_fRuAUatb1Jrka7wODoleKsFS_bU
