###
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMWVkYWM3ZjllZmEyYjYzNzA4NTk1NGNjN2ZmZDJjNWVjNmRkNjZlNjQ2ZTUxZjkyNWUwZTI1YjBiYmNjODY3ODg2ZjJjZWFiNzFkZDM1MjkiLCJpYXQiOjE1OTUwNTk3NDQsIm5iZiI6MTU5NTA1OTc0NCwiZXhwIjoxNTk1MTQ2MTQ0LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.ng4nq260r6gRdohqkk7u6ju9AssL65d6J50zEOm-63UsM9bJGsdBJBwBlP5_Urs_sLpoLIjfkrQIgCv52T9PZmz1get_CY3F9n4sM9yiGXEsOmvO3kSc4zLGfr1lJP5Gft311Lf10Tqi8obrs7OmcYCQfPu_Afc7HmJ4JiCjyf3IA7uUY8z7GS86TJbx-WiLxCu3r-qFWg6gmhM1LJ4QuBCrmx0nTRD1N3LfxIWD5r-1av_LRLMOU0sJXy2v1GDp7fgc9eymnRUTI9ETONqRx5Ncc5sPOkOfiZbMiq9X9X0vN7zjWuzYqvJ5I1o2lLnywEpswOBT3VMqsAblsHwabE8iD-BtOtZDyy95lXyPrlggml7vRCncIX7PhX741YB7ZIjTuoCCw8C_wbhprWhB4plokWaoKC1lQ_uJMEb1Zze8zEluMVHSn5QzD7xZOe8bGFxvO8dx8WYkaXEv4E4KxgGsdOaXFqptkJvapr2PgFkF27zE_5GHFbb3Kxybz93EgXkYK6UyQOZoSZa7IIYO_Fk1c4muxcdbO-5gUH2LvMaeSp7bp4ZtMdxXZ8fPKzwDjg5AgqaulIvNcm-mgwcNA3xp67thltbUuonyVitd62MlXUYCKD1abJWPbdwTy2K-YrHdt5v8HkRemc2GnQUTvkUK_DsE8GGFweEq_o8_RMI

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/pim/variations?ids=34435&with=supplier
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMWVkYWM3ZjllZmEyYjYzNzA4NTk1NGNjN2ZmZDJjNWVjNmRkNjZlNjQ2ZTUxZjkyNWUwZTI1YjBiYmNjODY3ODg2ZjJjZWFiNzFkZDM1MjkiLCJpYXQiOjE1OTUwNTk3NDQsIm5iZiI6MTU5NTA1OTc0NCwiZXhwIjoxNTk1MTQ2MTQ0LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.ng4nq260r6gRdohqkk7u6ju9AssL65d6J50zEOm-63UsM9bJGsdBJBwBlP5_Urs_sLpoLIjfkrQIgCv52T9PZmz1get_CY3F9n4sM9yiGXEsOmvO3kSc4zLGfr1lJP5Gft311Lf10Tqi8obrs7OmcYCQfPu_Afc7HmJ4JiCjyf3IA7uUY8z7GS86TJbx-WiLxCu3r-qFWg6gmhM1LJ4QuBCrmx0nTRD1N3LfxIWD5r-1av_LRLMOU0sJXy2v1GDp7fgc9eymnRUTI9ETONqRx5Ncc5sPOkOfiZbMiq9X9X0vN7zjWuzYqvJ5I1o2lLnywEpswOBT3VMqsAblsHwabE8iD-BtOtZDyy95lXyPrlggml7vRCncIX7PhX741YB7ZIjTuoCCw8C_wbhprWhB4plokWaoKC1lQ_uJMEb1Zze8zEluMVHSn5QzD7xZOe8bGFxvO8dx8WYkaXEv4E4KxgGsdOaXFqptkJvapr2PgFkF27zE_5GHFbb3Kxybz93EgXkYK6UyQOZoSZa7IIYO_Fk1c4muxcdbO-5gUH2LvMaeSp7bp4ZtMdxXZ8fPKzwDjg5AgqaulIvNcm-mgwcNA3xp67thltbUuonyVitd62MlXUYCKD1abJWPbdwTy2K-YrHdt5v8HkRemc2GnQUTvkUK_DsE8GGFweEq_o8_RMI
