###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/7787/variations/29097?with=stock
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZWY3MmNhNTM5M2Q3YTRjM2E1MjFmYzg5Y2QyZGE4MzVmYzc5MmJlZmU2ZTIyOTIwZTYzMjdhMjQ3NjdhYWMxOWI5ZmY2NTBkYWFlNGM4MWMiLCJpYXQiOjE2MTgxMjUxMzUsIm5iZiI6MTYxODEyNTEzNSwiZXhwIjoxNjE4MjExNTM1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.mzS50LrrgOs9mMZE-o2iGF8xEsMT17E4HH0GRzrsWc9dV7xguXUhQF69oglqEdgxqZZJ5h2yyR7P4UJyy78Y1rDImQbJ0EqKJ16wCuQu4RP-CHngXPywAUfSPPZi4tFfxZLA0-MuWy0mToUVh4fJicHKn6IuCRfN5jUbToP2JGDLARGJiD_z8HsaFQNlD31JXKa9TMrRgb6p_FXsateJ0rWhnYp2fiUOZ8CF0poGYvMSbgnzyt1kv4BysfWCI92YlB6SCrrHEzbbSCPfnD2txT3gJwZw1DLLGKnb6KQoWKzMrJCol8dBesRvdjxBh88PYCYuYS7eTax2NHisV_MPoP-1HjK14hI0D03DufuY7HgCwnkt1sUtjL4_pEJjcDCGdjjC2RQbzW6lKU6xrF29jzQKRpNNhvyWmEvwsdsODTc3ZfE3LiaPMUhd-zY5evcC0YCOlDFX-GLMcoGudc5idqtJW-7HNRLmZLTPW1Jb7J4mzP5Hov3Io5wcjHyO83RspUmTbRzzmfHt7vpDAtRA3zVR2aqH-T1VHQWfud6PfpgAu8yYlEbAEBuQWdgbNq1cPsIHYGhYHGzc67RQpLqF7YInWIjeESOficmOmizp0jFBYEGxYO_MCu2rRGg9RE-QOzCTAwTzfO7tk6Sjvrtuyv92mDLRGhxN6jlBfOblZAc

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/7769/variations?with=stock
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZWY3MmNhNTM5M2Q3YTRjM2E1MjFmYzg5Y2QyZGE4MzVmYzc5MmJlZmU2ZTIyOTIwZTYzMjdhMjQ3NjdhYWMxOWI5ZmY2NTBkYWFlNGM4MWMiLCJpYXQiOjE2MTgxMjUxMzUsIm5iZiI6MTYxODEyNTEzNSwiZXhwIjoxNjE4MjExNTM1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.mzS50LrrgOs9mMZE-o2iGF8xEsMT17E4HH0GRzrsWc9dV7xguXUhQF69oglqEdgxqZZJ5h2yyR7P4UJyy78Y1rDImQbJ0EqKJ16wCuQu4RP-CHngXPywAUfSPPZi4tFfxZLA0-MuWy0mToUVh4fJicHKn6IuCRfN5jUbToP2JGDLARGJiD_z8HsaFQNlD31JXKa9TMrRgb6p_FXsateJ0rWhnYp2fiUOZ8CF0poGYvMSbgnzyt1kv4BysfWCI92YlB6SCrrHEzbbSCPfnD2txT3gJwZw1DLLGKnb6KQoWKzMrJCol8dBesRvdjxBh88PYCYuYS7eTax2NHisV_MPoP-1HjK14hI0D03DufuY7HgCwnkt1sUtjL4_pEJjcDCGdjjC2RQbzW6lKU6xrF29jzQKRpNNhvyWmEvwsdsODTc3ZfE3LiaPMUhd-zY5evcC0YCOlDFX-GLMcoGudc5idqtJW-7HNRLmZLTPW1Jb7J4mzP5Hov3Io5wcjHyO83RspUmTbRzzmfHt7vpDAtRA3zVR2aqH-T1VHQWfud6PfpgAu8yYlEbAEBuQWdgbNq1cPsIHYGhYHGzc67RQpLqF7YInWIjeESOficmOmizp0jFBYEGxYO_MCu2rRGg9RE-QOzCTAwTzfO7tk6Sjvrtuyv92mDLRGhxN6jlBfOblZAc

###
PUT https://skorohoda.plentymarkets-cloud02.com/rest/items/7807/variations/29152/stock/correction
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZWY3MmNhNTM5M2Q3YTRjM2E1MjFmYzg5Y2QyZGE4MzVmYzc5MmJlZmU2ZTIyOTIwZTYzMjdhMjQ3NjdhYWMxOWI5ZmY2NTBkYWFlNGM4MWMiLCJpYXQiOjE2MTgxMjUxMzUsIm5iZiI6MTYxODEyNTEzNSwiZXhwIjoxNjE4MjExNTM1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.mzS50LrrgOs9mMZE-o2iGF8xEsMT17E4HH0GRzrsWc9dV7xguXUhQF69oglqEdgxqZZJ5h2yyR7P4UJyy78Y1rDImQbJ0EqKJ16wCuQu4RP-CHngXPywAUfSPPZi4tFfxZLA0-MuWy0mToUVh4fJicHKn6IuCRfN5jUbToP2JGDLARGJiD_z8HsaFQNlD31JXKa9TMrRgb6p_FXsateJ0rWhnYp2fiUOZ8CF0poGYvMSbgnzyt1kv4BysfWCI92YlB6SCrrHEzbbSCPfnD2txT3gJwZw1DLLGKnb6KQoWKzMrJCol8dBesRvdjxBh88PYCYuYS7eTax2NHisV_MPoP-1HjK14hI0D03DufuY7HgCwnkt1sUtjL4_pEJjcDCGdjjC2RQbzW6lKU6xrF29jzQKRpNNhvyWmEvwsdsODTc3ZfE3LiaPMUhd-zY5evcC0YCOlDFX-GLMcoGudc5idqtJW-7HNRLmZLTPW1Jb7J4mzP5Hov3Io5wcjHyO83RspUmTbRzzmfHt7vpDAtRA3zVR2aqH-T1VHQWfud6PfpgAu8yYlEbAEBuQWdgbNq1cPsIHYGhYHGzc67RQpLqF7YInWIjeESOficmOmizp0jFBYEGxYO_MCu2rRGg9RE-QOzCTAwTzfO7tk6Sjvrtuyv92mDLRGhxN6jlBfOblZAc

{"quantity":5,"warehouseId":"1","storageLocationId":0,"reasonId":301}

###
PUT https://skorohoda.plentymarkets-cloud02.com/rest/stockmanagement/warehouses/103/stock/correction
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZWY3MmNhNTM5M2Q3YTRjM2E1MjFmYzg5Y2QyZGE4MzVmYzc5MmJlZmU2ZTIyOTIwZTYzMjdhMjQ3NjdhYWMxOWI5ZmY2NTBkYWFlNGM4MWMiLCJpYXQiOjE2MTgxMjUxMzUsIm5iZiI6MTYxODEyNTEzNSwiZXhwIjoxNjE4MjExNTM1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.mzS50LrrgOs9mMZE-o2iGF8xEsMT17E4HH0GRzrsWc9dV7xguXUhQF69oglqEdgxqZZJ5h2yyR7P4UJyy78Y1rDImQbJ0EqKJ16wCuQu4RP-CHngXPywAUfSPPZi4tFfxZLA0-MuWy0mToUVh4fJicHKn6IuCRfN5jUbToP2JGDLARGJiD_z8HsaFQNlD31JXKa9TMrRgb6p_FXsateJ0rWhnYp2fiUOZ8CF0poGYvMSbgnzyt1kv4BysfWCI92YlB6SCrrHEzbbSCPfnD2txT3gJwZw1DLLGKnb6KQoWKzMrJCol8dBesRvdjxBh88PYCYuYS7eTax2NHisV_MPoP-1HjK14hI0D03DufuY7HgCwnkt1sUtjL4_pEJjcDCGdjjC2RQbzW6lKU6xrF29jzQKRpNNhvyWmEvwsdsODTc3ZfE3LiaPMUhd-zY5evcC0YCOlDFX-GLMcoGudc5idqtJW-7HNRLmZLTPW1Jb7J4mzP5Hov3Io5wcjHyO83RspUmTbRzzmfHt7vpDAtRA3zVR2aqH-T1VHQWfud6PfpgAu8yYlEbAEBuQWdgbNq1cPsIHYGhYHGzc67RQpLqF7YInWIjeESOficmOmizp0jFBYEGxYO_MCu2rRGg9RE-QOzCTAwTzfO7tk6Sjvrtuyv92mDLRGhxN6jlBfOblZAc

{
    "corrections": [
        {
            "variationId": 29252,
            "reasonId": 304,
            "quantity": 50,
            "storageLocationId": 27
        }
    ]
}

###
