###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/variations
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGU0NTVjYmM1MjFkZjQyMjUwOGRiMGRjYThiMmVmOGI4NDA5ZWFhMjRhOWE3ZWFiYzYyZjRjMGUyZjRlZGE1NDkyZmM5ZTRhNDE3MmRiNzIiLCJpYXQiOjE2NTI2ODg2MDUuMTY1NCwibmJmIjoxNjUyNjg4NjA1LjE2NTQsImV4cCI6MTY1Mjc3NTAwNS4xNDk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.O55IJmFgxCmRdC42bMQVd6_KN1YoLDjadwwtTm_1hz9qrA5snFu4hg8WvkH2wjNcYpxqbXTH4ZeEciTBzJcA2kHZ5B91ZuY84Jl2t_mz49OkVi9P-a-jOdA3jl_oGz3r0kUHBdFzpoyJvW3c2jwsbXqwbhKV75UKYv4XDDiQlDqlSDTo6ZO4cOsrZGNy2wfGdgCGJ2o5DcSKapMWPFeSQtpDAqucrRlVQhtTW2tlmjJ_nNHn8UNQUhWK-S8qIM1xhUzYpSzFYsrYocnt-1MDCzqnkf6PnY3P9POcTP4skWu3r5QQTHATA7Hap-drXlaGKc8zfnz1U77uaev7wCwlu6M8YnEcKcUEoKVXltxwDILtXy7DkfxCU0GEIBAku9K0QqyDzW0pkmAk_sT_oGmJbU9hzllXmgTXqagUg3zZBJH_MiiIU5LiIw4dN5FnSDNoY3IvWVMgyXdI1vUKb_Pr6w7Cml3xne4zKQznPWhoDAjJ97WLqnpcGzooItsZ2u6W0MrGKVToeXVYhNMJwIDmJh_3aAZKs9_IDc2YeyTIHRp0hcPNX6YVKqOjIRmsdjsS4yZKDJF5GPhKY3nQduySM1svweYbQt0PYw-d4VN_1QQvcg3F6HN0dlHpXyVVMa8xSJdDKW8TX6BO5IRkw7Ab6tG0YeVcL0UeN-M27NEfWVA

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/variations?id=7730
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGU0NTVjYmM1MjFkZjQyMjUwOGRiMGRjYThiMmVmOGI4NDA5ZWFhMjRhOWE3ZWFiYzYyZjRjMGUyZjRlZGE1NDkyZmM5ZTRhNDE3MmRiNzIiLCJpYXQiOjE2NTI2ODg2MDUuMTY1NCwibmJmIjoxNjUyNjg4NjA1LjE2NTQsImV4cCI6MTY1Mjc3NTAwNS4xNDk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.O55IJmFgxCmRdC42bMQVd6_KN1YoLDjadwwtTm_1hz9qrA5snFu4hg8WvkH2wjNcYpxqbXTH4ZeEciTBzJcA2kHZ5B91ZuY84Jl2t_mz49OkVi9P-a-jOdA3jl_oGz3r0kUHBdFzpoyJvW3c2jwsbXqwbhKV75UKYv4XDDiQlDqlSDTo6ZO4cOsrZGNy2wfGdgCGJ2o5DcSKapMWPFeSQtpDAqucrRlVQhtTW2tlmjJ_nNHn8UNQUhWK-S8qIM1xhUzYpSzFYsrYocnt-1MDCzqnkf6PnY3P9POcTP4skWu3r5QQTHATA7Hap-drXlaGKc8zfnz1U77uaev7wCwlu6M8YnEcKcUEoKVXltxwDILtXy7DkfxCU0GEIBAku9K0QqyDzW0pkmAk_sT_oGmJbU9hzllXmgTXqagUg3zZBJH_MiiIU5LiIw4dN5FnSDNoY3IvWVMgyXdI1vUKb_Pr6w7Cml3xne4zKQznPWhoDAjJ97WLqnpcGzooItsZ2u6W0MrGKVToeXVYhNMJwIDmJh_3aAZKs9_IDc2YeyTIHRp0hcPNX6YVKqOjIRmsdjsS4yZKDJF5GPhKY3nQduySM1svweYbQt0PYw-d4VN_1QQvcg3F6HN0dlHpXyVVMa8xSJdDKW8TX6BO5IRkw7Ab6tG0YeVcL0UeN-M27NEfWVA

### with=properties,variationProperties,variationBarcodes,variationBundleComponents,variationComponentBundles,variationSalesPrices,marketItemNumbers,variationCategories,variationClients,variationMarkets,variationDefaultCategory,variationSuppliers,variationWarehouses,images,itemImages,variationAttributeValues,variationSkus,variationAdditionalSkus,unit,parent,item,stock
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/variations?id=34570&with=properties,variationProperties,variationBarcodes,variationBundleComponents,variationComponentBundles,variationSalesPrices,marketItemNumbers,variationCategories,variationClients,variationMarkets,variationDefaultCategory,variationSuppliers,variationWarehouses,images,itemImages,variationAttributeValues,variationSkus,variationAdditionalSkus,unit,parent,item,stock
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGU0NTVjYmM1MjFkZjQyMjUwOGRiMGRjYThiMmVmOGI4NDA5ZWFhMjRhOWE3ZWFiYzYyZjRjMGUyZjRlZGE1NDkyZmM5ZTRhNDE3MmRiNzIiLCJpYXQiOjE2NTI2ODg2MDUuMTY1NCwibmJmIjoxNjUyNjg4NjA1LjE2NTQsImV4cCI6MTY1Mjc3NTAwNS4xNDk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.O55IJmFgxCmRdC42bMQVd6_KN1YoLDjadwwtTm_1hz9qrA5snFu4hg8WvkH2wjNcYpxqbXTH4ZeEciTBzJcA2kHZ5B91ZuY84Jl2t_mz49OkVi9P-a-jOdA3jl_oGz3r0kUHBdFzpoyJvW3c2jwsbXqwbhKV75UKYv4XDDiQlDqlSDTo6ZO4cOsrZGNy2wfGdgCGJ2o5DcSKapMWPFeSQtpDAqucrRlVQhtTW2tlmjJ_nNHn8UNQUhWK-S8qIM1xhUzYpSzFYsrYocnt-1MDCzqnkf6PnY3P9POcTP4skWu3r5QQTHATA7Hap-drXlaGKc8zfnz1U77uaev7wCwlu6M8YnEcKcUEoKVXltxwDILtXy7DkfxCU0GEIBAku9K0QqyDzW0pkmAk_sT_oGmJbU9hzllXmgTXqagUg3zZBJH_MiiIU5LiIw4dN5FnSDNoY3IvWVMgyXdI1vUKb_Pr6w7Cml3xne4zKQznPWhoDAjJ97WLqnpcGzooItsZ2u6W0MrGKVToeXVYhNMJwIDmJh_3aAZKs9_IDc2YeyTIHRp0hcPNX6YVKqOjIRmsdjsS4yZKDJF5GPhKY3nQduySM1svweYbQt0PYw-d4VN_1QQvcg3F6HN0dlHpXyVVMa8xSJdDKW8TX6BO5IRkw7Ab6tG0YeVcL0UeN-M27NEfWVA

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/7730/variations
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGU0NTVjYmM1MjFkZjQyMjUwOGRiMGRjYThiMmVmOGI4NDA5ZWFhMjRhOWE3ZWFiYzYyZjRjMGUyZjRlZGE1NDkyZmM5ZTRhNDE3MmRiNzIiLCJpYXQiOjE2NTI2ODg2MDUuMTY1NCwibmJmIjoxNjUyNjg4NjA1LjE2NTQsImV4cCI6MTY1Mjc3NTAwNS4xNDk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.O55IJmFgxCmRdC42bMQVd6_KN1YoLDjadwwtTm_1hz9qrA5snFu4hg8WvkH2wjNcYpxqbXTH4ZeEciTBzJcA2kHZ5B91ZuY84Jl2t_mz49OkVi9P-a-jOdA3jl_oGz3r0kUHBdFzpoyJvW3c2jwsbXqwbhKV75UKYv4XDDiQlDqlSDTo6ZO4cOsrZGNy2wfGdgCGJ2o5DcSKapMWPFeSQtpDAqucrRlVQhtTW2tlmjJ_nNHn8UNQUhWK-S8qIM1xhUzYpSzFYsrYocnt-1MDCzqnkf6PnY3P9POcTP4skWu3r5QQTHATA7Hap-drXlaGKc8zfnz1U77uaev7wCwlu6M8YnEcKcUEoKVXltxwDILtXy7DkfxCU0GEIBAku9K0QqyDzW0pkmAk_sT_oGmJbU9hzllXmgTXqagUg3zZBJH_MiiIU5LiIw4dN5FnSDNoY3IvWVMgyXdI1vUKb_Pr6w7Cml3xne4zKQznPWhoDAjJ97WLqnpcGzooItsZ2u6W0MrGKVToeXVYhNMJwIDmJh_3aAZKs9_IDc2YeyTIHRp0hcPNX6YVKqOjIRmsdjsS4yZKDJF5GPhKY3nQduySM1svweYbQt0PYw-d4VN_1QQvcg3F6HN0dlHpXyVVMa8xSJdDKW8TX6BO5IRkw7Ab6tG0YeVcL0UeN-M27NEfWVA

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/8364/variations/34484
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGU0NTVjYmM1MjFkZjQyMjUwOGRiMGRjYThiMmVmOGI4NDA5ZWFhMjRhOWE3ZWFiYzYyZjRjMGUyZjRlZGE1NDkyZmM5ZTRhNDE3MmRiNzIiLCJpYXQiOjE2NTI2ODg2MDUuMTY1NCwibmJmIjoxNjUyNjg4NjA1LjE2NTQsImV4cCI6MTY1Mjc3NTAwNS4xNDk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.O55IJmFgxCmRdC42bMQVd6_KN1YoLDjadwwtTm_1hz9qrA5snFu4hg8WvkH2wjNcYpxqbXTH4ZeEciTBzJcA2kHZ5B91ZuY84Jl2t_mz49OkVi9P-a-jOdA3jl_oGz3r0kUHBdFzpoyJvW3c2jwsbXqwbhKV75UKYv4XDDiQlDqlSDTo6ZO4cOsrZGNy2wfGdgCGJ2o5DcSKapMWPFeSQtpDAqucrRlVQhtTW2tlmjJ_nNHn8UNQUhWK-S8qIM1xhUzYpSzFYsrYocnt-1MDCzqnkf6PnY3P9POcTP4skWu3r5QQTHATA7Hap-drXlaGKc8zfnz1U77uaev7wCwlu6M8YnEcKcUEoKVXltxwDILtXy7DkfxCU0GEIBAku9K0QqyDzW0pkmAk_sT_oGmJbU9hzllXmgTXqagUg3zZBJH_MiiIU5LiIw4dN5FnSDNoY3IvWVMgyXdI1vUKb_Pr6w7Cml3xne4zKQznPWhoDAjJ97WLqnpcGzooItsZ2u6W0MrGKVToeXVYhNMJwIDmJh_3aAZKs9_IDc2YeyTIHRp0hcPNX6YVKqOjIRmsdjsS4yZKDJF5GPhKY3nQduySM1svweYbQt0PYw-d4VN_1QQvcg3F6HN0dlHpXyVVMa8xSJdDKW8TX6BO5IRkw7Ab6tG0YeVcL0UeN-M27NEfWVA

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/8343/variations/34372?with=variationWarehouses
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGU0NTVjYmM1MjFkZjQyMjUwOGRiMGRjYThiMmVmOGI4NDA5ZWFhMjRhOWE3ZWFiYzYyZjRjMGUyZjRlZGE1NDkyZmM5ZTRhNDE3MmRiNzIiLCJpYXQiOjE2NTI2ODg2MDUuMTY1NCwibmJmIjoxNjUyNjg4NjA1LjE2NTQsImV4cCI6MTY1Mjc3NTAwNS4xNDk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.O55IJmFgxCmRdC42bMQVd6_KN1YoLDjadwwtTm_1hz9qrA5snFu4hg8WvkH2wjNcYpxqbXTH4ZeEciTBzJcA2kHZ5B91ZuY84Jl2t_mz49OkVi9P-a-jOdA3jl_oGz3r0kUHBdFzpoyJvW3c2jwsbXqwbhKV75UKYv4XDDiQlDqlSDTo6ZO4cOsrZGNy2wfGdgCGJ2o5DcSKapMWPFeSQtpDAqucrRlVQhtTW2tlmjJ_nNHn8UNQUhWK-S8qIM1xhUzYpSzFYsrYocnt-1MDCzqnkf6PnY3P9POcTP4skWu3r5QQTHATA7Hap-drXlaGKc8zfnz1U77uaev7wCwlu6M8YnEcKcUEoKVXltxwDILtXy7DkfxCU0GEIBAku9K0QqyDzW0pkmAk_sT_oGmJbU9hzllXmgTXqagUg3zZBJH_MiiIU5LiIw4dN5FnSDNoY3IvWVMgyXdI1vUKb_Pr6w7Cml3xne4zKQznPWhoDAjJ97WLqnpcGzooItsZ2u6W0MrGKVToeXVYhNMJwIDmJh_3aAZKs9_IDc2YeyTIHRp0hcPNX6YVKqOjIRmsdjsS4yZKDJF5GPhKY3nQduySM1svweYbQt0PYw-d4VN_1QQvcg3F6HN0dlHpXyVVMa8xSJdDKW8TX6BO5IRkw7Ab6tG0YeVcL0UeN-M27NEfWVA

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/variations?with=variationTexts
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGU0NTVjYmM1MjFkZjQyMjUwOGRiMGRjYThiMmVmOGI4NDA5ZWFhMjRhOWE3ZWFiYzYyZjRjMGUyZjRlZGE1NDkyZmM5ZTRhNDE3MmRiNzIiLCJpYXQiOjE2NTI2ODg2MDUuMTY1NCwibmJmIjoxNjUyNjg4NjA1LjE2NTQsImV4cCI6MTY1Mjc3NTAwNS4xNDk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.O55IJmFgxCmRdC42bMQVd6_KN1YoLDjadwwtTm_1hz9qrA5snFu4hg8WvkH2wjNcYpxqbXTH4ZeEciTBzJcA2kHZ5B91ZuY84Jl2t_mz49OkVi9P-a-jOdA3jl_oGz3r0kUHBdFzpoyJvW3c2jwsbXqwbhKV75UKYv4XDDiQlDqlSDTo6ZO4cOsrZGNy2wfGdgCGJ2o5DcSKapMWPFeSQtpDAqucrRlVQhtTW2tlmjJ_nNHn8UNQUhWK-S8qIM1xhUzYpSzFYsrYocnt-1MDCzqnkf6PnY3P9POcTP4skWu3r5QQTHATA7Hap-drXlaGKc8zfnz1U77uaev7wCwlu6M8YnEcKcUEoKVXltxwDILtXy7DkfxCU0GEIBAku9K0QqyDzW0pkmAk_sT_oGmJbU9hzllXmgTXqagUg3zZBJH_MiiIU5LiIw4dN5FnSDNoY3IvWVMgyXdI1vUKb_Pr6w7Cml3xne4zKQznPWhoDAjJ97WLqnpcGzooItsZ2u6W0MrGKVToeXVYhNMJwIDmJh_3aAZKs9_IDc2YeyTIHRp0hcPNX6YVKqOjIRmsdjsS4yZKDJF5GPhKY3nQduySM1svweYbQt0PYw-d4VN_1QQvcg3F6HN0dlHpXyVVMa8xSJdDKW8TX6BO5IRkw7Ab6tG0YeVcL0UeN-M27NEfWVA

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/7769/variations?with=variationBarcodes
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGU0NTVjYmM1MjFkZjQyMjUwOGRiMGRjYThiMmVmOGI4NDA5ZWFhMjRhOWE3ZWFiYzYyZjRjMGUyZjRlZGE1NDkyZmM5ZTRhNDE3MmRiNzIiLCJpYXQiOjE2NTI2ODg2MDUuMTY1NCwibmJmIjoxNjUyNjg4NjA1LjE2NTQsImV4cCI6MTY1Mjc3NTAwNS4xNDk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.O55IJmFgxCmRdC42bMQVd6_KN1YoLDjadwwtTm_1hz9qrA5snFu4hg8WvkH2wjNcYpxqbXTH4ZeEciTBzJcA2kHZ5B91ZuY84Jl2t_mz49OkVi9P-a-jOdA3jl_oGz3r0kUHBdFzpoyJvW3c2jwsbXqwbhKV75UKYv4XDDiQlDqlSDTo6ZO4cOsrZGNy2wfGdgCGJ2o5DcSKapMWPFeSQtpDAqucrRlVQhtTW2tlmjJ_nNHn8UNQUhWK-S8qIM1xhUzYpSzFYsrYocnt-1MDCzqnkf6PnY3P9POcTP4skWu3r5QQTHATA7Hap-drXlaGKc8zfnz1U77uaev7wCwlu6M8YnEcKcUEoKVXltxwDILtXy7DkfxCU0GEIBAku9K0QqyDzW0pkmAk_sT_oGmJbU9hzllXmgTXqagUg3zZBJH_MiiIU5LiIw4dN5FnSDNoY3IvWVMgyXdI1vUKb_Pr6w7Cml3xne4zKQznPWhoDAjJ97WLqnpcGzooItsZ2u6W0MrGKVToeXVYhNMJwIDmJh_3aAZKs9_IDc2YeyTIHRp0hcPNX6YVKqOjIRmsdjsS4yZKDJF5GPhKY3nQduySM1svweYbQt0PYw-d4VN_1QQvcg3F6HN0dlHpXyVVMa8xSJdDKW8TX6BO5IRkw7Ab6tG0YeVcL0UeN-M27NEfWVA

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/8358/variations/34450?with=parent,variationSalesPrices
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGU0NTVjYmM1MjFkZjQyMjUwOGRiMGRjYThiMmVmOGI4NDA5ZWFhMjRhOWE3ZWFiYzYyZjRjMGUyZjRlZGE1NDkyZmM5ZTRhNDE3MmRiNzIiLCJpYXQiOjE2NTI2ODg2MDUuMTY1NCwibmJmIjoxNjUyNjg4NjA1LjE2NTQsImV4cCI6MTY1Mjc3NTAwNS4xNDk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.O55IJmFgxCmRdC42bMQVd6_KN1YoLDjadwwtTm_1hz9qrA5snFu4hg8WvkH2wjNcYpxqbXTH4ZeEciTBzJcA2kHZ5B91ZuY84Jl2t_mz49OkVi9P-a-jOdA3jl_oGz3r0kUHBdFzpoyJvW3c2jwsbXqwbhKV75UKYv4XDDiQlDqlSDTo6ZO4cOsrZGNy2wfGdgCGJ2o5DcSKapMWPFeSQtpDAqucrRlVQhtTW2tlmjJ_nNHn8UNQUhWK-S8qIM1xhUzYpSzFYsrYocnt-1MDCzqnkf6PnY3P9POcTP4skWu3r5QQTHATA7Hap-drXlaGKc8zfnz1U77uaev7wCwlu6M8YnEcKcUEoKVXltxwDILtXy7DkfxCU0GEIBAku9K0QqyDzW0pkmAk_sT_oGmJbU9hzllXmgTXqagUg3zZBJH_MiiIU5LiIw4dN5FnSDNoY3IvWVMgyXdI1vUKb_Pr6w7Cml3xne4zKQznPWhoDAjJ97WLqnpcGzooItsZ2u6W0MrGKVToeXVYhNMJwIDmJh_3aAZKs9_IDc2YeyTIHRp0hcPNX6YVKqOjIRmsdjsS4yZKDJF5GPhKY3nQduySM1svweYbQt0PYw-d4VN_1QQvcg3F6HN0dlHpXyVVMa8xSJdDKW8TX6BO5IRkw7Ab6tG0YeVcL0UeN-M27NEfWVA

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/7730/variations?updatedBetween=2020-01-27T11:23:40+00:00
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGU0NTVjYmM1MjFkZjQyMjUwOGRiMGRjYThiMmVmOGI4NDA5ZWFhMjRhOWE3ZWFiYzYyZjRjMGUyZjRlZGE1NDkyZmM5ZTRhNDE3MmRiNzIiLCJpYXQiOjE2NTI2ODg2MDUuMTY1NCwibmJmIjoxNjUyNjg4NjA1LjE2NTQsImV4cCI6MTY1Mjc3NTAwNS4xNDk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.O55IJmFgxCmRdC42bMQVd6_KN1YoLDjadwwtTm_1hz9qrA5snFu4hg8WvkH2wjNcYpxqbXTH4ZeEciTBzJcA2kHZ5B91ZuY84Jl2t_mz49OkVi9P-a-jOdA3jl_oGz3r0kUHBdFzpoyJvW3c2jwsbXqwbhKV75UKYv4XDDiQlDqlSDTo6ZO4cOsrZGNy2wfGdgCGJ2o5DcSKapMWPFeSQtpDAqucrRlVQhtTW2tlmjJ_nNHn8UNQUhWK-S8qIM1xhUzYpSzFYsrYocnt-1MDCzqnkf6PnY3P9POcTP4skWu3r5QQTHATA7Hap-drXlaGKc8zfnz1U77uaev7wCwlu6M8YnEcKcUEoKVXltxwDILtXy7DkfxCU0GEIBAku9K0QqyDzW0pkmAk_sT_oGmJbU9hzllXmgTXqagUg3zZBJH_MiiIU5LiIw4dN5FnSDNoY3IvWVMgyXdI1vUKb_Pr6w7Cml3xne4zKQznPWhoDAjJ97WLqnpcGzooItsZ2u6W0MrGKVToeXVYhNMJwIDmJh_3aAZKs9_IDc2YeyTIHRp0hcPNX6YVKqOjIRmsdjsS4yZKDJF5GPhKY3nQduySM1svweYbQt0PYw-d4VN_1QQvcg3F6HN0dlHpXyVVMa8xSJdDKW8TX6BO5IRkw7Ab6tG0YeVcL0UeN-M27NEfWVA

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/7769/variation_images
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGU0NTVjYmM1MjFkZjQyMjUwOGRiMGRjYThiMmVmOGI4NDA5ZWFhMjRhOWE3ZWFiYzYyZjRjMGUyZjRlZGE1NDkyZmM5ZTRhNDE3MmRiNzIiLCJpYXQiOjE2NTI2ODg2MDUuMTY1NCwibmJmIjoxNjUyNjg4NjA1LjE2NTQsImV4cCI6MTY1Mjc3NTAwNS4xNDk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.O55IJmFgxCmRdC42bMQVd6_KN1YoLDjadwwtTm_1hz9qrA5snFu4hg8WvkH2wjNcYpxqbXTH4ZeEciTBzJcA2kHZ5B91ZuY84Jl2t_mz49OkVi9P-a-jOdA3jl_oGz3r0kUHBdFzpoyJvW3c2jwsbXqwbhKV75UKYv4XDDiQlDqlSDTo6ZO4cOsrZGNy2wfGdgCGJ2o5DcSKapMWPFeSQtpDAqucrRlVQhtTW2tlmjJ_nNHn8UNQUhWK-S8qIM1xhUzYpSzFYsrYocnt-1MDCzqnkf6PnY3P9POcTP4skWu3r5QQTHATA7Hap-drXlaGKc8zfnz1U77uaev7wCwlu6M8YnEcKcUEoKVXltxwDILtXy7DkfxCU0GEIBAku9K0QqyDzW0pkmAk_sT_oGmJbU9hzllXmgTXqagUg3zZBJH_MiiIU5LiIw4dN5FnSDNoY3IvWVMgyXdI1vUKb_Pr6w7Cml3xne4zKQznPWhoDAjJ97WLqnpcGzooItsZ2u6W0MrGKVToeXVYhNMJwIDmJh_3aAZKs9_IDc2YeyTIHRp0hcPNX6YVKqOjIRmsdjsS4yZKDJF5GPhKY3nQduySM1svweYbQt0PYw-d4VN_1QQvcg3F6HN0dlHpXyVVMa8xSJdDKW8TX6BO5IRkw7Ab6tG0YeVcL0UeN-M27NEfWVA

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/7769/variations/29044/variation_images
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGU0NTVjYmM1MjFkZjQyMjUwOGRiMGRjYThiMmVmOGI4NDA5ZWFhMjRhOWE3ZWFiYzYyZjRjMGUyZjRlZGE1NDkyZmM5ZTRhNDE3MmRiNzIiLCJpYXQiOjE2NTI2ODg2MDUuMTY1NCwibmJmIjoxNjUyNjg4NjA1LjE2NTQsImV4cCI6MTY1Mjc3NTAwNS4xNDk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.O55IJmFgxCmRdC42bMQVd6_KN1YoLDjadwwtTm_1hz9qrA5snFu4hg8WvkH2wjNcYpxqbXTH4ZeEciTBzJcA2kHZ5B91ZuY84Jl2t_mz49OkVi9P-a-jOdA3jl_oGz3r0kUHBdFzpoyJvW3c2jwsbXqwbhKV75UKYv4XDDiQlDqlSDTo6ZO4cOsrZGNy2wfGdgCGJ2o5DcSKapMWPFeSQtpDAqucrRlVQhtTW2tlmjJ_nNHn8UNQUhWK-S8qIM1xhUzYpSzFYsrYocnt-1MDCzqnkf6PnY3P9POcTP4skWu3r5QQTHATA7Hap-drXlaGKc8zfnz1U77uaev7wCwlu6M8YnEcKcUEoKVXltxwDILtXy7DkfxCU0GEIBAku9K0QqyDzW0pkmAk_sT_oGmJbU9hzllXmgTXqagUg3zZBJH_MiiIU5LiIw4dN5FnSDNoY3IvWVMgyXdI1vUKb_Pr6w7Cml3xne4zKQznPWhoDAjJ97WLqnpcGzooItsZ2u6W0MrGKVToeXVYhNMJwIDmJh_3aAZKs9_IDc2YeyTIHRp0hcPNX6YVKqOjIRmsdjsS4yZKDJF5GPhKY3nQduySM1svweYbQt0PYw-d4VN_1QQvcg3F6HN0dlHpXyVVMa8xSJdDKW8TX6BO5IRkw7Ab6tG0YeVcL0UeN-M27NEfWVA

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/7769/variations/29044?with=images
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGU0NTVjYmM1MjFkZjQyMjUwOGRiMGRjYThiMmVmOGI4NDA5ZWFhMjRhOWE3ZWFiYzYyZjRjMGUyZjRlZGE1NDkyZmM5ZTRhNDE3MmRiNzIiLCJpYXQiOjE2NTI2ODg2MDUuMTY1NCwibmJmIjoxNjUyNjg4NjA1LjE2NTQsImV4cCI6MTY1Mjc3NTAwNS4xNDk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.O55IJmFgxCmRdC42bMQVd6_KN1YoLDjadwwtTm_1hz9qrA5snFu4hg8WvkH2wjNcYpxqbXTH4ZeEciTBzJcA2kHZ5B91ZuY84Jl2t_mz49OkVi9P-a-jOdA3jl_oGz3r0kUHBdFzpoyJvW3c2jwsbXqwbhKV75UKYv4XDDiQlDqlSDTo6ZO4cOsrZGNy2wfGdgCGJ2o5DcSKapMWPFeSQtpDAqucrRlVQhtTW2tlmjJ_nNHn8UNQUhWK-S8qIM1xhUzYpSzFYsrYocnt-1MDCzqnkf6PnY3P9POcTP4skWu3r5QQTHATA7Hap-drXlaGKc8zfnz1U77uaev7wCwlu6M8YnEcKcUEoKVXltxwDILtXy7DkfxCU0GEIBAku9K0QqyDzW0pkmAk_sT_oGmJbU9hzllXmgTXqagUg3zZBJH_MiiIU5LiIw4dN5FnSDNoY3IvWVMgyXdI1vUKb_Pr6w7Cml3xne4zKQznPWhoDAjJ97WLqnpcGzooItsZ2u6W0MrGKVToeXVYhNMJwIDmJh_3aAZKs9_IDc2YeyTIHRp0hcPNX6YVKqOjIRmsdjsS4yZKDJF5GPhKY3nQduySM1svweYbQt0PYw-d4VN_1QQvcg3F6HN0dlHpXyVVMa8xSJdDKW8TX6BO5IRkw7Ab6tG0YeVcL0UeN-M27NEfWVA

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/8409/variations/34595?with=properties
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGU0NTVjYmM1MjFkZjQyMjUwOGRiMGRjYThiMmVmOGI4NDA5ZWFhMjRhOWE3ZWFiYzYyZjRjMGUyZjRlZGE1NDkyZmM5ZTRhNDE3MmRiNzIiLCJpYXQiOjE2NTI2ODg2MDUuMTY1NCwibmJmIjoxNjUyNjg4NjA1LjE2NTQsImV4cCI6MTY1Mjc3NTAwNS4xNDk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.O55IJmFgxCmRdC42bMQVd6_KN1YoLDjadwwtTm_1hz9qrA5snFu4hg8WvkH2wjNcYpxqbXTH4ZeEciTBzJcA2kHZ5B91ZuY84Jl2t_mz49OkVi9P-a-jOdA3jl_oGz3r0kUHBdFzpoyJvW3c2jwsbXqwbhKV75UKYv4XDDiQlDqlSDTo6ZO4cOsrZGNy2wfGdgCGJ2o5DcSKapMWPFeSQtpDAqucrRlVQhtTW2tlmjJ_nNHn8UNQUhWK-S8qIM1xhUzYpSzFYsrYocnt-1MDCzqnkf6PnY3P9POcTP4skWu3r5QQTHATA7Hap-drXlaGKc8zfnz1U77uaev7wCwlu6M8YnEcKcUEoKVXltxwDILtXy7DkfxCU0GEIBAku9K0QqyDzW0pkmAk_sT_oGmJbU9hzllXmgTXqagUg3zZBJH_MiiIU5LiIw4dN5FnSDNoY3IvWVMgyXdI1vUKb_Pr6w7Cml3xne4zKQznPWhoDAjJ97WLqnpcGzooItsZ2u6W0MrGKVToeXVYhNMJwIDmJh_3aAZKs9_IDc2YeyTIHRp0hcPNX6YVKqOjIRmsdjsS4yZKDJF5GPhKY3nQduySM1svweYbQt0PYw-d4VN_1QQvcg3F6HN0dlHpXyVVMa8xSJdDKW8TX6BO5IRkw7Ab6tG0YeVcL0UeN-M27NEfWVA

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/8369/variations/34494/variation_additional_skus
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGU0NTVjYmM1MjFkZjQyMjUwOGRiMGRjYThiMmVmOGI4NDA5ZWFhMjRhOWE3ZWFiYzYyZjRjMGUyZjRlZGE1NDkyZmM5ZTRhNDE3MmRiNzIiLCJpYXQiOjE2NTI2ODg2MDUuMTY1NCwibmJmIjoxNjUyNjg4NjA1LjE2NTQsImV4cCI6MTY1Mjc3NTAwNS4xNDk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.O55IJmFgxCmRdC42bMQVd6_KN1YoLDjadwwtTm_1hz9qrA5snFu4hg8WvkH2wjNcYpxqbXTH4ZeEciTBzJcA2kHZ5B91ZuY84Jl2t_mz49OkVi9P-a-jOdA3jl_oGz3r0kUHBdFzpoyJvW3c2jwsbXqwbhKV75UKYv4XDDiQlDqlSDTo6ZO4cOsrZGNy2wfGdgCGJ2o5DcSKapMWPFeSQtpDAqucrRlVQhtTW2tlmjJ_nNHn8UNQUhWK-S8qIM1xhUzYpSzFYsrYocnt-1MDCzqnkf6PnY3P9POcTP4skWu3r5QQTHATA7Hap-drXlaGKc8zfnz1U77uaev7wCwlu6M8YnEcKcUEoKVXltxwDILtXy7DkfxCU0GEIBAku9K0QqyDzW0pkmAk_sT_oGmJbU9hzllXmgTXqagUg3zZBJH_MiiIU5LiIw4dN5FnSDNoY3IvWVMgyXdI1vUKb_Pr6w7Cml3xne4zKQznPWhoDAjJ97WLqnpcGzooItsZ2u6W0MrGKVToeXVYhNMJwIDmJh_3aAZKs9_IDc2YeyTIHRp0hcPNX6YVKqOjIRmsdjsS4yZKDJF5GPhKY3nQduySM1svweYbQt0PYw-d4VN_1QQvcg3F6HN0dlHpXyVVMa8xSJdDKW8TX6BO5IRkw7Ab6tG0YeVcL0UeN-M27NEfWVA

###
POST https://skorohoda.plentymarkets-cloud02.com/rest/items/8369/variations/34494/variation_additional_skus
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGU0NTVjYmM1MjFkZjQyMjUwOGRiMGRjYThiMmVmOGI4NDA5ZWFhMjRhOWE3ZWFiYzYyZjRjMGUyZjRlZGE1NDkyZmM5ZTRhNDE3MmRiNzIiLCJpYXQiOjE2NTI2ODg2MDUuMTY1NCwibmJmIjoxNjUyNjg4NjA1LjE2NTQsImV4cCI6MTY1Mjc3NTAwNS4xNDk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.O55IJmFgxCmRdC42bMQVd6_KN1YoLDjadwwtTm_1hz9qrA5snFu4hg8WvkH2wjNcYpxqbXTH4ZeEciTBzJcA2kHZ5B91ZuY84Jl2t_mz49OkVi9P-a-jOdA3jl_oGz3r0kUHBdFzpoyJvW3c2jwsbXqwbhKV75UKYv4XDDiQlDqlSDTo6ZO4cOsrZGNy2wfGdgCGJ2o5DcSKapMWPFeSQtpDAqucrRlVQhtTW2tlmjJ_nNHn8UNQUhWK-S8qIM1xhUzYpSzFYsrYocnt-1MDCzqnkf6PnY3P9POcTP4skWu3r5QQTHATA7Hap-drXlaGKc8zfnz1U77uaev7wCwlu6M8YnEcKcUEoKVXltxwDILtXy7DkfxCU0GEIBAku9K0QqyDzW0pkmAk_sT_oGmJbU9hzllXmgTXqagUg3zZBJH_MiiIU5LiIw4dN5FnSDNoY3IvWVMgyXdI1vUKb_Pr6w7Cml3xne4zKQznPWhoDAjJ97WLqnpcGzooItsZ2u6W0MrGKVToeXVYhNMJwIDmJh_3aAZKs9_IDc2YeyTIHRp0hcPNX6YVKqOjIRmsdjsS4yZKDJF5GPhKY3nQduySM1svweYbQt0PYw-d4VN_1QQvcg3F6HN0dlHpXyVVMa8xSJdDKW8TX6BO5IRkw7Ab6tG0YeVcL0UeN-M27NEfWVA

{
    "variationId": 34494,
    "marketId": 0,
    "marketAccountId": 12,
    "sku": "34494-test-market-sku"
}

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/items/8369/variations/34494/variation_markets
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGU0NTVjYmM1MjFkZjQyMjUwOGRiMGRjYThiMmVmOGI4NDA5ZWFhMjRhOWE3ZWFiYzYyZjRjMGUyZjRlZGE1NDkyZmM5ZTRhNDE3MmRiNzIiLCJpYXQiOjE2NTI2ODg2MDUuMTY1NCwibmJmIjoxNjUyNjg4NjA1LjE2NTQsImV4cCI6MTY1Mjc3NTAwNS4xNDk1LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.O55IJmFgxCmRdC42bMQVd6_KN1YoLDjadwwtTm_1hz9qrA5snFu4hg8WvkH2wjNcYpxqbXTH4ZeEciTBzJcA2kHZ5B91ZuY84Jl2t_mz49OkVi9P-a-jOdA3jl_oGz3r0kUHBdFzpoyJvW3c2jwsbXqwbhKV75UKYv4XDDiQlDqlSDTo6ZO4cOsrZGNy2wfGdgCGJ2o5DcSKapMWPFeSQtpDAqucrRlVQhtTW2tlmjJ_nNHn8UNQUhWK-S8qIM1xhUzYpSzFYsrYocnt-1MDCzqnkf6PnY3P9POcTP4skWu3r5QQTHATA7Hap-drXlaGKc8zfnz1U77uaev7wCwlu6M8YnEcKcUEoKVXltxwDILtXy7DkfxCU0GEIBAku9K0QqyDzW0pkmAk_sT_oGmJbU9hzllXmgTXqagUg3zZBJH_MiiIU5LiIw4dN5FnSDNoY3IvWVMgyXdI1vUKb_Pr6w7Cml3xne4zKQznPWhoDAjJ97WLqnpcGzooItsZ2u6W0MrGKVToeXVYhNMJwIDmJh_3aAZKs9_IDc2YeyTIHRp0hcPNX6YVKqOjIRmsdjsS4yZKDJF5GPhKY3nQduySM1svweYbQt0PYw-d4VN_1QQvcg3F6HN0dlHpXyVVMa8xSJdDKW8TX6BO5IRkw7Ab6tG0YeVcL0UeN-M27NEfWVA

