GET https://skorohoda.plentymarkets-cloud02.com/rest/stockmanagement/warehouses
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiODI1ZmI2MWJiOGFkYmY3OTU1ZTA1MzI3MWM1MDA2YjEzM2MxZGRhY2RjY2RkMzIwZjlhNGViNTc2M2U5ZTdhN2VhZGY0MTkyNWQ0ZDE3OTYiLCJpYXQiOjE2NTk1NDE1MDQuNzE0NiwibmJmIjoxNjU5NTQxNTA0LjcxNDYsImV4cCI6MTY1OTYyNzkwNC42OTg5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.yBSU88H9YaNgdGuWfJ9tBkVva87asiYKKqh9pOJEij6dzWERVkVJW0Glvc_LihRDEEfwR6zHn1j4k3lYJcLRb4UJr_1kweljLw585RqyU-Ud_hh-kUNXA75ZoA3ON4U-prrWBpsySrg-BS1_uIYr-wfbAREgd9xL9xcBPrPUjFeYtqaOKiUTrEu9olGRvqwaIGbYDWReHLRCQPM85QW8xJYuJD-TSrHGFFHOJE25vRoHSIwev9L222JXQGx67Wod9ZJ5pXnaGL3Wz2cwIp3dUioOYEMidABaQtJF20YegbIFaVd-Z4_gr-tlh2fnT-krUxxSTds3qZHveahltKri7aqJHPGTvQPnsFaEYRJ3z1WWi2ZzxZ2ZFhWVoB29RIDU2qEeygh-5FfXCsIpPej7GNU2yP49DE8NYZ4CMjhJMPTE4eCr5LKxH9yDD6P3bUdxxxwa_fnPFshpcF2Ow-ZszvuVZopyfo_fffchTbQcjocDiKhPwuXMH1myOBzmbWHT2VXzsZ1arP7mXPFDRSxKd-pShlvhtsDBtjwhHFA74GxROa8BYojtiX4OQVTfFi5omG-nkUZGgw2Lqh5OWrkyzkgm5hjSGa_F3Na94Hk4BADLVQ0GQi38TsUmKOj2M_GG2PTkbcGlk-wCKZH7Hcb0nbm4OSCrstN2L8Gq5vvB56Y

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/warehouses/locations/availability/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiODI1ZmI2MWJiOGFkYmY3OTU1ZTA1MzI3MWM1MDA2YjEzM2MxZGRhY2RjY2RkMzIwZjlhNGViNTc2M2U5ZTdhN2VhZGY0MTkyNWQ0ZDE3OTYiLCJpYXQiOjE2NTk1NDE1MDQuNzE0NiwibmJmIjoxNjU5NTQxNTA0LjcxNDYsImV4cCI6MTY1OTYyNzkwNC42OTg5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.yBSU88H9YaNgdGuWfJ9tBkVva87asiYKKqh9pOJEij6dzWERVkVJW0Glvc_LihRDEEfwR6zHn1j4k3lYJcLRb4UJr_1kweljLw585RqyU-Ud_hh-kUNXA75ZoA3ON4U-prrWBpsySrg-BS1_uIYr-wfbAREgd9xL9xcBPrPUjFeYtqaOKiUTrEu9olGRvqwaIGbYDWReHLRCQPM85QW8xJYuJD-TSrHGFFHOJE25vRoHSIwev9L222JXQGx67Wod9ZJ5pXnaGL3Wz2cwIp3dUioOYEMidABaQtJF20YegbIFaVd-Z4_gr-tlh2fnT-krUxxSTds3qZHveahltKri7aqJHPGTvQPnsFaEYRJ3z1WWi2ZzxZ2ZFhWVoB29RIDU2qEeygh-5FfXCsIpPej7GNU2yP49DE8NYZ4CMjhJMPTE4eCr5LKxH9yDD6P3bUdxxxwa_fnPFshpcF2Ow-ZszvuVZopyfo_fffchTbQcjocDiKhPwuXMH1myOBzmbWHT2VXzsZ1arP7mXPFDRSxKd-pShlvhtsDBtjwhHFA74GxROa8BYojtiX4OQVTfFi5omG-nkUZGgw2Lqh5OWrkyzkgm5hjSGa_F3Na94Hk4BADLVQ0GQi38TsUmKOj2M_GG2PTkbcGlk-wCKZH7Hcb0nbm4OSCrstN2L8Gq5vvB56Y

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/warehouses/locations/details
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiODI1ZmI2MWJiOGFkYmY3OTU1ZTA1MzI3MWM1MDA2YjEzM2MxZGRhY2RjY2RkMzIwZjlhNGViNTc2M2U5ZTdhN2VhZGY0MTkyNWQ0ZDE3OTYiLCJpYXQiOjE2NTk1NDE1MDQuNzE0NiwibmJmIjoxNjU5NTQxNTA0LjcxNDYsImV4cCI6MTY1OTYyNzkwNC42OTg5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.yBSU88H9YaNgdGuWfJ9tBkVva87asiYKKqh9pOJEij6dzWERVkVJW0Glvc_LihRDEEfwR6zHn1j4k3lYJcLRb4UJr_1kweljLw585RqyU-Ud_hh-kUNXA75ZoA3ON4U-prrWBpsySrg-BS1_uIYr-wfbAREgd9xL9xcBPrPUjFeYtqaOKiUTrEu9olGRvqwaIGbYDWReHLRCQPM85QW8xJYuJD-TSrHGFFHOJE25vRoHSIwev9L222JXQGx67Wod9ZJ5pXnaGL3Wz2cwIp3dUioOYEMidABaQtJF20YegbIFaVd-Z4_gr-tlh2fnT-krUxxSTds3qZHveahltKri7aqJHPGTvQPnsFaEYRJ3z1WWi2ZzxZ2ZFhWVoB29RIDU2qEeygh-5FfXCsIpPej7GNU2yP49DE8NYZ4CMjhJMPTE4eCr5LKxH9yDD6P3bUdxxxwa_fnPFshpcF2Ow-ZszvuVZopyfo_fffchTbQcjocDiKhPwuXMH1myOBzmbWHT2VXzsZ1arP7mXPFDRSxKd-pShlvhtsDBtjwhHFA74GxROa8BYojtiX4OQVTfFi5omG-nkUZGgw2Lqh5OWrkyzkgm5hjSGa_F3Na94Hk4BADLVQ0GQi38TsUmKOj2M_GG2PTkbcGlk-wCKZH7Hcb0nbm4OSCrstN2L8Gq5vvB56Y

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/warehouses/locations/dimensions/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiODI1ZmI2MWJiOGFkYmY3OTU1ZTA1MzI3MWM1MDA2YjEzM2MxZGRhY2RjY2RkMzIwZjlhNGViNTc2M2U5ZTdhN2VhZGY0MTkyNWQ0ZDE3OTYiLCJpYXQiOjE2NTk1NDE1MDQuNzE0NiwibmJmIjoxNjU5NTQxNTA0LjcxNDYsImV4cCI6MTY1OTYyNzkwNC42OTg5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.yBSU88H9YaNgdGuWfJ9tBkVva87asiYKKqh9pOJEij6dzWERVkVJW0Glvc_LihRDEEfwR6zHn1j4k3lYJcLRb4UJr_1kweljLw585RqyU-Ud_hh-kUNXA75ZoA3ON4U-prrWBpsySrg-BS1_uIYr-wfbAREgd9xL9xcBPrPUjFeYtqaOKiUTrEu9olGRvqwaIGbYDWReHLRCQPM85QW8xJYuJD-TSrHGFFHOJE25vRoHSIwev9L222JXQGx67Wod9ZJ5pXnaGL3Wz2cwIp3dUioOYEMidABaQtJF20YegbIFaVd-Z4_gr-tlh2fnT-krUxxSTds3qZHveahltKri7aqJHPGTvQPnsFaEYRJ3z1WWi2ZzxZ2ZFhWVoB29RIDU2qEeygh-5FfXCsIpPej7GNU2yP49DE8NYZ4CMjhJMPTE4eCr5LKxH9yDD6P3bUdxxxwa_fnPFshpcF2Ow-ZszvuVZopyfo_fffchTbQcjocDiKhPwuXMH1myOBzmbWHT2VXzsZ1arP7mXPFDRSxKd-pShlvhtsDBtjwhHFA74GxROa8BYojtiX4OQVTfFi5omG-nkUZGgw2Lqh5OWrkyzkgm5hjSGa_F3Na94Hk4BADLVQ0GQi38TsUmKOj2M_GG2PTkbcGlk-wCKZH7Hcb0nbm4OSCrstN2L8Gq5vvB56Y

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/warehouses/103/locations/dimensions
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiODI1ZmI2MWJiOGFkYmY3OTU1ZTA1MzI3MWM1MDA2YjEzM2MxZGRhY2RjY2RkMzIwZjlhNGViNTc2M2U5ZTdhN2VhZGY0MTkyNWQ0ZDE3OTYiLCJpYXQiOjE2NTk1NDE1MDQuNzE0NiwibmJmIjoxNjU5NTQxNTA0LjcxNDYsImV4cCI6MTY1OTYyNzkwNC42OTg5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.yBSU88H9YaNgdGuWfJ9tBkVva87asiYKKqh9pOJEij6dzWERVkVJW0Glvc_LihRDEEfwR6zHn1j4k3lYJcLRb4UJr_1kweljLw585RqyU-Ud_hh-kUNXA75ZoA3ON4U-prrWBpsySrg-BS1_uIYr-wfbAREgd9xL9xcBPrPUjFeYtqaOKiUTrEu9olGRvqwaIGbYDWReHLRCQPM85QW8xJYuJD-TSrHGFFHOJE25vRoHSIwev9L222JXQGx67Wod9ZJ5pXnaGL3Wz2cwIp3dUioOYEMidABaQtJF20YegbIFaVd-Z4_gr-tlh2fnT-krUxxSTds3qZHveahltKri7aqJHPGTvQPnsFaEYRJ3z1WWi2ZzxZ2ZFhWVoB29RIDU2qEeygh-5FfXCsIpPej7GNU2yP49DE8NYZ4CMjhJMPTE4eCr5LKxH9yDD6P3bUdxxxwa_fnPFshpcF2Ow-ZszvuVZopyfo_fffchTbQcjocDiKhPwuXMH1myOBzmbWHT2VXzsZ1arP7mXPFDRSxKd-pShlvhtsDBtjwhHFA74GxROa8BYojtiX4OQVTfFi5omG-nkUZGgw2Lqh5OWrkyzkgm5hjSGa_F3Na94Hk4BADLVQ0GQi38TsUmKOj2M_GG2PTkbcGlk-wCKZH7Hcb0nbm4OSCrstN2L8Gq5vvB56Y

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/warehouses/locations/levels/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiODI1ZmI2MWJiOGFkYmY3OTU1ZTA1MzI3MWM1MDA2YjEzM2MxZGRhY2RjY2RkMzIwZjlhNGViNTc2M2U5ZTdhN2VhZGY0MTkyNWQ0ZDE3OTYiLCJpYXQiOjE2NTk1NDE1MDQuNzE0NiwibmJmIjoxNjU5NTQxNTA0LjcxNDYsImV4cCI6MTY1OTYyNzkwNC42OTg5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.yBSU88H9YaNgdGuWfJ9tBkVva87asiYKKqh9pOJEij6dzWERVkVJW0Glvc_LihRDEEfwR6zHn1j4k3lYJcLRb4UJr_1kweljLw585RqyU-Ud_hh-kUNXA75ZoA3ON4U-prrWBpsySrg-BS1_uIYr-wfbAREgd9xL9xcBPrPUjFeYtqaOKiUTrEu9olGRvqwaIGbYDWReHLRCQPM85QW8xJYuJD-TSrHGFFHOJE25vRoHSIwev9L222JXQGx67Wod9ZJ5pXnaGL3Wz2cwIp3dUioOYEMidABaQtJF20YegbIFaVd-Z4_gr-tlh2fnT-krUxxSTds3qZHveahltKri7aqJHPGTvQPnsFaEYRJ3z1WWi2ZzxZ2ZFhWVoB29RIDU2qEeygh-5FfXCsIpPej7GNU2yP49DE8NYZ4CMjhJMPTE4eCr5LKxH9yDD6P3bUdxxxwa_fnPFshpcF2Ow-ZszvuVZopyfo_fffchTbQcjocDiKhPwuXMH1myOBzmbWHT2VXzsZ1arP7mXPFDRSxKd-pShlvhtsDBtjwhHFA74GxROa8BYojtiX4OQVTfFi5omG-nkUZGgw2Lqh5OWrkyzkgm5hjSGa_F3Na94Hk4BADLVQ0GQi38TsUmKOj2M_GG2PTkbcGlk-wCKZH7Hcb0nbm4OSCrstN2L8Gq5vvB56Y

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/stockmanagement/warehouses/1/stock
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiODI1ZmI2MWJiOGFkYmY3OTU1ZTA1MzI3MWM1MDA2YjEzM2MxZGRhY2RjY2RkMzIwZjlhNGViNTc2M2U5ZTdhN2VhZGY0MTkyNWQ0ZDE3OTYiLCJpYXQiOjE2NTk1NDE1MDQuNzE0NiwibmJmIjoxNjU5NTQxNTA0LjcxNDYsImV4cCI6MTY1OTYyNzkwNC42OTg5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.yBSU88H9YaNgdGuWfJ9tBkVva87asiYKKqh9pOJEij6dzWERVkVJW0Glvc_LihRDEEfwR6zHn1j4k3lYJcLRb4UJr_1kweljLw585RqyU-Ud_hh-kUNXA75ZoA3ON4U-prrWBpsySrg-BS1_uIYr-wfbAREgd9xL9xcBPrPUjFeYtqaOKiUTrEu9olGRvqwaIGbYDWReHLRCQPM85QW8xJYuJD-TSrHGFFHOJE25vRoHSIwev9L222JXQGx67Wod9ZJ5pXnaGL3Wz2cwIp3dUioOYEMidABaQtJF20YegbIFaVd-Z4_gr-tlh2fnT-krUxxSTds3qZHveahltKri7aqJHPGTvQPnsFaEYRJ3z1WWi2ZzxZ2ZFhWVoB29RIDU2qEeygh-5FfXCsIpPej7GNU2yP49DE8NYZ4CMjhJMPTE4eCr5LKxH9yDD6P3bUdxxxwa_fnPFshpcF2Ow-ZszvuVZopyfo_fffchTbQcjocDiKhPwuXMH1myOBzmbWHT2VXzsZ1arP7mXPFDRSxKd-pShlvhtsDBtjwhHFA74GxROa8BYojtiX4OQVTfFi5omG-nkUZGgw2Lqh5OWrkyzkgm5hjSGa_F3Na94Hk4BADLVQ0GQi38TsUmKOj2M_GG2PTkbcGlk-wCKZH7Hcb0nbm4OSCrstN2L8Gq5vvB56Y

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/stockmanagement/warehouses/1/stock/storageLocations
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiODI1ZmI2MWJiOGFkYmY3OTU1ZTA1MzI3MWM1MDA2YjEzM2MxZGRhY2RjY2RkMzIwZjlhNGViNTc2M2U5ZTdhN2VhZGY0MTkyNWQ0ZDE3OTYiLCJpYXQiOjE2NTk1NDE1MDQuNzE0NiwibmJmIjoxNjU5NTQxNTA0LjcxNDYsImV4cCI6MTY1OTYyNzkwNC42OTg5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.yBSU88H9YaNgdGuWfJ9tBkVva87asiYKKqh9pOJEij6dzWERVkVJW0Glvc_LihRDEEfwR6zHn1j4k3lYJcLRb4UJr_1kweljLw585RqyU-Ud_hh-kUNXA75ZoA3ON4U-prrWBpsySrg-BS1_uIYr-wfbAREgd9xL9xcBPrPUjFeYtqaOKiUTrEu9olGRvqwaIGbYDWReHLRCQPM85QW8xJYuJD-TSrHGFFHOJE25vRoHSIwev9L222JXQGx67Wod9ZJ5pXnaGL3Wz2cwIp3dUioOYEMidABaQtJF20YegbIFaVd-Z4_gr-tlh2fnT-krUxxSTds3qZHveahltKri7aqJHPGTvQPnsFaEYRJ3z1WWi2ZzxZ2ZFhWVoB29RIDU2qEeygh-5FfXCsIpPej7GNU2yP49DE8NYZ4CMjhJMPTE4eCr5LKxH9yDD6P3bUdxxxwa_fnPFshpcF2Ow-ZszvuVZopyfo_fffchTbQcjocDiKhPwuXMH1myOBzmbWHT2VXzsZ1arP7mXPFDRSxKd-pShlvhtsDBtjwhHFA74GxROa8BYojtiX4OQVTfFi5omG-nkUZGgw2Lqh5OWrkyzkgm5hjSGa_F3Na94Hk4BADLVQ0GQi38TsUmKOj2M_GG2PTkbcGlk-wCKZH7Hcb0nbm4OSCrstN2L8Gq5vvB56Y

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/warehouses/locations/stock/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiODI1ZmI2MWJiOGFkYmY3OTU1ZTA1MzI3MWM1MDA2YjEzM2MxZGRhY2RjY2RkMzIwZjlhNGViNTc2M2U5ZTdhN2VhZGY0MTkyNWQ0ZDE3OTYiLCJpYXQiOjE2NTk1NDE1MDQuNzE0NiwibmJmIjoxNjU5NTQxNTA0LjcxNDYsImV4cCI6MTY1OTYyNzkwNC42OTg5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.yBSU88H9YaNgdGuWfJ9tBkVva87asiYKKqh9pOJEij6dzWERVkVJW0Glvc_LihRDEEfwR6zHn1j4k3lYJcLRb4UJr_1kweljLw585RqyU-Ud_hh-kUNXA75ZoA3ON4U-prrWBpsySrg-BS1_uIYr-wfbAREgd9xL9xcBPrPUjFeYtqaOKiUTrEu9olGRvqwaIGbYDWReHLRCQPM85QW8xJYuJD-TSrHGFFHOJE25vRoHSIwev9L222JXQGx67Wod9ZJ5pXnaGL3Wz2cwIp3dUioOYEMidABaQtJF20YegbIFaVd-Z4_gr-tlh2fnT-krUxxSTds3qZHveahltKri7aqJHPGTvQPnsFaEYRJ3z1WWi2ZzxZ2ZFhWVoB29RIDU2qEeygh-5FfXCsIpPej7GNU2yP49DE8NYZ4CMjhJMPTE4eCr5LKxH9yDD6P3bUdxxxwa_fnPFshpcF2Ow-ZszvuVZopyfo_fffchTbQcjocDiKhPwuXMH1myOBzmbWHT2VXzsZ1arP7mXPFDRSxKd-pShlvhtsDBtjwhHFA74GxROa8BYojtiX4OQVTfFi5omG-nkUZGgw2Lqh5OWrkyzkgm5hjSGa_F3Na94Hk4BADLVQ0GQi38TsUmKOj2M_GG2PTkbcGlk-wCKZH7Hcb0nbm4OSCrstN2L8Gq5vvB56Y

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/warehouses/locations/13
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiODI1ZmI2MWJiOGFkYmY3OTU1ZTA1MzI3MWM1MDA2YjEzM2MxZGRhY2RjY2RkMzIwZjlhNGViNTc2M2U5ZTdhN2VhZGY0MTkyNWQ0ZDE3OTYiLCJpYXQiOjE2NTk1NDE1MDQuNzE0NiwibmJmIjoxNjU5NTQxNTA0LjcxNDYsImV4cCI6MTY1OTYyNzkwNC42OTg5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.yBSU88H9YaNgdGuWfJ9tBkVva87asiYKKqh9pOJEij6dzWERVkVJW0Glvc_LihRDEEfwR6zHn1j4k3lYJcLRb4UJr_1kweljLw585RqyU-Ud_hh-kUNXA75ZoA3ON4U-prrWBpsySrg-BS1_uIYr-wfbAREgd9xL9xcBPrPUjFeYtqaOKiUTrEu9olGRvqwaIGbYDWReHLRCQPM85QW8xJYuJD-TSrHGFFHOJE25vRoHSIwev9L222JXQGx67Wod9ZJ5pXnaGL3Wz2cwIp3dUioOYEMidABaQtJF20YegbIFaVd-Z4_gr-tlh2fnT-krUxxSTds3qZHveahltKri7aqJHPGTvQPnsFaEYRJ3z1WWi2ZzxZ2ZFhWVoB29RIDU2qEeygh-5FfXCsIpPej7GNU2yP49DE8NYZ4CMjhJMPTE4eCr5LKxH9yDD6P3bUdxxxwa_fnPFshpcF2Ow-ZszvuVZopyfo_fffchTbQcjocDiKhPwuXMH1myOBzmbWHT2VXzsZ1arP7mXPFDRSxKd-pShlvhtsDBtjwhHFA74GxROa8BYojtiX4OQVTfFi5omG-nkUZGgw2Lqh5OWrkyzkgm5hjSGa_F3Na94Hk4BADLVQ0GQi38TsUmKOj2M_GG2PTkbcGlk-wCKZH7Hcb0nbm4OSCrstN2L8Gq5vvB56Y

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/warehouses/structure/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiODI1ZmI2MWJiOGFkYmY3OTU1ZTA1MzI3MWM1MDA2YjEzM2MxZGRhY2RjY2RkMzIwZjlhNGViNTc2M2U5ZTdhN2VhZGY0MTkyNWQ0ZDE3OTYiLCJpYXQiOjE2NTk1NDE1MDQuNzE0NiwibmJmIjoxNjU5NTQxNTA0LjcxNDYsImV4cCI6MTY1OTYyNzkwNC42OTg5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.yBSU88H9YaNgdGuWfJ9tBkVva87asiYKKqh9pOJEij6dzWERVkVJW0Glvc_LihRDEEfwR6zHn1j4k3lYJcLRb4UJr_1kweljLw585RqyU-Ud_hh-kUNXA75ZoA3ON4U-prrWBpsySrg-BS1_uIYr-wfbAREgd9xL9xcBPrPUjFeYtqaOKiUTrEu9olGRvqwaIGbYDWReHLRCQPM85QW8xJYuJD-TSrHGFFHOJE25vRoHSIwev9L222JXQGx67Wod9ZJ5pXnaGL3Wz2cwIp3dUioOYEMidABaQtJF20YegbIFaVd-Z4_gr-tlh2fnT-krUxxSTds3qZHveahltKri7aqJHPGTvQPnsFaEYRJ3z1WWi2ZzxZ2ZFhWVoB29RIDU2qEeygh-5FfXCsIpPej7GNU2yP49DE8NYZ4CMjhJMPTE4eCr5LKxH9yDD6P3bUdxxxwa_fnPFshpcF2Ow-ZszvuVZopyfo_fffchTbQcjocDiKhPwuXMH1myOBzmbWHT2VXzsZ1arP7mXPFDRSxKd-pShlvhtsDBtjwhHFA74GxROa8BYojtiX4OQVTfFi5omG-nkUZGgw2Lqh5OWrkyzkgm5hjSGa_F3Na94Hk4BADLVQ0GQi38TsUmKOj2M_GG2PTkbcGlk-wCKZH7Hcb0nbm4OSCrstN2L8Gq5vvB56Y

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/warehouses/structure/1/moving
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiODI1ZmI2MWJiOGFkYmY3OTU1ZTA1MzI3MWM1MDA2YjEzM2MxZGRhY2RjY2RkMzIwZjlhNGViNTc2M2U5ZTdhN2VhZGY0MTkyNWQ0ZDE3OTYiLCJpYXQiOjE2NTk1NDE1MDQuNzE0NiwibmJmIjoxNjU5NTQxNTA0LjcxNDYsImV4cCI6MTY1OTYyNzkwNC42OTg5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.yBSU88H9YaNgdGuWfJ9tBkVva87asiYKKqh9pOJEij6dzWERVkVJW0Glvc_LihRDEEfwR6zHn1j4k3lYJcLRb4UJr_1kweljLw585RqyU-Ud_hh-kUNXA75ZoA3ON4U-prrWBpsySrg-BS1_uIYr-wfbAREgd9xL9xcBPrPUjFeYtqaOKiUTrEu9olGRvqwaIGbYDWReHLRCQPM85QW8xJYuJD-TSrHGFFHOJE25vRoHSIwev9L222JXQGx67Wod9ZJ5pXnaGL3Wz2cwIp3dUioOYEMidABaQtJF20YegbIFaVd-Z4_gr-tlh2fnT-krUxxSTds3qZHveahltKri7aqJHPGTvQPnsFaEYRJ3z1WWi2ZzxZ2ZFhWVoB29RIDU2qEeygh-5FfXCsIpPej7GNU2yP49DE8NYZ4CMjhJMPTE4eCr5LKxH9yDD6P3bUdxxxwa_fnPFshpcF2Ow-ZszvuVZopyfo_fffchTbQcjocDiKhPwuXMH1myOBzmbWHT2VXzsZ1arP7mXPFDRSxKd-pShlvhtsDBtjwhHFA74GxROa8BYojtiX4OQVTfFi5omG-nkUZGgw2Lqh5OWrkyzkgm5hjSGa_F3Na94Hk4BADLVQ0GQi38TsUmKOj2M_GG2PTkbcGlk-wCKZH7Hcb0nbm4OSCrstN2L8Gq5vvB56Y

### !!!!!
GET https://skorohoda.plentymarkets-cloud02.com/rest/warehouses/1/locations
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiODI1ZmI2MWJiOGFkYmY3OTU1ZTA1MzI3MWM1MDA2YjEzM2MxZGRhY2RjY2RkMzIwZjlhNGViNTc2M2U5ZTdhN2VhZGY0MTkyNWQ0ZDE3OTYiLCJpYXQiOjE2NTk1NDE1MDQuNzE0NiwibmJmIjoxNjU5NTQxNTA0LjcxNDYsImV4cCI6MTY1OTYyNzkwNC42OTg5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.yBSU88H9YaNgdGuWfJ9tBkVva87asiYKKqh9pOJEij6dzWERVkVJW0Glvc_LihRDEEfwR6zHn1j4k3lYJcLRb4UJr_1kweljLw585RqyU-Ud_hh-kUNXA75ZoA3ON4U-prrWBpsySrg-BS1_uIYr-wfbAREgd9xL9xcBPrPUjFeYtqaOKiUTrEu9olGRvqwaIGbYDWReHLRCQPM85QW8xJYuJD-TSrHGFFHOJE25vRoHSIwev9L222JXQGx67Wod9ZJ5pXnaGL3Wz2cwIp3dUioOYEMidABaQtJF20YegbIFaVd-Z4_gr-tlh2fnT-krUxxSTds3qZHveahltKri7aqJHPGTvQPnsFaEYRJ3z1WWi2ZzxZ2ZFhWVoB29RIDU2qEeygh-5FfXCsIpPej7GNU2yP49DE8NYZ4CMjhJMPTE4eCr5LKxH9yDD6P3bUdxxxwa_fnPFshpcF2Ow-ZszvuVZopyfo_fffchTbQcjocDiKhPwuXMH1myOBzmbWHT2VXzsZ1arP7mXPFDRSxKd-pShlvhtsDBtjwhHFA74GxROa8BYojtiX4OQVTfFi5omG-nkUZGgw2Lqh5OWrkyzkgm5hjSGa_F3Na94Hk4BADLVQ0GQi38TsUmKOj2M_GG2PTkbcGlk-wCKZH7Hcb0nbm4OSCrstN2L8Gq5vvB56Y

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/warehouses/1/locations/dimensions
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiODI1ZmI2MWJiOGFkYmY3OTU1ZTA1MzI3MWM1MDA2YjEzM2MxZGRhY2RjY2RkMzIwZjlhNGViNTc2M2U5ZTdhN2VhZGY0MTkyNWQ0ZDE3OTYiLCJpYXQiOjE2NTk1NDE1MDQuNzE0NiwibmJmIjoxNjU5NTQxNTA0LjcxNDYsImV4cCI6MTY1OTYyNzkwNC42OTg5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.yBSU88H9YaNgdGuWfJ9tBkVva87asiYKKqh9pOJEij6dzWERVkVJW0Glvc_LihRDEEfwR6zHn1j4k3lYJcLRb4UJr_1kweljLw585RqyU-Ud_hh-kUNXA75ZoA3ON4U-prrWBpsySrg-BS1_uIYr-wfbAREgd9xL9xcBPrPUjFeYtqaOKiUTrEu9olGRvqwaIGbYDWReHLRCQPM85QW8xJYuJD-TSrHGFFHOJE25vRoHSIwev9L222JXQGx67Wod9ZJ5pXnaGL3Wz2cwIp3dUioOYEMidABaQtJF20YegbIFaVd-Z4_gr-tlh2fnT-krUxxSTds3qZHveahltKri7aqJHPGTvQPnsFaEYRJ3z1WWi2ZzxZ2ZFhWVoB29RIDU2qEeygh-5FfXCsIpPej7GNU2yP49DE8NYZ4CMjhJMPTE4eCr5LKxH9yDD6P3bUdxxxwa_fnPFshpcF2Ow-ZszvuVZopyfo_fffchTbQcjocDiKhPwuXMH1myOBzmbWHT2VXzsZ1arP7mXPFDRSxKd-pShlvhtsDBtjwhHFA74GxROa8BYojtiX4OQVTfFi5omG-nkUZGgw2Lqh5OWrkyzkgm5hjSGa_F3Na94Hk4BADLVQ0GQi38TsUmKOj2M_GG2PTkbcGlk-wCKZH7Hcb0nbm4OSCrstN2L8Gq5vvB56Y

###
GET https://skorohoda.plentymarkets-cloud02.com/rest/warehouses/1/locations/levels
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiODI1ZmI2MWJiOGFkYmY3OTU1ZTA1MzI3MWM1MDA2YjEzM2MxZGRhY2RjY2RkMzIwZjlhNGViNTc2M2U5ZTdhN2VhZGY0MTkyNWQ0ZDE3OTYiLCJpYXQiOjE2NTk1NDE1MDQuNzE0NiwibmJmIjoxNjU5NTQxNTA0LjcxNDYsImV4cCI6MTY1OTYyNzkwNC42OTg5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.yBSU88H9YaNgdGuWfJ9tBkVva87asiYKKqh9pOJEij6dzWERVkVJW0Glvc_LihRDEEfwR6zHn1j4k3lYJcLRb4UJr_1kweljLw585RqyU-Ud_hh-kUNXA75ZoA3ON4U-prrWBpsySrg-BS1_uIYr-wfbAREgd9xL9xcBPrPUjFeYtqaOKiUTrEu9olGRvqwaIGbYDWReHLRCQPM85QW8xJYuJD-TSrHGFFHOJE25vRoHSIwev9L222JXQGx67Wod9ZJ5pXnaGL3Wz2cwIp3dUioOYEMidABaQtJF20YegbIFaVd-Z4_gr-tlh2fnT-krUxxSTds3qZHveahltKri7aqJHPGTvQPnsFaEYRJ3z1WWi2ZzxZ2ZFhWVoB29RIDU2qEeygh-5FfXCsIpPej7GNU2yP49DE8NYZ4CMjhJMPTE4eCr5LKxH9yDD6P3bUdxxxwa_fnPFshpcF2Ow-ZszvuVZopyfo_fffchTbQcjocDiKhPwuXMH1myOBzmbWHT2VXzsZ1arP7mXPFDRSxKd-pShlvhtsDBtjwhHFA74GxROa8BYojtiX4OQVTfFi5omG-nkUZGgw2Lqh5OWrkyzkgm5hjSGa_F3Na94Hk4BADLVQ0GQi38TsUmKOj2M_GG2PTkbcGlk-wCKZH7Hcb0nbm4OSCrstN2L8Gq5vvB56Y

### /rest/warehouses/locations/details
GET https://skorohoda.plentymarkets-cloud02.com/rest/warehouses/locations/details
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiODI1ZmI2MWJiOGFkYmY3OTU1ZTA1MzI3MWM1MDA2YjEzM2MxZGRhY2RjY2RkMzIwZjlhNGViNTc2M2U5ZTdhN2VhZGY0MTkyNWQ0ZDE3OTYiLCJpYXQiOjE2NTk1NDE1MDQuNzE0NiwibmJmIjoxNjU5NTQxNTA0LjcxNDYsImV4cCI6MTY1OTYyNzkwNC42OTg5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.yBSU88H9YaNgdGuWfJ9tBkVva87asiYKKqh9pOJEij6dzWERVkVJW0Glvc_LihRDEEfwR6zHn1j4k3lYJcLRb4UJr_1kweljLw585RqyU-Ud_hh-kUNXA75ZoA3ON4U-prrWBpsySrg-BS1_uIYr-wfbAREgd9xL9xcBPrPUjFeYtqaOKiUTrEu9olGRvqwaIGbYDWReHLRCQPM85QW8xJYuJD-TSrHGFFHOJE25vRoHSIwev9L222JXQGx67Wod9ZJ5pXnaGL3Wz2cwIp3dUioOYEMidABaQtJF20YegbIFaVd-Z4_gr-tlh2fnT-krUxxSTds3qZHveahltKri7aqJHPGTvQPnsFaEYRJ3z1WWi2ZzxZ2ZFhWVoB29RIDU2qEeygh-5FfXCsIpPej7GNU2yP49DE8NYZ4CMjhJMPTE4eCr5LKxH9yDD6P3bUdxxxwa_fnPFshpcF2Ow-ZszvuVZopyfo_fffchTbQcjocDiKhPwuXMH1myOBzmbWHT2VXzsZ1arP7mXPFDRSxKd-pShlvhtsDBtjwhHFA74GxROa8BYojtiX4OQVTfFi5omG-nkUZGgw2Lqh5OWrkyzkgm5hjSGa_F3Na94Hk4BADLVQ0GQi38TsUmKOj2M_GG2PTkbcGlk-wCKZH7Hcb0nbm4OSCrstN2L8Gq5vvB56Y


###
POST https://skorohoda.plentymarkets-cloud02.com/rest/items/8341/variations/34365/variation_warehouses
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiODI1ZmI2MWJiOGFkYmY3OTU1ZTA1MzI3MWM1MDA2YjEzM2MxZGRhY2RjY2RkMzIwZjlhNGViNTc2M2U5ZTdhN2VhZGY0MTkyNWQ0ZDE3OTYiLCJpYXQiOjE2NTk1NDE1MDQuNzE0NiwibmJmIjoxNjU5NTQxNTA0LjcxNDYsImV4cCI6MTY1OTYyNzkwNC42OTg5LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.yBSU88H9YaNgdGuWfJ9tBkVva87asiYKKqh9pOJEij6dzWERVkVJW0Glvc_LihRDEEfwR6zHn1j4k3lYJcLRb4UJr_1kweljLw585RqyU-Ud_hh-kUNXA75ZoA3ON4U-prrWBpsySrg-BS1_uIYr-wfbAREgd9xL9xcBPrPUjFeYtqaOKiUTrEu9olGRvqwaIGbYDWReHLRCQPM85QW8xJYuJD-TSrHGFFHOJE25vRoHSIwev9L222JXQGx67Wod9ZJ5pXnaGL3Wz2cwIp3dUioOYEMidABaQtJF20YegbIFaVd-Z4_gr-tlh2fnT-krUxxSTds3qZHveahltKri7aqJHPGTvQPnsFaEYRJ3z1WWi2ZzxZ2ZFhWVoB29RIDU2qEeygh-5FfXCsIpPej7GNU2yP49DE8NYZ4CMjhJMPTE4eCr5LKxH9yDD6P3bUdxxxwa_fnPFshpcF2Ow-ZszvuVZopyfo_fffchTbQcjocDiKhPwuXMH1myOBzmbWHT2VXzsZ1arP7mXPFDRSxKd-pShlvhtsDBtjwhHFA74GxROa8BYojtiX4OQVTfFi5omG-nkUZGgw2Lqh5OWrkyzkgm5hjSGa_F3Na94Hk4BADLVQ0GQi38TsUmKOj2M_GG2PTkbcGlk-wCKZH7Hcb0nbm4OSCrstN2L8Gq5vvB56Y

{
      "warehouseId": 1
}
