###
GET https://skorohoda.plentymarkets-cloud02.com/rest/webstores
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZGVmMjZjNWQ2MTcwM2FjNWE4YmRhZWZiNDMyN2I1ZGUxMWVkZmUwZWQ4Yzc4Yzg2M2I0MmZkNWY4NDNjNTIxMmZjMzI4MmFjMjdiZTJmZWIiLCJpYXQiOjE2MzY2NDIzNzgsIm5iZiI6MTYzNjY0MjM3OCwiZXhwIjoxNjM2NzI4Nzc4LCJzdWIiOiI2Iiwic2NvcGVzIjpbIioiXX0.y6bjgsfKrwYSufmHgwYIr0xO96mxMeh7LgGrpIX0WaFK5kunWdqNYbENeS69OA6hZ0G6xfDthX35vPQhwwb8qsjKy2Y85tcVFf7dzzIYJaUaedcFWygm3QfPKGcUZn-W_EYWqZ_vjf3fNFuNJaWx90gxKH6WOijECOf8Qn6ENhUIRyxPmHiu0vsHBNSR5eV_KZto3EG6xXv_oQBCr5Z6M4CPewOzzzRomYXjLqkufexxtAlmiV0gb8xTxw0nlhJ95xnnak1QFmef2t5ZOzD28AjlzZHPFPtV2uDxea9J0jBhE4EtILi6U1ZxXPN1DSZFAhcAubLNHM-lV92q8YADMa--yNN-zaeAZzpZCeS4WyzDExsGUQboNTwGJfHTpGV78mk7qZXmUG7Hv4NzlHEkNCkNZsdFoOtmFhg7YS4Kbmm3jnTdppzjQGAfj6p4cWOJ1sLp5fiXp7uRjZtnroTvzFwCWu95h-SiUeN0QO8OVLtDiQPc3jNy2M2AEziWG26RBd2eDFujIxwmmmiF5OSboH7CE2Juhc6d-F4wZKLDsxpTIUUOF0B0rhYL5IAyoOaMX9nM7TYbOnNdv9jjgZZbJOCZcDmG_M9iuDRxhzLXSmVPXWEKz_1AO0BVpuNcQ3fbmMsA7gEK52QLZeX-bzuwLt2qO6MW-XinByCTyviducc


